"""Amarys (card 1207). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, SUPPORTER, TrainerCard)

CARD = TrainerCard(
    card_id=1207,
    name='Amarys',
    kind=SUPPORTER,
    text='Draw 4 cards. At the end of this turn, if you have 5 or more cards in your hand, discard your hand.',
    tags=frozenset(['draw']),
    clauses=(Clause('draw', amount=4),),
    covers='partial',
)
