"""Arven's Sandwich (card 1130). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, ITEM, TrainerCard)

CARD = TrainerCard(
    card_id=1130,
    name="Arven's Sandwich",
    kind=ITEM,
    text='Heal 30 damage from your Active Pokémon. If that Pokémon is an Arven’s Pokémon, heal 100 damage from it instead.',
    tags=frozenset(['heal']),
    clauses=(Clause('heal', amount=100, restriction='arvens_pokemon'), Clause('heal', amount=30, restriction='active_only')),
    covers='full',
)
