"""Battle Cage (card 1264). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, STADIUM, TrainerCard)

CARD = TrainerCard(
    card_id=1264,
    name='Battle Cage',
    kind=STADIUM,
    text='Prevent all damage counters from being placed on Benched Pokémon (both yours and your opponent’s) by effects of attacks and Abilities from the opponent’s Pokémon. (Damage from attacks is still taken.)',
    clauses=(Clause('stadium_static', effect='prevent_damage_counters', applies_to='benched', source='opponent_effects_and_abilities', symmetric=True),),
    covers='full',
)
