"""Bianca’s Devotion (card 1190). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, SUPPORTER, TrainerCard)

CARD = TrainerCard(
    card_id=1190,
    name='Bianca’s Devotion',
    kind=SUPPORTER,
    text='Heal all damage from 1 of your Pokémon that has 30 HP or less remaining.',
    clauses=(Clause('heal', amount='all', condition='remaining_hp_30_or_less'),),
    covers='full',
)
