"""Billy & O'Nare (card 1181). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, SUPPORTER, TrainerCard)

CARD = TrainerCard(
    card_id=1181,
    name="Billy & O'Nare",
    kind=SUPPORTER,
    text='Draw 2 cards. Then, if you have 10 or more cards in your hand, draw 2 more cards.',
    tags=frozenset(['draw']),
    clauses=(Clause('draw', amount=2, amount_if={'condition': 'hand_size_10_plus_after_draw', 'amount': 4}),),
    covers='full',
)
