"""Black Belt’s Training (card 1211). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, SUPPORTER, TrainerCard)

CARD = TrainerCard(
    card_id=1211,
    name='Black Belt’s Training',
    kind=SUPPORTER,
    text='During this turn, attacks used by your Pokémon do 40 more damage to your opponent’s Active Pokémon {ex} (before applying Weakness and Resistance).',
    clauses=(Clause('damage_boost'),),
    covers='full',
)
