"""Buddy-Buddy Poffin (card 1086). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, ITEM, TrainerCard)

CARD = TrainerCard(
    card_id=1086,
    name='Buddy-Buddy Poffin',
    kind=ITEM,
    text='Search your deck for up to 2 Basic Pokémon with 70 HP or less and put them onto your Bench. Then, shuffle your deck.',
    clauses=(Clause('fetch', target='basic_pokemon', zone='deck', hp_max=70, amount=2, dest='bench'),),
    covers='full',
)
