"""Call Bell (card 1101). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, ITEM, TrainerCard)

CARD = TrainerCard(
    card_id=1101,
    name='Call Bell',
    kind=ITEM,
    text='You can use this card only if you go second, and only during your first turn.\n\nSearch your deck for a Supporter card, reveal it, and put it into your hand. Then, shuffle your deck.',
    clauses=(Clause('fetch', target='supporter', zone='deck', condition='going_second_first_turn'),),
    covers='full',
)
