"""Cheren (card 1224). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, SUPPORTER, TrainerCard)

CARD = TrainerCard(
    card_id=1224,
    name='Cheren',
    kind=SUPPORTER,
    text='Draw 3 cards.',
    tags=frozenset(['draw']),
    clauses=(Clause('draw', amount=3),),
    covers='full',
)
