"""Colress’s Tenacity (card 1194). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, SUPPORTER, TrainerCard)

CARD = TrainerCard(
    card_id=1194,
    name='Colress’s Tenacity',
    kind=SUPPORTER,
    text='Search your deck for a Stadium card and an Energy card, reveal them, and put them into your hand. Then, shuffle your deck.',
    clauses=(Clause('fetch', target='energy', zone='deck'), Clause('fetch', target='stadium', zone='deck')),
    covers='full',
)
