"""Cyrano (card 1205). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, SUPPORTER, TrainerCard)

CARD = TrainerCard(
    card_id=1205,
    name='Cyrano',
    kind=SUPPORTER,
    text='Search your deck for up to 3 Pokémon {ex}, reveal them, and put them into your hand. Then, shuffle your deck.',
    tags=frozenset(['search']),
    clauses=(Clause('fetch', target='pokemon_ex', zone='deck', amount=3),),
    covers='full',
)
