"""Drayton (card 1202). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (SUPPORTER, TrainerCard)

CARD = TrainerCard(
    card_id=1202,
    name='Drayton',
    kind=SUPPORTER,
    text='Look at the top 7 cards of your deck. You may reveal a Pokémon and a Trainer card you find there and put them into your hand. Shuffle the other cards back into your deck.',
    tags=frozenset(['dig', 'draw']),
)
