"""Emcee's Hype (card 1214). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, SUPPORTER, TrainerCard)

CARD = TrainerCard(
    card_id=1214,
    name="Emcee's Hype",
    kind=SUPPORTER,
    text='Draw 2 cards. If your opponent has 3 or fewer Prize cards remaining, draw 2 more cards.',
    clauses=(Clause('draw', amount=2, amount_if={'condition': 'opp_3_or_fewer_prizes', 'amount': 4}),),
    covers='full',
)
