"""Energy Search (card 1119). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, ITEM, TrainerCard)

CARD = TrainerCard(
    card_id=1119,
    name='Energy Search',
    kind=ITEM,
    text='Search your deck for a Basic Energy card, reveal it, and put it into your hand. Then, shuffle your deck.',
    clauses=(Clause('fetch', target='basic_energy', zone='deck'),),
    covers='full',
)
