"""Energy Coin (card 1135). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (ITEM, TrainerCard)

CARD = TrainerCard(
    card_id=1135,
    name='Energy Coin',
    kind=ITEM,
    text='Flip 2 coins. If both of them are heads, search your deck for a Basic Energy card and attach it to 1 of your Pokémon. Then, shuffle your deck.',
    tags=frozenset(['energy_accel']),
)
