"""Energy Search Pro (card 1100). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, ITEM, TrainerCard)

CARD = TrainerCard(
    card_id=1100,
    name='Energy Search Pro',
    kind=ITEM,
    text='Search your deck for any number of Basic Energy cards of different types, reveal them, and put them into your hand. Then, shuffle your deck.',
    ace_spec=True,
    tags=frozenset(['search', 'tutor_energy']),
    clauses=(Clause('fetch', target='basic_energy', zone='deck', amount='all', distinct_types=True),),
    covers='full',
)
