"""Enhanced Hammer (card 1081). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, ITEM, TrainerCard)

CARD = TrainerCard(
    card_id=1081,
    name='Enhanced Hammer',
    kind=ITEM,
    text='Discard a Special Energy from 1 of your opponent’s Pokémon.',
    tags=frozenset(['energy_denial']),
    clauses=(Clause('discard_opp_energy', amount=1, energy='special'),),
)
