"""Ethan's Adventure (card 1215). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, FIRE, SUPPORTER, TrainerCard)

CARD = TrainerCard(
    card_id=1215,
    name="Ethan's Adventure",
    kind=SUPPORTER,
    text='Search your deck for up to 3 in any combination of Ethan’s Pokémon and Basic {R} Energy cards, reveal them, and put them into your hand. Then, shuffle your deck.',
    clauses=(Clause('fetch', target='basic_energy', zone='deck', amount=3, energy_type=FIRE, choice=True), Clause('fetch', target='pokemon', zone='deck', amount=3, name_family="Ethan's", choice=True)),
    covers='partial',
)
