"""Explorer’s Guidance (card 1185). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, SUPPORTER, TrainerCard)

CARD = TrainerCard(
    card_id=1185,
    name='Explorer’s Guidance',
    kind=SUPPORTER,
    text='Look at the top 6 cards of your deck and put 2 of them into your hand. Discard the other cards.',
    tags=frozenset(['dig', 'draw']),
    clauses=(Clause('fetch', target='any', zone='deck', dig=6, amount=2, rider='discard_remainder'),),
    covers='full',
)
