"""Fennel (card 1222). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, SUPPORTER, TrainerCard)

CARD = TrainerCard(
    card_id=1222,
    name='Fennel',
    kind=SUPPORTER,
    text='Heal 40 damage from each of your Pokémon.',
    clauses=(Clause('heal', amount=40, target='any_pokemon', each_of=True),),
    covers='full',
)
