"""Festival Grounds (card 1245). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, STADIUM, TrainerCard)

CARD = TrainerCard(
    card_id=1245,
    name='Festival Grounds',
    kind=STADIUM,
    text='Each Pokémon that has any Energy attached (both yours and your opponent’s) recovers from all Special Conditions and can’t be affected by any Special Conditions.',
    clauses=(Clause('stadium_static', effect='special_condition_immunity', applies_to='has_energy_attached', rider='cure_existing', symmetric=True),),
    covers='full',
)
