"""Firebreather (card 1232). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (SUPPORTER, TrainerCard)

CARD = TrainerCard(
    card_id=1232,
    name='Firebreather',
    kind=SUPPORTER,
    text='Search your deck for up to 7 Basic {R} Energy cards, reveal them, and put them into your hand. Then, shuffle your deck.',
    tags=frozenset(['search', 'tutor_energy']),
)
