"""Gravity Mountain (card 1252). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, STADIUM, TrainerCard)

CARD = TrainerCard(
    card_id=1252,
    name='Gravity Mountain',
    kind=STADIUM,
    text='Each Stage 2 Pokémon in play (both yours and your opponent’s) gets -30 HP.',
    clauses=(Clause('stadium_static', effect='hp_delta', amount=-30, applies_to='stage2', symmetric=True),),
    covers='full',
)
