"""Grimsley's Move (card 1230). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (SUPPORTER, TrainerCard)

CARD = TrainerCard(
    card_id=1230,
    name="Grimsley's Move",
    kind=SUPPORTER,
    text='Look at the top 7 cards of your deck and put a {D} Pokémon you find there onto your Bench. Shuffle the other cards and put them on the bottom of your deck. You can’t use this card during your first turn.',
    tags=frozenset(['dig']),
)
