"""Hyper Aroma (card 1082). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, ITEM, TrainerCard)

CARD = TrainerCard(
    card_id=1082,
    name='Hyper Aroma',
    kind=ITEM,
    text='Search your deck for up to 3 Stage 1 Pokémon, reveal them, and put them into your hand. Then, shuffle your deck.',
    ace_spec=True,
    tags=frozenset([]),
    clauses=(Clause('fetch', target='stage1', zone='deck', amount=3),),
    covers='full',
)
