"""Kieran (card 1191). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (SUPPORTER, TrainerCard)

CARD = TrainerCard(
    card_id=1191,
    name='Kieran',
    kind=SUPPORTER,
    text='Choose 1:\n\n• Switch your Active Pokémon with 1 of your Benched Pokémon.\n• During this turn, attacks used by your Pokémon do 30 more damage to your opponent’s Active Pokémon {ex} and Active Pokémon {V} (before applying Weakness and Resistance).',
)
