"""Lacey (card 1199). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, SUPPORTER, TrainerCard)

CARD = TrainerCard(
    card_id=1199,
    name='Lacey',
    kind=SUPPORTER,
    text='Shuffle your hand into your deck. Then, draw 4 cards. If your opponent has 3 or fewer Prize cards remaining, draw 8 cards instead.',
    clauses=(Clause('draw', amount=4, amount_if={'condition': 'opp_3_or_fewer_prizes', 'amount': 8}, rider='shuffle_own_hand_in'),),
    covers='full',
)
