"""Lisia’s Appeal (card 1204). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, SUPPORTER, TrainerCard)

CARD = TrainerCard(
    card_id=1204,
    name='Lisia’s Appeal',
    kind=SUPPORTER,
    text='Switch in 1 of your opponent’s Benched Basic Pokémon to the Active Spot. If you do, the new Active Pokémon is now Confused.',
    tags=frozenset(['confuse', 'gust']),
    clauses=(Clause('gust', target='basic', rider='confuse_target'),),
    covers='full',
)
