"""Lumiose Galette (card 1153). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, ITEM, TrainerCard)

CARD = TrainerCard(
    card_id=1153,
    name='Lumiose Galette',
    kind=ITEM,
    text='Heal 20 damage and remove a Special Condition from your Active Pokémon.',
    clauses=(Clause('heal', amount=20, restriction='active_only'),),
    covers='partial',
)
