"""Master Ball (card 1125). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, ITEM, TrainerCard)

CARD = TrainerCard(
    card_id=1125,
    name='Master Ball',
    kind=ITEM,
    text='Search your deck for a Pokémon, reveal it, and put it into your hand. Then, shuffle your deck.',
    ace_spec=True,
    tags=frozenset(['search']),
    clauses=(Clause('fetch', target='pokemon', zone='deck'),),
    covers='full',
)
