"""Night Stretcher (card 1097). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, ITEM, TrainerCard)

CARD = TrainerCard(
    card_id=1097,
    name='Night Stretcher',
    kind=ITEM,
    text='Put a Pokémon or a Basic Energy card from your discard pile into your hand.',
    clauses=(Clause('fetch', target='pokemon_or_basic_energy', zone='discard', choice=True),),
    covers='full',
)
