"""Perrin (card 1183). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (SUPPORTER, TrainerCard)

CARD = TrainerCard(
    card_id=1183,
    name='Perrin',
    kind=SUPPORTER,
    text='Reveal up to 2 Pokémon in your hand and put them into your deck. If you do, search your deck for up to that many Pokémon, reveal them, and put them into your hand. Then, shuffle your deck.',
    tags=frozenset(['search']),
)
