"""Poké Pad (card 1152). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, ITEM, TrainerCard)

CARD = TrainerCard(
    card_id=1152,
    name='Poké Pad',
    kind=ITEM,
    text='Search your deck for a Pokémon that doesn’t have a Rule Box, reveal it, and put it into your hand. Then, shuffle your deck. (Pokémon {ex}, Pokémon {V}, etc. have Rule Boxes.)',
    clauses=(Clause('fetch', target='pokemon', zone='deck', no_rule_box=True),),
    covers='full',
)
