"""Poké Vital A (card 1096). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, ITEM, TrainerCard)

CARD = TrainerCard(
    card_id=1096,
    name='Poké Vital A',
    kind=ITEM,
    text='Heal 150 damage from 1 of your Pokémon.\n\nThis card can’t be put into your hand or deck from the discard pile.',
    ace_spec=True,
    clauses=(Clause('heal', amount=150),),
    covers='full',
)
