"""Potion (card 1117). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, ITEM, TrainerCard)

CARD = TrainerCard(
    card_id=1117,
    name='Potion',
    kind=ITEM,
    text='Heal 30 damage from 1 of your Pokémon.',
    tags=frozenset(['heal']),
    clauses=(Clause('heal', amount=30),),
    covers='full',
)
