"""Precious Trolley (card 1126). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, ITEM, TrainerCard)

CARD = TrainerCard(
    card_id=1126,
    name='Precious Trolley',
    kind=ITEM,
    text='Search your deck for any number of Basic Pokémon and put them onto your Bench. Then, shuffle your deck.',
    ace_spec=True,
    clauses=(Clause('fetch', target='basic_pokemon', zone='deck', amount='all', dest='bench'),),
    covers='full',
)
