"""Premium Power Pro (card 1141). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, ITEM, TrainerCard)

CARD = TrainerCard(
    card_id=1141,
    name='Premium Power Pro',
    kind=ITEM,
    text='During this turn, attacks used by your {F} Pokémon do 30 more damage to your opponent’s Active Pokémon (before applying Weakness and Resistance).',
    tags=frozenset([]),
    clauses=(Clause('damage_boost'),),
)
