"""Rosa's Encouragement (card 1240). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, SUPPORTER, TrainerCard)

CARD = TrainerCard(
    card_id=1240,
    name="Rosa's Encouragement",
    kind=SUPPORTER,
    text='You can use this card only if you have more Prize cards remaining than your opponent.\n\nAttach up to 2 Basic Energy cards from your discard pile to 1 of your Stage 2 Pokémon.',
    clauses=(Clause('accel', amount=2, source='discard', target='stage2', energy='basic', condition='more_prizes_remaining_than_opp'),),
    covers='full',
)
