"""Sacred Ash (card 1129). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (ITEM, TrainerCard)

CARD = TrainerCard(
    card_id=1129,
    name='Sacred Ash',
    kind=ITEM,
    text='Shuffle up to 5 Pokémon from your discard pile into your deck.',
    tags=frozenset(['recycle']),
)
