"""Scramble Switch (card 1107). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (ITEM, TrainerCard)

CARD = TrainerCard(
    card_id=1107,
    name='Scramble Switch',
    kind=ITEM,
    text='Switch your Active Pokémon with 1 of your Benched Pokémon. If you do, you may move any amount of Energy from the Pokémon you moved to your Bench to the new Active Pokémon.',
    ace_spec=True,
)
