"""Spikemuth Gym (card 1259). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, STADIUM, TrainerCard)

CARD = TrainerCard(
    card_id=1259,
    name='Spikemuth Gym',
    kind=STADIUM,
    text='Once during each player’s turn, that player may search their deck for a Marnie’s Pokémon, reveal it, and put it into their hand. Then, that player shuffles their deck.',
    clauses=(Clause('fetch', target='pokemon', zone='deck', amount=1, name_family="Marnie's"),),
)
