"""Super Potion (card 1112). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, ITEM, TrainerCard)

CARD = TrainerCard(
    card_id=1112,
    name='Super Potion',
    kind=ITEM,
    text='Heal 60 damage from 1 of your Pokémon. If you healed any damage in this way, discard an Energy from that Pokémon.',
    clauses=(Clause('heal', amount=60, rider='discard_own_energy'),),
    covers='full',
)
