"""Switch (card 1123). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, ITEM, TrainerCard)

CARD = TrainerCard(
    card_id=1123,
    name='Switch',
    kind=ITEM,
    text='Switch your Active Pokémon with 1 of your Benched Pokémon.',
    tags=frozenset(['switch']),
    clauses=(Clause('self_switch'),),
)
