"""Tarragon (card 1238). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, FIGHTING, SUPPORTER, TrainerCard)

CARD = TrainerCard(
    card_id=1238,
    name='Tarragon',
    kind=SUPPORTER,
    text='Put up to 4 in any combination of {F} Pokémon and Basic {F} Energy cards from your discard pile into your hand.',
    clauses=(Clause('fetch', target='basic_energy', zone='discard', amount=4, energy_type=FIGHTING, choice=True), Clause('fetch', target='pokemon', zone='discard', amount=4, energy_type=FIGHTING, choice=True)),
    covers='full',
)
