"""Team Rocket's Proton (card 1220). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, SUPPORTER, TrainerCard)

CARD = TrainerCard(
    card_id=1220,
    name="Team Rocket's Proton",
    kind=SUPPORTER,
    text='If you go first, you may use this card during your first turn.\n\nSearch your deck for up to 3 Basic Team Rocket’s Pokémon, reveal them, and put them into your hand. Then, shuffle your deck.',
    clauses=(Clause('fetch', target='basic_pokemon', zone='deck', amount=3, name_family="Team Rocket's"),),
    covers='partial',
)
