"""Team Rocket's Transceiver (card 1134). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, ITEM, TrainerCard)

CARD = TrainerCard(
    card_id=1134,
    name="Team Rocket's Transceiver",
    kind=ITEM,
    text='Search your deck for a Supporter card that has “Team Rocket” in its name, reveal it, and put it into your hand. Then, shuffle your deck.',
    clauses=(Clause('fetch', target='supporter', zone='deck', name_family='Team Rocket'),),
    covers='partial',
)
