"""Team Rocket's Great Ball (card 1132). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, ITEM, TrainerCard)

CARD = TrainerCard(
    card_id=1132,
    name="Team Rocket's Great Ball",
    kind=ITEM,
    text='Search your deck for a Trainer card, reveal it, and put it into your hand. Then, shuffle your deck.',
    tags=frozenset(['search']),
    clauses=(Clause('fetch', target='trainer', zone='deck'),),
    covers='full',
)
