"""Team Rocket's Giovanni (card 1218). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, SUPPORTER, TrainerCard)

CARD = TrainerCard(
    card_id=1218,
    name="Team Rocket's Giovanni",
    kind=SUPPORTER,
    text='Switch your Active Team Rocket’s Pokémon with 1 of your Benched Team Rocket’s Pokémon. If you do, switch in 1 of your opponent’s Benched Pokémon to the Active Spot.',
    clauses=(Clause('gust', target='any', rider='self_switch', name_family="Team Rocket's"),),
    covers='partial',
)
