"""Tera Orb (card 1127). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, ITEM, TrainerCard)

CARD = TrainerCard(
    card_id=1127,
    name='Tera Orb',
    kind=ITEM,
    text='Search your deck for a Tera Pokémon, reveal it, and put it into your hand. Then, shuffle your deck.',
    clauses=(Clause('fetch', target='tera', zone='deck'),),
    covers='full',
)
