"""Ultra Ball (card 1121). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, ITEM, TrainerCard)

CARD = TrainerCard(
    card_id=1121,
    name='Ultra Ball',
    kind=ITEM,
    text='You can use this card only if you discard 2 other cards from your hand.\n\nSearch your deck for a Pokémon, reveal it, and put it into your hand. Then, shuffle your deck.',
    clauses=(Clause('fetch', target='pokemon', zone='deck', cost='discard_2', cost_required=True),),
    covers='full',
)
