"""Unfair Stamp (card 1080). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, ITEM, TrainerCard)

CARD = TrainerCard(
    card_id=1080,
    name='Unfair Stamp',
    kind=ITEM,
    text='You can use this card only if any of your Pokémon were Knocked Out during your opponent’s last turn.\n\nEach player shuffles their hand into their deck. Then, you draw 5 cards, and your opponent draws 2 cards.',
    ace_spec=True,
    tags=frozenset(['draw', 'hand_disruption', 'shuffle_hand']),
    clauses=(Clause('draw', amount=5, condition='pokemon_ko_last_turn', opponent_amount=2, rider='shuffle_both_hands'),),
    covers='full',
)
