"""Wally's Compassion (card 1229). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, SUPPORTER, TrainerCard)

CARD = TrainerCard(
    card_id=1229,
    name="Wally's Compassion",
    kind=SUPPORTER,
    text='Heal all damage from 1 of your Mega Evolution Pokémon {ex}. If you healed any damage in this way, put all Energy attached to that Pokémon into your hand.',
    tags=frozenset(['clutch_heal', 'heal']),
    clauses=(Clause('heal', amount='all', restriction='mega_only', rider='bounce_energy_to_hand'),),
)
