"""Wondrous Patch (card 1146). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Clause, ITEM, PSYCHIC, TrainerCard)

CARD = TrainerCard(
    card_id=1146,
    name='Wondrous Patch',
    kind=ITEM,
    text='Attach a Basic {P} Energy card from your discard pile to 1 of your Benched {P} Pokémon.',
    tags=frozenset(['energy_accel']),
    clauses=(Clause('accel', amount=1, source='discard', target='benched', target_type=5, energy='basic', energy_type=PSYCHIC),),
)
