"""Basic {D} Energy (card 7). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (BASIC_ENERGY, DARKNESS, EnergyCard)

CARD = EnergyCard(
    card_id=7,
    name='Basic {D} Energy',
    kind=BASIC_ENERGY,
    provides=DARKNESS,
    tags=frozenset([]),
)
