"""Basic {F} Energy (card 6). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (BASIC_ENERGY, EnergyCard, FIGHTING)

CARD = EnergyCard(
    card_id=6,
    name='Basic {F} Energy',
    kind=BASIC_ENERGY,
    provides=FIGHTING,
)
