"""Basic {P} Energy (card 5). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (BASIC_ENERGY, EnergyCard, PSYCHIC)

CARD = EnergyCard(
    card_id=5,
    name='Basic {P} Energy',
    kind=BASIC_ENERGY,
    provides=PSYCHIC,
    tags=frozenset([]),
)
