"""Boomerang Energy (card 9). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (COLORLESS, EnergyCard, SPECIAL_ENERGY)

CARD = EnergyCard(
    card_id=9,
    name='Boomerang Energy',
    kind=SPECIAL_ENERGY,
    provides=COLORLESS,
    text='As long as this card is attached to a Pokémon, it provides {C} Energy.\n\nIf this card is discarded by an effect of an attack used by the Pokémon this card is attached to, attach this card from your discard pile to that Pokémon after attacking.',
)
