"""The Turn Planner (ADR-0031/0037): the eager whole-turn optimizer and the Pilot's ONE planning
entry point — the **Lethal Solver is its sound top rung**.

A deck-agnostic Pilot Mixin that runs at the start of my turn, BEFORE the tuned Hypothesis scoring.
``plan_turn`` runs the Goal Ladder: the **win rung** first (the Lethal Solver, ADR-0030 — sound,
engine-verified, preempting every heuristic goal), then the heuristic rungs (stabilize-then-KO,
KO-for-prizes, KO-the-key-threat), generated by working backward from a closed, prioritized set of
**Turn Goals** and committing the best — steering this decision toward that line's next step. See
``docs/adr/0037-lethal-solver-is-the-turn-planners-top-rung.md`` and the *Turn Planner* / *Turn
Goal* / *Turn Line* / *Lethal Solver* terms in ``common/CONTEXT.md``.

**Two soundness regimes, one module.** The win rung locks only a GUARANTEED win: min-bound damage
floors, worst-case coins, and the `_engine_confirms_win` verdict-driver (refute drops the candidate;
an unreachable verdict keeps the sound closed-form lock). Everything below it is **heuristic**:
`_simulate_line` auto-resolves coins and its end-of-turn board is trusted for RANKING, never as a
guarantee.

**Layer-on-top (ADR-0031 decision 6).** Below the win rung the Planner commits only when a line
reaches an outcome the tuned per-option scoring would MISS — otherwise it defers, so the proven
default is unchanged.
"""
from __future__ import annotations

from dataclasses import dataclass, replace

from common.strategy.context import (_ACTIVE, _ATTACH, _ATTACK, _BASIC_ENERGY, _COIN_HEAD, _EVOLVE,
                                     _MAIN, _PLAY, _RETREAT, _SPECIAL_ENERGY, KO_SCORE)


def _prune_none(v):
    """Convert an ``asdict``-ed engine Observation into the dict shape the LIVE obs has, so the Pilot's
    ``decide`` can be re-run on an intermediate SearchState. ``asdict`` keeps optional dataclass fields
    as ``None`` keys (e.g. ``option.playerIndex``), but the engine's live JSON OMITS them — the
    difference matters for ``option.get("playerIndex", yourIndex)``-style lookups, which otherwise read
    ``None`` and crash. Drops None-VALUED dict keys; KEEPS None list ELEMENTS (a facedown Active / a
    facedown prize slot is a meaningful ``None`` that carries the zone's count)."""
    if isinstance(v, dict):
        return {k: _prune_none(x) for k, x in v.items() if x is not None}
    if isinstance(v, list):
        return [_prune_none(x) for x in v]
    return v

# Leaf-eval term weights (ADR-0031 decision 4). Prizes KO_SCORE-weighted + DOMINANT — positional terms
# sum below one prize, never outrank real KO (hard-rung invariant, decision 3). Base Value Model (ADR-0007) replaces later.
_PLANNER_SURVIVAL_W = 50.0     # my Active survives predicted Incoming after the line (full turn)
_PLANNER_THREAT_W = 0.1        # per-point value of threat magnitude removed by the KO …
_PLANNER_THREAT_CAP = 100.0    # … capped, so a big threat still can't rival a prize
_PLANNER_DEV_W = 1.0           # development left on my end-of-turn board (engine-rank phase: bodies
_PLANNER_DEV_CAP = 100.0       # + attached Energy, `_board_development`) … capped below a prize
_PLANNER_PATH_W = 25.0         # Tier-3 (ADR-0040): the KO'd key threat sits on MY cheapest Prize
                               # Path — sub-prize, ranks lines within the rung, never beats a prize
_PLANNER_VALUE_W = 80.0        # Tier-5 (ADR-0042): the Base Value Model's P(win) on the simmed
                               # end-of-turn board scales into a sub-prize band (< one KO_SCORE), so
                               # the learned leaf breaks prize-EQUAL ties, never overriding a prize
_ESCALATE_EPS = 15.0          # Tier-6 (ADR-0043): two attacks within this many tactical points are a
                               # "close race tie" the closed-form can't separate — the escalation
                               # trigger. Narrow, so only genuinely ambiguous attack picks pay the tree
_PRIZE_AREA = 6                # AreaType.PRIZE — a hidden-zone pick: the sim's ids are predictions,
                               # so a recorded prize pick is policy-driven at replay (ADR-0037 stage 3)


@dataclass
class TurnLine:
    """A committed sequence of this-turn actions achieving a **Turn Goal**: the option index(es) to
    take at THIS decision (``next_step``), the ``goal`` it serves (for legibility / telemetry
    clustering), the leaf-eval ``value`` of the resulting board, and a one-line ``rationale``. A
    multi-step line surfaces one step per decision as the engine re-opens the turn menu.

    ``goal == "win"`` is the Lethal Solver's lock (ADR-0030/0037) — the ONE unified line type covers
    both regimes, and telemetry serialises a win line under the wire-compatible ``lethal`` key. Win
    lines carry ``kind`` (``direct`` / ``unlock`` / ``evolve``, so a correction can cluster by *how*
    the win was reached) and ``verified`` — the engine backstop's verdict on the lock
    (``lethal_verify``): True = the engine's own search confirmed the win; None = not checked
    (switch off / unverifiable kind / engine unavailable). A False never rides here — a refuted
    candidate is dropped, not locked.

    ``ranked_by`` records how a HEURISTIC committed line was VALUED when multi-candidate engine
    ranking ran (`planner_engine_rank`): "engine" = its own sim's leaf value; "closed" = the
    closed-form value (its sim was unavailable); None = ranking never ran (switch off / engine
    absent / mid-sim). ``diverged`` = the ranking committed a DIFFERENT line than the closed form
    would have — the A/B divergence signal. Win lines never enter ranking (they preempt it)."""
    next_step: list
    goal: str = ""
    value: float = 0.0
    rationale: str = ""
    ranked_by: str | None = None
    diverged: bool = False
    kind: str = ""
    verified: bool | None = None


class PlannerMixin:
    """Pilot-side Turn Planner. ``plan_turn`` returns a :class:`TurnLine` to commit, or None to defer
    to the tuned scoring. Depends on Pilot internals (``_opp_active``, ``_best_affordable_ko_value``,
    ``_prize_value``, the per-option ``OptionTrace``), so it is mixed into the Pilot."""

    def plan_turn(self, obs, select, board, options, traces) -> TurnLine | None:
        """The best committed Turn Line this turn, or None. Only acts at the single-pick MAIN menu;
        every other context (search, snipe, mulligan, multi-select) defers to the tuned scoring.

        The Goal Ladder runs top-down (ADR-0037): the **win rung** first — the Lethal Solver's sound
        lock, which preempts every heuristic goal and never enters ranking — then the heuristic
        rungs. Plan once, cache, re-plan on reveal (ADR-0031 decision 5): the verdict (win lock
        included) is cached as turn-scoped state keyed by a board fingerprint, so the plan — and the
        win rung's engine verify — is computed once per board and re-derived only when a search/draw
        reveals information that changes the fingerprint (`lethal_refuted` is thereby counted
        per-plan, not per-decision). While an engine sim is re-running my policy (``_planning``), it
        stays closed-form and uncached so it never launches a nested search."""
        if not self._planning:                        # per-plan engine-refute count (telemetry). A verify
            self._lethal_refutes = 0                  # cascade re-runs decide() -> re-enters here under
                                                      # _planning: never wipe the OUTER decision's count
                                                      # mid-scan (an in-sim call can't refute anyway — the
                                                      # verify gate is closed)
        if select.get("context") != _MAIN or select.get("maxCount", 0) != 1:
            return None
        if self._planning:                            # mid engine-sim: closed-form only, never nest search
            win = self._win_line(obs, select, board, options, traces)
            if win is not None:
                return win
            return self._closed_form_plan(obs, select, board, options, traces)
        fp = self._plan_fingerprint(obs, select)
        if self._turn_plan is not None and self._turn_plan[0] == fp:
            return self._turn_plan[1]                 # cache hit: re-plan only on reveal (fingerprint change)
        line = self._win_line(obs, select, board, options, traces)
        if line is None:
            candidates = self._closed_form_candidates(obs, select, board, options, traces)
            line = self._commit_best(obs, candidates)
        if line is None:                              # Tier-2 Gamble rung (ADR-0039): below every
            line = self._best_gamble_line(obs, select, board, options, traces)   # deterministic goal
        if line is None:                              # Tier-6 escalation (ADR-0043): a close
            line = self._escalate(obs, select, board, options, traces)   # attack tie → depth-2 tree
        self._turn_plan = (fp, line)
        return line

    def _closed_form_plan(self, obs, select, board, options, traces) -> TurnLine | None:
        """The single closed-form Goal-Ladder verdict (no engine) — the mid-sim / switch-off pick:
        the best candidate by closed-form leaf value, ties to the first generated (the original
        single-line behavior, exactly)."""
        candidates = self._closed_form_candidates(obs, select, board, options, traces)
        return max(candidates, key=lambda ln: ln.value) if candidates else None

    def _closed_form_candidates(self, obs, select, board, options, traces) -> list:
        """ALL candidate Turn Lines from closed-form generation, highest rung first.

        **Stabilize-then-KO** rules the pool alone when it fires — it is the one goal alive EVEN when
        a status-quo KO exists (it combines the heal + KO the greedy scorer treats as mutually
        exclusive), and mixing lower rungs under it would trade the heal away. Below it, the pool is
        strictly layer-on-top: it empties when the tuned machinery already reaches a KO (any option
        scored KO_SCORE-class), else it holds every **KO-for-prizes** enabling line plus — behind the
        `planner_key_threat` switch — every **KO-the-key-threat** snipe line (the Goal Ladder's middle
        rung, CONTEXT.md: the leaf scalar ranks across the two, prizes dominant)."""
        stabilize = self._stabilize_then_ko_lines(obs, select, board, options, traces)
        if stabilize:
            return stabilize
        if any(t.tactical >= KO_SCORE for t in traces):
            return []
        candidates = self._ko_for_prizes_lines(obs, select, board, options, traces)
        if self.planner_key_threat:
            candidates += self._ko_key_threat_lines(obs, select, board, options)
        return candidates

    def _commit_best(self, obs, candidates) -> TurnLine | None:
        """The line to commit from the candidate pool — the multi-candidate ENGINE RANKING seam
        (ADR-0031 P3 completed; `planner_engine_rank`).

        OFF (default) or engine absent: the closed-form best, its value engine-SHARPENED when
        available (the original behavior, byte-identical). ON: every candidate is forward-simmed to
        its end-of-turn board and ranked by the ENGINE leaf value — a candidate whose sim is
        unavailable keeps its closed-form value (same scale, decision 7: never lose a line to a
        failed fork). If even the best ranked value collapses below one prize, the pool's premise
        failed in sim — defer to the tuned scoring (the natural veto: the sim is trusted for ranking,
        and an all-candidates refute means there is nothing left to rank). ``diverged`` records a
        pick the closed form would not have made."""
        if not candidates:
            return None
        closed_best = max(candidates, key=lambda ln: ln.value)
        if not self.planner_engine_rank:
            return self._engine_rank(obs, closed_best)   # status quo: sharpen the committed value only
        ranked = []
        for cand in candidates:
            self._planning = True                        # per-sim reentrancy guard (never nest a search)
            try:
                val = self._engine_leaf_value(obs, cand.next_step)
            except Exception:
                val = None                               # a failed fork never crashes the decision
            finally:                                     # (decision 7) — the candidate keeps its
                self._planning = False                   # closed-form value below
            ranked.append((val if val is not None else cand.value, val is not None, cand))
        best_val, engine_valued, best = max(ranked, key=lambda t: t[0])
        if best_val < KO_SCORE:
            return None                                  # every candidate's prize premise failed in sim
        return replace(best, value=best_val,
                       ranked_by=("engine" if engine_valued else "closed"),
                       diverged=(best is not closed_best))

    # ═══ THE WIN RUNG — the Lethal Solver (ADR-0030/0037): sound, engine-verified, preempts all ═══
    # Everything in this section is SOUND by construction: min-bound damage floors, worst-case
    # coins, engine verdicts. It never trades against the heuristic rungs — a win, when locked,
    # owns the decision. A false Lethal is the one catastrophic error (a miss costs a turn; a
    # phantom loses the game), so soundness beats completeness throughout.

    def _win_line(self, obs, select, board, options, traces) -> TurnLine | None:
        """The shortest guaranteed win on the current turn as a ``goal="win"`` Turn Line, or None.

        Two generation modes (ADR-0037): ``lethal_family`` ON = the ONE generator family
        (`_family_win_candidates` — single+multi-develop, gust, tutor; all min-bound sound), every
        lock engine-verified (`lethal_verify`, cascade-driven to the engine's verdict). OFF = the
        legacy stage-1 rungs (`_legacy_win_candidates` — direct + hook-trace unlock + evolve), with
        verify on DIRECT locks only (a 1-step sim of a multi-step line ends mid-turn and would
        false-refute without the cascade drive the family mode uses). Either way: a refute drops the
        candidate (never lock a phantom, counted in `_lethal_refutes`); a None verdict keeps the
        sound closed-form lock (a coin-floor win can never verify True by construction — the
        min-bound floor is the authority there)."""
        if board.my_prizes_remaining <= 0:
            return None
        opp = self._opp_active(obs)
        family = self.lethal_family
        candidates = (self._family_win_candidates(obs, select, board, options, opp) if family
                      else self._legacy_win_candidates(obs, select, board, options, traces, opp))
        for cand in candidates:
            verified = None
            if (self.lethal_verify and not self._planning
                    and (family or cand.kind == "direct")):
                recorded = [] if (family and self.lethal_veto) else None
                verified = (self._engine_confirms_win(obs, [cand.next_step], max_cascade=40,
                                                      record=recorded)
                            if family else self._engine_confirms_win(obs, [cand.next_step]))
                if verified is False:
                    self._lethal_refutes += 1
                    continue                           # the engine says this "win" doesn't win — skip it
                if verified and recorded is not None:  # stage 3: a VERIFIED lock materializes its
                    self._win_lock_store(obs, recorded)   # confirmed cascade for replay
            return replace(cand, verified=verified)
        return None

    def _legacy_win_candidates(self, obs, select, board, options, traces, opp):
        """Yield the pre-family (stage-1) closed-form candidates in their exact order — the
        ``lethal_family=False`` path, ADR-0030's shipped rungs (shared-valuation upgrades — e.g.
        the typed-affordability guard — flow through): (1) a KO already
        on the menu that WINS now, judged by the attack's OWN prize yield (`_attack_wins`); (2) an
        Energy attach or a retreat into a READY benched attacker that unlocks the winning KO (the
        KO_SCORE-class closed-form hook traces); (3) an EVOLVE of the Active bringing a bigger
        attacker online (no hook scores it, so its own min-bound lookup)."""
        # 1) direct: a KO on the menu that wins now.
        for i, o in enumerate(options):
            if o.get("type") == _ATTACK and self._attack_wins(obs, board, o, opp):
                yield TurnLine(next_step=[i], goal="win", kind="direct",
                               rationale="lethal: this KO wins the match")

        # Develops below unlock a KO of opp ACTIVE (closed-form hooks). Wins iff takes my last prize
        # or opp has no bench to promote — under-counts any rider snipe, conservative but sound.
        if not (self._prize_value(opp) >= board.my_prizes_remaining or not board.opp_bench):
            return

        # 2) Energy attach (`_attach_lethal_tactical`) or retreat into ready bench attacker
        # (`_retreat_to_lethal_tactical`) unlocking that KO — both KO_SCORE-class; finishing attack
        # follows next menu.
        for i, o in enumerate(options):
            if o.get("type") in (_ATTACH, _RETREAT) and traces[i].tactical >= KO_SCORE:
                yield TurnLine(next_step=[i], goal="win", kind="unlock",
                               rationale="lethal (unlock): a develop enables the winning KO")
        # 3) EVOLVE of Active bringing bigger attacker online — no closed-form hook scores it, so
        # look up: evolved form inherits Active's Energy, best affordable attack must KO (same-turn
        # legal, rules.md §evolution). Typed-affordability guarded like every shared KO valuation.
        ma = next((p for p in (self._my_player(obs).get("active") or []) if p), None)
        for i, o in enumerate(options):
            if o.get("type") == _EVOLVE and o.get("inPlayArea") == _ACTIVE:
                evolved_id = self._option_card_id(obs, select, o)
                if self._best_affordable_ko_value(obs, board, opp, evolved_id, board.my_active_energy,
                                                  bound="min", body=ma) > 0:
                    yield TurnLine(next_step=[i], goal="win", kind="evolve",
                                   rationale="lethal (evolve): evolving enables the winning KO")

    def _family_win_candidates(self, obs, select, board, options, opp):
        """Yield ``goal="win"`` candidates from the ONE generator family (ADR-0037), SHORTEST-first:
        tier 0 = a direct KO already on the menu; tier 1 = one develop (attach the Active / retreat
        into a ready body / evolve the Active / gust up a KO-able last-prize body); tier 2 = the same
        develop PLUS this turn's one attach; tier 3 = the energy-tutor Supporter line (fetch the
        attach the line lacks). Every candidate is min-bound SOUND (worst-coin damage floors, exact
        prize math, engine-vetted step legality — an option on the menu IS legal); the develop tiers'
        win test is the conservative legacy precondition (opp-Active prize reaches my remaining count
        or their bench is empty — rider snipes under-counted, never over). An option index is yielded
        once, at its shortest tier (a refuted candidate is not retried at a longer tier: the verify
        cascade drives the same policy either way)."""
        # tier 0: direct — a KO on the menu that wins now.
        seen = set()
        for i, o in enumerate(options):
            if o.get("type") == _ATTACK and self._attack_wins(obs, board, o, opp):
                seen.add(i)
                yield TurnLine(next_step=[i], goal="win", kind="direct",
                               rationale="lethal: this KO wins the match")
        if board.turn <= 1:
            return                                     # turn 1 going first: no attack this turn, so
                                                       # no develop can cash a win (rules.md §first-turn)
        me = self._my_player(obs)
        ma = next((p for p in (me.get("active") or []) if p), None)
        extra = 1 if (board.reusable_energy_in_hand and not board.energy_attached) else 0
        for tier_extra in (0, extra) if extra else (0,):
            for i, o in enumerate(options):
                if i in seen:
                    continue
                t = o.get("type")
                if t == _ATTACH and o.get("inPlayArea") == _ACTIVE and tier_extra == 0:
                    provided = self._attach_provided(obs, select, board, o)
                    eid = self._option_card_id(obs, select, o)
                    estat = self.stats.get(eid) if (self.stats and eid is not None) else None
                    win = self._develop_wins(obs, board, opp, board.my_active_id,
                                             board.my_active_energy + provided, body=ma,
                                             extra_type=getattr(estat, "energyType", None),
                                             extra_units=provided)
                    kind, why = "unlock", "lethal (unlock): the attach enables the winning KO"
                elif t == _RETREAT:
                    win = any(self._develop_wins(obs, board, opp, p.get("id"),
                                                 len(p.get("energies") or []) + tier_extra, body=p)
                              for p in (me.get("bench") or []) if p)
                    kind, why = "unlock", "lethal (unlock): the retreat enables the winning KO"
                elif t == _EVOLVE and o.get("inPlayArea") == _ACTIVE:
                    win = self._develop_wins(obs, board, opp, self._option_card_id(obs, select, o),
                                             board.my_active_energy + tier_extra, body=ma)
                    kind, why = "evolve", "lethal (evolve): evolving enables the winning KO"
                elif t == _PLAY and self._is_gust(obs, select, o):
                    win = self._gust_win_target(obs, board, board.my_active_energy + tier_extra)
                    kind, why = "gust", "lethal (gust): dragging up the KO-able body wins the match"
                else:
                    continue
                if win:
                    seen.add(i)
                    yield TurnLine(next_step=[i], goal="win", kind=kind, rationale=why)
        # tier 3: the energy-tutor Supporter supplies the attach the line lacks (the 4298 shape,
        # game-winning). SOUND only when the deck DEFINITELY still holds a reusable Energy (the
        # match-scoped tracker's positive certainty) — a probable fetch is never a win.
        retreat_on_menu = any(o.get("type") == _RETREAT for o in options)
        if (not (board.energy_attached or board.reusable_energy_in_hand)
                and self._tutor_energy_certain(board)):
            for i, o in enumerate(options):
                if i in seen or o.get("type") != _PLAY or not self._is_energy_tutor(obs, select, o):
                    continue
                win = self._develop_wins(obs, board, opp, board.my_active_id,
                                         board.my_active_energy + 1, body=ma)
                if not win and retreat_on_menu:
                    win = any(self._develop_wins(obs, board, opp, p.get("id"),
                                                 len(p.get("energies") or []) + 1, body=p)
                              for p in (me.get("bench") or []) if p)
                if win:
                    seen.add(i)
                    yield TurnLine(next_step=[i], goal="win", kind="unlock",
                                   rationale="lethal (unlock): the energy tutor fetches the winning attach")
        # tier 4: the evolution-tutor Supporter line (Salvatore, `rush_evolve` — the a212 shape):
        # evolve a deck-certain, no-Ability DIRECT evolution onto an in-play body straight from the
        # deck, then (for a benched body) retreat into it and attach — e.g. Salvatore -> Mega Starmie
        # onto a Staryu, free-retreat the opener, attach, Jetting Blow the last body: bench-empty win.
        # Salvatore's own allowance covers every in-play target (setup-placed / played this turn;
        # anything older is normal-legal), so no timing gate. SOUND on the tracker's positive deck
        # certainty + min-bound KO math; the engine verify cascade backstops the rest.
        targets = [(p, False) for p in (me.get("active") or []) if p]
        if retreat_on_menu:
            targets += [(p, True) for p in (me.get("bench") or []) if p]
        for i, o in enumerate(options):
            if i in seen or o.get("type") != _PLAY or not self._is_evolution_tutor(obs, select, o):
                continue
            if any(self._tutor_evolution_wins(obs, board, opp, p) for p, _ in targets):
                yield TurnLine(next_step=[i], goal="win", kind="unlock",
                               rationale="lethal (unlock): the evolution tutor evolves the winning attacker")

    def _develop_wins(self, obs, board, opp, attacker_id, energy, body=None,
                      extra_type=None, extra_units: int = 0) -> bool:
        """SOUND: this attacker, carrying ``energy``, takes a min-bound affordable KO of the
        opponent's Active AND that KO wins — it reaches my remaining prize count or their bench is
        empty (no Pokémon to promote). The family's shared develop-tier win test: worst-coin damage
        floors via ``bound="min"``, rider snipes deliberately under-counted (conservative).
        ``body``/``extra_type``/``extra_units`` forward to the typed-affordability guard (an Energy
        the line provides can't fund a specific-type slot it doesn't match — Ignition never pays a
        {W}); budget beyond attached+extra stays wild (fail-open)."""
        if not (self._prize_value(opp) >= board.my_prizes_remaining or not board.opp_bench):
            return False
        return self._best_affordable_ko_value(obs, board, opp, attacker_id, energy, bound="min",
                                              body=body, extra_type=extra_type,
                                              extra_units=extra_units) > 0

    def _attach_provided(self, obs, select, board, option) -> int:
        """Energy units this ATTACH provides the Active — 1 for a plain Energy; 3 for a
        discard-burst (`discard_eot`, Ignition: CCC) onto an Evolution (mirrors
        `_attach_lethal_tactical`'s model). 0 when the card can't be resolved."""
        eid = self._option_card_id(obs, select, option)
        if eid is None:
            return 0
        etags = self.functions.tags(eid) if self.functions else []
        active_stat = (self.stats.get(board.my_active_id)
                       if (self.stats and board.my_active_id is not None) else None)
        is_evo = bool(getattr(active_stat, "evolvesFrom", None))
        return 3 if ("discard_eot" in etags and is_evo) else 1

    def _is_gust(self, obs, select, option) -> bool:
        """This PLAY option is a gust card (Function Tag `gust`, e.g. Boss's Orders)."""
        cid = self._option_card_id(obs, select, option)
        return bool(cid is not None and self.functions and "gust" in self.functions.tags(cid))

    def _gust_win_target(self, obs, board, energy) -> bool:
        """SOUND: some benched opponent body the gust drags Active is worth my remaining prize count
        AND my Active (at ``energy``) takes a min-bound affordable KO of it — the ADR-0022 gust
        lethal, generated (and locked) by the family rather than hook-scored. Dragging never empties
        their board (the old Active benches), so only the prize-out shape wins here; Tera bench
        immunity is irrelevant (the target is Active when hit)."""
        ma = next((p for p in (self._my_player(obs).get("active") or []) if p), None)
        for b in (self._opp_player(obs).get("bench") or []):
            if not b or self._prize_value(b) < board.my_prizes_remaining:
                continue
            if self._best_affordable_ko_value(obs, board, b, board.my_active_id, energy,
                                              bound="min", body=ma) > 0:
                return True
        return False

    def _tutor_energy_certain(self, board) -> bool:
        """SOUND: my deck DEFINITELY still holds a reusable typed Energy a `tutor_energy` Supporter
        can fetch — the deck tracker's positive certainty (`Board.deck_definitely_has`), never the
        probabilistic estimate. Reusable mirrors `_has_reusable_energy`: an Energy card (hp 0, real
        `energyType`) not tagged `discard_eot`."""
        if not self.stats:
            return False
        for cid in set(self.deck):
            stat = self.stats.get(cid)
            if not stat or getattr(stat, "hp", 0) or not getattr(stat, "energyType", 0):
                continue
            if self.functions and "discard_eot" in self.functions.tags(cid):
                continue
            if board.deck_definitely_has(cid):
                return True
        return False

    def _attack_wins(self, obs, board, option, opp) -> bool:
        """True iff taking this ATTACK wins the match THIS turn — its own KO(s) take my last prize, or
        it empties the opponent's board. Per-attack and CONSERVATIVE (under-counts riders rather than
        over): a false Lethal is the one catastrophic error, so soundness beats completeness. A
        simultaneous double-KO is a draw, not a win (ADR-0022 #2), so it never wins here."""
        aid = option.get("attackId")
        hp = (opp or {}).get("hp", 0)
        # Damage oracle (ADR-0032): ignore-flag attack (Nebula Beam) KOs through prevent_ex_damage wall old
        # path zeroed. bound="min" = sound FLOOR: coin/conditional contributes worst case, never locks phantom Lethal.
        dmg = self.predicted_damage(self._my_active_id(obs), aid, opp, bound="min",
                                    context=self._damage_context(obs))
        active_ko = bool(hp and dmg >= hp)
        if active_ko and self._is_simultaneous_draw(board, aid, self._prize_value(opp)):
            return False
        prizes_taken = ((self._prize_value(opp) if active_ko else 0)
                        + self._snipe_ko_prizes(board.opp_bench, self._rider_snipe(aid)))
        if prizes_taken >= board.my_prizes_remaining:
            return True
        return active_ko and not board.opp_bench       # KO leaves them no Pokémon to promote

    def _win_lock_store(self, obs, recorded) -> None:
        """Materialize a VERIFIED win line's confirmed cascade as the turn-scoped locked line
        (ADR-0037 stage 3, `lethal_veto`): the engine-driven selects, each an entry
        ``{ctx, max, drive, chosen}`` where ``chosen`` is the picked options' identity tuples and
        ``drive`` marks a hidden-zone pick (prize) the replay must policy-drive. Only a verified
        lock ever stores one — a None-verdict lock has no confirmed cascade to replay."""
        self._locked_line = {"turn": (obs.get("current") or {}).get("turn"),
                             "queue": list(recorded)}

    def _option_identity(self, obs, select, option) -> tuple:
        """The live-matchable identity of one select option — type + attack + resolved card +
        in-play target + owner. Deliberately EXCLUDES the option's menu index (the replay's whole
        point is index-independence); a visible-zone card resolves by id, so a sim pick maps onto
        the live menu wherever it sits."""
        return (option.get("type"), option.get("attackId"),
                self._option_card_id(obs, select, option),
                option.get("inPlayArea"), option.get("inPlayIndex"), option.get("playerIndex"))

    def replay_locked_line(self, obs, select):
        """The locked line's next step, replayed against the live select (ADR-0037 stage 3), as
        ``(chosen, TurnLine)`` — or None when there is nothing to replay: veto off, no lock, the
        lock expired (a new turn — natural, silent), the entry is a hidden-zone pick (policy-drives
        it, entry consumed, lock kept), the queue ran dry, or ANY identity failed to match — the
        mismatch path also clears the lock and raises the sparse ``lethal_lost`` flag
        (`_lethal_lost`, telemetry) so a live sim-vs-reality divergence is countable. Never a blind
        index: every replayed pick is identity-resolved on the LIVE menu."""
        if not self._planning:                         # mirror the refute counter's reentry guard:
            self._lethal_lost = False                  # an in-sim decide must never clobber the
        lock = self._locked_line                       # outer decision's loss flag
        if not self.lethal_veto or self._planning or lock is None:
            return None
        if lock["turn"] != (obs.get("current") or {}).get("turn"):
            self._locked_line = None                   # a new turn: natural expiry, not a loss
            return None
        if not lock["queue"]:
            self._locked_line = None                   # line fully executed
            return None
        entry = lock["queue"].pop(0)
        if entry.get("drive"):
            return None                                # hidden-zone pick: policy-drives, lock kept
        options = select.get("option") or []
        live = {}
        for i, o in enumerate(options):
            live.setdefault(self._option_identity(obs, select, o), i)
        chosen = []
        for ident in entry.get("chosen") or ():
            i = live.get(tuple(ident))
            if i is None or i in chosen:
                self._locked_line = None               # sim diverged from reality: fall back to
                self._lethal_lost = True               # re-derivation, surface the loss
                return None
            chosen.append(i)
        if not chosen or select.get("context") != entry.get("ctx"):
            self._locked_line = None
            self._lethal_lost = True
            return None
        return (chosen, TurnLine(next_step=chosen, goal="win", kind="replay", verified=True,
                                 rationale="lethal (replay): executing the verified line"))

    def _engine_confirms_win(self, obs, line_steps, max_cascade: int = 12, record=None):
        """Tier-1 (ADR-0030): forward-simulate ``line_steps`` — a list of per-select index lists, the
        exact moves of a candidate win line — through the engine's OWN search and report whether IT
        declares me the winner. The grading engine, not my closed-form math, is the authority, so it
        also resolves what closed-form is blind to (abilities, status, Tera, evolution/turn-1 timing).

        Distinct from `_simulate_line` by design: THIS is the sound regime (``manual_coin=True``,
        drives to the engine's VERDICT); that is the heuristic ranker (coins auto-resolve, reads the
        end-of-turn BOARD). A winning attack does not flip ``result`` at the attack step: the engine
        first opens MY cascade selects (take the prize(s), pick a snipe/Damage target, pay a cost),
        so after the line's own steps the search keeps driving MY selects through the policy
        (``decide``, under the ``_planning`` guard so nothing nests or pollutes) until the engine
        reaches a verdict — measured live: the prize-take TO_HAND select is what every real win
        parks on.

        Sound and fail-safe:
          * ``manual_coin=True`` so a coin the line doesn't account for surfaces as a COIN_HEAD
            select → **None** rather than trust a chosen flip (never let the policy pick heads).
          * the select passing to the OPPONENT with no verdict = the win did not materialize before
            they act → False (a real refute: our win-shapes need no opponent action).
          * an exhausted cascade cap is **None** (undetermined never refutes); so is an unavailable
            search (lib-free suite), a missing ``search_begin_input``, or any error — the caller
            then keeps its sound closed-form verdict.
        The hidden-zone predictions are filled from my own deck list; the cascade's prize picks
        reveal predicted cards but the ``result`` verdict is invariant to WHICH prize is taken.
        Lazy DLL import keeps the fast unit suite from ever loading the native engine.

        ``record`` (a list, ADR-0037 stage 3): materialize each cascade select this drive answers as
        ``{ctx, max, drive, chosen}`` — the picked options' identity tuples, ``drive``=True for an
        all-hidden-zone pick (prize area: the sim's ids are predictions, replay must policy-drive) —
        the confirmed-cascade record a verified lock replays (`lethal_veto`)."""
        if not (obs or {}).get("search_begin_input") or not line_steps:
            return None
        try:
            from cg import api as cgapi
        except Exception:
            return None
        from dataclasses import asdict
        cur = obs.get("current") or {}
        yi = cur.get("yourIndex", 0)
        players = cur.get("players") or []
        me = players[yi] if 0 <= yi < len(players) and players[yi] else {}
        opp = players[1 - yi] if 0 <= 1 - yi < len(players) and players[1 - yi] else {}
        deck = list(self.deck)

        def take(n):
            return deck[: max(0, n)]

        was_planning = self._planning
        self._planning = True                          # the cascade re-runs decide(): never nest a
        try:                                           # search, never verify inside a verify
            ob = cgapi.to_observation_class(obs)
            st = cgapi.search_begin(ob, take(me.get("deckCount", 0)), take(len(me.get("prize") or [])),
                                    take(opp.get("deckCount", 0)), take(len(opp.get("prize") or [])),
                                    take(opp.get("handCount", 0)), [], manual_coin=True)
            for step in line_steps:
                st = cgapi.search_step(st.searchId, list(step))
            verdict = None
            for _ in range(max_cascade):
                o = st.observation
                c = o.current
                if c and c.result != -1:
                    verdict = c.result == yi           # the engine's own verdict
                    break
                sel = o.select
                if sel is None or c is None:
                    break                              # nothing to drive: undetermined -> None
                if sel.context == _COIN_HEAD:
                    break                              # an unaccounted coin: never choose the flip
                if c.yourIndex != yi:
                    verdict = False                    # passed to the opponent unresolved: no win
                    break
                od = _prune_none(asdict(o))
                chosen = list(self.decide(od))
                if record is not None:
                    osel = od.get("select") or {}
                    opts = osel.get("option") or []
                    picked = [opts[j] for j in chosen if 0 <= j < len(opts)]
                    record.append({
                        "ctx": osel.get("context"), "max": osel.get("maxCount"),
                        "drive": bool(picked) and all(p.get("area") == _PRIZE_AREA for p in picked),
                        "chosen": [self._option_identity(od, osel, p) for p in picked]})
                st = cgapi.search_step(st.searchId, chosen)
            cgapi.search_end()
            return verdict
        except Exception:
            try:
                cgapi.search_end()
            except Exception:
                pass
            return None
        finally:
            self._planning = was_planning

    # ═══ THE HEURISTIC RUNGS — rank-grade, never a guarantee (ADR-0031) ═══

    def _stabilize_then_ko_lines(self, obs, select, board, options, traces) -> list:
        """The **stabilize-then-KO** goal (ADR-0031): when my Active is DOOMED yet can also KO this turn,
        a clutch-heal (Wally's Compassion — heal a Mega ex to FULL, then bounce all its Energy to hand)
        played FIRST lets me heal AND still take the KO (re-attach one Energy, then the cheapest KO
        attack). It combines the heal + KO goals the greedy scorer can't: its `active_can_ko` suppressor
        drops the heal whenever a KO is available — the exact trap that caused 0cbc (`heal-and-stall` and
        `heal-and-KO` conflated). A candidate fires ONLY when healing genuinely stabilises (full HP beats
        the **Incoming**) AND the KO survives the Energy bounce (a re-attach still affords it), so it never
        heals-and-stalls and never forfeits the prize. A winning KO is owned by the Lethal Solver upstream,
        so this only ever combines a heal with a NON-winning KO. Every valid heal option is a candidate
        (they were all `return`-first before multi-candidate ranking; ties still break to the first)."""
        if not board.active_doomed:
            return []
        if not any(o.get("type") in (_ATTACK, _ATTACH) and t.tactical >= KO_SCORE
                   for o, t in zip(options, traces)):
            return []                                 # no KO reachable (on the menu, or unlocked by an
                                                      # attach — `_attach_lethal_tactical`, the 6858 shape:
                                                      # heal FIRST so the one attach lands post-bounce);
                                                      # nothing to preserve -> defer to hold-clutch-heal
        opp = self._opp_active(obs)
        active_stat = (self.stats.get(board.my_active_id)
                       if (self.stats and board.my_active_id is not None) else None)
        if not (opp and active_stat):
            return []
        lines = []
        for i, o in enumerate(options):
            if o.get("type") != _PLAY:
                continue
            cid = self._option_card_id(obs, select, o)
            if cid is None:
                continue
            cand = self._heal_candidate(cid, board, active_stat)
            if cand is None:
                continue
            healed_hp, energy_total = cand
            if healed_hp <= board.incoming_active_damage:
                continue                              # heal can't outlast the Incoming
            if self._best_affordable_ko_value(obs, board, opp, board.my_active_id, energy_total) <= 0:
                continue                              # heal's Energy cost would forfeit the KO
                                                      # (no `body`: a bounce rider re-attaches ANY
                                                      # bounced type — attached counts are stale here)
            value = self._leaf_value(prizes=self._prize_value(opp), active_survives=True,
                                     threat_removed=self._threat_magnitude(opp))
            lines.append(TurnLine(next_step=[i], goal="stabilize_then_ko", value=value,
                                  rationale="plan (stabilize_then_ko): heal, re-power, still KO for the prize"))
        return lines

    def _condition_holds(self, condition, board) -> bool:
        """Evaluate a clause's dynamic ``condition`` gate against the Board — TRUE only when the
        gate is absent or PROVABLY satisfied right now. The two board-checkable gates (Bianca's
        remaining-HP, Jumbo Ice Cream's attached-Energy) are evaluated; any other condition string
        fails closed (never plan on an amount that might not materialise)."""
        if not condition:
            return True
        if condition == "remaining_hp_30_or_less":
            return bool(board.my_active_hp) and board.my_active_hp <= 30
        if condition == "energy_3_plus":
            return board.my_active_energy >= 3
        return False

    def _heal_candidate(self, cid: int, board, active_stat) -> tuple[int, int] | None:
        """What playing heal-card ``cid`` on my Active would leave: ``(healed_hp, energy_total)``
        — the post-heal HP and the total Energy the Active can still pay an attack with this turn
        (attached after the card's rider, plus the manual attach if unused). Two sources, clause
        first (ADR-0032 4b): an Effect Clause (`kind: heal` with the measured ``amount`` and its
        ``rider``/``restriction``) generalizes the tag path; the `clutch_heal` Function Tag stays
        as the fallback (full heal + bounce — Wally's) for a clause-blind Pilot. None when ``cid``
        heals nothing, a restriction excludes my Active (``mega_only`` on a non-Mega), or the
        clause carries a ``condition`` the closed form can't evaluate (fail-closed: don't plan on
        an amount that might not materialise)."""
        max_hp = getattr(active_stat, "hp", 0) or 0
        attach = 0 if board.energy_attached else self._best_hand_attach_units(board.hand_ids, active_stat)
        for clause in (self.effects.clauses(cid) if self.effects else ()):
            if clause.get("kind") != "heal":
                continue
            if not self._condition_holds(clause.get("condition"), board):
                continue                              # gate fails / not board-checkable: fail-closed
            restriction = clause.get("restriction")
            if restriction == "mega_only" and not getattr(active_stat, "megaEx", False):
                continue
            amount = clause.get("amount")
            healed = max_hp if amount == "all" else min(max_hp, board.my_active_hp + int(amount or 0))
            rider = clause.get("rider")
            if rider == "bounce_energy_to_hand":
                energy_total = attach                 # all Energy bounced; only re-attach pays
            elif rider == "discard_own_energy":
                energy_total = max(0, board.my_active_energy - 1) + attach
            else:
                energy_total = board.my_active_energy + attach
            return (healed, energy_total)
        if self.functions and "clutch_heal" in self.functions.tags(cid):
            return (max_hp, attach)                   # legacy tag path: full heal + Energy bounce
        return None

    def _best_hand_attach_units(self, hand_ids, active_stat) -> int:
        """Energy units the best single attach from MY hand (``hand_ids``) provides my Active — 3
        for a discard-burst special (`discard_eot`, Ignition: CCC) onto an Evolution, 1 for any
        other Energy card, 0 when the hand holds none (`_attach_provided`'s model, hand-scanned:
        the 6858 heal-then-attach line re-powers Nebula Beam with the bounced-around Ignition, and
        a heal whose re-attach doesn't exist can no longer fake a preserved KO). Also the
        gust-affordability read (`_board`'s ``payable`` — the f31 no-energy gust gate)."""
        best = 0
        is_evo = bool(getattr(active_stat, "evolvesFrom", None))
        for cid in hand_ids:
            st = self.stats.get(cid) if self.stats else None
            if st is None or getattr(st, "hp", 0):
                continue
            tags = self.functions.tags(cid) if self.functions else []
            # an Energy card: a typed Energy, a Basic/Special by cardType, or the colourless
            # discard-burst special (engine reports Ignition's energyType as 0 — cf `_has_reusable_energy`)
            if not (getattr(st, "energyType", 0) not in (None, 0)
                    or getattr(st, "cardType", None) in (_BASIC_ENERGY, _SPECIAL_ENERGY)
                    or "discard_eot" in tags):
                continue
            best = max(best, 3 if ("discard_eot" in tags and is_evo) else 1)
            if best == 3:
                break
        return best

    def _engine_rank(self, obs, line: TurnLine) -> TurnLine:
        """Refine a committed line's leaf VALUE with the Tier-1 engine sim (ADR-0031 phase 3) — the exact
        end-of-turn board rather than the closed-form approximation — when the engine is available. The
        closed-form gate already CHOSE the line (a KO the greedy scorer misses), so the choice is
        unchanged; the sim sharpens ``value`` for telemetry and future multi-candidate ranking. Guards
        against reentrancy and falls back to the closed-form value when the engine is absent (unit path)
        or the sim errors — never crashes (decision 7)."""
        if self._planning or not (obs or {}).get("search_begin_input"):
            return line
        self._planning = True
        try:
            val = self._engine_leaf_value(obs, line.next_step)
        finally:
            self._planning = False
        return replace(line, value=val) if val is not None else line

    def _plan_fingerprint(self, obs, select) -> tuple:
        """A hashable/comparable snapshot of everything a plan depends on — the turn, both boards
        (id / energy / HP per Pokémon), my hand, my prize count, the manual-attach flag, and the option
        signature. Any reveal (a draw, a search, a KO, a new turn) changes it, so the cache re-plans; an
        unchanged board reuses the committed line."""
        cur = obs.get("current") or {}
        me, opp = self._my_player(obs), self._opp_player(obs)

        def body(p):
            return (p.get("id"), len(p.get("energies") or []), p.get("hp")) if p else None

        def side(pl):
            return (tuple(body(x) for x in (pl.get("active") or [])),
                    tuple(body(x) for x in (pl.get("bench") or [])))

        hand = tuple(sorted(c.get("id") for c in (me.get("hand") or []) if c and c.get("id") is not None))
        opts = tuple((o.get("type"), o.get("attackId"), o.get("area"), o.get("index"),
                      o.get("inPlayArea"), o.get("inPlayIndex")) for o in (select.get("option") or []))
        return (cur.get("turn"), side(me), side(opp), hand, len(me.get("prize") or []),
                bool(cur.get("energyAttached")), opts)

    def _ko_for_prizes_lines(self, obs, select, board, options, traces) -> list:
        """The **KO-for-prizes** goal (ADR-0031 phase 1-2): multi-step enabling lines that unlock an
        otherwise-missed KO of the opponent's Active, each valued by the leaf-eval scalar (prizes
        dominant + my Active's survival vs Incoming + the threat removed). One candidate per enabling
        first-step (retreat into a benched attacker; evolve the Active; play an energy-tutor
        Supporter), each regressed to "does this body, after the step PLUS this turn's one attach,
        KO?" and evaluated at its end-of-turn board. Empty when no such line exists."""
        opp = self._opp_active(obs)
        if not (opp or {}).get("hp"):
            return []
        opp_player = self._opp_player(obs)
        extra = 1 if (board.reusable_energy_in_hand and not board.energy_attached) else 0
        threat = self._threat_magnitude(opp)
        lines = []
        for i, o in enumerate(options):
            if o.get("type") == _RETREAT:
                cand = self._retreat_ko_candidate(obs, board, opp, opp_player, extra)
                kind = "retreat"
            elif o.get("type") == _EVOLVE and o.get("inPlayArea") == _ACTIVE:
                cand = self._evolve_ko_candidate(obs, select, board, o, opp, opp_player, extra)
                kind = "evolve"
            elif o.get("type") == _PLAY and self._is_evolution_tutor(obs, select, o):
                retreat_on_menu = any(x.get("type") == _RETREAT for x in options)
                cand = self._tutor_evolve_ko_candidate(obs, board, opp, opp_player, extra,
                                                       retreat_on_menu)
                kind = "evolution tutor"
            elif o.get("type") == _PLAY:
                cand = self._supporter_ko_candidate(obs, select, board, o, opp, opp_player)
                kind = "energy tutor"
            else:
                continue
            if cand is None:
                continue
            prizes, survives = cand
            value = self._leaf_value(prizes=prizes, active_survives=survives, threat_removed=threat)
            lines.append(TurnLine(next_step=[i], goal="ko_for_prizes", value=value,
                                  rationale=f"plan (ko_for_prizes): {kind} unlocks a {int(prizes)}-prize KO"))
        return lines

    def _ko_key_threat_lines(self, obs, select, board, options) -> list:
        """The **KO-the-key-threat** goal (the Goal Ladder's middle rung, CONTEXT.md *Turn Goal*;
        `planner_key_threat`): ENABLING lines that unlock a bench-snipe KO of the opponent's benched
        TOP-threat body — the greatest shared threat rank (`_body_threat_rank`: eventual attack
        power, forward evolution, energized/hand-size boosts). A snipe-KO already ON the menu needs
        no rung (the Tactical layer credits its prize KO_SCORE-class), but no closed-form hook scores
        the STEP that reaches one — `_retreat_to_lethal_tactical` and the KO-for-prizes generators
        test KOs of the ACTIVE only — so a retreat into the sniper, an evolve that brings the snipe
        attack online, or the energy tutor that powers it is invisible to the greedy scorer and the
        biggest future attacker survives. Bench snipes ignore W/R so ``rider >= hp`` is the exact KO
        test (`_snipe_ko_prizes`'s rule), and a Tera body is snipe-immune. Candidates join the
        KO-for-prizes pool: the leaf scalar ranks across the rungs (prizes dominant, then the removed
        threat's magnitude)."""
        opp_player = self._opp_player(obs)
        bench = [p for p in (opp_player.get("bench") or []) if p]
        if not bench:
            return []
        ranked = [(self._body_threat_rank(obs, p, board.read, board.posture_confidence,
                                          board.brief_target_roles,
                                          bool(board.opp_property("opp_is_engine_dependent", False))), p)
                  for p in bench]
        top_rank, top = max(ranked, key=lambda t: t[0])
        top_stat = self.stats.get(top.get("id")) if self.stats else None
        own_mag = float(getattr(top_stat, "maxDamage", 0) or 0) if top_stat else 0.0
        fwd_fn = getattr(self.stats, "forward_max_damage", None)
        fwd_mag = float(fwd_fn(top.get("id")) or 0) if fwd_fn is not None else 0.0
        threat_mag = max(own_mag, fwd_mag)             # the SAME damage basis the rank uses — a
                                                       # 0-printed body with a monster forward line
                                                       # (the Evolving-Threat case) still counts
        hp = top.get("hp", 0)
        if top_rank <= 0 or threat_mag <= 0 or not hp or self._is_tera(top.get("id")):
            return []                                 # nothing benched actually threatens (or Tera-immune)
        me = self._my_player(obs)
        opp = self._opp_active(obs)
        others = [p for p in ([opp] + [p for p in bench if p is not top]) if p]
        extra = 1 if (board.reusable_energy_in_hand and not board.energy_attached) else 0
        prizes = self._prize_value(top)
        lines = []
        for i, o in enumerate(options):
            if o.get("type") == _RETREAT:
                cand = self._retreat_snipe_candidate(me, others, hp, extra)
                kind = "retreat"
            elif o.get("type") == _EVOLVE and o.get("inPlayArea") == _ACTIVE:
                evolved_id = self._option_card_id(obs, select, o)
                if not self._affords_snipe_ko(evolved_id, board.my_active_energy + extra, hp):
                    continue
                estat = self.stats.get(evolved_id) if self.stats else None
                my_hp = getattr(estat, "hp", 0) or 0
                cand = (bool(my_hp) and self._incoming_worst(evolved_id, my_hp, others) < my_hp)
                kind = "evolve"
            elif o.get("type") == _PLAY:
                if (board.energy_attached or board.reusable_energy_in_hand
                        or not self._is_energy_tutor(obs, select, o)):
                    continue                          # mirrors `_supporter_ko_candidate`'s gate
                cand = self._retreat_snipe_candidate(me, others, hp, extra=1)
                kind = "energy tutor"
            else:
                continue
            if cand is None:
                continue
            value = self._leaf_value(prizes=prizes, active_survives=bool(cand),
                                     threat_removed=threat_mag)
            if (getattr(self, "objectives_path", False)          # Tier-3 (ADR-0040): a key threat ON my
                    and top.get("id") in board.path_target_ids):  # cheapest Prize Path advances the MATCH
                value += _PLANNER_PATH_W                          # win — sub-prize bump, ranks within rung
            lines.append(TurnLine(
                next_step=[i], goal="ko_key_threat", value=value,
                rationale=f"plan (ko_key_threat): {kind} unlocks the snipe-KO of the benched key threat"))
        return lines

    # ═══ THE GAMBLE RUNG — Tier-2 (ADR-0039): closed-form expectimax over Outcome Classes ═══
    # Deliberately probabilistic and BELOW every deterministic goal: it runs only when the win rung
    # and the whole heuristic pool passed. Exact probabilities (tracker-anchored hypergeometrics),
    # closed-form branch values, NO engine sim through the chance node (a fork is ONE predicted
    # determinization — untrusted for prediction-dependent outcomes). Depth-1 by construction.

    def _best_gamble_line(self, obs, select, board, options, traces):
        """The best **Gamble Line** on this menu, or None: play a Hand Refresh (`shuffle_hand`)
        FIRST — before the turn's attach — because the draw probably yields the Energy that turns
        this turn into a KO the held hand cannot reach (the Lillie's-Determination class,
        ADR-0039/REQ-GAMBLE-0001).

        EV = P(enabling Outcome Class) × the enabled KO's tactical value, exact hypergeometric over
        the shuffle-grown pool (tracker-anchored counts + the returned hand); committed only when it
        beats the DETERMINISTIC baseline (the best menu tactical, or the best after-attach chip the
        held Energy reaches) — EV equality is the break-even, never a fixed threshold. Stands down:
        switch off / mid-sim (the engine re-run stays deterministic policy) / turn 1 / attach already
        spent / a KO already on the tuned menu / a protected hand (wincon, line piece, ACE-SPEC Tool
        — the keep-value floors own those shuffles) / pre-anchor (no exact counts, mirroring
        `dont-refresh-into-a-probable-miss`) / the hand already holds an enabler (just attach it)."""
        if (not getattr(self, "gamble_lines", False) or self._planning
                or board.turn <= 1 or board.energy_attached or board.active_can_ko):
            return None
        if any(t.tactical >= KO_SCORE for t in traces):
            return None
        if ((board.wincon_in_hand and not board.wincon_in_play) or board.line_preevo_in_hand
                or board.irreplaceable_tool_in_hand):
            return None
        counts = board.deck_known_counts
        if not counts:
            return None
        from common.strategy.doctrines.doctrine_shuffle_refresh import _DRAW_COUNTS
        me = self._my_player(obs)
        hand = [c for c in (me.get("hand") or []) if c and c.get("id") is not None]
        ma = next((p for p in (me.get("active") or []) if p), None)
        opp = self._opp_active(obs)
        hp = (opp or {}).get("hp", 0)
        stat = self.stats.get(board.my_active_id) if (self.stats and board.my_active_id) else None
        if not (hp and stat and ma):
            return None
        classes = self._gamble_ko_classes(board, stat, ma, opp, hp, counts, hand)
        if not classes:
            return None
        det = self._gamble_det_baseline(board, stat, ma, opp, hp, traces, hand)
        pool = sum(counts.values()) + max(0, len(hand) - 1)   # the shuffle-grown draw pool
        burst_copies = self._gamble_burst_copies(counts, hand, stat)   # the recovery class (below)
        best = None                                           # (ev, index, rationale)
        for i, o in enumerate(options):
            if o.get("type") != _PLAY:
                continue
            cid = self._option_card_id(obs, select, o)
            branches = _DRAW_COUNTS.get(cid)
            if (branches is None or cid is None or not self.functions
                    or "shuffle_hand" not in self.functions.tags(cid)):
                continue
            ns = branches(board)
            for copies, ko_value, label in classes:
                from common.deck_odds import draw_hit_probability
                p = sum(draw_hit_probability(copies, pool, n) for n in ns) / len(ns)
                ev = p * ko_value
                if burst_copies and det > 0:
                    # the RECOVERY class: the miss branch may still redraw the held burst Energy
                    # (returned to the pool by the shuffle) and bank the same after-attach chip the
                    # deterministic line held — the "no {W}, but the Ignition came back → Nebula
                    # anyway" branch. Independence approximation on the conditional (documented;
                    # errs small, and only ever ADDS honest EV to the miss side).
                    p_re = sum(draw_hit_probability(burst_copies, pool, n) for n in ns) / len(ns)
                    ev += (1 - p) * p_re * det
                if ev > det and (best is None or ev > best[0]):
                    best = (ev, i, f"gamble: {p:.0%} the {max(ns)}-card draw finds {label} "
                                   f"for the KO (EV {ev:.0f} > held line {det:.0f})")
        if best is None:
            return None
        return TurnLine(next_step=[best[1]], goal="gamble", value=best[0], rationale=best[2])

    def _gamble_burst_copies(self, counts: dict, hand: list, stat) -> int:
        """Copies (pool-wide, INCLUDING the returned hand copy) of a held `discard_eot` burst Energy
        that funds an attack of my Active by COUNT — the recovery-class enabler: a miss that redraws
        it re-banks the deterministic after-attach line. 0 when no such burst is held."""
        best = 0
        for c in hand:
            cid = c.get("id")
            est = self.stats.get(cid) if (self.stats and cid is not None) else None
            if not est or getattr(est, "hp", 1) != 0:
                continue
            tags = self.functions.tags(cid) if self.functions else []
            if "discard_eot" not in tags:
                continue
            in_hand = sum(1 for c2 in hand if c2.get("id") == cid)
            best = max(best, counts.get(cid, 0) + in_hand)
        return best

    def _gamble_ko_classes(self, board, stat, ma, opp, hp: int, counts: dict, hand: list):
        """The KO-enabling **Outcome Classes** of a refresh draw: for each of my Active's attacks
        exactly ONE Energy short whose damage fells the opponent's Active, the class of draws
        containing ≥1 Basic Energy that fills the missing slot (its specific type, or any Basic for
        a colourless slot). Returns ``[(enabler_copies_in_pool, ko_value, label), …]``; an enabler
        already in HAND voids the class (no gamble needed — attaching it is the deterministic line)."""
        out = []
        attached = self._attached_type_counts(ma)
        hand_ids = [c.get("id") for c in hand]
        for aid in (stat.attacks or ()):
            cost = self.attack_costs.get(aid, 99)
            if cost != board.my_active_energy + 1:            # exactly one attach short
                continue
            if self.predicted_damage(board.my_active_id, aid, opp) < hp:
                continue
            ast = self.attack_stats.get(aid) if self.attack_stats else None
            types = getattr(ast, "energyTypes", ()) if ast else ()
            from collections import Counter
            need = Counter(t for t in types if t not in (0, None))
            deficit = {t: n - attached.get(t, 0) for t, n in need.items() if n - attached.get(t, 0) > 0}
            if sum(deficit.values()) > 1:
                continue                                      # more than one specific slot short
            want = next(iter(deficit), None)                  # None -> the short slot is colourless

            def _enables(cid) -> bool:
                est = self.stats.get(cid) if self.stats else None
                if not est or getattr(est, "hp", 1) != 0:
                    return False
                if getattr(est, "cardType", None) not in (_BASIC_ENERGY,):
                    return False                              # Basics only (a special Energy pays
                et = getattr(est, "energyType", None)         # colourless slots — under-counted, safe)
                return (et == want) if want is not None else True
            if any(_enables(cid) for cid in hand_ids):
                continue                                      # hand already holds the enabler
            copies = sum(n for cid, n in counts.items() if n > 0 and _enables(cid))
            if copies <= 0:
                continue
            label = f"a type-{want} Basic Energy" if want is not None else "any Basic Energy"
            out.append((copies, KO_SCORE + self._prize_value(opp), label))
        return out

    def _gamble_det_baseline(self, board, stat, ma, opp, hp: int, traces, hand: list) -> float:
        """The DETERMINISTIC baseline a gamble must beat: the best tactical already on the menu, or
        the best after-attach chip the HELD Energy reaches (attach the best hand Energy → biggest
        affordable non-KO damage) — the value the banked line (attach first, refresh after) keeps."""
        det = max((t.tactical for t in traces), default=0.0)
        hand_ids = frozenset(c.get("id") for c in hand)
        units = self._best_hand_attach_units(hand_ids, stat)
        energy_after = board.my_active_energy + units
        for aid in (stat.attacks or ()):
            if (self.attack_costs.get(aid, 99) <= energy_after
                    and self._attack_type_payable(aid, ma, extra_type=0, extra_units=units)):
                det = max(det, self.predicted_damage(board.my_active_id, aid, opp))
                # extra_type=0: the held attach is priced as colourless — funds {C} slots only, the
                # conservative read (a held TYPED enabler voids the gamble class upstream anyway)
        return det

    def _retreat_snipe_candidate(self, me, others, target_hp: int, extra: int):
        """``active_survives`` (bool) for the best benched body that, once retreated INTO (its Energy
        plus this turn's one attach), affords an attack whose bench-snipe rider KOs the ``target_hp``
        key threat — or None when no benched body reaches one. Among the capable bodies it prefers
        the one that SURVIVES the opponent's remaining Incoming (the sniped threat excluded)."""
        best = None
        for p in (me.get("bench") or []):
            if not p:
                continue
            if not self._affords_snipe_ko(p.get("id"), len(p.get("energies") or []) + extra, target_hp):
                continue
            my_hp = p.get("hp", 0)
            survives = bool(my_hp) and self._incoming_worst(p.get("id"), my_hp, others) < my_hp
            if best is None or survives > best:
                best = survives
        return best

    def _affords_snipe_ko(self, body_id, energy: int, target_hp: int) -> bool:
        """True iff ``body_id`` carrying ``energy`` can pay an attack whose unconditional bench-snipe
        rider (`_rider_snipe`) reaches ``target_hp`` — the exact snipe-KO test (no W/R on the Bench)."""
        stat = self.stats.get(body_id) if (self.stats and body_id is not None) else None
        if not (stat and target_hp):
            return False
        return any(self.attack_costs.get(aid, 99) <= energy and self._rider_snipe(aid) >= target_hp
                   for aid in (stat.attacks or ()))

    def _is_energy_tutor(self, obs, select, option) -> bool:
        """This PLAY option is a `tutor_energy` Trainer (Hilda class) — it searches an attachable
        Energy into hand, supplying the attach an enabling line lacks (the 4298 shape)."""
        cid = self._option_card_id(obs, select, option)
        return bool(cid is not None and self.functions and "tutor_energy" in self.functions.tags(cid))

    def _is_evolution_tutor(self, obs, select, option) -> bool:
        """This PLAY option is a `rush_evolve` Trainer (Salvatore class) — it evolves one of my
        in-play Pokémon straight from the deck, its own allowance covering setup-placed and
        this-turn bodies (so every in-play body is a legal target)."""
        cid = self._option_card_id(obs, select, option)
        return bool(cid is not None and self.functions and "rush_evolve" in self.functions.tags(cid))

    def _tutor_evolution_wins(self, obs, board, opp, body) -> bool:
        """SOUND: some DIRECT evolution of ``body`` (its `evolvesFrom` names the body) is PROVABLY
        still in my deck (the tracker's positive certainty, `Board.deck_definitely_has`), is
        Salvatore-eligible (no Abilities — the card's own fetch filter), and — carrying the body's
        Energy plus this turn's one attach — takes a min-bound winning KO (`_develop_wins`). The
        family's tier-4 win test; multi-hop descendants are excluded (one Salvatore = one hop)."""
        if not self.stats:
            return False
        base = self.stats.get(body.get("id"))
        if base is None or not getattr(base, "name", None):
            return False
        energy = len(body.get("energies") or [])
        extra = 1 if (board.reusable_energy_in_hand and not board.energy_attached) else 0
        for cid in set(self.deck):
            st = self.stats.get(cid)
            if (st is None or getattr(st, "evolvesFrom", None) != base.name
                    or getattr(st, "hasAbility", False)):
                continue
            if not board.deck_definitely_has(cid):
                continue
            if self._develop_wins(obs, board, opp, cid, energy + extra, body=body):
                return True
        return False

    def _retreat_ko_candidate(self, obs, board, opp, opp_player, extra: int):
        """``(prizes, active_survives)`` for the best benched body that KOs the opponent's Active AFTER a
        retreat plus this turn's one attach — but that does NOT already KO at its current Energy (that
        single-step case is the existing ``_retreat_to_lethal_tactical`` hook's job). Among the KO-capable
        bodies (all take the same prize off the shared target) it prefers the one that SURVIVES the
        opponent's post-KO Incoming. None when no benched body needs the attach to reach a KO. Reuses the
        shared sound KO valuation (``_best_affordable_ko_value``: Weakness/Resistance, ex-immunity)."""
        me = self._my_player(obs)
        best = None                                   # (prizes, survives)
        for p in (me.get("bench") or []):
            if not p:
                continue
            energy = len(p.get("energies") or [])
            if self._best_affordable_ko_value(obs, board, opp, p.get("id"), energy, body=p) > 0:
                continue                              # retreat alone already KOs — existing hook owns it
            if not (extra and self._best_affordable_ko_value(obs, board, opp, p.get("id"),
                                                             energy + extra, body=p) > 0):
                continue
            cand = (self._prize_value(opp), self._survives_after_ko(p.get("id"), p.get("hp", 0), opp_player))
            if best is None or cand > best:           # prefer more prizes, then survival (bool > bool)
                best = cand
        return best

    def _tutor_evolve_ko_candidate(self, obs, board, opp, opp_player, extra: int,
                                   retreat_on_menu: bool):
        """``(prizes, active_survives)`` if playing an **evolution-tutor Supporter** (Salvatore: evolve
        one of my in-play Pokémon straight from the deck — the ``rush_evolve`` tag) unlocks an
        otherwise-missed KO of the opponent's Active: some DIRECT, no-Ability evolution still LIKELY in
        my deck (``deck_contains_probability`` majority-odds — rank-grade, the win rung upstream owns
        the certain case), put onto an in-play body and carried to the Active (a benched body needs the
        retreat still on the menu), affords a KO with the body's Energy plus this turn's one attach.
        No closed-form hook scores a Supporter first-step, so this is net-new (the a212 shape:
        Salvatore -> Mega Starmie onto a setup Staryu -> free retreat -> attach -> Jetting Blow).
        None when no such evolution reaches a KO."""
        me = self._my_player(obs)
        bodies = [p for p in (me.get("active") or []) if p]
        if retreat_on_menu:
            bodies += [p for p in (me.get("bench") or []) if p]
        best = None
        for body in bodies:
            base = self.stats.get(body.get("id")) if self.stats else None
            if base is None or not getattr(base, "name", None):
                continue
            energy = len(body.get("energies") or [])
            for cid in set(self.deck):
                st = self.stats.get(cid)
                if (st is None or getattr(st, "evolvesFrom", None) != base.name
                        or getattr(st, "hasAbility", False)):
                    continue
                if board.deck_contains_probability(cid) <= 0.5:
                    continue                          # likely whiff: never plan on a improbable fetch
                if self._best_affordable_ko_value(obs, board, opp, cid, energy + extra,
                                                  body=body) <= 0:
                    continue
                my_hp = getattr(st, "hp", 0) or 0
                cand = (self._prize_value(opp),
                        bool(my_hp) and self._survives_after_ko(cid, my_hp, opp_player))
                if best is None or cand > best:
                    best = cand
        return best

    def _supporter_ko_candidate(self, obs, select, board, option, opp, opp_player):
        """``(prizes, active_survives)`` if playing a **tutor-energy Supporter** (Hilda: search an Energy
        into hand — the ``tutor_energy`` tag) unlocks an otherwise-missed retreat→attach→KO. The Supporter
        SUPPLIES the attachable Energy the plain retreat line lacks: with that fetched Energy modelled as
        this turn's one attach, a benched body KOs the opponent's Active after a retreat. The enabling
        first step here is the Supporter, not a retreat/evolve — no closed-form hook scores it, so it is
        net-new (corpus 4298). Fires ONLY when no reusable Energy is already in hand (else the plain
        retreat line covers it) AND the turn's one attach is still available (else the fetched Energy can't
        power the KO this turn). None otherwise. Reuses the sound retreat-KO valuation."""
        if board.energy_attached or board.reusable_energy_in_hand:
            return None
        if not self._is_energy_tutor(obs, select, option):
            return None
        return self._retreat_ko_candidate(obs, board, opp, opp_player, extra=1)

    def _evolve_ko_candidate(self, obs, select, board, option, opp, opp_player, extra: int):
        """``(prizes, active_survives)`` if EVOLVING the Active unlocks a KO of the opponent's Active this
        turn — the evolved form (the option's in-hand card) inherits the Active's Energy and, with this
        turn's one attach, its best affordable attack KOs. Evolving then attacking is legal the same turn
        (rules.md §evolution). No closed-form hook scores an evolve-unlock, so this is always net-new.
        Survival uses the evolved form's HP (closed-form approximation; the P3 engine-sim is exact).
        None when evolving doesn't reach a KO."""
        evolved_id = self._option_card_id(obs, select, option)
        if evolved_id is None:
            return None
        energy = board.my_active_energy
        ma = next((p for p in (self._my_player(obs).get("active") or []) if p), None)
        if self._best_affordable_ko_value(obs, board, opp, evolved_id, energy + extra,
                                          body=ma) <= 0:
            return None
        estat = self.stats.get(evolved_id) if self.stats else None
        my_hp = getattr(estat, "hp", 0) or 0          # evolved max HP — P3 engine-sim resolves damage exactly
        return (self._prize_value(opp), self._survives_after_ko(evolved_id, my_hp, opp_player))

    # ---- leaf evaluation (ADR-0031 decision 4): scalar over the resulting end-of-turn board ---------
    def _leaf_value(self, *, prizes: float, active_survives: bool, threat_removed: float = 0.0,
                    development: float = 0.0, value: float = 0.0) -> float:
        """The leaf-eval scalar over a resulting board: prizes taken (dominant, KO_SCORE-weighted) +
        the threat removed + my Active's survival vs Incoming + the development left on my board
        (engine-rank phase input, `_board_development`; 0 for closed-form candidates) + the Base
        Value Model's re-centred P(win) (``value ∈ [-0.5, 0.5]``, Tier-5/ADR-0042; 0 when off/absent).
        EVERY positional term is capped, and their capped sum stays below one prize, so a bigger KO
        always ranks first — a positional score can NEVER outrank a real prize (the hard-rung
        invariant, ADR-0031 decision 3). The learned term REFINES; it never overrides a sound rung."""
        return (KO_SCORE * prizes
                + min(_PLANNER_THREAT_CAP, _PLANNER_THREAT_W * threat_removed)
                + (_PLANNER_SURVIVAL_W if active_survives else 0.0)
                + min(_PLANNER_DEV_CAP, _PLANNER_DEV_W * development)
                + _PLANNER_VALUE_W * value)

    def _survives_after_ko(self, my_id, my_hp, opp_player) -> bool:
        """True if my body (``my_id`` at ``my_hp``) survives the opponent's Incoming AFTER I KO their
        Active this turn — their best affordable REMAINING attacker (a benched body they promote) can't
        KO it. The 1-ply survival term for the leaf-eval (ADR-0031 decision 2); the opponent's Active is
        excluded because the line Knocks it Out. False when my HP is unknown."""
        bench = (opp_player or {}).get("bench") or []
        return bool(my_hp) and self._incoming_worst(my_id, my_hp, bench) < my_hp

    def _incoming_worst(self, my_id, my_hp: int, opp_bodies) -> int:
        """The worst Weakness/Resistance-adjusted damage the opponent's affordable attackers among
        ``opp_bodies`` could deal to my body next turn — the closed-form **Incoming** (CONTEXT.md): the
        hardest-hitting body whose Energy plus one attach affords an attack, their predicted next
        promotion. An upper-bound estimate (counts each body's biggest attack once it can afford its
        cheapest), so a survival check is conservative. 0 when unknown."""
        my_stat = self.stats.get(my_id) if (self.stats and my_id is not None) else None
        if not (my_stat and my_hp):
            return 0
        worst = 0
        for p in opp_bodies:
            if not p:
                continue
            pstat = self.stats.get(p.get("id")) if self.stats else None
            if not pstat:
                continue
            energy = len(p.get("energies") or []) + 1          # allow one attach next turn
            if (pstat.minAttackCost or 99) <= energy:
                worst = max(worst, int(self._predicted_max_damage(pstat, {"id": my_id})))
        return worst

    def _threat_magnitude(self, opp) -> float:
        """The threat magnitude of the opponent's Active — its biggest printed attack — as the
        ``threat_removed`` term when a line KOs it. A coarse "how dangerous was the body I removed"
        signal; 0 when unknown."""
        stat = self.stats.get((opp or {}).get("id")) if (self.stats and opp) else None
        return float(getattr(stat, "maxDamage", 0) or 0) if stat else 0.0

    def _my_player(self, obs) -> dict:
        state = obs.get("current") or {}
        players = state.get("players") or []
        yi = state.get("yourIndex", 0)
        return players[yi] if 0 <= yi < len(players) and players[yi] else {}

    def _opp_player(self, obs) -> dict:
        state = obs.get("current") or {}
        players = state.get("players") or []
        oi = 1 - state.get("yourIndex", 0)
        return players[oi] if 0 <= oi < len(players) and players[oi] else {}

    # ---- Tier-1 Engine Search (ADR-0031 phase 3): simulate a line to its end-of-turn board -----------
    def _engine_leaf_value(self, obs, first_step) -> float | None:
        """The leaf-eval value of a candidate line computed on its ENGINE-SIMULATED end-of-turn board
        (ADR-0031 phase 3): the exact prizes taken and my Active's survival vs Incoming, read off the
        board the simulator produces rather than closed-form-approximated. A line that finishes the game
        in my favour scores above any prize count (dominant). None when the search is unavailable — the
        caller then keeps the closed-form leaf value (never crashes, decision 7)."""
        sim = self._simulate_line(obs, first_step)
        if sim is None:
            return None
        end, my_index, start_prizes, result = sim
        players = (end.get("current") or {}).get("players") or []
        me = players[my_index] if 0 <= my_index < len(players) and players[my_index] else {}
        opp = players[1 - my_index] if 0 <= 1 - my_index < len(players) and players[1 - my_index] else {}
        if result == my_index:                            # line wins outright — dominant
            return KO_SCORE * (start_prizes + 1)
        prizes_taken = max(0, start_prizes - len(me.get("prize") or []))
        active = next((p for p in (me.get("active") or []) if p), None)
        survives = False
        if active and active.get("hp"):
            bodies = (opp.get("active") or []) + (opp.get("bench") or [])
            survives = self._incoming_worst(active.get("id"), active.get("hp", 0), bodies) < active.get("hp", 0)
        return self._leaf_value(prizes=prizes_taken, active_survives=survives,
                                development=self._board_development(me),
                                value=self._value_term(end))    # Tier-5 learned leaf (ADR-0042)

    def _board_hypothetical(self, obs):
        """Build a :class:`Board` on a HYPOTHETICAL obs (a simmed end-of-turn board) for FEATURES
        only, WITHOUT letting it pollute the live turn-scoped memory — ``_board`` mutates the phase
        hysteresis (``_phase_prev``) and the path stickiness (``_my_path_prev``) as a side effect of
        the in-order decision sequence, which a ranked/escalated future must not perturb. Snapshot +
        restore both around the build (ADR-0042/0043)."""
        saved_phase = getattr(self, "_phase_prev", None)
        saved_path = getattr(self, "_my_path_prev", None)
        try:
            return self._board(obs, (obs or {}).get("select"))
        finally:
            self._phase_prev = saved_phase
            self._my_path_prev = saved_path

    def _value_term(self, end_obs) -> float:
        """The Base Value Model's contribution to a simmed leaf (ADR-0042): P(win) on the end-of-turn
        board, re-centred to ``[-0.5, 0.5]`` so a better-than-even board adds and a worse-than-even
        board subtracts. 0.0 when the model is off or absent (the null model returns 0.5 → term 0),
        so the closed-form leaf is unchanged. `_leaf_value` scales + caps it below a prize."""
        if not getattr(self, "value_model", None) or not self.value_model.present:
            return 0.0
        try:
            board = self._board_hypothetical(end_obs)
            from common.value.features import features_from_board
            return self.value_model.predict(features_from_board(board)) - 0.5
        except Exception:
            return 0.0                                   # a featurize/predict slip never crashes ranking

    @staticmethod
    def _board_development(me: dict) -> float:
        """The development left on MY simmed end-of-turn board — the `_PLANNER_DEV_W` term's input
        (ADR-0031 decision 4, exercised from the engine-rank phase): bodies in play plus the Energy
        attached to them. A coarse, engine-readable progress measure that splits prize-equal lines
        toward the one that leaves the stronger board (e.g. a line that spent nothing over one that
        stripped the Bench); `_leaf_value` caps its contribution below a prize."""
        bodies = [p for p in ((me.get("active") or []) + (me.get("bench") or [])) if p]
        return 10.0 * len(bodies) + 5.0 * sum(len(p.get("energies") or []) for p in bodies)

    def _simulate_line(self, obs, first_step, max_steps: int = 40, *, opponent_reply: bool = False):
        """Forward-simulate a candidate line through the Engine Search to my end-of-turn board (the
        Tier-1 seam). Steps ``first_step``, then re-runs my own closed-form policy (``decide``) on each
        intermediate SearchState until my turn ends (the select passes to the opponent) or the game
        finishes — the ADR-0031 "re-running the policy on each intermediate SearchState." Returns
        ``(end_obs_dict, my_index, start_prizes, result)`` or **None** when the search is unavailable,
        the observation carries no ``search_begin_input``, or anything errors (the caller falls back to
        the closed-form value — never crashes).

        With ``opponent_reply=True`` (Tier-6, ADR-0043) the sim does NOT stop at my turn end: it keeps
        stepping through the OPPONENT's turn using our own policy as the reply proxy, until it is my
        turn again or the game finishes — so the returned board is the start of MY next turn, seeing
        the opponent's best (proxy) answer. Every step decrements the per-move ``_search_steps``
        budget; the sim halts when it is spent (returns the board reached so far).

        Heuristic, not sound (ADR-0031): coins auto-resolve (``manual_coin=False``) and the opponent's
        hidden zones are predicted from my own deck list, so the end-of-turn board is trusted for
        ranking, not as a guarantee. The live game is untouched (the search forks an independent sim).
        Lazy DLL import keeps the fast unit suite from ever loading the native engine."""
        if not (obs or {}).get("search_begin_input") or not first_step:
            return None
        try:
            from cg import api as cgapi
        except Exception:
            return None
        from dataclasses import asdict
        cur = obs.get("current") or {}
        my_index = cur.get("yourIndex", 0)
        players = cur.get("players") or []
        me = players[my_index] if 0 <= my_index < len(players) and players[my_index] else {}
        opp = players[1 - my_index] if 0 <= 1 - my_index < len(players) and players[1 - my_index] else {}
        start_prizes = len(me.get("prize") or [])
        deck = list(self.deck)

        def take(n):
            return deck[: max(0, n)]

        def budget_ok() -> bool:
            if not opponent_reply:
                return True                            # Tier-1 sims are unbudgeted (the original path)
            self._search_steps = getattr(self, "_search_steps", 0) + 1
            return self._search_steps <= self.search_budget

        self._planning = True                          # never nest a search inside the reply policy
        try:
            ob = cgapi.to_observation_class(obs)
            st = cgapi.search_begin(ob, take(me.get("deckCount", 0)), take(start_prizes),
                                    take(opp.get("deckCount", 0)), take(len(opp.get("prize") or [])),
                                    take(opp.get("handCount", 0)), [], manual_coin=False)
            st = cgapi.search_step(st.searchId, list(first_step))
            crossed_my_turn_end = False
            for _ in range(max_steps):
                o = st.observation
                c = o.current
                if c is None or c.result != -1 or o.select is None:
                    break                                 # game over
                mine = c.yourIndex == my_index
                if not mine and not opponent_reply:
                    break                                 # Tier-1: stop at my turn end
                if not mine:
                    crossed_my_turn_end = True             # into the opponent's reply now
                elif crossed_my_turn_end:
                    break                                 # back to MY next turn — the depth-2 leaf
                if not budget_ok():
                    break                                 # per-move engine budget spent
                st = cgapi.search_step(st.searchId, list(self.decide(_prune_none(asdict(o)))))
            end = _prune_none(asdict(st.observation))
            result = st.observation.current.result if st.observation.current else -1
            cgapi.search_end()
            return (end, my_index, start_prizes, result)
        except Exception:
            try:
                cgapi.search_end()
            except Exception:
                pass
            return None
        finally:
            self._planning = False

    # ═══ TIER-6 ESCALATION (ADR-0043): budgeted depth-2 tree for the opponent-CHOICE residue ═══
    # Closed-form (Tiers 0-3) is blind to the opponent's REPLY: two attacks can price identically
    # this turn yet leave very different boards after the opponent's best answer. When the tuned
    # scoring can't separate the top attacks (a race tie within ε), escalate — sim each candidate
    # through MY turn AND the opponent's reply (our own policy as the proxy), then rank by the leaf
    # (value model when present, else closed-form). Hard per-move step budget; the tuned pick is the
    # guaranteed fallback (budget exhausted / engine absent → return None → tuned scoring decides).

    def _escalate(self, obs, select, board, options, traces):
        """A committed Turn Line from the depth-2 escalation, or None to defer to the tuned scoring.

        Fires only when: the ``escalation`` switch is on, a search budget is set, we're not already
        mid-sim, and the top attack options are a **close race tie** (``_close_attack_tie``). Each
        tied attack is simulated two-ply (my turn + the opponent's reply) and ranked by the
        resulting board's leaf value; the best commits ONLY if it strictly beats the tuned top
        attack's own two-ply value (else defer — escalation never overturns a clear tuned pick).
        Budget-guarded: ``_search_steps`` is capped per move, and any engine slip returns None."""
        if (not getattr(self, "escalation", False) or self._planning
                or self.search_budget <= 0 or not (obs or {}).get("search_begin_input")):
            return None
        tied = self._close_attack_tie(options, traces)
        if len(tied) < 2:
            return None
        self._search_steps = 0                         # per-move engine-step budget (reset per plan)
        scored = []
        for i in tied:
            val = self._two_ply_value(obs, [i])
            if val is not None:
                scored.append((val, i))
            if self._search_steps >= self.search_budget:
                break                                  # budget spent — rank what we reached
        if len(scored) < 2:
            return None                                # not enough sims completed → defer (fallback)
        scored.sort(reverse=True)
        best_val, best_i = scored[0]
        tuned_top = max(tied, key=lambda i: traces[i].tactical)   # the pick tuned scoring would make
        if best_i == tuned_top:
            return None                                # escalation agrees → let tuned scoring own it
        tuned_val = next((v for v, i in scored if i == tuned_top), None)
        if tuned_val is None or best_val <= tuned_val:
            return None                                # no strict improvement → defer
        return TurnLine(next_step=[best_i], goal="escalation", value=best_val,
                        rationale=f"escalation: depth-2 tree prefers attack [{best_i}] over the "
                                  f"tuned tie-pick [{tuned_top}] (opponent-reply-aware)")

    def _close_attack_tie(self, options, traces) -> list:
        """Indices of the ATTACK options whose tactical score is within ``_ESCALATE_EPS`` of the top
        attack — the close race tie the closed-form can't separate. Empty (or singleton) when one
        attack clearly leads, a KO is on the menu (KO_SCORE-class — no tie to break), or there are
        fewer than two attacks. Only these few candidates pay the engine cost."""
        atks = [(t.tactical, i) for i, (o, t) in enumerate(zip(options, traces))
                if o.get("type") == _ATTACK and t.tactical > 0]
        if len(atks) < 2:
            return []
        top = max(a[0] for a in atks)
        if top >= KO_SCORE:
            return []                                  # a KO dominates — nothing to escalate
        tie = [i for score, i in atks if top - score <= _ESCALATE_EPS]
        return tie if len(tie) >= 2 else []            # a lone leader is no tie to break

    def _two_ply_value(self, obs, first_step) -> float | None:
        """The leaf value of ``first_step`` after MY turn AND the opponent's reply (ADR-0043): sim my
        turn to its end, then continue stepping the engine through the OPPONENT's turn using our own
        policy as the reply proxy, until it is my turn again or the game ends, and read the leaf on
        that board. The opponent-choice-aware read closed-form lacks. None when the search is
        unavailable / the budget is spent / anything errors (caller falls back)."""
        sim = self._simulate_line(obs, first_step, opponent_reply=True)
        if sim is None:
            return None
        end, my_index, start_prizes, result = sim
        players = (end.get("current") or {}).get("players") or []
        me = players[my_index] if 0 <= my_index < len(players) and players[my_index] else {}
        opp = players[1 - my_index] if 0 <= 1 - my_index < len(players) and players[1 - my_index] else {}
        if result == my_index:
            return KO_SCORE * (start_prizes + 1)
        if result == 1 - my_index:
            return -KO_SCORE                           # the reply WON for them — worst outcome
        prizes_taken = max(0, start_prizes - len(me.get("prize") or []))
        active = next((p for p in (me.get("active") or []) if p), None)
        survives = False
        if active and active.get("hp"):
            bodies = (opp.get("active") or []) + (opp.get("bench") or [])
            survives = self._incoming_worst(active.get("id"), active.get("hp", 0), bodies) < active.get("hp", 0)
        return self._leaf_value(prizes=prizes_taken, active_survives=survives,
                                development=self._board_development(me), value=self._value_term(end))
