"""**The sequence composer** — beam search over within-turn action SEQUENCES, scored by end-state
differencing (POC-T4/4, Issue #385; governing spec Issue #263).

`common.apply_option` answers *"what would the board be if I did this?"* and `common.state_value`
answers *"what is that board worth?"*. This module is what puts them in a loop: it enumerates the
sequences a turn could take, transitions each one through the seam, scores the end board with the
leaf, and reports which first action the best sequence commits to.

    score(sequence) = state_value(end board) + EV(terminal action),   EV(end-turn) = 0

**DARK.** Nothing in production calls :func:`compose`. Arming it at the MAIN menu is T4/5's
(Issue #386), and T4/5 **deletes** the switch rather than flipping it — a composer flag that survives
the track is a defect against ADR-0092's no-dark-flags acceptance. Both ADR-0072 gates therefore see
byte-identical output at this commit, which is the acceptance line that proves the darkness.

## The ordering heuristic is UNIFORM 1-ply differencing — no per-family logic exists here

Ruled 2026-08-01 (Issue #263 § *The ordering heuristic*), superseding an earlier *"per-class top-k by
local marginal"* draft. Apply the single option through the seam, `state_value` the result, rank by
the delta — for **every** option kind. The same scorer runs at 1 ply and at n ply, so the
ordering-disagrees-with-the-leaf bug class cannot arise by construction, and a heal / fetch / Tool
equip / Stadium / draw Supporter (none of which has a local price at all) is ranked on the same scale
as an attach.

Options resolve by the seam's three fates:

* **MODELLED** and **ENGINE-RESOLVED** are ordinary candidates. ENGINE-RESOLVED is 1-ply only; at
  depth >= 1 the seam refuses it, because the board is synthesized and the native engine cannot be
  handed one back.
* **REFUSED** cannot be applied, so it becomes a **one-action terminal candidate flagged as a
  coverage gap** — surfaced in :attr:`ComposerResult.gaps`, never silently competing with scored
  sequences and never silently dropped. `apply_option.must_expand` is the policy; this module obeys
  it rather than re-deciding it.

## Two collapses run, on different axes, and they compose

* **Option Equivalence** (ADR-0091) dedupes indistinguishable SIBLINGS at one ply: one representative
  per class via `class_representatives`, values fanned to members via `fan_out`.
* **Commutative-block collapse** (Issue #263 § *Commutative-block collapse*) dedupes ORDERINGS of
  distinct options across depth. Emitted a-priori as the SUBSET lattice — 2**n candidates, one
  canonical ordering per subset — never generate-then-hash-then-merge.

The lattice is generated by :func:`_admissible_in_block`: inside a block a member may only extend the
sequence if its canonical key is strictly greater than the last block member's. For *n* pairwise
commuting options that yields exactly the 2**n subsets (8 / 16 / 32 for n = 3 / 4 / 5) against the
16 / 65 / 326 ordered prefixes a naive tree holds, and duplicates are never CREATED, which is the
difference the spec insists on: a post-hoc transposition table pays full generation cost first.

**Blocks are licensed ONLY by proven per-option footprints, and fail closed.**
`apply_option.option_footprint` + `footprints_commute` are asked; an unknown or partial footprint
commutes with nothing, and a revealing play can never join a block whatever its footprint says.

**The canonical in-block order is the information-before-commitment tier order**
(`sound_rules.information-before-commitment`, ADR-0095 decision 1). Its ratified reason survives the
move verbatim — *"digging first and digging second reach the same end state, so no function of that
state separates them"* — and generalises to exactly the block case: inside a commutative block NO
function of the end state separates any ordering, so the doctrine order is the principled canonical
choice rather than an arbitrary one. Canonical ordering is also what makes the Issue #254 index-order
bug class (a KO reachable from one bench slot and missed from the isomorphic other) structurally
impossible instead of hand-fixed.

## An Expectation is ranked by its MAX, never by `.expected()`

Both seams that hand this module an `Expectation` emit a **choice** node, not a chance node, and both
rule the consequence in their own headers: `board_expectation` (*"For a choice node the true value is
the max … The composer takes the max over `classes`"*) and `board_choice.deferred_target` (*"the
composer takes the max over `classes`, never `.expected()`"*). A deck search is not a coin flip — the
player sees the whole deck and CHOOSES, so an `OutcomeClass.probability` there is an availability
weight (*"is the target in the deck at all"*, `deck_odds.p_contains`) rather than a chance-node
probability, and a deferred target is a pick by construction.

So :meth:`~common.apply_option.Expectation.best` orders and `expected()` does not. Ranking on the
mean under-prices every reveal-bearing and every target-deferring sequence, which at ordering time is
a PRUNED option rather than an undervalued one. Both bounds are reported per node
(:attr:`ComposerResult.bounds`) because each is wrong in a different direction — the max over-reads a
5%-likely target at its full value — and the gap between them is this module's epistemic exposure,
recorded rather than smoothed into a third number nobody ruled on.

## Deferred-target EXPANSION, not beam admission (ADR-0121)

An option whose target the engine defers to a follow-up select — a `_RETREAT`, a Boss's Orders, a
Crispin — has a point transition that moves almost nothing. `board_delta._retreat` writes
`allowance_retreat_used` alone and **no `state_value` family reads the retreat allowance**, so its
1-ply delta is *exactly* 0.0 rather than approximately so. Under uniform differencing that reads as
*never explore this*.

Issue #392 offered a structural beam-admission whitelist and it was **rejected**: admission buys
*presence* without *comparability*, so the ~0 score stays a lie and this beam ranks on it. Expansion
dissolves the bug instead — :func:`choose_target` resolves the target class against the board and
scores one fully synthesized instance per legal target, so there is no ~0-scored retreat left to
admit. Measured: `85046350|0|decision|32` +0.00075 over 2 classes, `86091435|0|decision|35` +0.00186
over 4.

Three properties, each load-bearing:

* **D1 — unconditional.** `expand_deferred_targets=True` is passed as a CALL-SITE argument, because
  `apply_option` is pure and the flag is deployment config. This composer is *written against*
  expansion, so it is not switchable here; `runtime.PROFILE["deferred_target_expansion"]` stays False
  and becomes an orphan for T4/5 to delete. **Every other caller keeps the default `False`** — both
  ADR-0072 gates and the ADR-0098 parity lane therefore see the byte-identical seam they saw at
  Issue #382, which is what makes this module's darkness mechanically checkable.
* **D4 — parent-slot accounting.** An expanded family holds **ONE** beam slot, taken by its best
  child: score every instance, `argmax`, emit one candidate carrying
  ``(parent_option, chosen_target, score)``. The fan-out is evaluation-time, never
  candidate-generation, so beam width `k` keeps its pre-expansion meaning and the epsilon band and
  margin telemetry keep meaning what Issue #263 says they mean. Flat competition was rejected for
  silently redefining `k` (a Crispin would need `k >= 40` before an unrelated play survived); a
  per-family quota for adding a second width parameter the telemetry has no notion of. The accepted
  loss — the *second*-best target is unreachable at this node — is bounded by D6 rather than silent,
  and is reported as :attr:`TargetChoice.runner_up`.
* **D6 — one evaluator, both sites.** :func:`rank_targets` is that evaluator. Issue #387 wires it at
  the follow-up select, where it RE-DECIDES on the real board rather than replaying this node's pick.
  Its docstring carries the reason, which is not the obvious one.

**What expansion COSTS, measured on the acceptance frames rather than asserted away.** A retreat that
used to price at a flat 0.0 now prices at a real number, and a real number can outrank something else
— so the ordering moves in both directions:

===== ============================ ============================
frame  ruled first step UNEXPANDED  ruled first step EXPANDED
===== ============================ ============================
f32    rank 4, delta **exactly 0**  rank 2, delta **+0.00224**
f35    rank 2, delta 0.0            rank 3, delta 0.0
f82    rank 4, **in beam**          rank 5, **OUT** (margin −0.093)
===== ============================ ============================

Corpus-wide the trade is positive — agreement with the human's ruling goes **79 → 82 of 270** — and
f32 is the case the whole ruling was written about: it reached the beam on the canonical tie-break
before and now EARNS its place on a score. **f82 is the counter-example and it is recorded, not
tuned around.** Its ruled step is an evolve that expansion pushes to rank 5 at ``k = 4``. Widening
the beam to 5 would make it pass, which is exactly what Issue #385 §S12.2 forbids — *"a near-miss
re-sizes the width from the measurement and records it, it does NOT get widened until it passes"* —
and :data:`BEAM_WIDTH` is derived from a TIME budget, not from acceptance coverage. So the cap stands
and the miss is reported here and by ``composer_lab.py --acceptance``.

## Re-resolution by INSTANCE — the trap the commutativity ruling flagged in advance

Element-level commutativity is a claim about the resulting BOARD, never about option ENCODINGS. An
option names its card by hand INDEX, and removing hand card 0 shifts card 3 to index 2 — so two plays
whose boards provably commute still have order-dependent encodings, and replaying a stored option
dict from a permuted position applies a **different play**. The failure is silent by construction: a
shifted index still resolves to *a* legal card, so it produces a plausible board rather than an error.

:func:`resolve_against` therefore re-resolves every step by the `(hand serial, body serial)` instance
key `apply_option.option_serials` produces, against the board the step is actually applied to. A
serial that is gone means the card was consumed and the option is dropped; an option that named no
resolvable instance at depth 0 is dropped at depth >= 1 rather than replayed on trust.

## Legality is RE-CHECKED, because a synthesized board has no menu

At depth 0 the engine's menu is the legality proof. At depth >= 1 there is no menu — the board is
this module's own synthesis — and `apply_option` models a transition rather than policing one, so
nothing else would stop the beam sequencing two manual Energy attaches. :func:`_still_legal` re-checks
the per-turn allowances at source (`docs/rules.md` §3: Energy attach 1, Supporter 1, Stadium 1,
Retreat 1, Attack 1-and-ends-the-turn) plus §4's evolution timing (*"Cannot evolve a Pokémon the turn
it was played/put into play"*). Fail closed: an unreadable card is not sequenced.

## The beam-quality package — THREE distinct mechanisms, deliberately not merged

Issue #263 § *Beam-quality package* warns against conflating them, so each has its own home here:

1. **Deterministic tie-break at SELECTION time** (:func:`selection_key`), in ONE place. Primary the
   sequence score; secondary the Worth of the touched card (`card_worth.role_value`, reached through
   `MySide.role_worth`, the sole-supplier accessor); then a stable card-id sort. This rule is on
   record because it fixed three CRITICAL production bugs (ADR-0062:29's oldest-attached
   fall-through; `mega_starmie` ep82867148 f48/f87; `mega_lucario` ep83661652 f33/f40/f44 —
   *"benched whichever Basic sat lowest in the menu"*), and a differencing composer is exactly as
   exposed to that class as the rung system it replaces.
2. **Epsilon-band admission at PRUNING time** (:func:`_admit`), a different mechanism. Top-k PLUS
   anything within :data:`EPSILON` of the k-th score, so a genuine near-tie with the cutoff is not
   hard-dropped. Measured against the corpus by `tools/train/composer_lab.py`, never guessed.
3. **Margin telemetry** (:class:`Margin`), required rather than optional. Per decision: the
   eventually-chosen line's first-step RANK at 1-ply relative to k and its score MARGIN to the k-th
   candidate, in the `working()`-adjacent shape `state_value` established. A first step that barely
   survives on many corpus frames is an early warning that beam width or term shaping needs work,
   visible BEFORE it fails silently on an unseen board.

## What this composer is STRUCTURALLY BLIND TO — declared here, before the beam was sized

Issue #263 ceiling #2: *"a play that moves state no term reads prices 0"* — and under uniform 1-ply
differencing a 0 delta is **never explored**, not merely undervalued. The consolidated checklist is
`data/leaf_lab/wave3-rulings.md` § *3b · The consolidated blind-spot checklist* (Issue #291's
closeout): **35 `blind_to` entries across 7 families, plus a 36th that is in no registry**. It is
cited rather than copied, because a second copy of a ruling record drifts. The shape of it, so a
reader meets the list before writing a beam rather than after:

* Six entries are **by design** (3, 17, 27, 28, 33 and half of 29) — the double-counting rule and the
  1-ply bound doing their jobs, not gaps.
* Four are **closed by this track's own scope**: entry 29 dies with the develop rollout (T4/5), and
  9 / 10 / 22 / 25 were narrowed by Issues #284 / #329 / #351.
* The live list's centre of gravity is `threat` — **15 of 35** — and entries **11, 20 and 21** each
  silently zero a family Issue #263 explicitly retires a rung into (gust whether-to-play,
  counter-placement, denial). Entry **11 is additionally UNOWNED**.
* The **36th** is Issue #376's ruled-and-accepted blindness: enabling cards (Boss's Orders, Premium
  Power Pro) *"may be underplayed until Issue #263 lands"* — owned by this track, with no `blind_to`
  entry because the term that would carry it is the one this track wires.

Two further ceilings, stated because they bound this module and are not defects in it:

* **Information value is not expressible by differencing at all.** Playing an informative card before
  a committing one versus after reaches the SAME end state, so no function of that state separates
  the two orderings (`apply_option`'s header; ADR-0095 decision 3). That is why the tier order above
  is a STRUCTURAL canonical choice and why `information-before-commitment` stays on the sound-rule
  whitelist as a preempting rule rather than being retired into this beam.
* **A sequence that ends at a REVEAL was a partial line priced as a finished one — RULED, ADR-0127.**
  The engine re-presents the menu after a draw/search, so the composer stops there and replans; such
  a candidate used to carry `EV(terminal) = 0` and be compared head-to-head against full attack lines
  carrying a prize. It now carries :func:`continuation_ev` — the best attack still reachable from the
  pre-reveal board, the same `attack_ev_legs` / `attack_ev` pair :func:`terminal_ev` composes, read at
  the truncation seam. `_stop_here` and a REFUSAL are excluded, each for its own recorded reason.
  Measured over the 270 MAIN ruled frames: agreement **90 -> 92**, `_PLAY` picks **9 -> 15**,
  **2 fixed / 0 broken**, and `leaf_evals` **identical** — the continuation is not a leaf call.

  **What it does NOT close is the `_PLAY` gap, and the size of that is measured too.** The human
  rules a `_PLAY` on **95** frames and the composer picks one on 15; of the 92 it misses, **77 are
  seam REFUSALS** that no valuation ruling can reach (`selection_key` sorts a gap candidate last
  whatever EV it carries) and are owned elsewhere — RNG-class under Issue #178's no-sampled-shuffle
  doctrine, `board_expectation` enumeration gaps under Issues #301 / #302, `board_delta` choice-key
  gaps under Issues #303 / #304 / #403 / #410. This ceiling is now a COVERAGE ceiling, not a
  valuation one. It remains the second reason the structural information rule is kept.

## Budget — the caps are STRUCTURAL constants chosen from a measurement

:data:`BEAM_WIDTH`, :data:`SEQUENCE_DEPTH` and :data:`EPSILON` are whitelisted together under
`sound_rules.composer-budget-caps` (`authored-scaffold`), with the derivation on that entry and the
re-measurement owed on grader hardware post-POC (Issue #273). The expectation-branch cap is
`board_expectation.BRANCH_CAP` and is NOT re-declared here — one store, per ADR-0087.
"""
from __future__ import annotations

import time
from dataclasses import dataclass, field
from typing import Mapping, Sequence

from common import apply_option as ao
from common import board_expectation as bx
from common import snapshot_coverage
from common.board_delta import Unmodellable
from common.option_equivalence import (
    AREA_ACTIVE, AREA_BENCH, AREA_HAND, canonical_keys, class_representatives, fan_out,
    option_equivalence,
)
from common.state_value import attack_ev, attack_ev_legs, state_value
from common.strategy.context import _ATTACH, _ATTACK, _END, _EVOLVE, _PLAY, _RETREAT

# ── the budget caps (whitelisted: `sound_rules.composer-budget-caps`) ─────────────────────────────

#: How many candidate sequences survive each pruning step. **Derived, not tuned** — see the whitelist
#: entry for the arithmetic. Sized against the two measurements already on the record rather than a
#: fresh guess: the post-Option-Equivalence menu width is P50 **6** / P95 **12** / max **23** and the
#: leaf costs P95 **6.57 ms** (Issue #291 §3a, over the 372 corpus frames both gates replay), while
#: the grader's own per-decision FLOOR is **>= 3.0 s** (2 vCPU x ~10 min per player per match,
#: against P95 137 / max 198 decisions per match over the 377 committed native traces).
#:
#: A full run costs at most ``1 + (SEQUENCE_DEPTH - 1) x BEAM_WIDTH`` node expansions of ``width``
#: leaf evaluations each: ``(1 + 3 x 4) x 12 = 156`` leaves ~ **1.03 s** at the P95 leaf, i.e. ~34% of
#: the grader floor. Anchored on the WIDTH half deliberately, the same reasoning `BRANCH_CAP` records:
#: the width is exactly 12 on every run while the millisecond half moves ~10% run-to-run and ~45%
#: between boxes, so a cap keyed to a wall-clock figure is a property of whoever ran it last.
#:
#: **Measured end to end** — `python tools/train/composer_lab.py` over the 374 corpus frames (278
#: composed) at these caps, three fresh processes on an OTHERWISE-IDLE box: per-decision wall-clock
#: **median 24.8-26.5 ms, P95 0.40-0.43 s, max 1.31-1.40 s**. The bound holds with room to spare: the
#: max is ~**44-47%** of the grader's >= 3.0 s per-decision floor and the P95 ~14%.
#:
#: The width is **not** derived from acceptance COVERAGE, and the distinction matters because the two
#: readings disagree: the human-ruled first step lands at rank P50 **2** / P90 **6** / P95 **7** over
#: the 361 gradeable frames, so ``k = 4`` reaches **81.7%** of ruled first steps (k=5 -> 88.1%,
#: k=6 -> 93.6%, k=8 -> 97.5%). Re-deriving the cap from that curve would be a different design call
#: — a coverage budget rather than a time budget — and is not made here.
#:
#: ⚠️ **Two cautions on that number, both learned the hard way.**
#:
#: 1. **The arithmetic above is quoted at the P95 WIDTH, so it under-predicts the widest menus by
#:    ~2x.** The LEAF-EVAL count — which is what the formula actually bounds — is **3515** corpus-wide
#:    and **323** on the widest frame, against the 156 the P95-width form predicts. The same formula
#:    at the observed MAX width gets it right: ``(1 + 3 x 4) x 27 = 351`` against 323. So the honest
#:    statement is *P95 width bounds the P95 decision, not the max one* — quote both or quote neither.
#: 2. **Wall-clock here is only meaningful on an idle machine, and a first pass at these figures was
#:    taken while a full pytest run was in flight.** It read median 35-58 ms / P95 0.58-1.14 s / max
#:    2.45-4.05 s and produced a false alarm — *"the max crosses the grader floor"* — that a review's
#:    independent re-measurement refuted. The tell was available and ignored: the LEAF-EVAL count is
#:    **identical under load and idle**, because the composer is pure, so any spread is the box rather
#:    than the search. Re-measure quiet, and cross-check against leaf evals before believing a
#:    millisecond figure. This is the same trap `BRANCH_CAP` records when it anchors on the WIDTH half.
#:
#: What survives that correction: the cost is **leaf-bound, not beam-bound**. Profiling the widest
#: frame (`86090164|1|turn|6`, 27 options) puts ~100% of the time inside `state_value` — `_hand_legs`
#: -> `needs` -> `_leaf_needs_resolution` -> `pilot._board`. Re-sizing was MEASURED rather than
#: assumed: over ``k`` in {2,3,4} x ``depth`` in {2,3,4} the corpus max does not move outside noise,
#: because leaf evaluations SATURATE at depth 2 (323 at depth 2, 3 and 4 alike — the beam exhausts the
#: legal options before the depth cap binds). Shrinking a cap that does not move the metric would be a
#: constant changed to look responsive, so the caps stand as derived.
#:
#: Machine, because Issue #291 §3a requires a dev-machine number be labelled one: Windows 11,
#: Python 3.11.9, Intel64 Family 6 Model 186 (12 logical cores) — **not** the grader's 2 vCPU.
BEAM_WIDTH = 4

#: Maximum actions in a composed sequence BEFORE its terminal action — i.e. the deepest commutative
#: block the lattice is allowed to reach. 4 bounds one block's a-priori lattice at
#: ``sum(C(n, j) for j <= 4)`` while leaving the worked triple of Issue #263 § *Commutative-block
#: collapse* (an Energy, an evolution and a Tool onto distinct targets) fully inside it with a slot to
#: spare. Truncation is REPORTED (`ComposerResult.stats["depth_truncated"]`), never silent.
#:
#: **It costs nothing over 2 on this corpus, measured**: leaf evaluations on the worst frame are 323
#: at depth 2, 3 and 4 alike, because the beam runs out of legal options before the cap binds. Kept
#: at 4 rather than shrunk to the measured saturation point precisely because that saturation is a
#: fact about THIS corpus's seam coverage (246 of 278 composed frames still carry a refusal), not
#: about the game — a deeper turn becomes reachable the moment Issues #403 / #410 widen the seam, and
#: a cap trimmed to today's coverage would silently bound tomorrow's.
SEQUENCE_DEPTH = 4

#: The epsilon-band admission width, **in prizes** — a candidate within this of the k-th score is
#: admitted alongside the top-k rather than hard-dropped. It is `family_diag.DECIDER_FLOOR`, the
#: corpus-calibrated threshold below which a family cannot be any frame's decider, so a candidate
#: inside the band is one the corpus says nothing separates. Carried under its own name rather than
#: imported, because `tools/` must never be a `src/` dependency; the agreement is asserted by
#: `test_composer.py`.
#:
#: **Swept against the corpus rather than guessed** (`python tools/train/composer_lab.py
#: --epsilon-sweep`, 374 frames, 278 composed). Over epsilon in
#: {0.0, 0.001, 0.005, 0.01, 0.05, 0.1}:
#:
#:     0.0            earned top-k 152/278   band-only 38   agree(ruled) 83   agree(chosen) 50
#:     0.001 - 0.01   earned top-k 150/278   band-only 40   agree(ruled) 82   agree(chosen) 50
#:     0.05 - 0.1     earned top-k 148/278   band-only 42   agree(ruled) 82   agree(chosen) 50
#:
#: ⚠️ **The sweep MOVES now, and its predecessor's not moving was a symptom rather than a result.**
#: Before deferred-target expansion (§S7) every band read identically, which meant the 39 band-only
#: admissions were EXACT ties and not near-ties — on `85046350|0|decision|32` all five options priced
#: exactly 0.0, so there was nothing for a band to be near. Expansion gives those options real
#: deltas, and the sweep separates: three plateaus, 4 frames of movement across the whole range.
#:
#: The value sits in the flat MIDDLE plateau, where 0.001 / 0.005 / 0.01 are indistinguishable. It is
#: not chosen as the argmax: 0.0 reads one agreement better (83 vs 82 of 270), which is a single frame
#: and not evidence that turning the band off is right — the band exists to keep a genuine near-tie
#: with the k-th slot, which is where a good enabling move is most likely to be lost, and one frame
#: is a worse reason to delete that protection than the corpus calibration is to keep it.
#: Re-sweep when the apply seam's coverage widens (246 of 278 frames still carry a refusal), because
#: that is what would make the deltas separate further.
EPSILON = 0.005

def _bench_max(model) -> int:
    """The engine's own ``benchMax`` for my side, or `board_delta`'s fallback.

    Read from the observation rather than assumed, and the fallback is `board_delta`'s so the two
    halves of "is this deploy legal" cannot disagree about the cap — a second constant here is
    exactly the drift ADR-0087 charges for one store over."""
    from common.board_delta import _BENCH_MAX
    obs = getattr(model, "source_obs", None) or {}
    players = ((obs.get("current") or {}).get("players")) or []
    seat = int(getattr(model, "my_index", 0))
    me = players[seat] if 0 <= seat < len(players) and players[seat] else {}
    return int(me.get("benchMax") or _BENCH_MAX)


# ── the canonical in-block order (ADR-0095 decision 1's tiers, over board facts) ──────────────────

#: `pilot._finish_turn_last`'s six tiers, re-expressed over the facts a StateModel supplies. The
#: NUMBERS and their meaning are ADR-0095 decision 1's and are not re-derived here; what differs is
#: the input, and the difference is forced: the Pilot's `_tier` reads `traces[i]` (a scored
#: `OptionTrace` carrying `tactical`, `card_id` and `fired`), which is Pilot plumbing no StateModel
#: supplies. The composer keys off the option, its card's `CardStat`, and its footprint's
#: `reveals_information` instead.
#:
#: **Two Pilot-side nuances are deliberately NOT reproduced**, because both are score-conditional and
#: a canonical ORDER must be a pure function of the board: the KO_SCORE promotions (a lethal
#: play/attach riding tier 0) and the *"an Evolve of the Active drops to the last tier when a KO is on
#: the menu"* demotion. Inside a commutative block neither can change the end board — that is the
#: block's defining property — so their absence changes no candidate's SCORE, only which member of an
#: indistinguishable ordering is emitted first.
TIER_INFORMATIVE = 0     # free AND informative: a draw / search / dig, a Bench fill, an evolve
TIER_COMMIT_FREE = 1     # free but COMMITTING: an Item / Stadium play that reveals nothing
TIER_SUPPORTER = 2       # the one-per-turn Supporter
TIER_COMMITMENT = 3      # the blind / costly commitments: the Energy attach, a Tool equip
TIER_SHUFFLE = 4         # a hand-SHUFFLE Supporter — it nukes the hand, so attach before it
TIER_ENDER = 5           # the turn-ENDER, plus Retreat / End / anything uncharacterised

#: The behavioural Function Tag that makes a Supporter a hand-NUKE, so an Energy attach sequences
#: ahead of it. Same tag `pilot._is_shuffle_refresh` reads; named once here rather than spelled again.
_SHUFFLE_TAG = "shuffle_hand"


# ── the shapes ───────────────────────────────────────────────────────────────────────────────────


@dataclass(frozen=True)
class Step:
    """One applied action inside a candidate sequence.

    ``option`` is the dict **as applied** — re-resolved against the board it actually hit, never the
    stored depth-0 dict replayed from a permuted position (see :func:`resolve_against`) — and it is
    STRIPPED of the composer's private origin stamp, because a `Step` is the shape that leaves this
    module and the stamp is not an engine field. Stripping at construction rather than at each
    consumer is what makes that a property of the type instead of a convention three call sites could
    each forget. ``index`` is the depth-0 menu index of the Option-Equivalence class this step came
    from, which is what the composer would COMMIT if this sequence wins."""

    option: Mapping
    index: int
    tier: int
    fate: str
    #: For a step whose TARGET was deferred to a follow-up select (§S7): the fingerprint of the
    #: instance the expansion chose, and how many it beat. D4 emits one candidate carrying
    #: ``(parent_option, chosen_target, score)`` and this is the middle term — without it a
    #: candidate would say the composer retreated while staying silent about whom it promoted.
    #:
    #: **Advisory, not a commitment.** D6 rules that the follow-up select RE-DECIDES on the real
    #: board through the same :func:`rank_targets`, so this records what the play was chosen FOR,
    #: never what the later select must do.
    chosen_target: tuple = ()
    target_classes: int = 0


@dataclass(frozen=True)
class Candidate:
    """One composed sequence and its score.

    ``score = leaf + terminal_ev`` — Issue #263 § *Terminal-action valuation*, with
    ``EV(end-turn) = 0``. ``coverage_gap`` is non-empty when the candidate exists only because the
    seam could not price something: a REFUSED option, or an attack no
    :func:`~common.state_value.attack_ev_legs` leg matched. Such a candidate is REPORTED, never
    silently competing with a scored sequence."""

    steps: tuple = ()
    terminal: Mapping | None = None
    terminal_index: int | None = None
    leaf: float = 0.0
    terminal_ev: float = 0.0
    score: float = 0.0
    coverage_gap: str = ""
    truncated: int = 0

    @property
    def first_index(self):
        """The depth-0 menu index this sequence commits to, or None for the empty (stop-now) line."""
        if self.steps:
            return self.steps[0].index
        return self.terminal_index

    def working(self) -> dict:
        """The per-leg breakdown, in the shape `state_value`'s ``working`` established — so a wave-3
        packet can show a human which leg carried a flip without a second convention to learn."""
        return {"leaf": self.leaf, "terminal_ev": self.terminal_ev, "score": self.score,
                "steps": len(self.steps), "truncated": self.truncated,
                "coverage_gap": self.coverage_gap}


@dataclass(frozen=True)
class Bounds:
    """**Both** bounds of one expectation node, plus what the cap dropped (§S3.4, §S3.5).

    Public, because it LEAVES this module on :attr:`ComposerResult.bounds` and
    `tools/train/composer_lab.py` reads it — the same rule §S5.4 applied to `option_serials`: a
    second consumer means a public name, never an underscore reached across a boundary.

    Reported rather than reduced to the one number that ordered, because the two are wrong in
    OPPOSITE directions and the gap between them is this seam's epistemic exposure: ``best`` prices
    a 5%-likely target at its full value, ``expected`` prices a free choice as if someone else made
    it. Neither is smoothed into a third number nobody ruled on.

    ``total_probability`` rides along because a capped enumeration that reads as a complete one is
    the no-silent-caps failure: it falls below 1.0 by exactly the dropped mass, so a reader can see
    what ``truncated`` cost without re-deriving it."""

    index: int
    best: float
    expected: float
    classes: int
    truncated: int
    total_probability: float

    def working(self) -> dict:
        return {"index": self.index, "best": self.best, "expected": self.expected,
                "gap": self.best - self.expected, "classes": self.classes,
                "truncated": self.truncated, "total_probability": self.total_probability}


@dataclass(frozen=True)
class Margin:
    """Issue #263 § *Beam-quality package* item 3 — **required**, not optional.

    How close the eventually-chosen line's FIRST step came to the beam cutoff: its rank at 1-ply
    ordering relative to ``k``, and its score margin to the k-th candidate. ``in_beam`` is False when
    the chosen first step survived only on the epsilon band or not at all — which is the beam-width
    sizing signal, and the thing that must be MEASURED on f32 / f35 / f82 rather than guessed."""

    rank: int | None = None
    k: int = 0
    ranked: int = 0
    in_beam: bool = False
    admitted: bool = False
    always_expand: bool = False
    chosen_delta: float | None = None
    kth_delta: float | None = None
    margin_to_kth: float | None = None

    def working(self) -> dict:
        return {"rank": self.rank, "k": self.k, "ranked": self.ranked, "in_beam": self.in_beam,
                "admitted": self.admitted, "always_expand": self.always_expand,
                "chosen_delta": self.chosen_delta, "kth_delta": self.kth_delta,
                "margin_to_kth": self.margin_to_kth}


@dataclass(frozen=True)
class ComposerResult:
    """What :func:`compose` returns.

    ``chosen`` is the winning candidate under :func:`selection_key`; ``fanned`` is the per-OPTION
    1-ply delta with each Option-Equivalence class's value spread across its members (`fan_out`), so
    a caller indexing the live menu gets an answer for every option and not only for representatives.
    ``gaps`` carries every refusal's reason — the telemetry half of *"a refusal is an unknown, not a
    zero"*.

    ``order`` is the depth-0 1-ply ranking as ``((menu index, delta), ...)``, best first. It is
    exported rather than kept private because the acceptance property Issue #263 § *Beam-quality
    package* item 3 actually asks about is *"the eventually-chosen line's first step"* for the
    composer's OWN answer and *"f32 / f35 / f82's first steps IN-BEAM"* for the human's RULED one —
    two different options, one ranking. :meth:`margin_for` is how a caller asks about the second
    without re-deriving the first.

    **``chosen`` is None on a menu the seam can price nothing on.** That is a REPORT, not a crash:
    at a non-MAIN select every option is a `_CARD` / `_YES` / `_NUMBER` whose whole content is a card
    effect, so all of them refuse, and the honest answer is *"the composer has no opinion here"*
    rather than the argmax of a set of unknowns. ``gaps`` says why, option by option."""

    chosen: Candidate | None = None
    candidates: tuple = ()
    margin: Margin = field(default_factory=Margin)
    fanned: tuple = ()
    order: tuple = ()
    admitted: frozenset = frozenset()
    always_expanded: frozenset = frozenset()
    blocks: tuple = ()
    gaps: tuple = ()
    #: Both bounds of every expectation node this run met (§S3.5), newest last. `max` is the number
    #: that ordered; `expected` is the reported lower bound; the gap between them is the exposure.
    bounds: tuple = ()
    stats: dict = field(default_factory=dict)

    def margin_for(self, index: int) -> Margin:
        """The margin telemetry for ANY depth-0 menu option, not only the chosen one.

        Issue #392's acceptance criterion is *"f32 and f35 reach the composer's beam at the chosen
        width, demonstrated by the margin telemetry"* — a claim about the option the HUMAN ruled,
        which is the one a beam would prune. Measuring the composer's own pick instead would answer a
        different question and would pass by construction whenever the composer picked at all."""
        return _margin_at(self.order, self.always_expanded, self.admitted, self.margin.k, index)


# ── instance re-resolution ───────────────────────────────────────────────────────────────────────


def resolve_against(model, option: Mapping) -> dict | None:
    """``option`` re-pointed at the instances it named, on the board ``model`` actually holds — or
    **None** when one of them is gone.

    The composer emits a block's subsets in an order the original menu did not have, and an option
    names its card by hand INDEX. Removing hand card 0 shifts card 3 to index 2, so a stored dict
    replayed from a permuted position applies a different play — and it does so SILENTLY, because a
    shifted index still resolves to *a* legal card. This is the re-resolution the 2026-08-04
    commutativity ruling required of any consumer of element-level footprints.

    The instance keys come from `apply_option.option_serials`, which is the ONE walk that resolves
    them (and honours the option's `playerIndex`). None is returned whenever an instance the ORIGINAL
    option named cannot be found again: the card was consumed, so the option is no longer a play.
    An option that named no resolvable instance in the first place — a targetless `_RETREAT`, an
    `_END` — carries no index to go stale and is returned unchanged."""
    obs = getattr(model, "source_obs", None) or {}
    seat = int(getattr(model, "my_index", 0))
    named = option.get("playerIndex")
    if named is not None and int(named) != seat:
        return dict(option)                      # an option about THEIR board keys nothing of mine
    players = ((obs.get("current") or {}).get("players")) or []
    me = players[seat] if 0 <= seat < len(players) and players[seat] else {}
    out = dict(option)

    hand_serial, body_serial = _origin_serials(option)
    if hand_serial is not None:
        index = _index_of(me.get("hand") or (), hand_serial)
        if index is None:
            return None
        out["index"] = index
    if body_serial is not None:
        for area, zone in ((AREA_ACTIVE, "active"), (AREA_BENCH, "bench")):
            index = _index_of(me.get(zone) or (), body_serial)
            if index is not None:
                out["inPlayArea"], out["inPlayIndex"] = area, index
                break
        else:
            return None
    return out


#: Where :func:`resolve_against` stashes the instance key an option was FIRST resolved against. It
#: rides the option dict rather than a parallel map because the dict is what travels through the
#: beam, and a parallel map is exactly the thing that gets out of step with a permuted sequence.
#: Private-by-name (a leading underscore is not a legal engine field) so it can never be mistaken for
#: something `src/cg/api.py` declares.
_ORIGIN = "_composer_origin"


def stamp_origin(model, option: Mapping) -> dict:
    """``option`` with its depth-0 instance key stamped on, ready to be re-resolved at any depth.

    Called ONCE per menu option, at depth 0, where the engine's own indices are still valid. Every
    later resolution reads the stamp rather than the (now stale) indices, which is what makes
    :func:`resolve_against` a function of the INSTANCE rather than of the position."""
    hand_serial, body_serial = ao.option_serials(model, option)
    return {**option, _ORIGIN: (hand_serial, body_serial)}


def _origin_serials(option: Mapping):
    """The stamped instance key, or ``(None, None)`` for an unstamped option.

    Unstamped means *"nothing to re-resolve"*, never *"resolve it from the current indices"* — an
    option whose serials were never captured must not be re-pointed by position, which is precisely
    the silent failure this module exists to prevent."""
    origin = option.get(_ORIGIN)
    if not origin:
        return None, None
    return origin[0], origin[1]


def _index_of(cards, serial):
    """Where ``serial`` sits in ``cards`` now, or None if it is gone."""
    for i, card in enumerate(cards or ()):
        if card and card.get("serial") == serial:
            return i
    return None


def strip_origin(option: Mapping) -> dict:
    """``option`` without the composer's stamp — what a caller hands back to the engine.

    Separate from :func:`resolve_against` on purpose: the stamp must survive every internal hop and
    must never leave the module, and one function that both re-resolves and strips would make the
    boundary a matter of call order."""
    return {k: v for k, v in option.items() if k != _ORIGIN}


# ── legality, re-checked because a synthesized board has no menu ──────────────────────────────────


def _still_legal(model, option: Mapping) -> bool:
    """Would the engine still offer this option on ``model``'s board?

    At depth 0 the menu IS the proof and this is a no-op. At depth >= 1 there is no menu, and
    `apply_option` models a transition rather than policing one — so without this the beam would
    happily sequence two manual Energy attaches, or evolve a Basic it benched on the same step.

    Every limit checked here is read at source, not recalled (`docs/rules.md` §3 *Action economy* and
    §4 *Evolution timing*, both rulebook-cited):

    * **Energy attach 1 per turn** — the manual attachment only; a Tool is an ordinary Trainer play
      and `docs/rules.md` §3 caps it not at all beyond one per Pokémon, so a Tool `_ATTACH` is gated
      on the holder rather than on the allowance.
    * **Supporter 1**, **Stadium 1** (*"and only if it differs from the one in play"*), **Retreat 1**.
    * **Evolution** — *"Cannot evolve a Pokémon the turn it was played/put into play"*, read off the
      engine's own `appearThisTurn` bit through `BodyView.new_in_play`.
    * **Bench capacity** — a deploy onto a full Bench. `board_delta._play` already refuses it, but as
      an `Unmodellable`, and the composer turns an `Unmodellable` into a COVERAGE GAP. That would put
      a phantom entry in the modelling backlog for a move that is merely illegal, so the legality
      check has to catch it first. The cap is the engine's own ``benchMax``.

    **What §4 says that this does NOT check, named rather than left to be discovered:** *"Cannot
    evolve on either player's very first turn of the game."* It is safe by construction rather than by
    omission — every candidate descends from an option the ENGINE offered at depth 0, and the engine
    does not offer an illegal evolve, so a first-turn evolve can never enter the tree for this
    function to re-reject. The four limits above are different: each is spent by an EARLIER STEP of
    the composer's own sequence, which is state the depth-0 menu could not have known about.

    Fail closed: an unreadable card, an unresolvable target or an unrecognised kind is NOT sequenced.
    A phantom option is a candidate the composer will happily rank."""
    kind = ao.transition_kind(option)
    if kind == _RETREAT:
        return not model.retreated
    card = _option_card_stat(model, option)
    if kind == _ATTACH:
        if card is None:
            return False
        if getattr(card, "is_tool", False):
            body = _target_body(model, option)
            return body is not None and not body.tool_ids
        return not model.energy_attached
    if kind == _EVOLVE:
        body = _target_body(model, option)
        return body is not None and not body.new_in_play
    if kind == _PLAY:
        if card is None:
            return False
        if getattr(card, "is_supporter", False):
            return not model.supporter_played
        if getattr(card, "is_stadium", False):
            return not model.stadium_played and model.stadium_id != card.cardId
        if getattr(card, "is_pokemon", False) and not getattr(card, "evolvesFrom", None):
            return len(model.mine.bench) < _bench_max(model)
        return True                              # an Item — no per-turn allowance and no capacity
    return True                                  # terminal kinds and anything the seam refuses


def _option_card_stat(model, option: Mapping):
    """The `CardStat` of the card an option plays from hand, or None.

    The HAND reference, deliberately: every allowance in `docs/rules.md` §3 is keyed on what is being
    PLAYED, not on what it lands on. A `_PLAY` names its hand index bare with no ``area`` at all,
    which is why the default is the hand rather than a skip — the same convention
    `apply_option._option_card` keeps."""
    obs = getattr(model, "source_obs", None) or {}
    seat = int(getattr(model, "my_index", 0))
    players = ((obs.get("current") or {}).get("players")) or []
    me = players[seat] if 0 <= seat < len(players) and players[seat] else {}
    area, index = option.get("area"), option.get("index")
    if area not in (None, AREA_HAND) or not isinstance(index, int) or index < 0:
        return None
    hand = me.get("hand") or ()
    if index >= len(hand) or not hand[index]:
        return None
    return model.card_stat(hand[index].get("id"))


def _target_body(model, option: Mapping):
    """The `BodyView` an option's in-play reference names, or None when it names none."""
    area, index = option.get("inPlayArea"), option.get("inPlayIndex")
    if not isinstance(index, int) or index < 0:
        return None
    if area == AREA_ACTIVE:
        active = model.mine.active
        return active if index == 0 else None
    if area == AREA_BENCH:
        bench = model.mine.bench
        return bench[index] if index < len(bench) else None
    return None


# ── the canonical in-block order ─────────────────────────────────────────────────────────────────


#: `trigger` -> the option KIND that clause fires with. The vocabulary is
#: `snapshot_coverage.VOCABULARY["trigger"]`'s own — *"which OPTION the clause rides (on_evolve /
#: on_bench_play / on_attach / on_attack)"* — read from the registry rather than invented here, and
#: `test_composer.py` asserts this map covers exactly `snapshot_coverage.CLAUSE_SELECTORS["trigger"]`,
#: so a new trigger value cannot silently fall through to "does not ride".
_TRIGGER_KIND = {"on_attach": _ATTACH, "on_evolve": _EVOLVE, "on_bench_play": _PLAY,
                 "on_attack": _ATTACK}


def _reveal_rides(model, option: Mapping) -> bool:
    """Does a revealing clause actually fire when THIS option is taken?

    **A different question from the footprint's, and the difference cost a real acceptance frame.**
    `option_footprint.reveals_information` asks *"can this CARD reveal at all?"* and is deliberately
    conservative, because it feeds `footprints_commute`'s veto — a card that might reveal must never
    join a commutative block. Routing is the narrower question, and answering it with the footprint
    refuses transitions the seam models perfectly well.

    Measured, not reasoned (`data/EN_Card_Data.csv` + `src/common/card_effects.json`, read at source):

    * **120 Drakloak** — its `draw` clause carries ``condition: once_per_turn_ability`` and the CSV
      prints it as *"[Ability] Recon Directive"*. The Ability is its OWN `_ABILITY` option; evolving
      into Drakloak reveals nothing, and `board_delta._evolve` models that evolve exactly. Routing on
      the footprint refused it, unpriced, on a live acceptance board — option 1 of
      `85046350|0|decision|32` (Issue #263's **f32**) is exactly that evolve. Same shape for
      66 Dudunsparce, 140 Fezandipiti ex and 675 Lunatone.

      ⚠️ An earlier draft of this note called that evolve *"f32's RULED first step"*. **It is not** —
      f32's ruling was REFRAMED on 2026-07-10 and the authoritative record is
      `tests/fixtures/corrections/dragapult_hammer_over_develop_f32.json`, whose
      ``claims.decision.correct`` is `[3]`, the `_RETREAT` (*"Retreat Dreepy → promote Budew
      (sacrificial item-lock wall)"*). The superseded `data/corrections/` record still carries `[1]`,
      and reading THAT is how the wrong claim got written. The routing fix stands on its own merits;
      only the sentence justifying it was wrong.
    * **19 Telepath Psychic Energy** — its `fetch` clause carries ``trigger: "on_attach"``, and the
      CSV prints *"When you attach this card from your hand to a {P} Pokemon, search your deck for up
      to 2 Basic {P} Pokemon and put them onto your Bench."* The reveal DOES ride the attach, and
      `board_delta._attach` never consults clauses at all (`_clause_writes` is reached only from
      `_play` and the Stadium gate), so letting it through would model the structural attach and drop
      a two-Pokemon Bench fill. It must refuse.
    * **1071 Meowth ex** — ``trigger: "on_bench_play"``: the reveal rides the `_PLAY`, so it routes to
      the Expectation like any Item.

    Fail closed in the direction that matters: an untriggered clause on a `_PLAY` rides it (a
    Trainer's effect IS the play), and an untriggered clause on any other kind does not (it is an
    Ability, which the engine poses as its own option)."""
    from common.board_delta import card_clauses
    kind = ao.transition_kind(option)
    card = _option_card_stat(model, option)
    if card is None:
        return kind == _PLAY                       # unreadable: keep the conservative `_PLAY` answer
    for clause in card_clauses(getattr(model, "combat", None), card.cardId) or ():
        values = set(snapshot_coverage.clause_values(clause))
        if not (values & snapshot_coverage.REVEALING_CLAUSES):
            continue
        trigger = clause.get("trigger")
        if trigger is not None:
            if _TRIGGER_KIND.get(trigger) == kind:
                return True
        elif kind == _PLAY:
            return True
    return False


def canonical_tier(model, option: Mapping, footprint=None) -> int:
    """This option's information-before-commitment TIER — the canonical in-block ordering
    (ADR-0095 decision 1, moved inside the composer by Issue #263 § *Commutative-block collapse*).

    Derived from the option, its card's `CardStat`, and — for the informative test — the per-option
    footprint's ``reveals_information``, which is the seam's own answer to *"does this ENLARGE the
    information set?"* rather than a second tag list beside it. Passing the footprint in is an
    optimisation only: the caller has already computed it for the commutativity test, and computing
    it twice on the ordering hot path is the cost `option_footprint`'s docstring exists about.

    Note the tier is TOTAL over the menu even though a revealing option can never join a block
    (`footprints_commute` vetoes it): the beam expands every admitted option, and an ordering key that
    answered None for some of them would fall through to menu position — the exact fall-through
    Issue #263 § *Beam-quality package* item 1 forbids."""
    kind = ao.transition_kind(option)
    if kind in (_ATTACK, _END, _RETREAT):
        return TIER_ENDER
    fp = footprint if footprint is not None else ao.option_footprint(model, option)
    if fp.reveals_information:
        return TIER_INFORMATIVE
    card = _option_card_stat(model, option)
    if kind == _EVOLVE:
        return TIER_INFORMATIVE                  # "evolve a benched Pokemon" rides the free band
    if kind == _ATTACH:
        return TIER_COMMITMENT                   # Energy AND Tool: a Tool is an `_ATTACH` (tier 3)
    if kind == _PLAY and card is not None:
        if getattr(card, "is_supporter", False):
            return TIER_SHUFFLE if _shuffles_hand(model, card) else TIER_SUPPORTER
        if getattr(card, "is_pokemon", False):
            return TIER_INFORMATIVE              # a Bench fill is free and reveals a better target
        return TIER_COMMIT_FREE                  # an Item / a Stadium: free but committing
    return TIER_ENDER                            # uncharacterised: last, fail closed


def _shuffles_hand(model, card) -> bool:
    """Does this Supporter NUKE my hand (`shuffle_hand`)? Asked of the Function Tags through the
    model's combat surface, which is the one place behavioural tags are read."""
    functions = getattr(getattr(model, "combat", None), "functions", None)
    if functions is None:
        return False
    try:
        return _SHUFFLE_TAG in (functions.tags(card.cardId) or ())
    except Exception:                            # noqa: BLE001 — an unknown card is not a shuffler
        return False


def canonical_key(model, option: Mapping, index: int, canon: str, footprint=None) -> tuple:
    """The TOTAL in-block ordering key: ``(tier, board-derived identity, menu index)``.

    ``canon`` is `option_equivalence.canonical_keys`' entry for this option — the ADR-0103 fingerprint
    that makes the key a pure function of the BOARD, so permuting the menu permutes these keys with it
    and invents no new ones. The menu index is last and separates only options that key equal on
    everything above it, exactly as `pilot._order_key` does."""
    return (canonical_tier(model, option, footprint), canon, index)


# ── commutative blocks ───────────────────────────────────────────────────────────────────────────


def commutative_blocks(model, options: Sequence[Mapping], indices=None) -> tuple:
    """Maximal sets of pairwise-COMMUTING options, as tuples of menu indices.

    Reported for telemetry and for the lattice tests; the beam itself asks :func:`_admissible_in_block`
    pairwise as it expands, because a block is a property of the sequence being built rather than a
    partition computed once. Greedy-maximal and deterministic: options are visited in menu order and
    each joins the first block whose every member it provably commutes with.

    The licence is `apply_option.footprints_commute` over per-OPTION footprints and nothing else.
    Fail closed everywhere — an unknown or partial footprint commutes with nothing, a revealing play
    can never join a block, and a pair that is merely *not proven* to conflict is treated as
    conflicting.

    ⚠️ **Corpus census, restated because it is a fact about SEAM COVERAGE and not about the lattice:**
    over the 278 composed frames the corpus yields **25 blocks, every one of size 2**. No corpus board
    exercises n >= 3, so the 8 / 16 / 32 counting property is proven by unit test and one hand-built
    triple — **not** by the corpus. That is exactly the shape of claim that reads as verified when it
    is not, so it is stated here rather than left to be inferred from a passing test."""
    prints = {i: ao.option_footprint(model, options[i])
              for i in (range(len(options)) if indices is None else indices)
              if not ao.is_terminal(options[i])}
    blocks: list[list[int]] = []
    for i in sorted(prints):
        for block in blocks:
            if all(ao.footprints_commute(prints[i], prints[j]) for j in block):
                block.append(i)
                break
        else:
            blocks.append([i])
    return tuple(tuple(b) for b in blocks if len(b) > 1)


def subset_lattice(members: Sequence) -> tuple:
    """Every SUBSET of ``members``, each in one canonical order — ``2**n`` tuples, never the
    ``sum(n!/(n-k)!)`` ordered prefixes.

    Generated a-priori by extending only with a member that sorts strictly AFTER the last one, which
    is the same rule :func:`_admissible_in_block` applies inside the beam. Stated as a standalone
    function so the counting property (8 / 16 / 32 against 16 / 65 / 326 for n = 3 / 4 / 5) is
    testable without driving a whole beam, and so the two spellings of the rule can be asserted
    identical."""
    out = [()]
    for member in members:
        out = out + [prefix + (member,) for prefix in out]
    return tuple(out)


def _admissible_in_block(key, block_keys) -> bool:
    """May a step with canonical ``key`` extend a block whose members' keys are ``block_keys``?

    Only when it sorts strictly after every one of them. That single rule is what turns the beam's
    tree into the SUBSET lattice: for *n* pairwise-commuting options it generates each subset exactly
    once, in the canonical order, and a duplicate ordering is never CREATED — which is the difference
    Issue #263 insists on against a post-hoc transposition table that pays full generation cost first
    and then needs a canonical state hash to merge."""
    return all(key > other for other in block_keys)


# ── the terminal action ──────────────────────────────────────────────────────────────────────────


def terminal_ev(model, option: Mapping) -> tuple:
    """``(EV in prizes, AttackEV or None, coverage-gap reason)`` for a TERMINAL option.

    ``EV(end-turn) = 0`` by definition — ending the turn buys nothing beyond the board already
    scored. ``EV(attack)`` composes `state_value.attack_ev` over POC-T4/3's extractor
    (`attack_ev_legs`), matched to the option's own ``attackId``.

    ⚠️ **Reads `AttackEV.total`, never the working-dict sum.** The `working()` shape is FROZEN and
    ASYMMETRIC: it omits ``total`` and emits ``next_turn_cost`` POSITIVE while ``total`` subtracts it,
    so a consumer that sums the dict gets ``total + 2 x next_turn_cost``. This is the consumer that
    docstring warns about.

    An attack no leg matches is a **coverage gap**, not a zero. Returning 0.0 quietly would sort a
    real attack below every scored line — *"a 0 delta is never explored, not undervalued"* — so the
    reason is carried out and the candidate is flagged, the same treatment a `Refusal` gets."""
    kind = ao.transition_kind(option)
    if kind == _END:
        return 0.0, None, ""
    if kind != _ATTACK:
        return 0.0, None, f"option kind {kind} is terminal but is neither attack nor end-turn"
    attack_id = option.get("attackId")
    for leg in attack_ev_legs(model):
        if leg.attack_id == attack_id:
            ev = attack_ev(**leg.kwargs)
            return float(ev.total), ev, ""
    return 0.0, None, (
        f"attack {attack_id!r} has no `attack_ev_legs` leg on this board — its EV is UNKNOWN, and "
        f"pricing it 0.0 would rank a real attack below every scored line")


def continuation_ev(model) -> float:
    """The best terminal action still REACHABLE from this board, in prizes — the second summand of a
    line the composer CUT rather than one it finished (ADR-0127, Issue #400 Phase 1).

    A sequence that ends at a REVEAL is not a turn that ENDED. The engine re-presents the menu after
    a draw or a search, so the attack allowance is untouched and the turn will still spend it; the
    missing summand is that terminal action, not zero. :func:`_stop_here` and a REFUSAL are both
    excluded from this — see :func:`_gap_or_reveal_candidate` for why each exclusion is a soundness
    property rather than a preference.

    Floored at 0 by ``default=0.0`` because ending the turn is always available and
    ``EV(end-turn) = 0``, so a board whose only attacks price negative continues at 0 rather than
    below it. **No new math and no constant:** this composes the same `attack_ev_legs` /
    `attack_ev` pair :func:`terminal_ev` composes for an `_ATTACK` option, read at a SECOND seam —
    the truncation point. Reads ``AttackEV.total``, never the working-dict sum, for the reason that
    function's own warning gives.

    ⚠️ **Answers from the BOARD, not from the menu**, which is exactly why the empty line must never
    inherit it: `attack_ev_legs` will happily price an attack the engine did not offer. That is
    harmless at a truncation (the turn really does continue) and unsound at ``_stop_here`` (the root
    stop-here has ``first_index is None``, so "commit nothing" would win a decision outright — 4 of
    270 corpus frames produced no pick at all when that arm was measured)."""
    return max((float(attack_ev(**leg.kwargs).total) for leg in attack_ev_legs(model)), default=0.0)


# ── deferred-target expansion (ADR-0121 decisions 1, 4 and 6) ────────────────────────────────────


@dataclass(frozen=True)
class ScoredTarget:
    """One instance of a deferred target, scored on the board it actually produces.

    ``rank`` is 1-based over :func:`rank_targets`' ordering and is what makes *"the second-best
    target"* a nameable thing rather than a number nobody kept — which matters because D4's accepted
    loss is precisely that the runner-up is unreachable at this node."""

    rank: int
    leaf: float
    model: object
    fingerprint: tuple = ()
    probability: float = 0.0


@dataclass(frozen=True)
class TargetChoice:
    """The winner of a deferred-target expansion, and what it beat.

    ``leaf`` is the score that ORDERS — the max over the enumeration, per §S3 — while ``expected``
    is the availability-weighted mean carried alongside as the reported lower bound. ``runner_up``
    is the second-best instance's leaf, or None when the space held one class: it is the size of
    D4's accepted loss, made visible rather than argued about."""

    scored: tuple = ()
    leaf: float = 0.0
    expected: float = 0.0
    truncated: int = 0
    total_probability: float = 0.0

    @property
    def best(self) -> ScoredTarget | None:
        """The chosen instance — the one the sequence continues from."""
        return self.scored[0] if self.scored else None

    @property
    def runner_up(self) -> float | None:
        return self.scored[1].leaf if len(self.scored) > 1 else None

    def working(self) -> dict:
        return {"classes": len(self.scored), "leaf": self.leaf, "expected": self.expected,
                "gap": self.leaf - self.expected, "runner_up": self.runner_up,
                "truncated": self.truncated, "total_probability": self.total_probability}


def rank_targets(model, expectation) -> TargetChoice:
    """**THE evaluator for a deferred target — one entry point, both sites** (ADR-0121 decision 6).

    Scores every enumerated instance with `state_value` on the board that instance actually produces
    and orders them best-first. `compose` calls it at the MAIN menu, where the target is still
    deferred; **Issue #387 calls this same function at the follow-up select**, where the engine has
    posed the `_SWITCH` / `_DISCARD_ENERGY` / `_TO_HAND` for real. That is the whole point of naming
    it: ADR-0100 §9's invariant is *"that the two sites run the same evaluator is what makes the old
    divergence — retreat BECAUSE Cinderace is worth promoting, then promote Budew — structurally
    impossible"*, and an invariant that depends on two call sites agreeing is only as strong as the
    discipline keeping them spelled the same.

    **The follow-up select REPLANS rather than replaying a commitment, and the honest reason is not
    the obvious one.** For a bare retreat nothing changes between choosing it and being asked whom to
    promote — the `_DISCARD_ENERGY` touches only the Active, every term of a promote's value reads
    the promoted body, and the opponent cannot act during my turn — so a commitment would provably
    agree *there*. The argument is that **Crispin already breaks it today**: *"Search your deck for up
    to 2 Basic Energy cards of different types, reveal them"* is information-revealing, which is a
    block boundary, and the recipient would have been chosen before the search resolved. Commitment
    makes coherence a standing per-member proof obligation over a vocabulary that will grow, whose
    failure mode is a legal, plausible, WRONG pick with no error anywhere. Replanning makes it
    structural.

    Deterministic by construction: ties on the leaf fall through to the enumeration order, which
    `board_choice.deferred_target` already fixes as a pure function of the board (ranker-descending,
    then the candidate itself). No dict iteration decides anything.

    ⚠️ **``leaf`` is the same MAX that `Expectation.best` computes, reached a second way** — the sort
    is needed for the ranking anyway, so taking ``scored[0]`` is free where a second pass over the
    classes would not be. Two spellings of one rule is exactly the drift ADR-0087 charges for one
    store over, so the agreement is not left to inspection: `test_composer.py` asserts
    ``rank_targets(m, e).leaf == e.best(state_value)`` on a fixture where the classes differ."""
    scored = sorted(
        (ScoredTarget(rank=0, leaf=float(state_value(c.model)), model=c.model,
                      fingerprint=tuple(c.fingerprint or ()), probability=float(c.probability))
         for c in expectation.classes),
        key=lambda s: (-s.leaf, s.fingerprint))
    ranked = tuple(ScoredTarget(rank=n + 1, leaf=s.leaf, model=s.model, fingerprint=s.fingerprint,
                                probability=s.probability) for n, s in enumerate(scored))
    mass = float(expectation.total_probability)
    return TargetChoice(
        scored=ranked,
        leaf=ranked[0].leaf if ranked else 0.0,
        expected=(sum(s.probability * s.leaf for s in ranked) / mass) if mass > 0.0 else 0.0,
        truncated=int(expectation.truncated), total_probability=mass)


def choose_target(model, option: Mapping, *, seat_index=None, cap=None, ranker=None):
    """Enumerate this option's deferred target space and evaluate it — the MAIN-site convenience.

    A thin front door onto :func:`rank_targets`, kept separate so the EVALUATOR and the ENUMERATOR
    are different names: Issue #387's site does not enumerate (the engine hands it the menu), so a
    single function doing both would force it to fake an enumeration or to spell the scoring again.

    ``cap`` defaults to `board_choice.deferred_target`'s own, which is
    `board_expectation.BRANCH_CAP` **reused, not re-declared** — a choice node and a chance node both
    cost leaf evaluations on one option, so they take the same cap (`sound_rules.composer-budget-caps`
    usage 3). Returns None when the space is unmodellable; the caller turns that into a refusal."""
    from common import board_choice
    kwargs = {} if cap is None else {"cap": cap}
    try:
        expectation = board_choice.deferred_target(
            model, dict(option), seat_index=seat_index, ranker=ranker, **kwargs)
    except Unmodellable:
        return None
    return rank_targets(model, expectation)


# ── the deterministic selection tie-break, in ONE place ──────────────────────────────────────────

#: Decimal places the score leg of :func:`selection_key` is compared at — **a float-noise floor, not
#: a band**, and deliberately NOT :data:`EPSILON`.
#:
#: Two orderings of one commutative block reach the SAME end board, so their scores are the same sum
#: added in a different order — and floating-point addition is not associative, which
#: `state_value._terms` already says outright (*"a reordering would move the last bits of the sum"*).
#: Measured on `82226116|0|decision|70`: retreat-then-evolve scores `0.9052836100260416` and
#: evolve-then-retreat `0.9052836100260415`, a difference of **1.11e-16** — one ULP. An EXACT `-score`
#: leg separates on that, so the Worth leg below never runs, and the corpus frame is decided by the
#: last bit of a sum rather than by the rule Issue #263 § *Beam-quality package* item 1 wrote for it
#: (the Worth leg would have picked the ruled evolve, `-30.0` against `-0.0`). That is the same
#: fall-through class as ADR-0062:29 and `mega_lucario` f33/f40/f44, reached through arithmetic
#: instead of through generation order.
#:
#: **12 places is six orders of magnitude above the noise and six below anything real**: the observed
#: 1-ply deltas on this corpus run 1e-5 to 1e-3 and the epsilon band is 5e-3, so rounding here cannot
#: merge two candidates the leaf actually separates. :data:`EPSILON` is deliberately not reused — it
#: is the corpus-calibrated ADMISSION band for not LOSING a near-tie during search, and Issue #263 is
#: explicit that the two mechanisms must not be merged; quantising selection onto it would silently
#: hand every sub-epsilon decision to the Worth leg, which is a different ruling nobody has made.
_SCORE_PLACES = 12


def selection_key(model, candidate: Candidate) -> tuple:
    """The ONE ordering key for choosing among candidates — Issue #263 § *Beam-quality package*
    item 1 (old Issue #145 amendment D, moved here because it was always a composer concern).

    Ascending, so every leg is negated where it should rank high:

    1. **sequence score** (descending);
    2. **Worth of the touched card** (descending) — `card_worth.role_value` reached through
       `MySide.role_worth`, which is the sole-supplier route (Roles are DECLARED by the Strategy, not
       a card fact, so the model resolves them);
    3. **a stable card-id sort**, then the depth-0 menu index.

    **This supersedes the ADR-0103 canon string as the third key AT THE SELECTION POINT**, and the
    difference is worth stating rather than leaving to be found: `pilot._order_key`'s third leg is the
    board-derived fingerprint, which separates two options the board CAN tell apart; here the Worth
    leg does that job first and more meaningfully, and what remains after it is a card-id sort that is
    equally a pure function of the board. Neither ever falls through to raw generation order, which is
    the property both keys exist for and the one that fixed ADR-0062:29, `mega_starmie` ep82867148
    f48/f87 and `mega_lucario` ep83661652 f33/f40/f44.

    A coverage-gap candidate sorts LAST within its score band, so it can never quietly beat a scored
    sequence it merely failed to be compared with."""
    worth, card_id = 0.0, -1
    step = candidate.steps[0] if candidate.steps else None
    option = step.option if step is not None else candidate.terminal
    if option is not None:
        stat = _option_card_stat(model, option)
        if stat is not None:
            card_id = int(getattr(stat, "cardId", -1) or -1)
            worth = float(model.mine.role_worth(stat.cardId))
    index = candidate.first_index
    return (bool(candidate.coverage_gap), -round(candidate.score, _SCORE_PLACES), -worth, card_id,
            index if index is not None else 1 << 30)


# ── the beam ─────────────────────────────────────────────────────────────────────────────────────


@dataclass(frozen=True)
class _Node:
    """A partially-composed sequence: the board it reached, the steps that got there, which depth-0
    classes it consumed, and the canonical keys of the commutative block currently open."""

    model: object
    steps: tuple = ()
    used: frozenset = frozenset()
    block: tuple = ()            # canonical keys of the open block's members
    block_prints: tuple = ()     # their footprints, for the pairwise commutativity test
    truncated: int = 0
    leaf: float = 0.0


def compose(model, options: Sequence[Mapping], *, k: int = BEAM_WIDTH, epsilon: float = EPSILON,
            depth: int = SEQUENCE_DEPTH, search_api=None, deterministic=None,
            clauses_cover=None) -> ComposerResult:
    """Compose this decision's candidate sequences and return the best, with its telemetry.

    ``options`` is the engine's live menu. ``deterministic`` and ``clauses_cover`` are the seam's own
    per-option inputs (`apply_option.fate`) and may be given either as a plain value or as a callable
    ``option -> value``; the callable form is the real one, because both are per-option facts and
    `fate`'s closing paragraph makes joining them the CALLER's job. Their default `None` takes the
    structural MODELLED path, which is what the pool mostly is.

    **Pure and bit-identical across runs** (Issue #262's purity, inherited): no dict/set iteration
    decides an order anywhere, every tie resolves through :func:`selection_key`, and the model is
    never mutated — `apply_option` hands back a FRESH model per hypothetical.

    Wall-clock is recorded in ``stats`` rather than enforced. A composer that silently gave up at a
    time limit would produce an under-explored line that looks confidently valued, which is the
    no-silent-caps failure; the caps that DO bind are structural and their truncation is reported."""
    if int(k) < 1 or int(depth) < 0:
        # Caller error, so it RAISES where a modelling gap refuses — the same split
        # `board_expectation.expectation` draws for its own `cap < 1`. And it is not pedantry: both
        # `_admit` and `_prune_nodes` index the k-th as `[k - 1]`, so a `k` of 0 indexes the WORST
        # candidate from the end and admits the entire menu. A beam that silently stops being a beam
        # is the exact shape of failure the no-silent-caps discipline exists against.
        raise ValueError(
            f"k={k!r}, depth={depth!r}: a beam must keep at least one candidate and cannot search a "
            f"negative number of plies. k=0 would index the k-th candidate as [-1] and admit "
            f"everything, which reads as a working beam while being none.")
    t0 = time.perf_counter()
    obs = getattr(model, "source_obs", None) or {}
    options = list(options or [])
    equiv = option_equivalence(options, obs)
    reps = class_representatives(equiv, len(options))
    canon = canonical_keys(options, obs)
    stamped = [stamp_origin(model, o) for o in options]

    state = _Run(k=k, epsilon=epsilon, depth=depth, search_api=search_api,
                 deterministic=deterministic, clauses_cover=clauses_cover,
                 canon=canon, reps=reps, stamped=stamped)

    root = _Node(model=model, leaf=float(state_value(model)))
    frontier, root_ranked = [root], None
    for ply in range(depth + 1):
        expanded = []
        for node in frontier:
            ranked = _rank(state, node)
            if node is root:
                root_ranked = ranked
            expanded.extend(_expand(state, node, ranked))
        if not expanded:
            break
        if ply == depth:
            state.depth_truncated += len(expanded)
            break
        frontier = _prune_nodes(state, expanded)

    ranked0 = root_ranked or []
    chosen = min(state.candidates, key=lambda c: selection_key(model, c)) \
        if state.candidates else None
    return ComposerResult(
        chosen=chosen,
        candidates=tuple(sorted(state.candidates, key=lambda c: selection_key(model, c))),
        margin=_margin(state, ranked0, chosen),
        fanned=tuple(fan_out([state.one_ply.get(i) for i in range(len(options))], equiv)),
        order=tuple((e.index, e.delta) for e in ranked0),
        admitted=_admitted_indices(state, ranked0), always_expanded=_free_indices(ranked0),
        blocks=commutative_blocks(model, stamped, reps),
        gaps=tuple(state.gaps),
        bounds=tuple(state.bounds),
        stats={"leaf_evals": state.leaf_evals, "nodes": state.nodes,
               "candidates": len(state.candidates), "truncated": state.truncated,
               "depth_truncated": state.depth_truncated,
               "expectation_nodes": len(state.bounds),
               "expanded_families": state.expanded_families,
               "expansion_children": state.expansion_children,
               "ms": (time.perf_counter() - t0) * 1000.0})


@dataclass
class _Run:
    """One :func:`compose` call's mutable bookkeeping. A plain record rather than closure variables so
    the helpers below are testable in isolation and so nothing is captured by accident."""

    k: int
    epsilon: float
    depth: int
    search_api: object
    deterministic: object
    clauses_cover: object
    canon: list
    reps: list
    stamped: list
    candidates: list = field(default_factory=list)
    gaps: list = field(default_factory=list)
    bounds: list = field(default_factory=list)    # both bounds of every expectation node (§S3.5)
    one_ply: dict = field(default_factory=dict)   # depth-0 delta per representative index
    leaf_evals: int = 0
    nodes: int = 0
    truncated: int = 0
    depth_truncated: int = 0
    expanded_families: int = 0        # §S7 D4: options whose deferred target was fanned out
    expansion_children: int = 0       # the instances scored across all of them


def _ask(resolver, option):
    """A per-option seam input, however the caller supplied it — a callable is asked, anything else
    is passed straight through. Both `fate` inputs are per-option facts, so the callable form is the
    honest one; the scalar form exists because a test fixing one answer for a whole menu should not
    have to write a lambda."""
    return resolver(option) if callable(resolver) else resolver


def _rank(state: _Run, node: _Node) -> list:
    """One node's 1-ply ordering — **the whole ordering heuristic, applied uniformly**.

    Every option still available on this board is applied through the seam, `state_value`'d, and
    ranked by the delta against the node's own leaf. Returns a list of ``_Ranked`` sorted by delta
    descending with a deterministic tail (canonical key, then menu index), never by menu position.

    Availability is two tests and both are re-checks rather than assumptions: the option's instances
    must still resolve (:func:`resolve_against`) and the per-turn allowances must still permit it
    (:func:`_still_legal`)."""
    out = []
    for i in state.reps:
        if i in node.used:
            continue
        option = resolve_against(node.model, state.stamped[i])
        if option is None or not _still_legal(node.model, option):
            continue
        entry = _one_ply(state, node, option, i)
        if entry is None:
            continue
        if not node.steps:
            # Recorded HERE rather than after admission, so `ComposerResult.fanned` answers for every
            # option the menu offered — a caller indexing the live menu must not meet a None that
            # means "pruned" where it expects one that means "unfingerprintable".
            state.one_ply[i] = entry.delta
        out.append(entry)
    out.sort(key=lambda e: (-e.delta, e.key))
    return out


@dataclass(frozen=True)
class _Ranked:
    """One option's 1-ply verdict at one node."""

    index: int
    option: dict
    key: tuple
    delta: float
    after: object            # the model to continue from, or None (terminal / refused / reveal)
    fate: str
    footprint: object
    terminal: bool = False
    reveals: bool = False
    refused: bool = False
    truncated: int = 0
    ev: float = 0.0
    gap: str = ""
    #: The deferred-target expansion this option resolved through, or None (§S7). Carried so the
    #: `Step` can name WHICH target won — a candidate that reports only the parent option would tell
    #: a reader the composer retreated without telling them whom it promoted.
    choice: object = None


def _one_ply(state: _Run, node: _Node, option: dict, index: int):
    """Apply ONE option and price it. The four fates, each with its own honest answer.

    * **TERMINAL** — no successor board. The candidate's leaf is the board it was reached FROM, and
      the terminal action's own EV is the second summand (Issue #263 § *Terminal-action valuation*).
    * **REFUSED** — cannot be applied, so it becomes a one-action terminal candidate flagged as a
      coverage gap. Ranked at the node's own leaf so it is never dropped and never silently
      out-competes a scored sequence; `selection_key` sorts it last within its score band.
    * **an Expectation** — ranked by `best()`, the **MAX** over its classes, never `expected()`.
      Both producers emit a CHOICE node and the value of a choice is the value of the best branch
      (§S3; `board_expectation`'s header and `board_choice.deferred_target` both rule it in their
      own words). A reveal is additionally a BLOCK BOUNDARY and a REPLAN POINT, so the beam stops
      there rather than continuing from a synthesized post-reveal board; a deferred TARGET is not —
      §S7's expansion resolves it in place and the sequence continues.
    * **a model** (MODELLED, or ENGINE-RESOLVED unwrapped) — the ordinary case.

    **Routing a revealing option to an Expectation happens HERE, and that is by design.**
    `apply_option`'s dispatch is deliberately unchanged by POC-T4/2 — its header says outright that
    *"routing a revealing option to an Expectation is a behaviour change, and the composer is what
    makes it"* — so this is the one site that asks `common.board_expectation` instead of the point
    transition. The reveal test is the per-option footprint's ``reveals_information``, armed off
    `snapshot_coverage.REVEALING_CLAUSES`, rather than a second card list beside it."""
    if ao.is_terminal(option):
        ev, _detail, gap = terminal_ev(node.model, option)
        if gap:
            state.gaps.append(f"{_frame_of(option)}: {gap}")
        return _Ranked(index=index, option=option,
                       key=(TIER_ENDER, state.canon[index], index),
                       delta=ev, after=None, fate=ao.TERMINAL, footprint=ao.Footprint(),
                       terminal=True, ev=ev, gap=gap)
    cover = _ask(state.clauses_cover, option)
    footprint = ao.option_footprint(node.model, option, clauses_cover=cover)
    key = canonical_key(node.model, option, index, state.canon[index], footprint)

    def _refuse(reason: str) -> _Ranked:
        state.gaps.append(f"{_frame_of(option)}: {reason}")
        return _Ranked(index=index, option=option, key=key, delta=0.0, after=None,
                       fate=ao.REFUSED, footprint=footprint, refused=True, gap=reason)

    if footprint.reveals_information and _reveal_rides(node.model, option):
        if ao.transition_kind(option) != _PLAY:
            return _refuse(
                "a revealing clause RIDES this option and it is not a `_PLAY`, so neither seam can "
                "price it: `board_expectation` enumerates a played Item/Supporter's search and "
                "refuses a reveal riding another kind, while the point transition consults no "
                "clauses on this kind at all and would apply the structural half while silently "
                "DROPPING the reveal — an under-reported delta, which at ordering time is a pruned "
                "option rather than an undervalued one")
        try:
            result = bx.expectation(node.model, option)
        except Unmodellable as gap:
            return _refuse(str(gap))
        state.leaf_evals += len(result.classes)
        try:
            leaf = float(result.best(state_value))          # §S3: MAX over classes, never expected()
            lower = float(result.expected(state_value))      # §S3.5: the other bound, REPORTED
        except ValueError as gap:                # an un-enumerated effect: an unknown, not a zero
            return _refuse(str(gap))
        state.truncated += result.truncated
        state.bounds.append(Bounds(index=index, best=leaf, expected=lower,
                                    classes=len(result.classes), truncated=result.truncated,
                                    total_probability=float(result.total_probability)))
        return _Ranked(index=index, option=option, key=key, delta=leaf - node.leaf, after=None,
                       fate=ao.MODELLED, footprint=footprint, reveals=True,
                       truncated=result.truncated, ev=leaf)

    result = ao.apply_option(node.model, option, depth=len(node.steps),
                             search_api=state.search_api,
                             deterministic=_ask(state.deterministic, option),
                             clauses_cover=cover,
                             expand_deferred_targets=True)
    if ao.must_expand(result):
        return _refuse(f"{result.scope}: {result.reason}")
    if isinstance(result, ao.Expectation):
        # A CHOICE node from `board_choice` — the option's TARGET is deferred to a follow-up select.
        # D4's parent-slot accounting lives here and nowhere else: score every instance, take the
        # argmax, emit ONE `_Ranked`. The fan-out is evaluation-time, so beam width `k` keeps its
        # pre-expansion meaning and the epsilon band and margin telemetry keep meaning what
        # Issue #263 says they mean. Unlike a REVEAL this is not a boundary — the chosen board is a
        # real synthesized model, so `after` is set and the sequence continues from it.
        choice = rank_targets(node.model, result)
        state.leaf_evals += len(choice.scored)
        state.expanded_families += 1
        state.expansion_children += len(choice.scored)
        state.truncated += choice.truncated
        state.bounds.append(Bounds(index=index, best=choice.leaf, expected=choice.expected,
                                    classes=len(choice.scored), truncated=choice.truncated,
                                    total_probability=choice.total_probability))
        if choice.best is None:
            return _refuse(
                "the deferred-target space enumerated to zero classes — an un-enumerated effect, "
                "and pricing it 0.0 would rank a real play below every scored line")
        return _Ranked(index=index, option=option, key=key, delta=choice.leaf - node.leaf,
                       after=choice.best.model, fate=ao.MODELLED, footprint=footprint,
                       truncated=choice.truncated, ev=choice.leaf, choice=choice)
    after = ao.require_model(result)
    state.leaf_evals += 1
    leaf = float(state_value(after))
    return _Ranked(index=index, option=option, key=key, delta=leaf - node.leaf, after=after,
                   fate=ao.ENGINE_RESOLVED if isinstance(result, ao.EngineResolved) else ao.MODELLED,
                   footprint=footprint, ev=leaf)


def _step_of(entry: _Ranked) -> Step:
    """One `_Ranked` as the `Step` that leaves this module — the ONE construction site.

    Built once rather than at each of the two candidate constructors, so the origin-stripping and
    the deferred-target attribution cannot drift apart: a `Step` that carried the stamp on one path
    and not the other would leak a private field, and one that named its chosen target on only one
    path would make §S7's attribution a property of which branch happened to build it."""
    choice = entry.choice
    best = None if choice is None else choice.best
    return Step(option=strip_origin(entry.option), index=entry.index, tier=entry.key[0],
                fate=entry.fate,
                chosen_target=() if best is None else best.fingerprint,
                target_classes=0 if choice is None else len(choice.scored))


def _frame_of(option: Mapping) -> str:
    """A refusal's subject, for the telemetry line — the option kind and its instance key, which is
    what a modelling backlog entry needs to be actionable."""
    hand, body = _origin_serials(option)
    return f"kind {ao.transition_kind(option)} (hand {hand}, body {body})"


def _admit(state: _Run, ranked: list) -> list:
    """The **epsilon-band beam admission** — top-k PLUS anything within :data:`EPSILON` of the k-th.

    A different mechanism from :func:`selection_key`, and Issue #263 § *Beam-quality package* is
    explicit that they must not be merged: this one is about not LOSING a candidate during search,
    that one is about choosing DETERMINISTICALLY among candidates already in front of the composer.
    A hard top-k cutoff drops a genuine near-tie with the k-th slot, which is exactly where a good
    enabling move is most likely to be lost.

    Terminal and refused entries are admitted unconditionally: neither costs a further expansion, and
    dropping either would make an unpriceable option indistinguishable from a worthless one — the
    always-expand contract `apply_option.must_expand` names."""
    free = [e for e in ranked if e.terminal or e.refused]
    scored = [e for e in ranked if not (e.terminal or e.refused)]
    if len(scored) <= state.k:
        return free + scored
    cutoff = scored[state.k - 1].delta - state.epsilon
    return free + [e for e in scored if e.delta >= cutoff]


def _expand(state: _Run, node: _Node, ranked: list) -> list:
    """Turn one node's admitted options into candidates and child nodes.

    The node ITSELF is always emitted as a candidate — the stop-here line, which is the empty member
    of its block's subset lattice — so a sequence is never forced to keep going to be scored.

    The commutative-block rule is applied HERE and a-priori: a child that provably commutes with every
    open block member may only extend the block when its canonical key sorts strictly after all of
    them, which generates each subset exactly once. A child that does NOT commute with some member
    opens a FRESH block and is admitted unconditionally, so both orderings of a genuinely
    order-dependent pair are still explored at full beam width (two `_EVOLVE`s on distinct bodies are
    the worked case — they collide on whole-zone `special_conditions`)."""
    state.nodes += 1
    children = []
    state.candidates.append(_stop_here(state, node))
    for entry in _admit(state, ranked):
        if entry.terminal:
            state.candidates.append(_terminal_candidate(node, entry))
            continue
        if entry.refused or entry.after is None:
            state.candidates.append(_gap_or_reveal_candidate(node, entry))
            continue
        commutes = all(ao.footprints_commute(entry.footprint, fp) for fp in node.block_prints)
        if commutes and node.block and not _admissible_in_block(entry.key, node.block):
            continue                             # this subset already exists in canonical order
        step = _step_of(entry)
        children.append(_Node(
            model=entry.after, steps=node.steps + (step,), used=node.used | {entry.index},
            block=(node.block + (entry.key,)) if commutes else (entry.key,),
            block_prints=(node.block_prints + (entry.footprint,)) if commutes
            else (entry.footprint,),
            truncated=node.truncated + entry.truncated, leaf=node.leaf + entry.delta))
    return children


def _stop_here(state: _Run, node: _Node) -> Candidate:
    """The candidate that takes ``node``'s steps and stops — ``EV(terminal) = 0``.

    Distinct from the `_END` option's candidate even though they score the same: `_END` is only on the
    menu at a MAIN select, and the composer must be able to value a line at every decision point it
    visits (Issue #263 § *Every fresh decision point is a composer decision*).

    ⚠️ **It does NOT carry :func:`continuation_ev`, and that is a soundness property.** Stopping here
    is a CHOICE to stop, which is what `EV(end-turn) = 0` already means; and because the root
    stop-here has ``first_index is None``, crediting it would let *"commit nothing"* win a decision
    outright — measured, 4 of 270 corpus frames produced no pick at all under that arm. ADR-0127's
    reveal credit is for a line the composer CUT, never for one it declined to start."""
    return Candidate(steps=node.steps, terminal=None, leaf=node.leaf, terminal_ev=0.0,
                     score=node.leaf, truncated=node.truncated)


def _terminal_candidate(node: _Node, entry: _Ranked) -> Candidate:
    """A sequence ending in an attack or an end-turn. The leaf is the board the terminal action was
    reached FROM — a terminal option has no successor state — and the EV is the second summand."""
    return Candidate(steps=node.steps, terminal=strip_origin(entry.option),
                     terminal_index=entry.index, leaf=node.leaf, terminal_ev=entry.ev,
                     score=node.leaf + entry.ev, coverage_gap=entry.gap,
                     truncated=node.truncated)


def _gap_or_reveal_candidate(node: _Node, entry: _Ranked) -> Candidate:
    """A line that STOPS at this option — either because the seam refused it (a coverage gap) or
    because it reveals information and the engine will re-present the menu.

    A refusal keeps the node's own leaf: the option was never applied, so nothing about the board
    moved, and the flag is what carries the fact that its value is UNKNOWN rather than zero. A reveal
    keeps its Expectation's `best()` — the **max** over the classes, which is the value of a choice
    (§S3). `expected()` is reported alongside it as the lower bound (`ComposerResult.bounds`), never
    used to rank; ranking on it under-prices every reveal-bearing sequence.

    **A reveal additionally carries :func:`continuation_ev` as its terminal summand (ADR-0127).** The
    line was CUT at a replan point, not ended, so the turn's remaining attack is still ahead of it;
    pricing it 0 compared a partial line head-to-head against full attack lines carrying a prize.

    **A REFUSAL is deliberately excluded, and the exclusion is measured rather than argued.** Its
    board never moved and its value is UNKNOWN — a different claim from *"the turn continues"*.
    Crediting it too was measured as its own arm and is byte-identical, because :func:`selection_key`
    leads with ``bool(candidate.coverage_gap)`` and sorts every gap candidate behind every scored one
    whatever its score. The narrow spelling is taken and the wider one recorded as equivalent."""
    step = _step_of(entry)
    if entry.refused:
        leaf, ev = node.leaf, 0.0
    else:
        leaf, ev = node.leaf + entry.delta, continuation_ev(node.model)
    return Candidate(steps=node.steps + (step,), terminal=None, leaf=leaf, terminal_ev=ev,
                     score=leaf + ev, coverage_gap=entry.gap,
                     truncated=node.truncated + entry.truncated)


def _prune_nodes(state: _Run, nodes: list) -> list:
    """Prune the frontier by the same top-k-plus-epsilon rule the option ranking uses.

    One rule, asked twice, rather than two spellings that could drift: the quantity is a leaf value
    in prizes in both cases, and the band means the same thing at both sites."""
    if len(nodes) <= state.k:
        return nodes
    ordered = sorted(nodes, key=lambda n: (-n.leaf, tuple(s.index for s in n.steps)))
    cutoff = ordered[state.k - 1].leaf - state.epsilon
    return [n for n in ordered if n.leaf >= cutoff]


def _margin_at(order: tuple, free: frozenset, admitted: frozenset, k: int, index) -> Margin:
    """The ONE margin computation over a depth-0 ordering — shared by :func:`compose`'s own answer and
    by :meth:`ComposerResult.margin_for`, so the composer's line and the human's ruled line are
    measured by the same instrument rather than by two spellings of it."""
    kth = order[k - 1][1] if len(order) >= k else None
    if index is None:
        return Margin(k=k, ranked=len(order), kth_delta=kth)
    rank = next((n + 1 for n, (i, _d) in enumerate(order) if i == index), None)
    delta = next((d for i, d in order if i == index), None)
    return Margin(rank=rank, k=k, ranked=len(order),
                  in_beam=rank is not None and rank <= k and index not in free,
                  admitted=index in admitted, always_expand=index in free,
                  chosen_delta=delta, kth_delta=kth,
                  margin_to_kth=None if (delta is None or kth is None) else delta - kth)


def _free_indices(ranked0: list) -> frozenset:
    """Depth-0 options admitted UNCONDITIONALLY — the terminals and the refusals."""
    return frozenset(e.index for e in ranked0 if e.terminal or e.refused)


def _admitted_indices(state: _Run, ranked0: list) -> frozenset:
    """Depth-0 options that survived pruning, by any route."""
    return frozenset(e.index for e in _admit(state, ranked0))


def _margin(state: _Run, ranked0: list, chosen: Candidate | None) -> Margin:
    """The chosen line's first step, measured against the beam cutoff it had to survive.

    ``rank`` is 1-based over the depth-0 ordering.

    **THREE survival fields, because "did it survive" and "did it earn its place" are different
    questions and conflating them would make this instrument report a pass it never measured:**

    * ``in_beam`` — it made the hard top-k **by score**. A step admitted purely by the epsilon band
      reads as the near-miss it is, which is the whole point: *"a first step that barely survives on
      many corpus frames is an early warning that beam width or term shaping needs work, visible
      BEFORE it silently fails on an unseen board"*.
    * ``admitted`` — it survived pruning at all, by any route.
    * ``always_expand`` — it survived because a TERMINAL or a REFUSED option is admitted
      unconditionally (`must_expand`'s always-expand contract). Such an option carries delta 0.0 by
      construction, since it was never applied, so an ``in_beam`` reading of it would be a statement
      about a tie at zero rather than about the leaf preferring it. Measured on the corpus this is
      not a corner case: on `85046350|0|decision|32` (f32) **all five** options price exactly 0.0.
    """
    return _margin_at(tuple((e.index, e.delta) for e in ranked0), _free_indices(ranked0),
                      _admitted_indices(state, ranked0), state.k,
                      None if chosen is None else chosen.first_index)


__all__ = (
    "BEAM_WIDTH", "SEQUENCE_DEPTH", "EPSILON",
    "TIER_INFORMATIVE", "TIER_COMMIT_FREE", "TIER_SUPPORTER", "TIER_COMMITMENT", "TIER_SHUFFLE",
    "TIER_ENDER",
    "Step", "Candidate", "Margin", "Bounds", "ComposerResult", "ScoredTarget", "TargetChoice",
    "compose", "selection_key", "terminal_ev", "continuation_ev", "canonical_tier", "canonical_key",
    "commutative_blocks", "subset_lattice", "resolve_against", "stamp_origin", "strip_origin",
    "rank_targets", "choose_target",
)
