"""**The sequence composer** — beam search over within-turn action SEQUENCES, scored by end-state
differencing (POC-T4/4, Issue #385; governing spec Issue #263).

`common.apply_option` answers *"what would the board be if I did this?"* and `common.state_value`
answers *"what is that board worth?"*. This module is what puts them in a loop: it enumerates the
sequences a turn could take, transitions each one through the seam, scores the end board with the
leaf, and reports which first action the best sequence commits to.

    score(sequence) = state_value(end board) + EV(terminal action),   EV(end-turn) = 0

**DARK.** Nothing in production calls :func:`compose`. Arming it at the MAIN menu is T4/5's
(Issue #386), and T4/5 **deletes** the switch rather than flipping it — a composer flag that survives
the track is a defect against ADR-0092's no-dark-flags acceptance. Both ADR-0072 gates therefore see
byte-identical output at this commit, which is the acceptance line that proves the darkness.

## The ordering heuristic is UNIFORM 1-ply differencing — no per-family logic exists here

Ruled 2026-08-01 (Issue #263 § *The ordering heuristic*), superseding an earlier *"per-class top-k by
local marginal"* draft. Apply the single option through the seam, `state_value` the result, rank by
the delta — for **every** option kind. The same scorer runs at 1 ply and at n ply, so the
ordering-disagrees-with-the-leaf bug class cannot arise by construction, and a heal / fetch / Tool
equip / Stadium / draw Supporter (none of which has a local price at all) is ranked on the same scale
as an attach.

Options resolve by the seam's three fates:

* **MODELLED** and **ENGINE-RESOLVED** are ordinary candidates. ENGINE-RESOLVED is 1-ply only; at
  depth >= 1 the seam refuses it, because the board is synthesized and the native engine cannot be
  handed one back.
* **REFUSED** cannot be applied, so it becomes a **one-action terminal candidate flagged as a
  coverage gap** — surfaced in :attr:`ComposerResult.gaps`, never silently competing with scored
  sequences and never silently dropped. `apply_option.must_expand` is the policy; this module obeys
  it rather than re-deciding it.

## Two collapses run, on different axes, and they compose

* **Option Equivalence** (ADR-0091) dedupes indistinguishable SIBLINGS at one ply: one representative
  per class via `class_representatives`, values fanned to members via `fan_out`.
* **Commutative-block collapse** (Issue #263 § *Commutative-block collapse*) dedupes ORDERINGS of
  distinct options across depth. Emitted a-priori as the SUBSET lattice — 2**n candidates, one
  canonical ordering per subset — never generate-then-hash-then-merge.

The lattice is generated by :func:`_admissible_in_block`: inside a block a member may only extend the
sequence if its canonical key is strictly greater than the last block member's. For *n* pairwise
commuting options that yields exactly the 2**n subsets (8 / 16 / 32 for n = 3 / 4 / 5) against the
16 / 65 / 326 ordered prefixes a naive tree holds, and duplicates are never CREATED, which is the
difference the spec insists on: a post-hoc transposition table pays full generation cost first.

**Blocks are licensed ONLY by proven per-option footprints, and fail closed.**
`apply_option.option_footprint` + `footprints_commute` are asked; an unknown or partial footprint
commutes with nothing, and a revealing play can never join a block whatever its footprint says.

**The canonical in-block order is the information-before-commitment tier order**
(`sound_rules.information-before-commitment`, ADR-0095 decision 1). Its ratified reason survives the
move verbatim — *"digging first and digging second reach the same end state, so no function of that
state separates them"* — and generalises to exactly the block case: inside a commutative block NO
function of the end state separates any ordering, so the doctrine order is the principled canonical
choice rather than an arbitrary one. Canonical ordering is also what makes the Issue #254 index-order
bug class (a KO reachable from one bench slot and missed from the isomorphic other) structurally
impossible instead of hand-fixed.

## Re-resolution by INSTANCE — the trap the commutativity ruling flagged in advance

Element-level commutativity is a claim about the resulting BOARD, never about option ENCODINGS. An
option names its card by hand INDEX, and removing hand card 0 shifts card 3 to index 2 — so two plays
whose boards provably commute still have order-dependent encodings, and replaying a stored option
dict from a permuted position applies a **different play**. The failure is silent by construction: a
shifted index still resolves to *a* legal card, so it produces a plausible board rather than an error.

:func:`resolve_against` therefore re-resolves every step by the `(hand serial, body serial)` instance
key `apply_option.option_serials` produces, against the board the step is actually applied to. A
serial that is gone means the card was consumed and the option is dropped; an option that named no
resolvable instance at depth 0 is dropped at depth >= 1 rather than replayed on trust.

## Legality is RE-CHECKED, because a synthesized board has no menu

At depth 0 the engine's menu is the legality proof. At depth >= 1 there is no menu — the board is
this module's own synthesis — and `apply_option` models a transition rather than policing one, so
nothing else would stop the beam sequencing two manual Energy attaches. :func:`_still_legal` re-checks
the per-turn allowances at source (`docs/rules.md` §3: Energy attach 1, Supporter 1, Stadium 1,
Retreat 1, Attack 1-and-ends-the-turn) plus §4's evolution timing (*"Cannot evolve a Pokémon the turn
it was played/put into play"*). Fail closed: an unreadable card is not sequenced.

## The beam-quality package — THREE distinct mechanisms, deliberately not merged

Issue #263 § *Beam-quality package* warns against conflating them, so each has its own home here:

1. **Deterministic tie-break at SELECTION time** (:func:`selection_key`), in ONE place. Primary the
   sequence score; secondary the Worth of the touched card (`card_worth.role_value`, reached through
   `MySide.role_worth`, the sole-supplier accessor); then a stable card-id sort. This rule is on
   record because it fixed three CRITICAL production bugs (ADR-0062:29's oldest-attached
   fall-through; `mega_starmie` ep82867148 f48/f87; `mega_lucario` ep83661652 f33/f40/f44 —
   *"benched whichever Basic sat lowest in the menu"*), and a differencing composer is exactly as
   exposed to that class as the rung system it replaces.
2. **Epsilon-band admission at PRUNING time** (:func:`_admit`), a different mechanism. Top-k PLUS
   anything within :data:`EPSILON` of the k-th score, so a genuine near-tie with the cutoff is not
   hard-dropped. Measured against the corpus by `tools/train/composer_lab.py`, never guessed.
3. **Margin telemetry** (:class:`Margin`), required rather than optional. Per decision: the
   eventually-chosen line's first-step RANK at 1-ply relative to k and its score MARGIN to the k-th
   candidate, in the `working()`-adjacent shape `state_value` established. A first step that barely
   survives on many corpus frames is an early warning that beam width or term shaping needs work,
   visible BEFORE it fails silently on an unseen board.

## What this composer is STRUCTURALLY BLIND TO — declared here, before the beam was sized

Issue #263 ceiling #2: *"a play that moves state no term reads prices 0"* — and under uniform 1-ply
differencing a 0 delta is **never explored**, not merely undervalued. The consolidated checklist is
`data/leaf_lab/wave3-rulings.md` § *3b · The consolidated blind-spot checklist* (Issue #291's
closeout): **35 `blind_to` entries across 7 families, plus a 36th that is in no registry**. It is
cited rather than copied, because a second copy of a ruling record drifts. The shape of it, so a
reader meets the list before writing a beam rather than after:

* Six entries are **by design** (3, 17, 27, 28, 33 and half of 29) — the double-counting rule and the
  1-ply bound doing their jobs, not gaps.
* Four are **closed by this track's own scope**: entry 29 dies with the develop rollout (T4/5), and
  9 / 10 / 22 / 25 were narrowed by Issues #284 / #329 / #351.
* The live list's centre of gravity is `threat` — **15 of 35** — and entries **11, 20 and 21** each
  silently zero a family Issue #263 explicitly retires a rung into (gust whether-to-play,
  counter-placement, denial). Entry **11 is additionally UNOWNED**.
* The **36th** is Issue #376's ruled-and-accepted blindness: enabling cards (Boss's Orders, Premium
  Power Pro) *"may be underplayed until Issue #263 lands"* — owned by this track, with no `blind_to`
  entry because the term that would carry it is the one this track wires.

Two further ceilings, stated because they bound this module and are not defects in it:

* **Information value is not expressible by differencing at all.** Playing an informative card before
  a committing one versus after reaches the SAME end state, so no function of that state separates
  the two orderings (`apply_option`'s header; ADR-0095 decision 3). That is why the tier order above
  is a STRUCTURAL canonical choice and why `information-before-commitment` stays on the sound-rule
  whitelist as a preempting rule rather than being retired into this beam.
* **A sequence that ends at a REVEAL is a partial line.** The engine re-presents the menu after a
  draw/search, so the composer stops there and replans — which means such a candidate carries
  `EV(terminal) = 0` and is compared against full attack lines that carry a prize. Recorded as a
  named ceiling, and it is the second reason the structural information rule is kept.

## Budget — the caps are STRUCTURAL constants chosen from a measurement

:data:`BEAM_WIDTH`, :data:`SEQUENCE_DEPTH` and :data:`EPSILON` are whitelisted together under
`sound_rules.composer-budget-caps` (`authored-scaffold`), with the derivation on that entry and the
re-measurement owed on grader hardware post-POC (Issue #273). The expectation-branch cap is
`board_expectation.BRANCH_CAP` and is NOT re-declared here — one store, per ADR-0087.
"""
from __future__ import annotations

import time
from dataclasses import dataclass, field
from typing import Mapping, Sequence

from common import apply_option as ao
from common import board_expectation as bx
from common import snapshot_coverage
from common.board_delta import Unmodellable
from common.option_equivalence import (
    AREA_ACTIVE, AREA_BENCH, AREA_HAND, canonical_keys, class_representatives, fan_out,
    option_equivalence,
)
from common.state_value import attack_ev, attack_ev_legs, state_value
from common.strategy.context import _ATTACH, _ATTACK, _END, _EVOLVE, _PLAY, _RETREAT

# ── the budget caps (whitelisted: `sound_rules.composer-budget-caps`) ─────────────────────────────

#: How many candidate sequences survive each pruning step. **Derived, not tuned** — see the whitelist
#: entry for the arithmetic. Sized against the two measurements already on the record rather than a
#: fresh guess: the post-Option-Equivalence menu width is P50 **6** / P95 **12** / max **23** and the
#: leaf costs P95 **4.46 ms** (`board_expectation`'s header, `python tools/train/value_lab.py --menu`
#: over the 372 corpus frames both gates replay), while the grader's own per-decision FLOOR is
#: **>= 3.0 s** (2 vCPU x ~10 min per player per match, against P95 137 / max 198 decisions per match
#: over the 377 committed native traces).
#:
#: A full run costs at most ``1 + (SEQUENCE_DEPTH - 1) x BEAM_WIDTH`` node expansions of ``width``
#: leaf evaluations each: ``(1 + 3 x 4) x 12 = 156`` leaves ~ **0.70 s** at the P95 leaf, i.e. ~23% of
#: the grader floor. Anchored on the WIDTH half deliberately, the same reasoning `BRANCH_CAP` records:
#: the width is exactly 12 on every run while the millisecond half moves ~10% run-to-run and ~45%
#: between boxes, so a cap keyed to a wall-clock figure is a property of whoever ran it last.
#:
#: **Then measured end to end rather than left as arithmetic** — `python tools/train/composer_lab.py`
#: over the 371 corpus frames at these caps: per-decision wall-clock **median 10.3 ms, P95 155 ms,
#: max 737 ms**. The bound above held (the max lands at the predicted 0.70 s), and the whole
#: distribution sits under the grader's >= 3.0 s per-decision floor — the max at ~23%, the P95 at ~5%.
BEAM_WIDTH = 4

#: Maximum actions in a composed sequence BEFORE its terminal action — i.e. the deepest commutative
#: block the lattice is allowed to reach. 4 bounds one block's a-priori lattice at
#: ``sum(C(n, j) for j <= 4)`` while leaving the worked triple of Issue #263 § *Commutative-block
#: collapse* (an Energy, an evolution and a Tool onto distinct targets) fully inside it with a slot to
#: spare. Truncation is REPORTED (`ComposerResult.stats["depth_truncated"]`), never silent.
SEQUENCE_DEPTH = 4

#: The epsilon-band admission width, **in prizes** — a candidate within this of the k-th score is
#: admitted alongside the top-k rather than hard-dropped. It is `family_diag.DECIDER_FLOOR`, the
#: corpus-calibrated threshold below which a family cannot be any frame's decider, so a candidate
#: inside the band is one the corpus says nothing separates. Carried under its own name rather than
#: imported, because `tools/` must never be a `src/` dependency; the agreement is asserted by
#: `test_composer.py`.
#:
#: **Swept against the corpus rather than guessed, and the sweep's answer is that the band is not
#: load-bearing here** (`python tools/train/composer_lab.py --epsilon-sweep`, 371 frames, 278
#: composed). Over epsilon in {0.0, 0.001, 0.005, 0.01, 0.05} the counts do not move at all —
#: 153 first steps earn a scored top-k slot, **39** are admitted by the band alone, agreement with
#: the human's ruling holds at 79/270 and with the committed decision at 54/278. Only at 0.1 does
#: anything shift (40 band-only, one reordered top-k), and no answer changes there either. So those
#: 39 are EXACT ties with the k-th rather than near-ties, which is what a corpus dominated by
#: unmoved terms looks like: on `85046350|0|decision|32` all five options price exactly 0.0.
#:
#: The value is therefore chosen INSIDE the flat region and at the measured noise floor — the
#: conservative reading of a measurement that does not discriminate, rather than a constant nobody
#: tested. Re-sweep when the apply seam's coverage widens (246 of 278 frames still carry a refusal),
#: because that is what would make the deltas separate in the first place.
EPSILON = 0.005

def _bench_max(model) -> int:
    """The engine's own ``benchMax`` for my side, or `board_delta`'s fallback.

    Read from the observation rather than assumed, and the fallback is `board_delta`'s so the two
    halves of "is this deploy legal" cannot disagree about the cap — a second constant here is
    exactly the drift ADR-0087 charges for one store over."""
    from common.board_delta import _BENCH_MAX
    obs = getattr(model, "source_obs", None) or {}
    players = ((obs.get("current") or {}).get("players")) or []
    seat = int(getattr(model, "my_index", 0))
    me = players[seat] if 0 <= seat < len(players) and players[seat] else {}
    return int(me.get("benchMax") or _BENCH_MAX)


# ── the canonical in-block order (ADR-0095 decision 1's tiers, over board facts) ──────────────────

#: `pilot._finish_turn_last`'s six tiers, re-expressed over the facts a StateModel supplies. The
#: NUMBERS and their meaning are ADR-0095 decision 1's and are not re-derived here; what differs is
#: the input, and the difference is forced: the Pilot's `_tier` reads `traces[i]` (a scored
#: `OptionTrace` carrying `tactical`, `card_id` and `fired`), which is Pilot plumbing no StateModel
#: supplies. The composer keys off the option, its card's `CardStat`, and its footprint's
#: `reveals_information` instead.
#:
#: **Two Pilot-side nuances are deliberately NOT reproduced**, because both are score-conditional and
#: a canonical ORDER must be a pure function of the board: the KO_SCORE promotions (a lethal
#: play/attach riding tier 0) and the *"an Evolve of the Active drops to the last tier when a KO is on
#: the menu"* demotion. Inside a commutative block neither can change the end board — that is the
#: block's defining property — so their absence changes no candidate's SCORE, only which member of an
#: indistinguishable ordering is emitted first.
TIER_INFORMATIVE = 0     # free AND informative: a draw / search / dig, a Bench fill, an evolve
TIER_COMMIT_FREE = 1     # free but COMMITTING: an Item / Stadium play that reveals nothing
TIER_SUPPORTER = 2       # the one-per-turn Supporter
TIER_COMMITMENT = 3      # the blind / costly commitments: the Energy attach, a Tool equip
TIER_SHUFFLE = 4         # a hand-SHUFFLE Supporter — it nukes the hand, so attach before it
TIER_ENDER = 5           # the turn-ENDER, plus Retreat / End / anything uncharacterised

#: The behavioural Function Tag that makes a Supporter a hand-NUKE, so an Energy attach sequences
#: ahead of it. Same tag `pilot._is_shuffle_refresh` reads; named once here rather than spelled again.
_SHUFFLE_TAG = "shuffle_hand"


# ── the shapes ───────────────────────────────────────────────────────────────────────────────────


@dataclass(frozen=True)
class Step:
    """One applied action inside a candidate sequence.

    ``option`` is the dict **as applied** — re-resolved against the board it actually hit, never the
    stored depth-0 dict replayed from a permuted position (see :func:`resolve_against`) — and it is
    STRIPPED of the composer's private origin stamp, because a `Step` is the shape that leaves this
    module and the stamp is not an engine field. Stripping at construction rather than at each
    consumer is what makes that a property of the type instead of a convention three call sites could
    each forget. ``index`` is the depth-0 menu index of the Option-Equivalence class this step came
    from, which is what the composer would COMMIT if this sequence wins."""

    option: Mapping
    index: int
    tier: int
    fate: str


@dataclass(frozen=True)
class Candidate:
    """One composed sequence and its score.

    ``score = leaf + terminal_ev`` — Issue #263 § *Terminal-action valuation*, with
    ``EV(end-turn) = 0``. ``coverage_gap`` is non-empty when the candidate exists only because the
    seam could not price something: a REFUSED option, or an attack no
    :func:`~common.state_value.attack_ev_legs` leg matched. Such a candidate is REPORTED, never
    silently competing with a scored sequence."""

    steps: tuple = ()
    terminal: Mapping | None = None
    terminal_index: int | None = None
    leaf: float = 0.0
    terminal_ev: float = 0.0
    score: float = 0.0
    coverage_gap: str = ""
    truncated: int = 0

    @property
    def first_index(self):
        """The depth-0 menu index this sequence commits to, or None for the empty (stop-now) line."""
        if self.steps:
            return self.steps[0].index
        return self.terminal_index

    def working(self) -> dict:
        """The per-leg breakdown, in the shape `state_value`'s ``working`` established — so a wave-3
        packet can show a human which leg carried a flip without a second convention to learn."""
        return {"leaf": self.leaf, "terminal_ev": self.terminal_ev, "score": self.score,
                "steps": len(self.steps), "truncated": self.truncated,
                "coverage_gap": self.coverage_gap}


@dataclass(frozen=True)
class Margin:
    """Issue #263 § *Beam-quality package* item 3 — **required**, not optional.

    How close the eventually-chosen line's FIRST step came to the beam cutoff: its rank at 1-ply
    ordering relative to ``k``, and its score margin to the k-th candidate. ``in_beam`` is False when
    the chosen first step survived only on the epsilon band or not at all — which is the beam-width
    sizing signal, and the thing that must be MEASURED on f32 / f35 / f82 rather than guessed."""

    rank: int | None = None
    k: int = 0
    ranked: int = 0
    in_beam: bool = False
    admitted: bool = False
    always_expand: bool = False
    chosen_delta: float | None = None
    kth_delta: float | None = None
    margin_to_kth: float | None = None

    def working(self) -> dict:
        return {"rank": self.rank, "k": self.k, "ranked": self.ranked, "in_beam": self.in_beam,
                "admitted": self.admitted, "always_expand": self.always_expand,
                "chosen_delta": self.chosen_delta, "kth_delta": self.kth_delta,
                "margin_to_kth": self.margin_to_kth}


@dataclass(frozen=True)
class ComposerResult:
    """What :func:`compose` returns.

    ``chosen`` is the winning candidate under :func:`selection_key`; ``fanned`` is the per-OPTION
    1-ply delta with each Option-Equivalence class's value spread across its members (`fan_out`), so
    a caller indexing the live menu gets an answer for every option and not only for representatives.
    ``gaps`` carries every refusal's reason — the telemetry half of *"a refusal is an unknown, not a
    zero"*.

    ``order`` is the depth-0 1-ply ranking as ``((menu index, delta), ...)``, best first. It is
    exported rather than kept private because the acceptance property Issue #263 § *Beam-quality
    package* item 3 actually asks about is *"the eventually-chosen line's first step"* for the
    composer's OWN answer and *"f32 / f35 / f82's first steps IN-BEAM"* for the human's RULED one —
    two different options, one ranking. :meth:`margin_for` is how a caller asks about the second
    without re-deriving the first.

    **``chosen`` is None on a menu the seam can price nothing on.** That is a REPORT, not a crash:
    at a non-MAIN select every option is a `_CARD` / `_YES` / `_NUMBER` whose whole content is a card
    effect, so all of them refuse, and the honest answer is *"the composer has no opinion here"*
    rather than the argmax of a set of unknowns. ``gaps`` says why, option by option."""

    chosen: Candidate | None = None
    candidates: tuple = ()
    margin: Margin = field(default_factory=Margin)
    fanned: tuple = ()
    order: tuple = ()
    admitted: frozenset = frozenset()
    always_expanded: frozenset = frozenset()
    blocks: tuple = ()
    gaps: tuple = ()
    stats: dict = field(default_factory=dict)

    def margin_for(self, index: int) -> Margin:
        """The margin telemetry for ANY depth-0 menu option, not only the chosen one.

        Issue #392's acceptance criterion is *"f32 and f35 reach the composer's beam at the chosen
        width, demonstrated by the margin telemetry"* — a claim about the option the HUMAN ruled,
        which is the one a beam would prune. Measuring the composer's own pick instead would answer a
        different question and would pass by construction whenever the composer picked at all."""
        return _margin_at(self.order, self.always_expanded, self.admitted, self.margin.k, index)


# ── instance re-resolution ───────────────────────────────────────────────────────────────────────


def resolve_against(model, option: Mapping) -> dict | None:
    """``option`` re-pointed at the instances it named, on the board ``model`` actually holds — or
    **None** when one of them is gone.

    The composer emits a block's subsets in an order the original menu did not have, and an option
    names its card by hand INDEX. Removing hand card 0 shifts card 3 to index 2, so a stored dict
    replayed from a permuted position applies a different play — and it does so SILENTLY, because a
    shifted index still resolves to *a* legal card. This is the re-resolution the 2026-08-04
    commutativity ruling required of any consumer of element-level footprints.

    The instance keys come from `apply_option.option_serials`, which is the ONE walk that resolves
    them (and honours the option's `playerIndex`). None is returned whenever an instance the ORIGINAL
    option named cannot be found again: the card was consumed, so the option is no longer a play.
    An option that named no resolvable instance in the first place — a targetless `_RETREAT`, an
    `_END` — carries no index to go stale and is returned unchanged."""
    obs = getattr(model, "source_obs", None) or {}
    seat = int(getattr(model, "my_index", 0))
    named = option.get("playerIndex")
    if named is not None and int(named) != seat:
        return dict(option)                      # an option about THEIR board keys nothing of mine
    players = ((obs.get("current") or {}).get("players")) or []
    me = players[seat] if 0 <= seat < len(players) and players[seat] else {}
    out = dict(option)

    hand_serial, body_serial = _origin_serials(option)
    if hand_serial is not None:
        index = _index_of(me.get("hand") or (), hand_serial)
        if index is None:
            return None
        out["index"] = index
    if body_serial is not None:
        for area, zone in ((AREA_ACTIVE, "active"), (AREA_BENCH, "bench")):
            index = _index_of(me.get(zone) or (), body_serial)
            if index is not None:
                out["inPlayArea"], out["inPlayIndex"] = area, index
                break
        else:
            return None
    return out


#: Where :func:`resolve_against` stashes the instance key an option was FIRST resolved against. It
#: rides the option dict rather than a parallel map because the dict is what travels through the
#: beam, and a parallel map is exactly the thing that gets out of step with a permuted sequence.
#: Private-by-name (a leading underscore is not a legal engine field) so it can never be mistaken for
#: something `src/cg/api.py` declares.
_ORIGIN = "_composer_origin"


def stamp_origin(model, option: Mapping) -> dict:
    """``option`` with its depth-0 instance key stamped on, ready to be re-resolved at any depth.

    Called ONCE per menu option, at depth 0, where the engine's own indices are still valid. Every
    later resolution reads the stamp rather than the (now stale) indices, which is what makes
    :func:`resolve_against` a function of the INSTANCE rather than of the position."""
    hand_serial, body_serial = ao.option_serials(model, option)
    return {**option, _ORIGIN: (hand_serial, body_serial)}


def _origin_serials(option: Mapping):
    """The stamped instance key, or ``(None, None)`` for an unstamped option.

    Unstamped means *"nothing to re-resolve"*, never *"resolve it from the current indices"* — an
    option whose serials were never captured must not be re-pointed by position, which is precisely
    the silent failure this module exists to prevent."""
    origin = option.get(_ORIGIN)
    if not origin:
        return None, None
    return origin[0], origin[1]


def _index_of(cards, serial):
    """Where ``serial`` sits in ``cards`` now, or None if it is gone."""
    for i, card in enumerate(cards or ()):
        if card and card.get("serial") == serial:
            return i
    return None


def strip_origin(option: Mapping) -> dict:
    """``option`` without the composer's stamp — what a caller hands back to the engine.

    Separate from :func:`resolve_against` on purpose: the stamp must survive every internal hop and
    must never leave the module, and one function that both re-resolves and strips would make the
    boundary a matter of call order."""
    return {k: v for k, v in option.items() if k != _ORIGIN}


# ── legality, re-checked because a synthesized board has no menu ──────────────────────────────────


def _still_legal(model, option: Mapping) -> bool:
    """Would the engine still offer this option on ``model``'s board?

    At depth 0 the menu IS the proof and this is a no-op. At depth >= 1 there is no menu, and
    `apply_option` models a transition rather than policing one — so without this the beam would
    happily sequence two manual Energy attaches, or evolve a Basic it benched on the same step.

    Every limit checked here is read at source, not recalled (`docs/rules.md` §3 *Action economy* and
    §4 *Evolution timing*, both rulebook-cited):

    * **Energy attach 1 per turn** — the manual attachment only; a Tool is an ordinary Trainer play
      and `docs/rules.md` §3 caps it not at all beyond one per Pokémon, so a Tool `_ATTACH` is gated
      on the holder rather than on the allowance.
    * **Supporter 1**, **Stadium 1** (*"and only if it differs from the one in play"*), **Retreat 1**.
    * **Evolution** — *"Cannot evolve a Pokémon the turn it was played/put into play"*, read off the
      engine's own `appearThisTurn` bit through `BodyView.new_in_play`.
    * **Bench capacity** — a deploy onto a full Bench. `board_delta._play` already refuses it, but as
      an `Unmodellable`, and the composer turns an `Unmodellable` into a COVERAGE GAP. That would put
      a phantom entry in the modelling backlog for a move that is merely illegal, so the legality
      check has to catch it first. The cap is the engine's own ``benchMax``.

    **What §4 says that this does NOT check, named rather than left to be discovered:** *"Cannot
    evolve on either player's very first turn of the game."* It is safe by construction rather than by
    omission — every candidate descends from an option the ENGINE offered at depth 0, and the engine
    does not offer an illegal evolve, so a first-turn evolve can never enter the tree for this
    function to re-reject. The four limits above are different: each is spent by an EARLIER STEP of
    the composer's own sequence, which is state the depth-0 menu could not have known about.

    Fail closed: an unreadable card, an unresolvable target or an unrecognised kind is NOT sequenced.
    A phantom option is a candidate the composer will happily rank."""
    kind = ao.transition_kind(option)
    if kind == _RETREAT:
        return not model.retreated
    card = _option_card_stat(model, option)
    if kind == _ATTACH:
        if card is None:
            return False
        if getattr(card, "is_tool", False):
            body = _target_body(model, option)
            return body is not None and not body.tool_ids
        return not model.energy_attached
    if kind == _EVOLVE:
        body = _target_body(model, option)
        return body is not None and not body.new_in_play
    if kind == _PLAY:
        if card is None:
            return False
        if getattr(card, "is_supporter", False):
            return not model.supporter_played
        if getattr(card, "is_stadium", False):
            return not model.stadium_played and model.stadium_id != card.cardId
        if getattr(card, "is_pokemon", False) and not getattr(card, "evolvesFrom", None):
            return len(model.mine.bench) < _bench_max(model)
        return True                              # an Item — no per-turn allowance and no capacity
    return True                                  # terminal kinds and anything the seam refuses


def _option_card_stat(model, option: Mapping):
    """The `CardStat` of the card an option plays from hand, or None.

    The HAND reference, deliberately: every allowance in `docs/rules.md` §3 is keyed on what is being
    PLAYED, not on what it lands on. A `_PLAY` names its hand index bare with no ``area`` at all,
    which is why the default is the hand rather than a skip — the same convention
    `apply_option._option_card` keeps."""
    obs = getattr(model, "source_obs", None) or {}
    seat = int(getattr(model, "my_index", 0))
    players = ((obs.get("current") or {}).get("players")) or []
    me = players[seat] if 0 <= seat < len(players) and players[seat] else {}
    area, index = option.get("area"), option.get("index")
    if area not in (None, AREA_HAND) or not isinstance(index, int) or index < 0:
        return None
    hand = me.get("hand") or ()
    if index >= len(hand) or not hand[index]:
        return None
    return model.card_stat(hand[index].get("id"))


def _target_body(model, option: Mapping):
    """The `BodyView` an option's in-play reference names, or None when it names none."""
    area, index = option.get("inPlayArea"), option.get("inPlayIndex")
    if not isinstance(index, int) or index < 0:
        return None
    if area == AREA_ACTIVE:
        active = model.mine.active
        return active if index == 0 else None
    if area == AREA_BENCH:
        bench = model.mine.bench
        return bench[index] if index < len(bench) else None
    return None


# ── the canonical in-block order ─────────────────────────────────────────────────────────────────


#: `trigger` -> the option KIND that clause fires with. The vocabulary is
#: `snapshot_coverage.VOCABULARY["trigger"]`'s own — *"which OPTION the clause rides (on_evolve /
#: on_bench_play / on_attach / on_attack)"* — read from the registry rather than invented here, and
#: `test_composer.py` asserts this map covers exactly `snapshot_coverage.CLAUSE_SELECTORS["trigger"]`,
#: so a new trigger value cannot silently fall through to "does not ride".
_TRIGGER_KIND = {"on_attach": _ATTACH, "on_evolve": _EVOLVE, "on_bench_play": _PLAY,
                 "on_attack": _ATTACK}


def _reveal_rides(model, option: Mapping) -> bool:
    """Does a revealing clause actually fire when THIS option is taken?

    **A different question from the footprint's, and the difference cost a real acceptance frame.**
    `option_footprint.reveals_information` asks *"can this CARD reveal at all?"* and is deliberately
    conservative, because it feeds `footprints_commute`'s veto — a card that might reveal must never
    join a commutative block. Routing is the narrower question, and answering it with the footprint
    refuses transitions the seam models perfectly well.

    Measured, not reasoned (`data/EN_Card_Data.csv` + `src/common/card_effects.json`, read at source):

    * **120 Drakloak** — its `draw` clause carries ``condition: once_per_turn_ability`` and the CSV
      prints it as *"[Ability] Recon Directive"*. The Ability is its OWN `_ABILITY` option; evolving
      into Drakloak reveals nothing, and `board_delta._evolve` models that evolve exactly. Routing on
      the footprint refused it, unpriced, on a live acceptance board — option 1 of
      `85046350|0|decision|32` (Issue #263's **f32**) is exactly that evolve. Same shape for
      66 Dudunsparce, 140 Fezandipiti ex and 675 Lunatone.

      ⚠️ An earlier draft of this note called that evolve *"f32's RULED first step"*. **It is not** —
      f32's ruling was REFRAMED on 2026-07-10 and the authoritative record is
      `tests/fixtures/corrections/dragapult_hammer_over_develop_f32.json`, whose
      ``claims.decision.correct`` is `[3]`, the `_RETREAT` (*"Retreat Dreepy → promote Budew
      (sacrificial item-lock wall)"*). The superseded `data/corrections/` record still carries `[1]`,
      and reading THAT is how the wrong claim got written. The routing fix stands on its own merits;
      only the sentence justifying it was wrong.
    * **19 Telepath Psychic Energy** — its `fetch` clause carries ``trigger: "on_attach"``, and the
      CSV prints *"When you attach this card from your hand to a {P} Pokemon, search your deck for up
      to 2 Basic {P} Pokemon and put them onto your Bench."* The reveal DOES ride the attach, and
      `board_delta._attach` never consults clauses at all (`_clause_writes` is reached only from
      `_play` and the Stadium gate), so letting it through would model the structural attach and drop
      a two-Pokemon Bench fill. It must refuse.
    * **1071 Meowth ex** — ``trigger: "on_bench_play"``: the reveal rides the `_PLAY`, so it routes to
      the Expectation like any Item.

    Fail closed in the direction that matters: an untriggered clause on a `_PLAY` rides it (a
    Trainer's effect IS the play), and an untriggered clause on any other kind does not (it is an
    Ability, which the engine poses as its own option)."""
    from common.board_delta import card_clauses
    kind = ao.transition_kind(option)
    card = _option_card_stat(model, option)
    if card is None:
        return kind == _PLAY                       # unreadable: keep the conservative `_PLAY` answer
    for clause in card_clauses(getattr(model, "combat", None), card.cardId) or ():
        values = set(snapshot_coverage.clause_values(clause))
        if not (values & snapshot_coverage.REVEALING_CLAUSES):
            continue
        trigger = clause.get("trigger")
        if trigger is not None:
            if _TRIGGER_KIND.get(trigger) == kind:
                return True
        elif kind == _PLAY:
            return True
    return False


def canonical_tier(model, option: Mapping, footprint=None) -> int:
    """This option's information-before-commitment TIER — the canonical in-block ordering
    (ADR-0095 decision 1, moved inside the composer by Issue #263 § *Commutative-block collapse*).

    Derived from the option, its card's `CardStat`, and — for the informative test — the per-option
    footprint's ``reveals_information``, which is the seam's own answer to *"does this ENLARGE the
    information set?"* rather than a second tag list beside it. Passing the footprint in is an
    optimisation only: the caller has already computed it for the commutativity test, and computing
    it twice on the ordering hot path is the cost `option_footprint`'s docstring exists about.

    Note the tier is TOTAL over the menu even though a revealing option can never join a block
    (`footprints_commute` vetoes it): the beam expands every admitted option, and an ordering key that
    answered None for some of them would fall through to menu position — the exact fall-through
    Issue #263 § *Beam-quality package* item 1 forbids."""
    kind = ao.transition_kind(option)
    if kind in (_ATTACK, _END, _RETREAT):
        return TIER_ENDER
    fp = footprint if footprint is not None else ao.option_footprint(model, option)
    if fp.reveals_information:
        return TIER_INFORMATIVE
    card = _option_card_stat(model, option)
    if kind == _EVOLVE:
        return TIER_INFORMATIVE                  # "evolve a benched Pokemon" rides the free band
    if kind == _ATTACH:
        return TIER_COMMITMENT                   # Energy AND Tool: a Tool is an `_ATTACH` (tier 3)
    if kind == _PLAY and card is not None:
        if getattr(card, "is_supporter", False):
            return TIER_SHUFFLE if _shuffles_hand(model, card) else TIER_SUPPORTER
        if getattr(card, "is_pokemon", False):
            return TIER_INFORMATIVE              # a Bench fill is free and reveals a better target
        return TIER_COMMIT_FREE                  # an Item / a Stadium: free but committing
    return TIER_ENDER                            # uncharacterised: last, fail closed


def _shuffles_hand(model, card) -> bool:
    """Does this Supporter NUKE my hand (`shuffle_hand`)? Asked of the Function Tags through the
    model's combat surface, which is the one place behavioural tags are read."""
    functions = getattr(getattr(model, "combat", None), "functions", None)
    if functions is None:
        return False
    try:
        return _SHUFFLE_TAG in (functions.tags(card.cardId) or ())
    except Exception:                            # noqa: BLE001 — an unknown card is not a shuffler
        return False


def canonical_key(model, option: Mapping, index: int, canon: str, footprint=None) -> tuple:
    """The TOTAL in-block ordering key: ``(tier, board-derived identity, menu index)``.

    ``canon`` is `option_equivalence.canonical_keys`' entry for this option — the ADR-0103 fingerprint
    that makes the key a pure function of the BOARD, so permuting the menu permutes these keys with it
    and invents no new ones. The menu index is last and separates only options that key equal on
    everything above it, exactly as `pilot._order_key` does."""
    return (canonical_tier(model, option, footprint), canon, index)


# ── commutative blocks ───────────────────────────────────────────────────────────────────────────


def commutative_blocks(model, options: Sequence[Mapping], indices=None) -> tuple:
    """Maximal sets of pairwise-COMMUTING options, as tuples of menu indices.

    Reported for telemetry and for the lattice tests; the beam itself asks :func:`_admissible_in_block`
    pairwise as it expands, because a block is a property of the sequence being built rather than a
    partition computed once. Greedy-maximal and deterministic: options are visited in menu order and
    each joins the first block whose every member it provably commutes with.

    The licence is `apply_option.footprints_commute` over per-OPTION footprints and nothing else.
    Fail closed everywhere — an unknown or partial footprint commutes with nothing, a revealing play
    can never join a block, and a pair that is merely *not proven* to conflict is treated as
    conflicting."""
    prints = {i: ao.option_footprint(model, options[i])
              for i in (range(len(options)) if indices is None else indices)
              if not ao.is_terminal(options[i])}
    blocks: list[list[int]] = []
    for i in sorted(prints):
        for block in blocks:
            if all(ao.footprints_commute(prints[i], prints[j]) for j in block):
                block.append(i)
                break
        else:
            blocks.append([i])
    return tuple(tuple(b) for b in blocks if len(b) > 1)


def subset_lattice(members: Sequence) -> tuple:
    """Every SUBSET of ``members``, each in one canonical order — ``2**n`` tuples, never the
    ``sum(n!/(n-k)!)`` ordered prefixes.

    Generated a-priori by extending only with a member that sorts strictly AFTER the last one, which
    is the same rule :func:`_admissible_in_block` applies inside the beam. Stated as a standalone
    function so the counting property (8 / 16 / 32 against 16 / 65 / 326 for n = 3 / 4 / 5) is
    testable without driving a whole beam, and so the two spellings of the rule can be asserted
    identical."""
    out = [()]
    for member in members:
        out = out + [prefix + (member,) for prefix in out]
    return tuple(out)


def _admissible_in_block(key, block_keys) -> bool:
    """May a step with canonical ``key`` extend a block whose members' keys are ``block_keys``?

    Only when it sorts strictly after every one of them. That single rule is what turns the beam's
    tree into the SUBSET lattice: for *n* pairwise-commuting options it generates each subset exactly
    once, in the canonical order, and a duplicate ordering is never CREATED — which is the difference
    Issue #263 insists on against a post-hoc transposition table that pays full generation cost first
    and then needs a canonical state hash to merge."""
    return all(key > other for other in block_keys)


# ── the terminal action ──────────────────────────────────────────────────────────────────────────


def terminal_ev(model, option: Mapping) -> tuple:
    """``(EV in prizes, AttackEV or None, coverage-gap reason)`` for a TERMINAL option.

    ``EV(end-turn) = 0`` by definition — ending the turn buys nothing beyond the board already
    scored. ``EV(attack)`` composes `state_value.attack_ev` over POC-T4/3's extractor
    (`attack_ev_legs`), matched to the option's own ``attackId``.

    ⚠️ **Reads `AttackEV.total`, never the working-dict sum.** The `working()` shape is FROZEN and
    ASYMMETRIC: it omits ``total`` and emits ``next_turn_cost`` POSITIVE while ``total`` subtracts it,
    so a consumer that sums the dict gets ``total + 2 x next_turn_cost``. This is the consumer that
    docstring warns about.

    An attack no leg matches is a **coverage gap**, not a zero. Returning 0.0 quietly would sort a
    real attack below every scored line — *"a 0 delta is never explored, not undervalued"* — so the
    reason is carried out and the candidate is flagged, the same treatment a `Refusal` gets."""
    kind = ao.transition_kind(option)
    if kind == _END:
        return 0.0, None, ""
    if kind != _ATTACK:
        return 0.0, None, f"option kind {kind} is terminal but is neither attack nor end-turn"
    attack_id = option.get("attackId")
    for leg in attack_ev_legs(model):
        if leg.attack_id == attack_id:
            ev = attack_ev(**leg.kwargs)
            return float(ev.total), ev, ""
    return 0.0, None, (
        f"attack {attack_id!r} has no `attack_ev_legs` leg on this board — its EV is UNKNOWN, and "
        f"pricing it 0.0 would rank a real attack below every scored line")


# ── the deterministic selection tie-break, in ONE place ──────────────────────────────────────────


def selection_key(model, candidate: Candidate) -> tuple:
    """The ONE ordering key for choosing among candidates — Issue #263 § *Beam-quality package*
    item 1 (old Issue #145 amendment D, moved here because it was always a composer concern).

    Ascending, so every leg is negated where it should rank high:

    1. **sequence score** (descending);
    2. **Worth of the touched card** (descending) — `card_worth.role_value` reached through
       `MySide.role_worth`, which is the sole-supplier route (Roles are DECLARED by the Strategy, not
       a card fact, so the model resolves them);
    3. **a stable card-id sort**, then the depth-0 menu index.

    **This supersedes the ADR-0103 canon string as the third key AT THE SELECTION POINT**, and the
    difference is worth stating rather than leaving to be found: `pilot._order_key`'s third leg is the
    board-derived fingerprint, which separates two options the board CAN tell apart; here the Worth
    leg does that job first and more meaningfully, and what remains after it is a card-id sort that is
    equally a pure function of the board. Neither ever falls through to raw generation order, which is
    the property both keys exist for and the one that fixed ADR-0062:29, `mega_starmie` ep82867148
    f48/f87 and `mega_lucario` ep83661652 f33/f40/f44.

    A coverage-gap candidate sorts LAST within its score band, so it can never quietly beat a scored
    sequence it merely failed to be compared with."""
    worth, card_id = 0.0, -1
    step = candidate.steps[0] if candidate.steps else None
    option = step.option if step is not None else candidate.terminal
    if option is not None:
        stat = _option_card_stat(model, option)
        if stat is not None:
            card_id = int(getattr(stat, "cardId", -1) or -1)
            worth = float(model.mine.role_worth(stat.cardId))
    index = candidate.first_index
    return (bool(candidate.coverage_gap), -candidate.score, -worth, card_id,
            index if index is not None else 1 << 30)


# ── the beam ─────────────────────────────────────────────────────────────────────────────────────


@dataclass(frozen=True)
class _Node:
    """A partially-composed sequence: the board it reached, the steps that got there, which depth-0
    classes it consumed, and the canonical keys of the commutative block currently open."""

    model: object
    steps: tuple = ()
    used: frozenset = frozenset()
    block: tuple = ()            # canonical keys of the open block's members
    block_prints: tuple = ()     # their footprints, for the pairwise commutativity test
    truncated: int = 0
    leaf: float = 0.0


def compose(model, options: Sequence[Mapping], *, k: int = BEAM_WIDTH, epsilon: float = EPSILON,
            depth: int = SEQUENCE_DEPTH, search_api=None, deterministic=None,
            clauses_cover=None) -> ComposerResult:
    """Compose this decision's candidate sequences and return the best, with its telemetry.

    ``options`` is the engine's live menu. ``deterministic`` and ``clauses_cover`` are the seam's own
    per-option inputs (`apply_option.fate`) and may be given either as a plain value or as a callable
    ``option -> value``; the callable form is the real one, because both are per-option facts and
    `fate`'s closing paragraph makes joining them the CALLER's job. Their default `None` takes the
    structural MODELLED path, which is what the pool mostly is.

    **Pure and bit-identical across runs** (Issue #262's purity, inherited): no dict/set iteration
    decides an order anywhere, every tie resolves through :func:`selection_key`, and the model is
    never mutated — `apply_option` hands back a FRESH model per hypothetical.

    Wall-clock is recorded in ``stats`` rather than enforced. A composer that silently gave up at a
    time limit would produce an under-explored line that looks confidently valued, which is the
    no-silent-caps failure; the caps that DO bind are structural and their truncation is reported."""
    if int(k) < 1 or int(depth) < 0:
        # Caller error, so it RAISES where a modelling gap refuses — the same split
        # `board_expectation.expectation` draws for its own `cap < 1`. And it is not pedantry: both
        # `_admit` and `_prune_nodes` index the k-th as `[k - 1]`, so a `k` of 0 indexes the WORST
        # candidate from the end and admits the entire menu. A beam that silently stops being a beam
        # is the exact shape of failure the no-silent-caps discipline exists against.
        raise ValueError(
            f"k={k!r}, depth={depth!r}: a beam must keep at least one candidate and cannot search a "
            f"negative number of plies. k=0 would index the k-th candidate as [-1] and admit "
            f"everything, which reads as a working beam while being none.")
    t0 = time.perf_counter()
    obs = getattr(model, "source_obs", None) or {}
    options = list(options or [])
    equiv = option_equivalence(options, obs)
    reps = class_representatives(equiv, len(options))
    canon = canonical_keys(options, obs)
    stamped = [stamp_origin(model, o) for o in options]

    state = _Run(k=k, epsilon=epsilon, depth=depth, search_api=search_api,
                 deterministic=deterministic, clauses_cover=clauses_cover,
                 canon=canon, reps=reps, stamped=stamped)

    root = _Node(model=model, leaf=float(state_value(model)))
    frontier, root_ranked = [root], None
    for ply in range(depth + 1):
        expanded = []
        for node in frontier:
            ranked = _rank(state, node)
            if node is root:
                root_ranked = ranked
            expanded.extend(_expand(state, node, ranked))
        if not expanded:
            break
        if ply == depth:
            state.depth_truncated += len(expanded)
            break
        frontier = _prune_nodes(state, expanded)

    ranked0 = root_ranked or []
    chosen = min(state.candidates, key=lambda c: selection_key(model, c)) \
        if state.candidates else None
    return ComposerResult(
        chosen=chosen,
        candidates=tuple(sorted(state.candidates, key=lambda c: selection_key(model, c))),
        margin=_margin(state, ranked0, chosen),
        fanned=tuple(fan_out([state.one_ply.get(i) for i in range(len(options))], equiv)),
        order=tuple((e.index, e.delta) for e in ranked0),
        admitted=_admitted_indices(state, ranked0), always_expanded=_free_indices(ranked0),
        blocks=commutative_blocks(model, stamped, reps),
        gaps=tuple(state.gaps),
        stats={"leaf_evals": state.leaf_evals, "nodes": state.nodes,
               "candidates": len(state.candidates), "truncated": state.truncated,
               "depth_truncated": state.depth_truncated,
               "ms": (time.perf_counter() - t0) * 1000.0})


@dataclass
class _Run:
    """One :func:`compose` call's mutable bookkeeping. A plain record rather than closure variables so
    the helpers below are testable in isolation and so nothing is captured by accident."""

    k: int
    epsilon: float
    depth: int
    search_api: object
    deterministic: object
    clauses_cover: object
    canon: list
    reps: list
    stamped: list
    candidates: list = field(default_factory=list)
    gaps: list = field(default_factory=list)
    one_ply: dict = field(default_factory=dict)   # depth-0 delta per representative index
    leaf_evals: int = 0
    nodes: int = 0
    truncated: int = 0
    depth_truncated: int = 0


def _ask(resolver, option):
    """A per-option seam input, however the caller supplied it — a callable is asked, anything else
    is passed straight through. Both `fate` inputs are per-option facts, so the callable form is the
    honest one; the scalar form exists because a test fixing one answer for a whole menu should not
    have to write a lambda."""
    return resolver(option) if callable(resolver) else resolver


def _rank(state: _Run, node: _Node) -> list:
    """One node's 1-ply ordering — **the whole ordering heuristic, applied uniformly**.

    Every option still available on this board is applied through the seam, `state_value`'d, and
    ranked by the delta against the node's own leaf. Returns a list of ``_Ranked`` sorted by delta
    descending with a deterministic tail (canonical key, then menu index), never by menu position.

    Availability is two tests and both are re-checks rather than assumptions: the option's instances
    must still resolve (:func:`resolve_against`) and the per-turn allowances must still permit it
    (:func:`_still_legal`)."""
    out = []
    for i in state.reps:
        if i in node.used:
            continue
        option = resolve_against(node.model, state.stamped[i])
        if option is None or not _still_legal(node.model, option):
            continue
        entry = _one_ply(state, node, option, i)
        if entry is None:
            continue
        if not node.steps:
            # Recorded HERE rather than after admission, so `ComposerResult.fanned` answers for every
            # option the menu offered — a caller indexing the live menu must not meet a None that
            # means "pruned" where it expects one that means "unfingerprintable".
            state.one_ply[i] = entry.delta
        out.append(entry)
    out.sort(key=lambda e: (-e.delta, e.key))
    return out


@dataclass(frozen=True)
class _Ranked:
    """One option's 1-ply verdict at one node."""

    index: int
    option: dict
    key: tuple
    delta: float
    after: object            # the model to continue from, or None (terminal / refused / reveal)
    fate: str
    footprint: object
    terminal: bool = False
    reveals: bool = False
    refused: bool = False
    truncated: int = 0
    ev: float = 0.0
    gap: str = ""


def _one_ply(state: _Run, node: _Node, option: dict, index: int):
    """Apply ONE option and price it. The four fates, each with its own honest answer.

    * **TERMINAL** — no successor board. The candidate's leaf is the board it was reached FROM, and
      the terminal action's own EV is the second summand (Issue #263 § *Terminal-action valuation*).
    * **REFUSED** — cannot be applied, so it becomes a one-action terminal candidate flagged as a
      coverage gap. Ranked at the node's own leaf so it is never dropped and never silently
      out-competes a scored sequence; `selection_key` sorts it last within its score band.
    * **an Expectation** — ranked by `expected()`, which is the availability-weighted average and
      therefore a strict LOWER bound on a choice node's true max (`board_expectation`'s header). A
      reveal is a BLOCK BOUNDARY and a REPLAN POINT, so the beam stops there rather than continuing
      from a synthesized post-reveal board.
    * **a model** (MODELLED, or ENGINE-RESOLVED unwrapped) — the ordinary case.

    **Routing a revealing option to an Expectation happens HERE, and that is by design.**
    `apply_option`'s dispatch is deliberately unchanged by POC-T4/2 — its header says outright that
    *"routing a revealing option to an Expectation is a behaviour change, and the composer is what
    makes it"* — so this is the one site that asks `common.board_expectation` instead of the point
    transition. The reveal test is the per-option footprint's ``reveals_information``, armed off
    `snapshot_coverage.REVEALING_CLAUSES`, rather than a second card list beside it."""
    if ao.is_terminal(option):
        ev, _detail, gap = terminal_ev(node.model, option)
        if gap:
            state.gaps.append(f"{_frame_of(option)}: {gap}")
        return _Ranked(index=index, option=option,
                       key=(TIER_ENDER, state.canon[index], index),
                       delta=ev, after=None, fate=ao.TERMINAL, footprint=ao.Footprint(),
                       terminal=True, ev=ev, gap=gap)
    cover = _ask(state.clauses_cover, option)
    footprint = ao.option_footprint(node.model, option, clauses_cover=cover)
    key = canonical_key(node.model, option, index, state.canon[index], footprint)

    def _refuse(reason: str) -> _Ranked:
        state.gaps.append(f"{_frame_of(option)}: {reason}")
        return _Ranked(index=index, option=option, key=key, delta=0.0, after=None,
                       fate=ao.REFUSED, footprint=footprint, refused=True, gap=reason)

    if footprint.reveals_information and _reveal_rides(node.model, option):
        if ao.transition_kind(option) != _PLAY:
            return _refuse(
                "a revealing clause RIDES this option and it is not a `_PLAY`, so neither seam can "
                "price it: `board_expectation` enumerates a played Item/Supporter's search and "
                "refuses a reveal riding another kind, while the point transition consults no "
                "clauses on this kind at all and would apply the structural half while silently "
                "DROPPING the reveal — an under-reported delta, which at ordering time is a pruned "
                "option rather than an undervalued one")
        try:
            result = bx.expectation(node.model, option)
        except Unmodellable as gap:
            return _refuse(str(gap))
        state.leaf_evals += len(result.classes)
        try:
            leaf = float(result.expected(state_value))
        except ValueError as gap:                # an un-enumerated effect: an unknown, not a zero
            return _refuse(str(gap))
        state.truncated += result.truncated
        return _Ranked(index=index, option=option, key=key, delta=leaf - node.leaf, after=None,
                       fate=ao.MODELLED, footprint=footprint, reveals=True,
                       truncated=result.truncated, ev=leaf)

    result = ao.apply_option(node.model, option, depth=len(node.steps),
                             search_api=state.search_api,
                             deterministic=_ask(state.deterministic, option),
                             clauses_cover=cover)
    if ao.must_expand(result):
        return _refuse(f"{result.scope}: {result.reason}")
    after = ao.require_model(result)
    state.leaf_evals += 1
    leaf = float(state_value(after))
    return _Ranked(index=index, option=option, key=key, delta=leaf - node.leaf, after=after,
                   fate=ao.ENGINE_RESOLVED if isinstance(result, ao.EngineResolved) else ao.MODELLED,
                   footprint=footprint, ev=leaf)


def _frame_of(option: Mapping) -> str:
    """A refusal's subject, for the telemetry line — the option kind and its instance key, which is
    what a modelling backlog entry needs to be actionable."""
    hand, body = _origin_serials(option)
    return f"kind {ao.transition_kind(option)} (hand {hand}, body {body})"


def _admit(state: _Run, ranked: list) -> list:
    """The **epsilon-band beam admission** — top-k PLUS anything within :data:`EPSILON` of the k-th.

    A different mechanism from :func:`selection_key`, and Issue #263 § *Beam-quality package* is
    explicit that they must not be merged: this one is about not LOSING a candidate during search,
    that one is about choosing DETERMINISTICALLY among candidates already in front of the composer.
    A hard top-k cutoff drops a genuine near-tie with the k-th slot, which is exactly where a good
    enabling move is most likely to be lost.

    Terminal and refused entries are admitted unconditionally: neither costs a further expansion, and
    dropping either would make an unpriceable option indistinguishable from a worthless one — the
    always-expand contract `apply_option.must_expand` names."""
    free = [e for e in ranked if e.terminal or e.refused]
    scored = [e for e in ranked if not (e.terminal or e.refused)]
    if len(scored) <= state.k:
        return free + scored
    cutoff = scored[state.k - 1].delta - state.epsilon
    return free + [e for e in scored if e.delta >= cutoff]


def _expand(state: _Run, node: _Node, ranked: list) -> list:
    """Turn one node's admitted options into candidates and child nodes.

    The node ITSELF is always emitted as a candidate — the stop-here line, which is the empty member
    of its block's subset lattice — so a sequence is never forced to keep going to be scored.

    The commutative-block rule is applied HERE and a-priori: a child that provably commutes with every
    open block member may only extend the block when its canonical key sorts strictly after all of
    them, which generates each subset exactly once. A child that does NOT commute with some member
    opens a FRESH block and is admitted unconditionally, so both orderings of a genuinely
    order-dependent pair are still explored at full beam width (two `_EVOLVE`s on distinct bodies are
    the worked case — they collide on whole-zone `special_conditions`)."""
    state.nodes += 1
    children = []
    state.candidates.append(_stop_here(state, node))
    for entry in _admit(state, ranked):
        if entry.terminal:
            state.candidates.append(_terminal_candidate(node, entry))
            continue
        if entry.refused or entry.after is None:
            state.candidates.append(_gap_or_reveal_candidate(node, entry))
            continue
        commutes = all(ao.footprints_commute(entry.footprint, fp) for fp in node.block_prints)
        if commutes and node.block and not _admissible_in_block(entry.key, node.block):
            continue                             # this subset already exists in canonical order
        step = Step(option=strip_origin(entry.option), index=entry.index, tier=entry.key[0],
                    fate=entry.fate)
        children.append(_Node(
            model=entry.after, steps=node.steps + (step,), used=node.used | {entry.index},
            block=(node.block + (entry.key,)) if commutes else (entry.key,),
            block_prints=(node.block_prints + (entry.footprint,)) if commutes
            else (entry.footprint,),
            truncated=node.truncated + entry.truncated, leaf=node.leaf + entry.delta))
    return children


def _stop_here(state: _Run, node: _Node) -> Candidate:
    """The candidate that takes ``node``'s steps and stops — ``EV(terminal) = 0``.

    Distinct from the `_END` option's candidate even though they score the same: `_END` is only on the
    menu at a MAIN select, and the composer must be able to value a line at every decision point it
    visits (Issue #263 § *Every fresh decision point is a composer decision*)."""
    return Candidate(steps=node.steps, terminal=None, leaf=node.leaf, terminal_ev=0.0,
                     score=node.leaf, truncated=node.truncated)


def _terminal_candidate(node: _Node, entry: _Ranked) -> Candidate:
    """A sequence ending in an attack or an end-turn. The leaf is the board the terminal action was
    reached FROM — a terminal option has no successor state — and the EV is the second summand."""
    return Candidate(steps=node.steps, terminal=strip_origin(entry.option),
                     terminal_index=entry.index, leaf=node.leaf, terminal_ev=entry.ev,
                     score=node.leaf + entry.ev, coverage_gap=entry.gap,
                     truncated=node.truncated)


def _gap_or_reveal_candidate(node: _Node, entry: _Ranked) -> Candidate:
    """A line that STOPS at this option — either because the seam refused it (a coverage gap) or
    because it reveals information and the engine will re-present the menu.

    A refusal keeps the node's own leaf: the option was never applied, so nothing about the board
    moved, and the flag is what carries the fact that its value is UNKNOWN rather than zero. A reveal
    keeps its Expectation's `expected()` — a strict lower bound on the choice node's true max."""
    step = Step(option=strip_origin(entry.option), index=entry.index, tier=entry.key[0],
                fate=entry.fate)
    leaf = node.leaf if entry.refused else node.leaf + entry.delta
    return Candidate(steps=node.steps + (step,), terminal=None, leaf=leaf, terminal_ev=0.0,
                     score=leaf, coverage_gap=entry.gap,
                     truncated=node.truncated + entry.truncated)


def _prune_nodes(state: _Run, nodes: list) -> list:
    """Prune the frontier by the same top-k-plus-epsilon rule the option ranking uses.

    One rule, asked twice, rather than two spellings that could drift: the quantity is a leaf value
    in prizes in both cases, and the band means the same thing at both sites."""
    if len(nodes) <= state.k:
        return nodes
    ordered = sorted(nodes, key=lambda n: (-n.leaf, tuple(s.index for s in n.steps)))
    cutoff = ordered[state.k - 1].leaf - state.epsilon
    return [n for n in ordered if n.leaf >= cutoff]


def _margin_at(order: tuple, free: frozenset, admitted: frozenset, k: int, index) -> Margin:
    """The ONE margin computation over a depth-0 ordering — shared by :func:`compose`'s own answer and
    by :meth:`ComposerResult.margin_for`, so the composer's line and the human's ruled line are
    measured by the same instrument rather than by two spellings of it."""
    kth = order[k - 1][1] if len(order) >= k else None
    if index is None:
        return Margin(k=k, ranked=len(order), kth_delta=kth)
    rank = next((n + 1 for n, (i, _d) in enumerate(order) if i == index), None)
    delta = next((d for i, d in order if i == index), None)
    return Margin(rank=rank, k=k, ranked=len(order),
                  in_beam=rank is not None and rank <= k and index not in free,
                  admitted=index in admitted, always_expand=index in free,
                  chosen_delta=delta, kth_delta=kth,
                  margin_to_kth=None if (delta is None or kth is None) else delta - kth)


def _free_indices(ranked0: list) -> frozenset:
    """Depth-0 options admitted UNCONDITIONALLY — the terminals and the refusals."""
    return frozenset(e.index for e in ranked0 if e.terminal or e.refused)


def _admitted_indices(state: _Run, ranked0: list) -> frozenset:
    """Depth-0 options that survived pruning, by any route."""
    return frozenset(e.index for e in _admit(state, ranked0))


def _margin(state: _Run, ranked0: list, chosen: Candidate | None) -> Margin:
    """The chosen line's first step, measured against the beam cutoff it had to survive.

    ``rank`` is 1-based over the depth-0 ordering.

    **THREE survival fields, because "did it survive" and "did it earn its place" are different
    questions and conflating them would make this instrument report a pass it never measured:**

    * ``in_beam`` — it made the hard top-k **by score**. A step admitted purely by the epsilon band
      reads as the near-miss it is, which is the whole point: *"a first step that barely survives on
      many corpus frames is an early warning that beam width or term shaping needs work, visible
      BEFORE it silently fails on an unseen board"*.
    * ``admitted`` — it survived pruning at all, by any route.
    * ``always_expand`` — it survived because a TERMINAL or a REFUSED option is admitted
      unconditionally (`must_expand`'s always-expand contract). Such an option carries delta 0.0 by
      construction, since it was never applied, so an ``in_beam`` reading of it would be a statement
      about a tie at zero rather than about the leaf preferring it. Measured on the corpus this is
      not a corner case: on `85046350|0|decision|32` (f32) **all five** options price exactly 0.0.
    """
    return _margin_at(tuple((e.index, e.delta) for e in ranked0), _free_indices(ranked0),
                      _admitted_indices(state, ranked0), state.k,
                      None if chosen is None else chosen.first_index)


__all__ = (
    "BEAM_WIDTH", "SEQUENCE_DEPTH", "EPSILON",
    "TIER_INFORMATIVE", "TIER_COMMIT_FREE", "TIER_SUPPORTER", "TIER_COMMITMENT", "TIER_SHUFFLE",
    "TIER_ENDER",
    "Step", "Candidate", "Margin", "ComposerResult",
    "compose", "selection_key", "terminal_ev", "canonical_tier", "canonical_key",
    "commutative_blocks", "subset_lattice", "resolve_against", "stamp_origin", "strip_origin",
)
