"""Abra (card 741). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, Clause, DARKNESS, FIGHTING, PSYCHIC, PokemonCard)

CARD = PokemonCard(
    card_id=741,
    name='Abra',
    hp=50,
    energy_type=PSYCHIC,
    stage=BASIC,
    weakness=DARKNESS,
    resistance=FIGHTING,
    retreat_cost=1,
    tags=frozenset([]),
    default_roles=('primary_attacker', 'support_pokemon'),
    attacks=(
        Attack(
            attack_id=1070,
            name='Teleportation Attack',
            cost=(PSYCHIC,),
            damage=10,
            text='Switch this Pokémon with 1 of your Benched Pokémon.',
            clauses=(Clause('switch_self'),),
        ),
    ),
)
