"""Aipom (card 843). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, FIGHTING, PokemonCard)

CARD = PokemonCard(
    card_id=843,
    name='Aipom',
    hp=70,
    energy_type=COLORLESS,
    stage=BASIC,
    weakness=FIGHTING,
    retreat_cost=1,
    tags=frozenset(['hand_disruption']),
    attacks=(
        Attack(
            attack_id=1216,
            name='Astonish',
            cost=(COLORLESS, COLORLESS),
            damage=20,
            text='Choose a random card from your opponent’s hand, and your opponent reveals that card and shuffles it into their deck.',
        ),
    ),
)
