"""Alakazam (card 245). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, Clause, DARKNESS, FIGHTING, PSYCHIC, PokemonCard, STAGE2)

CARD = PokemonCard(
    card_id=245,
    name='Alakazam',
    hp=140,
    energy_type=PSYCHIC,
    stage=STAGE2,
    evolves_from='Kadabra',
    weakness=DARKNESS,
    resistance=FIGHTING,
    retreat_cost=1,
    default_roles=('primary_attacker',),
    attacks=(
        Attack(
            attack_id=338,
            name='Strange Hacking',
            cost=(PSYCHIC,),
            damage=0,
            text='Your opponent’s Active Pokémon is now Confused. You may move any number of damage counters on your opponent’s Pokémon to their other Pokémon in any way you like.',
            clauses=(Clause('confuse', target='opp_active'), Clause('move_damage', amount='any', zone='opp_any', dest='opp_any', optional=True)),
        ),
        Attack(
            attack_id=339,
            name='Psychic',
            cost=(PSYCHIC,),
            damage=10,
            text='This attack does 50 more damage for each Energy attached to your opponent’s Active Pokémon.',
            clauses=(Clause('damage_boost', amount=50, per='energy_on_opp_active'),),
        ),
    ),
)
