"""Alolan Exeggutor ex (card 193). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, DRAGON, FIGHTING, GRASS, PokemonCard, STAGE1, WATER)

CARD = PokemonCard(
    card_id=193,
    name='Alolan Exeggutor ex',
    hp=300,
    energy_type=DRAGON,
    stage=STAGE1,
    evolves_from='Exeggcute',
    ex=True,
    tera=True,
    retreat_cost=3,
    attacks=(
        Attack(
            attack_id=258,
            name='Tropical Frenzy',
            cost=(GRASS, WATER),
            damage=150,
            text='You may attach any number of Basic Energy cards from your hand to your Pokémon in any way you like.',
        ),
        Attack(
            attack_id=259,
            name='Swinging Sphene',
            cost=(GRASS, WATER, FIGHTING),
            damage=0,
            text='Flip a coin. If heads, Knock Out your opponent’s Active Basic Pokémon. If tails, Knock Out 1 of your opponent’s Benched Basic Pokémon.',
            damage_min=0,
            damage_max=0,
        ),
    ),
)
