"""Annihilape (card 439). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, Clause, FIGHTING, PSYCHIC, PokemonCard, STAGE2)

CARD = PokemonCard(
    card_id=439,
    name='Annihilape',
    hp=150,
    energy_type=FIGHTING,
    stage=STAGE2,
    evolves_from='Primeape',
    weakness=PSYCHIC,
    retreat_cost=2,
    tags=frozenset([]),
    default_roles=('backup_attacker',),
    covers='full',
    abilities=(
        Ability(
            name='Lose Cool',
            text='If this Pokémon has 2 or more damage counters on it, attacks used by this Pokémon do 120 more damage to your opponent’s Active Pokémon (before applying Weakness and Resistance).',
            clauses=(Clause('damage_boost', amount=120, applies_to='self', target='opponent_active', timing='before_weakness_resistance', condition='self_damage_counters_2_plus'),),
        ),
    ),
    attacks=(
        Attack(
            attack_id=618,
            name='Impact Blow',
            cost=(FIGHTING, FIGHTING),
            damage=160,
            text='During your next turn, this Pokémon can’t use Impact Blow.',
            clauses=(Clause('same_attack_lock', duration='next_turn'),),
        ),
    ),
)
