"""Applin (card 42). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, Clause, DRAGON, FIRE, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=42,
    name='Applin',
    hp=40,
    energy_type=DRAGON,
    stage=BASIC,
    retreat_cost=1,
    default_roles=('primary_attacker',),
    attacks=(
        Attack(
            attack_id=37,
            name='Find a Friend',
            cost=(COLORLESS,),
            damage=0,
            text='Search your deck for a Pokémon, reveal it, and put it into your hand. Then, shuffle your deck.',
            clauses=(Clause('fetch', target='pokemon', zone='deck'),),
        ),
        Attack(
            attack_id=38,
            name='Rolling Tackle',
            cost=(GRASS, FIRE),
            damage=30,
        ),
    ),
)
