"""Ariados (card 1012). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, FIRE, GRASS, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=1012,
    name='Ariados',
    hp=110,
    energy_type=GRASS,
    stage=STAGE1,
    evolves_from='Spinarak',
    weakness=FIRE,
    retreat_cost=1,
    attacks=(
        Attack(
            attack_id=1462,
            name='Poison Ring',
            cost=(GRASS,),
            damage=50,
            text='Your opponent’s Active Pokémon is now Poisoned. During your opponent’s next turn, that Pokémon can’t retreat.',
        ),
    ),
)
