"""Azelf (card 217). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, DARKNESS, FIGHTING, PSYCHIC, PokemonCard)

CARD = PokemonCard(
    card_id=217,
    name='Azelf',
    hp=70,
    energy_type=PSYCHIC,
    stage=BASIC,
    weakness=DARKNESS,
    resistance=FIGHTING,
    retreat_cost=1,
    attacks=(
        Attack(
            attack_id=292,
            name='Neurokinesis',
            cost=(PSYCHIC, COLORLESS),
            damage=10,
            text='This attack does 10 more damage for each damage counter on all of your opponent’s Pokémon.',
            scale_var='def_counters_all',
            scale_per_unit=10,
        ),
    ),
)
