"""Barbaracle (card 1052). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, COLORLESS, FIGHTING, GRASS, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=1052,
    name='Barbaracle',
    hp=130,
    energy_type=FIGHTING,
    stage=STAGE1,
    evolves_from='Binacle',
    weakness=GRASS,
    retreat_cost=2,
    abilities=(
        Ability(
            name='Stone Arms',
            text='Once during your turn, you may use this Ability. Attach a Basic {F} Energy card from your hand to 1 of your {F} Pokémon.',
        ),
    ),
    attacks=(
        Attack(
            attack_id=1521,
            name='Hammer In',
            cost=(FIGHTING, FIGHTING, COLORLESS),
            damage=80,
        ),
    ),
)
