"""Barraskewda (card 422). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, LIGHTNING, PokemonCard, STAGE1, WATER)

CARD = PokemonCard(
    card_id=422,
    name='Barraskewda',
    hp=130,
    energy_type=WATER,
    stage=STAGE1,
    evolves_from='Arrokuda',
    weakness=LIGHTNING,
    retreat_cost=1,
    attacks=(
        Attack(
            attack_id=594,
            name='Sharp Fin',
            cost=(WATER,),
            damage=40,
        ),
        Attack(
            attack_id=595,
            name='Dive',
            cost=(WATER, WATER),
            damage=60,
            text='Flip a coin. If heads, during your opponent’s next turn, prevent all damage from and effects of attacks done to this Pokémon.',
            damage_min=60,
            damage_max=60,
        ),
    ),
)
