"""Bayleef (card 918). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, FIRE, GRASS, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=918,
    name='Bayleef',
    hp=100,
    energy_type=GRASS,
    stage=STAGE1,
    evolves_from='Chikorita',
    weakness=FIRE,
    retreat_cost=2,
    tags=frozenset([]),
    default_roles=('backup_attacker', 'support_pokemon'),
    attacks=(
        Attack(
            attack_id=1324,
            name='Leaf Step',
            cost=(GRASS, GRASS),
            damage=60,
        ),
    ),
)
