"""Bayleef (card 709). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, Clause, FIRE, GRASS, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=709,
    name='Bayleef',
    hp=110,
    energy_type=GRASS,
    stage=STAGE1,
    evolves_from='Chikorita',
    weakness=FIRE,
    retreat_cost=2,
    tags=frozenset([]),
    default_roles=('backup_attacker', 'support_pokemon'),
    attacks=(
        Attack(
            attack_id=1027,
            name='Push Down',
            cost=(GRASS, COLORLESS),
            damage=50,
            text='Switch out your opponent’s Active Pokémon to the Bench. (Your opponent chooses the new Active Pokémon.)',
            clauses=(Clause('push_out', chooser='opponent'),),
        ),
    ),
)
