"""Beautifly (card 852). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, FIRE, GRASS, PokemonCard, STAGE2)

CARD = PokemonCard(
    card_id=852,
    name='Beautifly',
    hp=130,
    energy_type=GRASS,
    stage=STAGE2,
    evolves_from='Silcoon',
    weakness=FIRE,
    retreat_cost=1,
    attacks=(
        Attack(
            attack_id=1229,
            name='Stun Spore',
            cost=(GRASS,),
            damage=40,
            text='Flip a coin. If heads, your opponent’s Active Pokémon is now Paralyzed.',
            damage_min=40,
            damage_max=40,
        ),
        Attack(
            attack_id=1230,
            name='Energy Straw',
            cost=(GRASS,),
            damage=0,
            text='Your opponent reveals their hand, and this attack does 80 damage for each Energy card you find there.',
        ),
    ),
)
