"""Breloom (card 395). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, FIRE, GRASS, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=395,
    name='Breloom',
    hp=120,
    energy_type=GRASS,
    stage=STAGE1,
    evolves_from='Shroomish',
    weakness=FIRE,
    retreat_cost=2,
    tags=frozenset([]),
    attacks=(
        Attack(
            attack_id=551,
            name='Damage Rush',
            cost=(COLORLESS, COLORLESS),
            damage=30,
            text='Flip a coin until you get tails. This attack does 50 more damage for each heads.',
            damage_min=0,
            damage_max=1180,
        ),
        Attack(
            attack_id=552,
            name='Mega Drain',
            cost=(GRASS, COLORLESS, COLORLESS),
            damage=90,
            text='Heal 30 damage from this Pokémon.',
        ),
    ),
)
