"""Brute Bonnet (card 986). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, DARKNESS, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=986,
    name='Brute Bonnet',
    hp=120,
    energy_type=DARKNESS,
    stage=BASIC,
    weakness=GRASS,
    retreat_cost=3,
    attacks=(
        Attack(
            attack_id=1421,
            name='Poison Spray',
            cost=(DARKNESS,),
            damage=0,
            text='Your opponent’s Active Pokémon is now Poisoned.',
        ),
        Attack(
            attack_id=1422,
            name='Relentless Punches',
            cost=(DARKNESS, DARKNESS, DARKNESS),
            damage=50,
            text='This attack does 50 more damage for each damage counter on your opponent’s Active Pokémon.',
        ),
    ),
)
