"""Budew (card 235). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, Clause, FIRE, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=235,
    name='Budew',
    hp=30,
    energy_type=GRASS,
    stage=BASIC,
    weakness=FIRE,
    retreat_cost=0,
    default_roles=('item_locker',),
    covers='full',
    attacks=(
        Attack(
            attack_id=323,
            name='Itchy Pollen',
            cost=(),
            damage=10,
            text='During your opponent’s next turn, they can’t play any Item cards from their hand.',
            clauses=(Clause('item_lock', duration='opp_next_turn'),),
        ),
    ),
)
