"""Buneary (card 848). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, Clause, FIGHTING, PokemonCard)

CARD = PokemonCard(
    card_id=848,
    name='Buneary',
    hp=70,
    energy_type=COLORLESS,
    stage=BASIC,
    weakness=FIGHTING,
    retreat_cost=1,
    tags=frozenset([]),
    default_roles=('primary_attacker', 'backup_attacker'),
    attacks=(
        Attack(
            attack_id=1223,
            name='Run Around',
            cost=(COLORLESS,),
            damage=0,
            text='Switch this Pokémon with 1 of your Benched Pokémon.',
            clauses=(Clause('switch_self'),),
        ),
        Attack(
            attack_id=1224,
            name='Kick',
            cost=(COLORLESS, COLORLESS),
            damage=20,
        ),
    ),
)
