"""Butterfree (card 254). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, FIRE, GRASS, PokemonCard, STAGE2)

CARD = PokemonCard(
    card_id=254,
    name='Butterfree',
    hp=120,
    energy_type=GRASS,
    stage=STAGE2,
    evolves_from='Metapod',
    weakness=FIRE,
    retreat_cost=1,
    tags=frozenset(['paralyze']),
    attacks=(
        Attack(
            attack_id=350,
            name='Scale Hurricane',
            cost=(GRASS,),
            damage=0,
            text='Flip 4 coins. This attack does 60 damage for each heads. If at least 2 of them are heads, your opponent’s Active Pokémon is now Paralyzed.',
            damage_min=0,
            damage_max=240,
        ),
    ),
)
