"""Celebi (card 655). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, Clause, FIRE, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=655,
    name='Celebi',
    hp=80,
    energy_type=GRASS,
    stage=BASIC,
    weakness=FIRE,
    retreat_cost=1,
    tags=frozenset([]),
    default_roles=('support_pokemon',),
    attacks=(
        Attack(
            attack_id=945,
            name='Traverse Time',
            cost=(GRASS,),
            damage=0,
            text='Search your deck for up to 3 in any combination of {G} Pokémon and Stadium cards, reveal them, and put them into your hand. Then, shuffle your deck.',
            clauses=(Clause('fetch', target='pokemon', zone='deck', amount=3, energy_type=GRASS, choice=True), Clause('fetch', target='stadium', zone='deck', amount=3, choice=True)),
        ),
        Attack(
            attack_id=946,
            name='Solar Cutter',
            cost=(GRASS,),
            damage=30,
        ),
    ),
)
