"""Chandelure (card 98). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, FIRE, PokemonCard, STAGE2, WATER)

CARD = PokemonCard(
    card_id=98,
    name='Chandelure',
    hp=130,
    energy_type=FIRE,
    stage=STAGE2,
    evolves_from='Lampent',
    weakness=WATER,
    retreat_cost=2,
    tags=frozenset(['dig:1', 'draw']),
    abilities=(
        Ability(
            name='Alluring Light',
            text='Once during your turn, you may have each player draw a card.',
        ),
    ),
    attacks=(
        Attack(
            attack_id=123,
            name='Mind Ruler',
            cost=(FIRE,),
            damage=0,
            text='This attack does 30 damage for each card in your opponent’s hand.',
        ),
    ),
)
