"""Chewtle (card 157). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, LIGHTNING, PokemonCard, WATER)

CARD = PokemonCard(
    card_id=157,
    name='Chewtle',
    hp=80,
    energy_type=WATER,
    stage=BASIC,
    weakness=LIGHTNING,
    retreat_cost=2,
    default_roles=('backup_attacker',),
    attacks=(
        Attack(
            attack_id=205,
            name='Headbutt',
            cost=(COLORLESS, COLORLESS, COLORLESS),
            damage=60,
        ),
    ),
)
