"""Chikorita (card 917). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, Clause, FIRE, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=917,
    name='Chikorita',
    hp=70,
    energy_type=GRASS,
    stage=BASIC,
    weakness=FIRE,
    retreat_cost=1,
    tags=frozenset([]),
    default_roles=('backup_attacker',),
    attacks=(
        Attack(
            attack_id=1322,
            name='Growl',
            cost=(COLORLESS,),
            damage=0,
            text='During your opponent’s next turn, attacks used by the Defending Pokémon do 20 less damage (before applying Weakness and Resistance).',
            clauses=(Clause('attack_debuff', amount=20, target='defending', duration='opp_next_turn', timing='before_weakness_resistance'),),
        ),
        Attack(
            attack_id=1323,
            name='Seed Bomb',
            cost=(GRASS, GRASS),
            damage=30,
        ),
    ),
)
