"""Cinderace (card 666). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, COLORLESS, Clause, FIRE, PokemonCard, STAGE2, WATER)

CARD = PokemonCard(
    card_id=666,
    name='Cinderace',
    hp=160,
    energy_type=FIRE,
    stage=STAGE2,
    evolves_from='Raboot',
    weakness=WATER,
    retreat_cost=0,
    tags=frozenset(['energy_accel', 'opener']),
    default_roles=('accel_source', 'backup_attacker'),
    abilities=(
        Ability(
            name='Explosiveness',
            text='If this Pokémon is in your hand when you are setting up to play, you may put it face down in the Active Spot.',
            clauses=(Clause('setup_active', trigger='setup'),),
        ),
    ),
    attacks=(
        Attack(
            attack_id=965,
            name='Turbo Flare',
            cost=(COLORLESS,),
            damage=50,
            text='Search your deck for up to 3 Basic Energy cards and attach them to your Benched Pokémon in any way you like. Then, shuffle your deck.',
            clauses=(Clause('accel', amount=3, zone='deck', target='bench_only'),),
        ),
    ),
)
