"""Conkeldurr (card 530). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, COLORLESS, Clause, FIGHTING, PSYCHIC, PokemonCard, STAGE2)

CARD = PokemonCard(
    card_id=530,
    name='Conkeldurr',
    hp=140,
    energy_type=FIGHTING,
    stage=STAGE2,
    evolves_from='Gurdurr',
    weakness=PSYCHIC,
    retreat_cost=3,
    tags=frozenset([]),
    default_roles=('backup_attacker',),
    abilities=(
        Ability(
            name='Craftsmanship',
            text='This Pokémon gets +40 HP for each {F} Energy attached to it.',
            clauses=(Clause('hp_bonus', amount=40, amount_per='attached_fighting_energy', energy_type=FIGHTING),),
        ),
    ),
    attacks=(
        Attack(
            attack_id=758,
            name='Swing Around',
            cost=(FIGHTING, COLORLESS, COLORLESS, COLORLESS),
            damage=100,
            text='Flip 2 coins. This attack does 50 more damage for each heads.',
            clauses=(Clause('coin', count=2, effect='damage_boost', amount=50, per='heads'),),
        ),
    ),
)
