"""Conkeldurr (card 115). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, Clause, FIGHTING, PSYCHIC, PokemonCard, STAGE2)

CARD = PokemonCard(
    card_id=115,
    name='Conkeldurr',
    hp=180,
    energy_type=FIGHTING,
    stage=STAGE2,
    evolves_from='Gurdurr',
    weakness=PSYCHIC,
    retreat_cost=3,
    default_roles=('backup_attacker',),
    attacks=(
        Attack(
            attack_id=145,
            name='Tantrum',
            cost=(FIGHTING,),
            damage=80,
            text='This Pokémon is now Confused.',
            clauses=(Clause('confuse', target='self'),),
        ),
        Attack(
            attack_id=146,
            name='Gutsy Swing',
            cost=(FIGHTING, COLORLESS, COLORLESS, COLORLESS),
            damage=250,
            text='If this Pokémon is affected by a Special Condition, ignore all Energy in this attack’s cost.',
            clauses=(Clause('cost_reduction', amount='all', condition='self_special_condition'),),
        ),
    ),
)
