"""Cornerstone Mask Ogerpon ex (card 117). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, BASIC, COLORLESS, Clause, FIGHTING, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=117,
    name='Cornerstone Mask Ogerpon ex',
    hp=210,
    energy_type=FIGHTING,
    stage=BASIC,
    ex=True,
    tera=True,
    weakness=GRASS,
    retreat_cost=1,
    tags=frozenset([]),
    default_roles=('primary_attacker',),
    abilities=(
        Ability(
            name='Cornerstone Stance',
            text='Prevent all damage from attacks done to this Pokémon by your opponent’s Pokémon that have an Ability.',
            clauses=(Clause('prevent_damage', applies_to='self', source='opponent_attack', source_class='has_ability'),),
        ),
    ),
    attacks=(
        Attack(
            attack_id=148,
            name='Demolish',
            cost=(FIGHTING, COLORLESS, COLORLESS),
            damage=140,
            text='This attack’s damage isn’t affected by Weakness or Resistance, or by any effects on your opponent’s Active Pokémon.',
            clauses=(Clause('ignores_wr'), Clause('ignores_effects')),
        ),
    ),
)
