"""Crustle (card 345). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, COLORLESS, Clause, FIRE, GRASS, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=345,
    name='Crustle',
    hp=150,
    energy_type=GRASS,
    stage=STAGE1,
    evolves_from='Dwebble',
    weakness=FIRE,
    retreat_cost=3,
    default_roles=('primary_attacker',),
    covers='full',
    abilities=(
        Ability(
            name='Mysterious Rock Inn',
            text='Prevent all damage done to this Pokémon by attacks from your opponent’s Pokémon {ex}.',
            clauses=(Clause('prevent_damage', applies_to='self', source='opponent_attack', source_class='ex'),),
        ),
    ),
    attacks=(
        Attack(
            attack_id=479,
            name='Superb Scissors',
            cost=(GRASS, COLORLESS, COLORLESS),
            damage=120,
            text='This attack’s damage isn’t affected by any effects on your opponent’s Active Pokémon.',
            clauses=(Clause('ignores_effects'),),
        ),
    ),
)
