"""Cynthia's Garchomp ex (card 381). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, Clause, FIGHTING, GRASS, PokemonCard, STAGE2)

CARD = PokemonCard(
    card_id=381,
    name="Cynthia's Garchomp ex",
    hp=330,
    energy_type=FIGHTING,
    stage=STAGE2,
    evolves_from="Cynthia's Gabite",
    ex=True,
    weakness=GRASS,
    retreat_cost=0,
    default_roles=('primary_attacker',),
    attacks=(
        Attack(
            attack_id=531,
            name='Corkscrew Dive',
            cost=(FIGHTING,),
            damage=100,
            text='You may draw cards until you have 6 cards in your hand.',
            clauses=(Clause('draw', to_hand_size=6),),
        ),
        Attack(
            attack_id=532,
            name='Draconic Buster',
            cost=(FIGHTING, FIGHTING),
            damage=260,
            text='Discard all Energy from this Pokémon.',
            clauses=(Clause('self_discard_energy', amount='all'),),
        ),
    ),
)
