"""Cynthia's Gible (card 379). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, Clause, FIGHTING, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=379,
    name="Cynthia's Gible",
    hp=70,
    energy_type=FIGHTING,
    stage=BASIC,
    weakness=GRASS,
    retreat_cost=1,
    tags=frozenset([]),
    default_roles=('primary_attacker',),
    attacks=(
        Attack(
            attack_id=529,
            name='Rock Hurl',
            cost=(FIGHTING,),
            damage=20,
            text='This attack’s damage isn’t affected by Resistance.',
            clauses=(Clause('ignores_wr', scope='resistance'),),
        ),
    ),
)
