"""Cynthia's Roselia (card 341). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, FIRE, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=341,
    name="Cynthia's Roselia",
    hp=70,
    energy_type=GRASS,
    stage=BASIC,
    weakness=FIRE,
    retreat_cost=1,
    default_roles=('backup_attacker', 'support_pokemon'),
    attacks=(
        Attack(
            attack_id=475,
            name='Spike Sting',
            cost=(COLORLESS,),
            damage=20,
        ),
    ),
)
