"""Cynthia's Gabite (card 380). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, Clause, FIGHTING, GRASS, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=380,
    name="Cynthia's Gabite",
    hp=100,
    energy_type=FIGHTING,
    stage=STAGE1,
    evolves_from="Cynthia's Gible",
    weakness=GRASS,
    retreat_cost=1,
    tags=frozenset(['search']),
    default_roles=('primary_attacker', 'disruption_target'),
    abilities=(
        Ability(
            name='Champion’s Call',
            text='Once during your turn, you may search your deck for a Cynthia’s Pokémon, reveal it, and put it into your hand. Then, shuffle your deck.',
            clauses=(Clause('fetch', target='pokemon', zone='deck', name_family="Cynthia's", allowance='body'),),
        ),
    ),
    attacks=(
        Attack(
            attack_id=530,
            name='Dragonslice',
            cost=(FIGHTING,),
            damage=40,
        ),
    ),
)
