"""Cynthia's Spiritomb (card 387). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, Clause, DARKNESS, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=387,
    name="Cynthia's Spiritomb",
    hp=70,
    energy_type=DARKNESS,
    stage=BASIC,
    weakness=GRASS,
    retreat_cost=1,
    tags=frozenset([]),
    default_roles=('backup_attacker',),
    attacks=(
        Attack(
            attack_id=540,
            name='Raging Curse',
            cost=(COLORLESS,),
            damage=0,
            text='This attack does 10 damage for each damage counter on all of your Benched Cynthia’s Pokémon. This attack’s damage isn’t affected by Weakness.',
            clauses=(Clause('damage_boost', amount=10, per='damage_counter_own_bench', name_family="Cynthia's"), Clause('ignores_wr', scope='weakness')),
        ),
    ),
)
