"""Dachsbun ex (card 968). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, COLORLESS, METAL, PSYCHIC, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=968,
    name='Dachsbun ex',
    hp=250,
    energy_type=PSYCHIC,
    stage=STAGE1,
    evolves_from='Fidough',
    ex=True,
    weakness=METAL,
    retreat_cost=2,
    tags=frozenset(['confuse']),
    abilities=(
        Ability(
            name='Time to Chow Down',
            text='Once during your turn, when you play this Pokémon from your hand to evolve 1 of your Pokémon, you may use this Ability. Heal all damage from each of your Evolution Pokémon. If you healed any damage in this way, discard all Energy from those Pokémon.',
        ),
    ),
    attacks=(
        Attack(
            attack_id=1392,
            name='Wonder Shine',
            cost=(COLORLESS, COLORLESS),
            damage=130,
            text='Your opponent’s Active Pokémon is now Confused.',
        ),
    ),
)
