"""Dedenne (card 1038). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, FIGHTING, LIGHTNING, PokemonCard)

CARD = PokemonCard(
    card_id=1038,
    name='Dedenne',
    hp=70,
    energy_type=LIGHTNING,
    stage=BASIC,
    weakness=FIGHTING,
    retreat_cost=1,
    tags=frozenset(['paralyze']),
    attacks=(
        Attack(
            attack_id=1497,
            name='Tail Generator',
            cost=(LIGHTNING,),
            damage=0,
            text='Choose Basic {L} Energy cards from your discard pile up to the amount of Energy attached to all of your opponent’s Pokémon and attach them to your {L} Pokémon in any way you like.',
        ),
        Attack(
            attack_id=1498,
            name='Thunder Shock',
            cost=(LIGHTNING, COLORLESS),
            damage=30,
            text='Flip a coin. If heads, your opponent’s Active Pokémon is now Paralyzed.',
            damage_min=30,
            damage_max=30,
        ),
    ),
)
