"""Dragapult ex (card 121). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, Clause, DRAGON, FIRE, PSYCHIC, PokemonCard, STAGE2)

CARD = PokemonCard(
    card_id=121,
    name='Dragapult ex',
    hp=320,
    energy_type=DRAGON,
    stage=STAGE2,
    evolves_from='Drakloak',
    ex=True,
    tera=True,
    retreat_cost=1,
    default_roles=('primary_attacker', 'sniper'),
    covers='full',
    attacks=(
        Attack(
            attack_id=153,
            name='Jet Headbutt',
            cost=(COLORLESS,),
            damage=70,
        ),
        Attack(
            attack_id=154,
            name='Phantom Dive',
            cost=(FIRE, PSYCHIC),
            damage=200,
            text='Put 6 damage counters on your opponent’s Benched Pokémon in any way you like.',
            clauses=(Clause('bench_spread', amount=60, target='opp_bench'),),
        ),
    ),
)
