"""Drakloak (card 120). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, Clause, DRAGON, FIRE, PSYCHIC, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=120,
    name='Drakloak',
    hp=90,
    energy_type=DRAGON,
    stage=STAGE1,
    evolves_from='Dreepy',
    retreat_cost=1,
    tags=frozenset(['dig', 'dig:2', 'draw']),
    default_roles=('primary_attacker', 'draw_engine'),
    covers='full',
    abilities=(
        Ability(
            name='Recon Directive',
            text='Once during your turn, you may look at the top 2 cards of your deck and put 1 of them into your hand. Put the other card on the bottom of your deck.',
            clauses=(Clause('draw', amount=1, window=2, allowance='body', rider='other_to_bottom'),),
        ),
    ),
    attacks=(
        Attack(
            attack_id=152,
            name='Dragon Headbutt',
            cost=(FIRE, PSYCHIC),
            damage=70,
        ),
    ),
)
