"""Drednaw (card 158). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, COLORLESS, Clause, LIGHTNING, PokemonCard, STAGE1, WATER)

CARD = PokemonCard(
    card_id=158,
    name='Drednaw',
    hp=140,
    energy_type=WATER,
    stage=STAGE1,
    evolves_from='Chewtle',
    weakness=LIGHTNING,
    retreat_cost=3,
    tags=frozenset([]),
    default_roles=('backup_attacker',),
    abilities=(
        Ability(
            name='Impervious Shell',
            text='Prevent all damage done to this Pokémon by attacks from your opponent’s Pokémon if that damage is 200 or more.',
            clauses=(Clause('prevent_damage', applies_to='self', source='opponent_attack', condition='damage_200_plus'),),
        ),
    ),
    attacks=(
        Attack(
            attack_id=206,
            name='Hard Crunch',
            cost=(COLORLESS, COLORLESS, COLORLESS),
            damage=80,
            text='If your opponent’s Active Pokémon already has any damage counters on it, this attack does 80 more damage.',
            clauses=(Clause('damage_boost', amount=80, condition='opp_active_damaged'),),
        ),
    ),
)
