"""Dreepy (card 119). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, DRAGON, FIRE, PSYCHIC, PokemonCard)

CARD = PokemonCard(
    card_id=119,
    name='Dreepy',
    hp=70,
    energy_type=DRAGON,
    stage=BASIC,
    retreat_cost=1,
    tags=frozenset([]),
    attacks=(
        Attack(
            attack_id=150,
            name='Petty Grudge',
            cost=(PSYCHIC,),
            damage=10,
        ),
        Attack(
            attack_id=151,
            name='Bite',
            cost=(FIRE, PSYCHIC),
            damage=40,
        ),
    ),
)
