"""Druddigon (card 625). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, Clause, DRAGON, FIRE, PokemonCard, WATER)

CARD = PokemonCard(
    card_id=625,
    name='Druddigon',
    hp=120,
    energy_type=DRAGON,
    stage=BASIC,
    retreat_cost=2,
    default_roles=('support_pokemon',),
    attacks=(
        Attack(
            attack_id=901,
            name='Shred',
            cost=(COLORLESS,),
            damage=40,
            text='This attack’s damage isn’t affected by any effects on your opponent’s Active Pokémon.',
            clauses=(Clause('ignores_effects'),),
        ),
        Attack(
            attack_id=902,
            name='Ambush',
            cost=(FIRE, WATER, COLORLESS),
            damage=90,
            text='Flip a coin. If heads, this attack does 60 more damage.',
            clauses=(Clause('coin', effect='damage_boost', amount=60),),
        ),
    ),
)
