"""Dudunsparce ex (card 306). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, FIGHTING, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=306,
    name='Dudunsparce ex',
    hp=270,
    energy_type=COLORLESS,
    stage=STAGE1,
    evolves_from='Dunsparce',
    ex=True,
    weakness=FIGHTING,
    retreat_cost=3,
    attacks=(
        Attack(
            attack_id=425,
            name='Tenacious Tail',
            cost=(COLORLESS,),
            damage=0,
            text='This attack does 60 damage for each of your opponent’s Pokémon {ex} in play.',
            scale_var='def_ex_in_play',
            scale_per_unit=60,
        ),
        Attack(
            attack_id=426,
            name='Destructive Drill',
            cost=(COLORLESS, COLORLESS, COLORLESS),
            damage=150,
            text='This attack’s damage isn’t affected by any effects on your opponent’s Active Pokémon.',
        ),
    ),
)
