"""Dudunsparce (card 66). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, COLORLESS, Clause, FIGHTING, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=66,
    name='Dudunsparce',
    hp=140,
    energy_type=COLORLESS,
    stage=STAGE1,
    evolves_from='Dunsparce',
    weakness=FIGHTING,
    retreat_cost=3,
    tags=frozenset(['dig:3', 'draw', 'recycle_line', 'stall']),
    abilities=(
        Ability(
            name='Run Away Draw',
            text='Once during your turn, you may draw 3 cards. If you drew any cards in this way, shuffle this Pokémon and all attached cards into your deck.',
            clauses=(Clause('draw', amount=3, allowance='body', rider='shuffle_self_in'),),
        ),
    ),
    attacks=(
        Attack(
            attack_id=76,
            name='Land Crush',
            cost=(COLORLESS, COLORLESS, COLORLESS),
            damage=90,
        ),
    ),
)
