"""Dunsparce (card 305). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, Clause, FIGHTING, PokemonCard)

CARD = PokemonCard(
    card_id=305,
    name='Dunsparce',
    hp=70,
    energy_type=COLORLESS,
    stage=BASIC,
    weakness=FIGHTING,
    retreat_cost=1,
    default_roles=('draw_engine', 'retreat_assist'),
    covers='full',
    attacks=(
        Attack(
            attack_id=423,
            name='Trading Places',
            cost=(COLORLESS,),
            damage=0,
            text='Switch this Pokémon with 1 of your Benched Pokémon.',
            clauses=(Clause('switch_self'),),
        ),
        Attack(
            attack_id=424,
            name='Ram',
            cost=(COLORLESS, COLORLESS),
            damage=20,
        ),
    ),
)
