"""Dunsparce (card 65). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, Clause, FIGHTING, PokemonCard)

CARD = PokemonCard(
    card_id=65,
    name='Dunsparce',
    hp=60,
    energy_type=COLORLESS,
    stage=BASIC,
    weakness=FIGHTING,
    retreat_cost=0,
    tags=frozenset([]),
    default_roles=('draw_engine',),
    attacks=(
        Attack(
            attack_id=74,
            name='Gnaw',
            cost=(COLORLESS,),
            damage=10,
        ),
        Attack(
            attack_id=75,
            name='Dig',
            cost=(COLORLESS, COLORLESS),
            damage=30,
            text='Flip a coin. If heads, during your opponent’s next turn, prevent all damage from and effects of attacks done to this Pokémon.',
            clauses=(Clause('coin', effect='damage_protection', scope='damage_and_effects', duration='opp_next_turn'),),
            damage_min=30,
            damage_max=30,
        ),
    ),
)
