"""Duraludon (card 169). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, Clause, FIRE, GRASS, METAL, PokemonCard)

CARD = PokemonCard(
    card_id=169,
    name='Duraludon',
    hp=130,
    energy_type=METAL,
    stage=BASIC,
    weakness=FIRE,
    resistance=GRASS,
    retreat_cost=2,
    tags=frozenset([]),
    default_roles=('primary_attacker',),
    attacks=(
        Attack(
            attack_id=223,
            name='Hammer In',
            cost=(METAL,),
            damage=30,
        ),
        Attack(
            attack_id=224,
            name='Raging Hammer',
            cost=(METAL, METAL, COLORLESS),
            damage=80,
            text='This attack does 10 more damage for each damage counter on this Pokémon.',
            clauses=(Clause('damage_boost', amount=10, per='damage_counter_on_self'),),
        ),
    ),
)
