"""Dusclops (card 132). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, Clause, DARKNESS, FIGHTING, PSYCHIC, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=132,
    name='Dusclops',
    hp=90,
    energy_type=PSYCHIC,
    stage=STAGE1,
    evolves_from='Duskull',
    weakness=DARKNESS,
    resistance=FIGHTING,
    retreat_cost=2,
    tags=frozenset([]),
    default_roles=('backup_attacker',),
    covers='full',
    abilities=(
        Ability(
            name='Cursed Blast',
            text='Once during your turn, you may put 5 damage counters on 1 of your opponent’s Pokémon. If you use this Ability, this Pokémon is Knocked Out.',
            clauses=(Clause('damage_counters', amount=5, target='opp_any', rider='self_ko', allowance='body'),),
        ),
    ),
    attacks=(
        Attack(
            attack_id=171,
            name='Will-O-Wisp',
            cost=(PSYCHIC, PSYCHIC),
            damage=50,
        ),
    ),
)
