"""Dusknoir (card 133). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, COLORLESS, Clause, DARKNESS, FIGHTING, PSYCHIC, PokemonCard, STAGE2)

CARD = PokemonCard(
    card_id=133,
    name='Dusknoir',
    hp=160,
    energy_type=PSYCHIC,
    stage=STAGE2,
    evolves_from='Dusclops',
    weakness=DARKNESS,
    resistance=FIGHTING,
    retreat_cost=3,
    tags=frozenset([]),
    default_roles=('backup_attacker',),
    abilities=(
        Ability(
            name='Cursed Blast',
            text='Once during your turn, you may put 13 damage counters on 1 of your opponent’s Pokémon. If you use this Ability, this Pokémon is Knocked Out.',
            clauses=(Clause('damage_counters', amount=13, target='opp_any', rider='self_ko', allowance='body'),),
        ),
    ),
    attacks=(
        Attack(
            attack_id=172,
            name='Shadow Bind',
            cost=(PSYCHIC, PSYCHIC, COLORLESS),
            damage=150,
            text='During your opponent’s next turn, the Defending Pokémon can’t retreat.',
            clauses=(Clause('retreat_lock', target='defending', duration='opp_next_turn'),),
        ),
    ),
)
