"""Duskull (card 131). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, Clause, DARKNESS, FIGHTING, PSYCHIC, PokemonCard)

CARD = PokemonCard(
    card_id=131,
    name='Duskull',
    hp=60,
    energy_type=PSYCHIC,
    stage=BASIC,
    weakness=DARKNESS,
    resistance=FIGHTING,
    retreat_cost=1,
    tags=frozenset([]),
    default_roles=('backup_attacker',),
    attacks=(
        Attack(
            attack_id=169,
            name='Come and Get You',
            cost=(PSYCHIC,),
            damage=0,
            text='Put up to 3 Duskull from your discard pile onto your Bench.',
            clauses=(Clause('fetch', target='pokemon', zone='discard', amount=3, dest='bench', name_family='Duskull'),),
        ),
        Attack(
            attack_id=170,
            name='Mumble',
            cost=(PSYCHIC, PSYCHIC),
            damage=30,
        ),
    ),
)
