"""Dustox (card 854). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, FIRE, GRASS, PokemonCard, STAGE2)

CARD = PokemonCard(
    card_id=854,
    name='Dustox',
    hp=140,
    energy_type=GRASS,
    stage=STAGE2,
    evolves_from='Cascoon',
    weakness=FIRE,
    retreat_cost=1,
    tags=frozenset(['poison', 'sleep']),
    abilities=(
        Ability(
            name='Boisterous Wind',
            text='Once during your turn, you may use this Ability. Flip a coin. If heads, put an Energy attached to your opponent’s Active Pokémon into their hand.',
        ),
    ),
    attacks=(
        Attack(
            attack_id=1232,
            name='Twilight Poison',
            cost=(GRASS, GRASS),
            damage=100,
            text='Your opponent’s Active Pokémon is now Asleep and Poisoned.',
        ),
    ),
)
