"""Dwebble (card 344). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, Clause, FIRE, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=344,
    name='Dwebble',
    hp=70,
    energy_type=GRASS,
    stage=BASIC,
    weakness=FIRE,
    retreat_cost=2,
    tags=frozenset(['search']),
    default_roles=('primary_attacker',),
    attacks=(
        Attack(
            attack_id=478,
            name='Ascension',
            cost=(COLORLESS,),
            damage=0,
            text='Search your deck for a card that evolves from this Pokémon and put it onto this Pokémon to evolve it. Then, shuffle your deck.',
            clauses=(Clause('fetch', target='evolution', zone='deck', dest='in_play', restriction='evolves_from_self'),),
        ),
    ),
)
