"""Eevee (card 317). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, BASIC, COLORLESS, Clause, FIGHTING, PokemonCard)

CARD = PokemonCard(
    card_id=317,
    name='Eevee',
    hp=50,
    energy_type=COLORLESS,
    stage=BASIC,
    weakness=FIGHTING,
    retreat_cost=1,
    tags=frozenset([]),
    default_roles=('backup_attacker',),
    abilities=(
        Ability(
            name='Boosted Evolution',
            text='As long as this Pokémon is in the Active Spot, it can evolve during your first turn or the turn you play it.',
            clauses=(Clause('evolve_early', condition='self_active'),),
        ),
    ),
    attacks=(
        Attack(
            attack_id=442,
            name='Reckless Charge',
            cost=(COLORLESS, COLORLESS),
            damage=30,
            text='This Pokémon also does 10 damage to itself.',
            clauses=(Clause('recoil', amount=10),),
        ),
    ),
)
