"""Eevee (card 145). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, Clause, FIGHTING, PokemonCard)

CARD = PokemonCard(
    card_id=145,
    name='Eevee',
    hp=70,
    energy_type=COLORLESS,
    stage=BASIC,
    weakness=FIGHTING,
    retreat_cost=1,
    tags=frozenset([]),
    default_roles=('backup_attacker',),
    attacks=(
        Attack(
            attack_id=189,
            name='Colorful Catch',
            cost=(COLORLESS,),
            damage=0,
            text='Search your deck for up to 3 Basic Energy cards of different types, reveal them, and put them into your hand. Then, shuffle your deck.',
            clauses=(Clause('fetch', target='basic_energy', zone='deck', amount=3, distinct_types=True),),
        ),
        Attack(
            attack_id=190,
            name='Headbutt',
            cost=(COLORLESS, COLORLESS),
            damage=20,
        ),
    ),
)
