"""Eiscue (card 731). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, METAL, PokemonCard, WATER)

CARD = PokemonCard(
    card_id=731,
    name='Eiscue',
    hp=110,
    energy_type=WATER,
    stage=BASIC,
    weakness=METAL,
    retreat_cost=1,
    tags=frozenset(['paralyze']),
    attacks=(
        Attack(
            attack_id=1056,
            name='Freezing Headbutt',
            cost=(COLORLESS,),
            damage=20,
            text='Flip a coin. If heads, your opponent’s Active Pokémon is now Paralyzed.',
            damage_min=20,
            damage_max=20,
        ),
        Attack(
            attack_id=1057,
            name='Tackle',
            cost=(WATER, COLORLESS, COLORLESS),
            damage=90,
        ),
    ),
)
