"""Emboar (card 569). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, COLORLESS, FIRE, PokemonCard, STAGE2, WATER)

CARD = PokemonCard(
    card_id=569,
    name='Emboar',
    hp=180,
    energy_type=FIRE,
    stage=STAGE2,
    evolves_from='Pignite',
    weakness=WATER,
    retreat_cost=4,
    abilities=(
        Ability(
            name='Inferno Fandango',
            text='As often as you like during your turn, you may attach a Basic {R} Energy card from your hand to 1 of your Pokémon.',
        ),
    ),
    attacks=(
        Attack(
            attack_id=812,
            name='Heat Crash',
            cost=(FIRE, FIRE, FIRE, COLORLESS),
            damage=120,
        ),
    ),
)
