"""Erika's Tangela (card 915). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, BASIC, COLORLESS, FIRE, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=915,
    name="Erika's Tangela",
    hp=80,
    energy_type=GRASS,
    stage=BASIC,
    weakness=FIRE,
    retreat_cost=2,
    abilities=(
        Ability(
            name='Gathering of Blossoms',
            text='Once during your turn, you may use this Ability. Search your deck for an Erika’s Pokémon, reveal it, and put it into your hand. Then, shuffle your deck.',
        ),
    ),
    attacks=(
        Attack(
            attack_id=1319,
            name='Bind',
            cost=(GRASS, COLORLESS),
            damage=50,
            text='Flip a coin. If heads, your opponent’s Active Pokémon is now Paralyzed.',
            damage_min=50,
            damage_max=50,
        ),
    ),
)
