"""Eternatus (card 777). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, DARKNESS, FIGHTING, PokemonCard)

CARD = PokemonCard(
    card_id=777,
    name='Eternatus',
    hp=150,
    energy_type=DARKNESS,
    stage=BASIC,
    weakness=FIGHTING,
    retreat_cost=2,
    tags=frozenset([]),
    attacks=(
        Attack(
            attack_id=1124,
            name='Shatter',
            cost=(DARKNESS, DARKNESS),
            damage=50,
            text='Discard a Stadium in play.',
        ),
        Attack(
            attack_id=1125,
            name='Power Rush',
            cost=(DARKNESS, DARKNESS, DARKNESS),
            damage=130,
            text='Flip a coin. If tails, during your next turn, this Pokémon can’t use attacks.',
            damage_min=130,
            damage_max=130,
        ),
    ),
)
