"""Ethan's Cyndaquil (card 352). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, Clause, FIRE, PokemonCard, WATER)

CARD = PokemonCard(
    card_id=352,
    name="Ethan's Cyndaquil",
    hp=70,
    energy_type=FIRE,
    stage=BASIC,
    weakness=WATER,
    retreat_cost=1,
    tags=frozenset([]),
    default_roles=('backup_attacker',),
    attacks=(
        Attack(
            attack_id=488,
            name='Ember',
            cost=(FIRE,),
            damage=30,
            text='Discard an Energy from this Pokémon.',
            clauses=(Clause('self_discard_energy', amount=1),),
        ),
    ),
)
