"""Ethan's Typhlosion (card 354). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, Clause, FIRE, PokemonCard, STAGE2, WATER)

CARD = PokemonCard(
    card_id=354,
    name="Ethan's Typhlosion",
    hp=170,
    energy_type=FIRE,
    stage=STAGE2,
    evolves_from="Ethan's Quilava",
    weakness=WATER,
    retreat_cost=2,
    tags=frozenset([]),
    default_roles=('backup_attacker',),
    attacks=(
        Attack(
            attack_id=490,
            name='Buddy Blast',
            cost=(FIRE,),
            damage=40,
            text='This attack does 60 more damage for each Ethan’s Adventure card in your discard pile.',
            clauses=(Clause('damage_boost', amount=60, per='ethans_adventure_in_own_discard'),),
        ),
        Attack(
            attack_id=491,
            name='Steam Artillery',
            cost=(FIRE, FIRE, COLORLESS),
            damage=160,
        ),
    ),
)
