"""Ethan's Ho-Oh ex (card 357). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, BASIC, FIRE, PokemonCard, WATER)

CARD = PokemonCard(
    card_id=357,
    name="Ethan's Ho-Oh ex",
    hp=230,
    energy_type=FIRE,
    stage=BASIC,
    ex=True,
    weakness=WATER,
    retreat_cost=2,
    tags=frozenset(['energy_accel']),
    abilities=(
        Ability(
            name='Golden Flame',
            text='Once during your turn, you may attach up to 2 Basic {R} Energy cards from your hand to 1 of your Benched Ethan’s Pokémon.',
        ),
    ),
    attacks=(
        Attack(
            attack_id=494,
            name='Shining Feathers',
            cost=(FIRE, FIRE, FIRE, FIRE),
            damage=160,
            text='Heal 50 damage from each of your Pokémon.',
        ),
    ),
)
