"""Ethan's Pichu (card 373). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, FIGHTING, LIGHTNING, PokemonCard)

CARD = PokemonCard(
    card_id=373,
    name="Ethan's Pichu",
    hp=30,
    energy_type=LIGHTNING,
    stage=BASIC,
    weakness=FIGHTING,
    retreat_cost=0,
    tags=frozenset(['draw']),
    attacks=(
        Attack(
            attack_id=518,
            name='Zapping Draw',
            cost=(),
            damage=30,
            text='Draw a card.',
        ),
    ),
)
