"""Fearow (card 702). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, FIGHTING, LIGHTNING, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=702,
    name='Fearow',
    hp=100,
    energy_type=COLORLESS,
    stage=STAGE1,
    evolves_from='Spearow',
    weakness=LIGHTNING,
    resistance=FIGHTING,
    retreat_cost=1,
    attacks=(
        Attack(
            attack_id=1016,
            name='Repeating Drill',
            cost=(COLORLESS,),
            damage=0,
            text='Flip 5 coins. This attack does 30 damage for each heads.',
            damage_min=0,
            damage_max=150,
        ),
    ),
)
