"""Flittle (card 185). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, DARKNESS, FIGHTING, PSYCHIC, PokemonCard)

CARD = PokemonCard(
    card_id=185,
    name='Flittle',
    hp=40,
    energy_type=PSYCHIC,
    stage=BASIC,
    weakness=DARKNESS,
    resistance=FIGHTING,
    retreat_cost=1,
    tags=frozenset([]),
    attacks=(
        Attack(
            attack_id=244,
            name='Splashing Dodge',
            cost=(COLORLESS,),
            damage=10,
            text='Flip a coin. If heads, during your opponent’s next turn, prevent all damage from and effects of attacks done to this Pokémon.',
            damage_min=10,
            damage_max=10,
        ),
    ),
)
