"""Flutter Mane (card 56). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, BASIC, COLORLESS, Clause, METAL, PSYCHIC, PokemonCard)

CARD = PokemonCard(
    card_id=56,
    name='Flutter Mane',
    hp=90,
    energy_type=PSYCHIC,
    stage=BASIC,
    weakness=METAL,
    retreat_cost=1,
    tags=frozenset(['spread']),
    default_roles=('support_pokemon', 'disruption_target'),
    covers='full',
    abilities=(
        Ability(
            name='Midnight Fluttering',
            text='As long as this Pokémon is in the Active Spot, your opponent’s Active Pokémon has no Abilities, except for Midnight Fluttering.',
            clauses=(Clause('ability_suppression', target='opp_active', condition='self_active'),),
        ),
    ),
    attacks=(
        Attack(
            attack_id=60,
            name='Hex Hurl',
            cost=(COLORLESS, COLORLESS, COLORLESS),
            damage=90,
            text='Put 2 damage counters on your opponent’s Benched Pokémon in any way you like.',
            clauses=(Clause('damage_counters', amount=2, target='opp_bench'),),
        ),
    ),
)
