"""Foongus (card 488). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, FIRE, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=488,
    name='Foongus',
    hp=50,
    energy_type=GRASS,
    stage=BASIC,
    weakness=FIRE,
    retreat_cost=1,
    attacks=(
        Attack(
            attack_id=691,
            name='Toxic Spore',
            cost=(COLORLESS,),
            damage=0,
            text='Your opponent’s Active Pokémon is now Poisoned.',
        ),
    ),
)
