"""Forretress (card 465). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, FIRE, GRASS, METAL, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=465,
    name='Forretress',
    hp=130,
    energy_type=METAL,
    stage=STAGE1,
    evolves_from='Pineco',
    weakness=FIRE,
    resistance=GRASS,
    retreat_cost=2,
    attacks=(
        Attack(
            attack_id=656,
            name='Iron Shake-Up',
            cost=(COLORLESS,),
            damage=20,
            text='You may move any amount of {M} Energy from your Pokémon to your other Pokémon in any way you like.',
        ),
        Attack(
            attack_id=657,
            name='Hurricane of Needles',
            cost=(METAL, COLORLESS, COLORLESS, COLORLESS),
            damage=0,
            text='Flip 4 coins. This attack does 80 damage for each heads.',
            damage_min=0,
            damage_max=320,
        ),
    ),
)
