"""Frosmoth (card 866). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, METAL, PokemonCard, STAGE1, WATER)

CARD = PokemonCard(
    card_id=866,
    name='Frosmoth',
    hp=110,
    energy_type=WATER,
    stage=STAGE1,
    evolves_from='Snom',
    weakness=METAL,
    retreat_cost=2,
    abilities=(
        Ability(
            name='Alluring Wings',
            text='Once during your turn, if this Pokémon is in the Active Spot, you may use this Ability. Each player draws a card.',
        ),
    ),
    attacks=(
        Attack(
            attack_id=1249,
            name='Cold Cyclone',
            cost=(WATER, WATER),
            damage=90,
            text='Move a {W} Energy from this Pokémon to 1 of your Benched Pokémon.',
        ),
    ),
)
