"""Garbodor (card 613). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, DARKNESS, FIGHTING, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=613,
    name='Garbodor',
    hp=140,
    energy_type=DARKNESS,
    stage=STAGE1,
    evolves_from='Trubbish',
    weakness=FIGHTING,
    retreat_cost=3,
    attacks=(
        Attack(
            attack_id=882,
            name='Suffocating Gas',
            cost=(DARKNESS,),
            damage=40,
        ),
        Attack(
            attack_id=883,
            name='Gunk Shot',
            cost=(DARKNESS, DARKNESS, COLORLESS),
            damage=120,
            text='Your opponent’s Active Pokémon is now Poisoned.',
        ),
    ),
)
