"""Gastly (card 59). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, DARKNESS, FIGHTING, PokemonCard)

CARD = PokemonCard(
    card_id=59,
    name='Gastly',
    hp=60,
    energy_type=DARKNESS,
    stage=BASIC,
    weakness=FIGHTING,
    retreat_cost=1,
    tags=frozenset([]),
    attacks=(
        Attack(
            attack_id=64,
            name='Mysterious Beam',
            cost=(DARKNESS,),
            damage=0,
            text='Flip a coin. If heads, discard an Energy from your opponent’s Active Pokémon.',
            damage_min=0,
            damage_max=0,
        ),
        Attack(
            attack_id=65,
            name='Suffocating Gas',
            cost=(DARKNESS, DARKNESS),
            damage=30,
        ),
    ),
)
