"""Golurk (card 524). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, DARKNESS, FIGHTING, PSYCHIC, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=524,
    name='Golurk',
    hp=160,
    energy_type=PSYCHIC,
    stage=STAGE1,
    evolves_from='Golett',
    weakness=DARKNESS,
    resistance=FIGHTING,
    retreat_cost=4,
    tags=frozenset([]),
    attacks=(
        Attack(
            attack_id=747,
            name='Double Smash',
            cost=(COLORLESS, COLORLESS, COLORLESS),
            damage=0,
            text='Flip 2 coins. This attack does 80 damage for each heads.',
            damage_min=0,
            damage_max=160,
        ),
        Attack(
            attack_id=748,
            name='Golurk Hammer',
            cost=(PSYCHIC, PSYCHIC, COLORLESS, COLORLESS, COLORLESS),
            damage=200,
        ),
    ),
)
