"""Gorebyss (card 417). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, LIGHTNING, PokemonCard, STAGE1, WATER)

CARD = PokemonCard(
    card_id=417,
    name='Gorebyss',
    hp=90,
    energy_type=WATER,
    stage=STAGE1,
    evolves_from='Clamperl',
    weakness=LIGHTNING,
    retreat_cost=1,
    attacks=(
        Attack(
            attack_id=586,
            name='Crescendo Wave',
            cost=(WATER,),
            damage=0,
            text='This attack does 30 damage for each {W} Energy attached to this Pokémon. Before doing damage, you may attach any number of Basic {W} Energy cards from your hand to this Pokémon.',
        ),
    ),
)
