"""Gothitelle (card 596). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, COLORLESS, DARKNESS, FIGHTING, PSYCHIC, PokemonCard, STAGE2)

CARD = PokemonCard(
    card_id=596,
    name='Gothitelle',
    hp=150,
    energy_type=PSYCHIC,
    stage=STAGE2,
    evolves_from='Gothorita',
    weakness=DARKNESS,
    resistance=FIGHTING,
    retreat_cost=2,
    abilities=(
        Ability(
            name='Distorted Future',
            text='Once during your turn, if this Pokémon is in the Active Spot, you may have your opponent shuffle their hand into their deck and draw 3 cards.',
        ),
    ),
    attacks=(
        Attack(
            attack_id=857,
            name='Synchro Shot',
            cost=(PSYCHIC, COLORLESS),
            damage=90,
            text='If you have the same number of cards in your hand as your opponent, this attack does 90 more damage.',
        ),
    ),
)
