"""Grafaiai (card 693). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, DARKNESS, FIGHTING, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=693,
    name='Grafaiai',
    hp=100,
    energy_type=DARKNESS,
    stage=STAGE1,
    evolves_from='Shroodle',
    weakness=FIGHTING,
    retreat_cost=1,
    tags=frozenset([]),
    attacks=(
        Attack(
            attack_id=1003,
            name='Miraculous Paint',
            cost=(DARKNESS, COLORLESS),
            damage=90,
            text='Flip a coin. If heads, choose a Special Condition. Your opponent’s Active Pokémon is now affected by that Special Condition.',
            damage_min=90,
            damage_max=90,
        ),
    ),
)
