"""Grookey (card 89). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, FIRE, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=89,
    name='Grookey',
    hp=70,
    energy_type=GRASS,
    stage=BASIC,
    weakness=FIRE,
    retreat_cost=1,
    tags=frozenset([]),
    default_roles=('backup_attacker', 'support_pokemon'),
    attacks=(
        Attack(
            attack_id=109,
            name='Smash Kick',
            cost=(GRASS,),
            damage=10,
        ),
        Attack(
            attack_id=110,
            name='Branch Poke',
            cost=(GRASS, GRASS),
            damage=30,
        ),
    ),
)
