"""Gumshoos (card 705). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, COLORLESS, FIGHTING, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=705,
    name='Gumshoos',
    hp=100,
    energy_type=COLORLESS,
    stage=STAGE1,
    evolves_from='Yungoos',
    weakness=FIGHTING,
    retreat_cost=1,
    tags=frozenset(['draw']),
    abilities=(
        Ability(
            name='Evidence Gathering',
            text='Once during your turn, you may use this Ability. Switch a card from your hand with the top card of your deck.',
        ),
    ),
    attacks=(
        Attack(
            attack_id=1021,
            name='Bite',
            cost=(COLORLESS, COLORLESS),
            damage=50,
        ),
    ),
)
