"""Gurdurr (card 114). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, Clause, FIGHTING, PSYCHIC, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=114,
    name='Gurdurr',
    hp=100,
    energy_type=FIGHTING,
    stage=STAGE1,
    evolves_from='Timburr',
    weakness=PSYCHIC,
    retreat_cost=2,
    default_roles=('backup_attacker',),
    attacks=(
        Attack(
            attack_id=143,
            name='Knuckle Punch',
            cost=(FIGHTING,),
            damage=20,
        ),
        Attack(
            attack_id=144,
            name='Superpower',
            cost=(FIGHTING, COLORLESS, COLORLESS),
            damage=50,
            text='You may do 30 more damage. If you do, this Pokémon also does 30 damage to itself.',
            clauses=(Clause('damage_boost', amount=30, optional=True, rider='recoil', rider_amount=30),),
        ),
    ),
)
