"""Haunter (card 60). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, DARKNESS, FIGHTING, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=60,
    name='Haunter',
    hp=90,
    energy_type=DARKNESS,
    stage=STAGE1,
    evolves_from='Gastly',
    weakness=FIGHTING,
    retreat_cost=1,
    tags=frozenset(['poison']),
    attacks=(
        Attack(
            attack_id=66,
            name='Super Poison Breath',
            cost=(DARKNESS, DARKNESS),
            damage=30,
            text='Your opponent’s Active Pokémon is now Poisoned.',
        ),
    ),
)
