"""Hawlucha (card 1055). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, Clause, FIGHTING, PSYCHIC, PokemonCard)

CARD = PokemonCard(
    card_id=1055,
    name='Hawlucha',
    hp=70,
    energy_type=FIGHTING,
    stage=BASIC,
    weakness=PSYCHIC,
    retreat_cost=0,
    tags=frozenset([]),
    default_roles=('backup_attacker',),
    attacks=(
        Attack(
            attack_id=1524,
            name='Vengeful Kick',
            cost=(FIGHTING,),
            damage=30,
            text='If your Benched Pokémon have any damage counters on them, this attack does 60 more damage.',
            clauses=(Clause('damage_boost', amount=60, condition='own_bench_damaged'),),
        ),
    ),
)
