"""Heatran (card 118). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, BASIC, COLORLESS, FIRE, GRASS, METAL, PokemonCard)

CARD = PokemonCard(
    card_id=118,
    name='Heatran',
    hp=140,
    energy_type=METAL,
    stage=BASIC,
    weakness=FIRE,
    resistance=GRASS,
    retreat_cost=4,
    tags=frozenset(['burn']),
    abilities=(
        Ability(
            name='Incandescent Body',
            text='If this Pokémon is in the Active Spot and is damaged by an attack from your opponent’s Pokémon (even if this Pokémon is Knocked Out), the Attacking Pokémon is now Burned.',
        ),
    ),
    attacks=(
        Attack(
            attack_id=149,
            name='Steel Burst',
            cost=(METAL, COLORLESS, COLORLESS),
            damage=0,
            text='Discard all {M} Energy from this Pokémon. This attack does 50 damage for each card you discarded in this way.',
        ),
    ),
)
