"""Heat Rotom (card 413). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, FIRE, PokemonCard, WATER)

CARD = PokemonCard(
    card_id=413,
    name='Heat Rotom',
    hp=80,
    energy_type=FIRE,
    stage=BASIC,
    weakness=WATER,
    retreat_cost=2,
    tags=frozenset(['burn']),
    attacks=(
        Attack(
            attack_id=581,
            name='Singe',
            cost=(FIRE,),
            damage=0,
            text='Your opponent’s Active Pokémon is now Burned.',
        ),
        Attack(
            attack_id=582,
            name='Gadget Show',
            cost=(COLORLESS, COLORLESS),
            damage=0,
            text='This attack does 30 damage for each Pokémon Tool attached to all of your Pokémon.',
        ),
    ),
)
