"""Hoothoot (card 172). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, FIGHTING, LIGHTNING, PokemonCard)

CARD = PokemonCard(
    card_id=172,
    name='Hoothoot',
    hp=70,
    energy_type=COLORLESS,
    stage=BASIC,
    weakness=LIGHTNING,
    resistance=FIGHTING,
    retreat_cost=1,
    tags=frozenset([]),
    attacks=(
        Attack(
            attack_id=228,
            name='Triple Stab',
            cost=(COLORLESS,),
            damage=0,
            text='Flip 3 coins. This attack does 10 damage for each heads.',
            damage_min=0,
            damage_max=30,
        ),
    ),
)
