"""Hop’s Snorlax (card 304). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, BASIC, COLORLESS, Clause, FIGHTING, PokemonCard)

CARD = PokemonCard(
    card_id=304,
    name='Hop’s Snorlax',
    hp=150,
    energy_type=COLORLESS,
    stage=BASIC,
    weakness=FIGHTING,
    retreat_cost=4,
    tags=frozenset([]),
    default_roles=('backup_attacker', 'support_pokemon'),
    covers='full',
    abilities=(
        Ability(
            name='Extra Helpings',
            text='Attacks used by your Hop’s Pokémon do 30 more damage to your opponent’s Active Pokémon (before applying Weakness and Resistance). The effect of Extra Helpings doesn’t stack.',
            clauses=(Clause('damage_boost', amount=30, applies_to='name_family', name_family="Hop's", target='opponent_active', timing='before_weakness_resistance', no_stack=True),),
        ),
    ),
    attacks=(
        Attack(
            attack_id=422,
            name='Dynamic Press',
            cost=(COLORLESS, COLORLESS, COLORLESS),
            damage=140,
            text='This Pokémon also does 80 damage to itself.',
            clauses=(Clause('recoil', amount=80),),
        ),
    ),
)
