"""Hop's Phantump (card 878). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, Clause, DARKNESS, FIGHTING, PSYCHIC, PokemonCard)

CARD = PokemonCard(
    card_id=878,
    name="Hop's Phantump",
    hp=70,
    energy_type=PSYCHIC,
    stage=BASIC,
    weakness=DARKNESS,
    resistance=FIGHTING,
    retreat_cost=2,
    tags=frozenset([]),
    default_roles=('primary_attacker',),
    attacks=(
        Attack(
            attack_id=1266,
            name='Splashing Dodge',
            cost=(COLORLESS,),
            damage=10,
            text='Flip a coin. If heads, during your opponent’s next turn, prevent all damage from and effects of attacks done to this Pokémon.',
            clauses=(Clause('coin', effect='damage_protection', duration='opp_next_turn', includes_effects=True),),
        ),
    ),
)
