"""Hop's Trevenant (card 879). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, Clause, DARKNESS, FIGHTING, PSYCHIC, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=879,
    name="Hop's Trevenant",
    hp=140,
    energy_type=PSYCHIC,
    stage=STAGE1,
    evolves_from="Hop's Phantump",
    weakness=DARKNESS,
    resistance=FIGHTING,
    retreat_cost=2,
    tags=frozenset([]),
    default_roles=('primary_attacker',),
    attacks=(
        Attack(
            attack_id=1267,
            name='Horrifying Revenge',
            cost=(COLORLESS,),
            damage=30,
            text='If any of your Hop’s Pokémon were Knocked Out by damage from an attack during your opponent’s last turn, this attack does 100 more damage.',
            clauses=(Clause('damage_boost', amount=100, condition='pokemon_ko_last_turn', name_family="Hop's"),),
        ),
        Attack(
            attack_id=1268,
            name='Corner',
            cost=(PSYCHIC, COLORLESS, COLORLESS),
            damage=90,
            text='During your opponent’s next turn, the Defending Pokémon can’t retreat.',
            clauses=(Clause('no_retreat', target='defending', duration='opp_next_turn'),),
        ),
    ),
)
