"""Hop’s Dubwool (card 310). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, COLORLESS, Clause, FIGHTING, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=310,
    name='Hop’s Dubwool',
    hp=120,
    energy_type=COLORLESS,
    stage=STAGE1,
    evolves_from='Hop’s Wooloo',
    weakness=FIGHTING,
    retreat_cost=2,
    tags=frozenset([]),
    covers='full',
    abilities=(
        Ability(
            name='Defiant Horn',
            text='When you play this Pokémon from your hand to evolve 1 of your Pokémon during your turn, you may switch in 1 of your opponent’s Benched Pokémon to the Active Spot.',
            clauses=(Clause('gust', target='any', trigger='on_evolve'),),
        ),
    ),
    attacks=(
        Attack(
            attack_id=432,
            name='Headbutt',
            cost=(COLORLESS, COLORLESS, COLORLESS),
            damage=80,
        ),
    ),
)
