"""Incineroar ex (card 79). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, COLORLESS, FIRE, PokemonCard, STAGE2, WATER)

CARD = PokemonCard(
    card_id=79,
    name='Incineroar ex',
    hp=320,
    energy_type=FIRE,
    stage=STAGE2,
    evolves_from='Torracat',
    ex=True,
    weakness=WATER,
    retreat_cost=2,
    abilities=(
        Ability(
            name='Hustle Play',
            text='Attacks used by this Pokémon cost {C} less for each of your opponent’s Benched Pokémon.',
        ),
    ),
    attacks=(
        Attack(
            attack_id=94,
            name='Blaze Blast',
            cost=(FIRE, COLORLESS, COLORLESS, COLORLESS, COLORLESS),
            damage=240,
            text='Your opponent’s Active Pokémon is now Burned.',
        ),
    ),
)
