"""Iono’s Voltorb (card 265). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, FIGHTING, LIGHTNING, PokemonCard)

CARD = PokemonCard(
    card_id=265,
    name='Iono’s Voltorb',
    hp=70,
    energy_type=LIGHTNING,
    stage=BASIC,
    weakness=FIGHTING,
    retreat_cost=1,
    tags=frozenset([]),
    attacks=(
        Attack(
            attack_id=363,
            name='Voltaic Chain',
            cost=(COLORLESS, COLORLESS),
            damage=20,
            text='This attack does 20 more damage for each {L} Energy attached to all of your Iono’s Pokémon.',
            scale_var='atk_active_energy',
            scale_per_unit=20,
        ),
    ),
)
