"""Iono’s Bellibolt ex (card 269). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, COLORLESS, FIGHTING, LIGHTNING, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=269,
    name='Iono’s Bellibolt ex',
    hp=280,
    energy_type=LIGHTNING,
    stage=STAGE1,
    evolves_from='Iono’s Tadbulb',
    ex=True,
    weakness=FIGHTING,
    retreat_cost=2,
    abilities=(
        Ability(
            name='Electric Streamer',
            text='As often as you like during your turn, you may attach a Basic {L} Energy card from your hand to 1 of your Iono’s Pokémon.',
        ),
    ),
    attacks=(
        Attack(
            attack_id=368,
            name='Thunderous Bolt',
            cost=(LIGHTNING, LIGHTNING, LIGHTNING, COLORLESS),
            damage=230,
            text='During your next turn, this Pokémon can’t use attacks.',
        ),
    ),
)
