"""Iono’s Electrode (card 266). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, FIGHTING, LIGHTNING, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=266,
    name='Iono’s Electrode',
    hp=100,
    energy_type=LIGHTNING,
    stage=STAGE1,
    evolves_from='Iono’s Voltorb',
    weakness=FIGHTING,
    retreat_cost=0,
    tags=frozenset([]),
    attacks=(
        Attack(
            attack_id=364,
            name='Thump-Thump Boom',
            cost=(LIGHTNING, LIGHTNING),
            damage=0,
            text='This Pokémon does 100 damage to itself. Flip a coin. If heads, your opponent’s Active Pokémon is Knocked Out.',
            damage_min=0,
            damage_max=0,
        ),
        Attack(
            attack_id=365,
            name='Electric Ball',
            cost=(LIGHTNING, LIGHTNING, COLORLESS),
            damage=100,
        ),
    ),
)
