"""Iron Crown (card 192). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, FIRE, GRASS, METAL, PokemonCard)

CARD = PokemonCard(
    card_id=192,
    name='Iron Crown',
    hp=130,
    energy_type=METAL,
    stage=BASIC,
    weakness=FIRE,
    resistance=GRASS,
    retreat_cost=2,
    tags=('future',),
    attacks=(
        Attack(
            attack_id=256,
            name='Deleting Slash',
            cost=(METAL, COLORLESS),
            damage=40,
            text='If your opponent has 3 or more Benched Pokémon, this attack does 80 more damage.',
        ),
        Attack(
            attack_id=257,
            name='Slicing Blade',
            cost=(METAL, COLORLESS, COLORLESS),
            damage=100,
        ),
    ),
)
