"""Iron Thorns ex (card 37). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, BASIC, COLORLESS, FIGHTING, LIGHTNING, PokemonCard)

CARD = PokemonCard(
    card_id=37,
    name='Iron Thorns ex',
    hp=230,
    energy_type=LIGHTNING,
    stage=BASIC,
    ex=True,
    weakness=FIGHTING,
    retreat_cost=4,
    tags=('future',),
    abilities=(
        Ability(
            name='Initialization',
            text='As long as this Pokémon is in the Active Spot, Pokémon with a Rule Box in play\xa0(both yours and your opponent’s)\xa0have no Abilities, except for Future Pokémon.\xa0(Pokémon {ex}, Pokémon {V}, etc. have Rule Boxes.)',
        ),
    ),
    attacks=(
        Attack(
            attack_id=29,
            name='Volt Cyclone',
            cost=(LIGHTNING, COLORLESS, COLORLESS),
            damage=140,
            text='Move an Energy from this Pokémon to 1 of your Benched Pokémon.',
        ),
    ),
)
