"""Iron Crown ex (card 80). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, BASIC, COLORLESS, DARKNESS, FIGHTING, PSYCHIC, PokemonCard)

CARD = PokemonCard(
    card_id=80,
    name='Iron Crown ex',
    hp=220,
    energy_type=PSYCHIC,
    stage=BASIC,
    ex=True,
    weakness=DARKNESS,
    resistance=FIGHTING,
    retreat_cost=2,
    tags=('future',),
    abilities=(
        Ability(
            name='Cobalt Command',
            text='Attacks used by your Future Pokémon, except any Iron Crown {ex}, do 20 more damage to your opponent’s Active Pokémon\xa0(before applying Weakness and Resistance).',
        ),
    ),
    attacks=(
        Attack(
            attack_id=95,
            name='Twin Shotels',
            cost=(PSYCHIC, COLORLESS, COLORLESS),
            damage=0,
            text='This attack does 50 damage to 2 of your opponent’s Pokémon. This attack’s damage isn’t affected by Weakness or Resistance, or by any effects on those Pokémon.',
        ),
    ),
)
