"""Iron Boulder (card 971). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, DARKNESS, FIGHTING, PSYCHIC, PokemonCard)

CARD = PokemonCard(
    card_id=971,
    name='Iron Boulder',
    hp=140,
    energy_type=PSYCHIC,
    stage=BASIC,
    weakness=DARKNESS,
    resistance=FIGHTING,
    retreat_cost=3,
    tags=('future',),
    attacks=(
        Attack(
            attack_id=1396,
            name='Adjusted Horn',
            cost=(PSYCHIC, COLORLESS),
            damage=170,
            text='If you don’t have the same number of cards in your hand as your opponent, this attack does nothing.',
        ),
    ),
)
