"""Jigglypuff (card 841). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, FIGHTING, PokemonCard)

CARD = PokemonCard(
    card_id=841,
    name='Jigglypuff',
    hp=70,
    energy_type=COLORLESS,
    stage=BASIC,
    weakness=FIGHTING,
    retreat_cost=1,
    attacks=(
        Attack(
            attack_id=1213,
            name='Ball Roll',
            cost=(COLORLESS,),
            damage=0,
            text='Flip a coin until you get tails. This attack does 20 damage for each heads.',
            damage_min=0,
            damage_max=460,
        ),
    ),
)
