"""Jynx (card 744). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, Clause, DARKNESS, FIGHTING, PSYCHIC, PokemonCard)

CARD = PokemonCard(
    card_id=744,
    name='Jynx',
    hp=110,
    energy_type=PSYCHIC,
    stage=BASIC,
    weakness=DARKNESS,
    resistance=FIGHTING,
    retreat_cost=1,
    default_roles=('support_pokemon',),
    attacks=(
        Attack(
            attack_id=1073,
            name='Psychic',
            cost=(PSYCHIC, PSYCHIC),
            damage=30,
            text='This attack does 30 more damage for each Energy attached to your opponent’s Active Pokémon.',
            clauses=(Clause('damage_boost', amount=30, per='energy_on_opp_active'),),
        ),
    ),
)
