"""Jynx (card 101). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, Clause, METAL, PokemonCard, WATER)

CARD = PokemonCard(
    card_id=101,
    name='Jynx',
    hp=90,
    energy_type=WATER,
    stage=BASIC,
    weakness=METAL,
    retreat_cost=1,
    default_roles=('support_pokemon',),
    attacks=(
        Attack(
            attack_id=127,
            name='Inviting Kiss',
            cost=(COLORLESS,),
            damage=0,
            text='Search your deck for a Basic Pokémon and put it onto your Bench. Then, shuffle your deck. If you put any Pokémon onto your Bench in this way, move an Energy from this Pokémon to the new Benched Pokémon.',
            clauses=(Clause('fetch', target='basic_pokemon', zone='deck', dest='bench'), Clause('move_energy', amount=1, source='self', dest='new_benched', trigger='on_fetch_success')),
        ),
        Attack(
            attack_id=128,
            name='Icy Snow',
            cost=(WATER,),
            damage=30,
        ),
    ),
)
