"""Kadabra (card 742). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, Clause, DARKNESS, FIGHTING, PSYCHIC, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=742,
    name='Kadabra',
    hp=80,
    energy_type=PSYCHIC,
    stage=STAGE1,
    evolves_from='Abra',
    weakness=DARKNESS,
    resistance=FIGHTING,
    retreat_cost=1,
    tags=frozenset([]),
    default_roles=('primary_attacker', 'support_pokemon'),
    covers='full',
    abilities=(
        Ability(
            name='Psychic Draw',
            text='Once during your turn, when you play this Pokémon from your hand to evolve 1 of your Pokémon, you may use this Ability. Draw 2 cards.',
            clauses=(Clause('draw', amount=2, trigger='on_evolve'),),
        ),
    ),
    attacks=(
        Attack(
            attack_id=1071,
            name='Super Psy Bolt',
            cost=(PSYCHIC,),
            damage=30,
        ),
    ),
)
