"""Koraidon (card 226). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, Clause, FIGHTING, PSYCHIC, PokemonCard)

CARD = PokemonCard(
    card_id=226,
    name='Koraidon',
    hp=130,
    energy_type=FIGHTING,
    stage=BASIC,
    weakness=PSYCHIC,
    retreat_cost=2,
    tags=frozenset([]),
    default_roles=('backup_attacker',),
    attacks=(
        Attack(
            attack_id=307,
            name='Unrelenting Onslaught',
            cost=(COLORLESS, COLORLESS),
            damage=30,
            text='If 1 of your other Ancient Pokémon used an attack during your last turn, this attack does 150 more damage.',
            clauses=(Clause('damage_boost', amount=150, condition='other_ancient_attacked_last_turn'),),
        ),
        Attack(
            attack_id=308,
            name='Hammer In',
            cost=(FIGHTING, FIGHTING, COLORLESS),
            damage=110,
        ),
    ),
)
