"""Liepard (card 609). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, DARKNESS, GRASS, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=609,
    name='Liepard',
    hp=110,
    energy_type=DARKNESS,
    stage=STAGE1,
    evolves_from='Purrloin',
    weakness=GRASS,
    retreat_cost=1,
    attacks=(
        Attack(
            attack_id=876,
            name='Knock Off',
            cost=(DARKNESS,),
            damage=50,
            text='Discard a random card from your opponent’s hand.',
        ),
    ),
)
