"""Lillie’s Clefairy ex (card 272). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, BASIC, COLORLESS, Clause, METAL, PSYCHIC, PokemonCard)

CARD = PokemonCard(
    card_id=272,
    name='Lillie’s Clefairy ex',
    hp=190,
    energy_type=PSYCHIC,
    stage=BASIC,
    ex=True,
    weakness=METAL,
    retreat_cost=1,
    tags=frozenset([]),
    default_roles=('primary_attacker',),
    covers='full',
    abilities=(
        Ability(
            name='Fairy Zone',
            text='The Weakness of each of your opponent’s {N} Pokémon in play is now {P}. (Apply Weakness as\xa0×2.)',
            clauses=(Clause('weakness_override', target='opp_dragon_pokemon', new_weakness=5),),
        ),
    ),
    attacks=(
        Attack(
            attack_id=371,
            name='Full Moon Rondo',
            cost=(PSYCHIC, COLORLESS),
            damage=20,
            text='This attack does 20 more damage for each Benched Pokémon (both yours and your opponent’s).',
            clauses=(Clause('damage_boost', amount=20, per='all_bench'),),
            scale_var='both_bench',
            scale_per_unit=20,
        ),
    ),
)
