"""Litten (card 77). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, FIRE, PokemonCard, WATER)

CARD = PokemonCard(
    card_id=77,
    name='Litten',
    hp=70,
    energy_type=FIRE,
    stage=BASIC,
    weakness=WATER,
    retreat_cost=2,
    attacks=(
        Attack(
            attack_id=91,
            name='Fake Out',
            cost=(FIRE,),
            damage=10,
            text='Flip a coin. If heads, your opponent’s Active Pokémon is now Paralyzed.',
            damage_min=10,
            damage_max=10,
        ),
    ),
)
