"""LugiaEX (card 337). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, FIGHTING, LIGHTNING, PokemonCard)

CARD = PokemonCard(
    card_id=337,
    name='LugiaEX',
    hp=220,
    energy_type=COLORLESS,
    stage=BASIC,
    ex=True,
    weakness=LIGHTNING,
    resistance=FIGHTING,
    retreat_cost=2,
    tags=frozenset([]),
    attacks=(
        Attack(
            attack_id=469,
            name='Hyper Whirlpool',
            cost=(COLORLESS, COLORLESS, COLORLESS),
            damage=140,
            text='Flip a coin until you get tails. For each heads, discard an Energy from your opponent’s Active Pokémon.',
            damage_min=140,
            damage_max=140,
        ),
    ),
)
