"""Lunatone (card 675). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, BASIC, Clause, FIGHTING, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=675,
    name='Lunatone',
    hp=110,
    energy_type=FIGHTING,
    stage=BASIC,
    weakness=GRASS,
    retreat_cost=1,
    default_roles=('draw_engine',),
    covers='full',
    synergy=('Solrock',),
    abilities=(
        Ability(
            name='Lunar Cycle',
            text='Once during your turn, if you have Solrock in play, you may discard a Basic {F} Energy card from your hand in order to use this Ability. Draw 3 cards. You can’t use more than 1 Lunar Cycle Ability each turn.',
            clauses=(Clause('draw', amount=3, condition='solrock_in_play', allowance='card', rider='discard_basic_f_energy', rider_energy_type=FIGHTING, rider_amount=1),),
        ),
    ),
    attacks=(
        Attack(
            attack_id=979,
            name='Power Gem',
            cost=(FIGHTING, FIGHTING),
            damage=50,
        ),
    ),
)
