"""Magmortar (card 256). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, COLORLESS, FIRE, PokemonCard, STAGE1, WATER)

CARD = PokemonCard(
    card_id=256,
    name='Magmortar',
    hp=130,
    energy_type=FIRE,
    stage=STAGE1,
    evolves_from='Magmar',
    weakness=WATER,
    retreat_cost=2,
    abilities=(
        Ability(
            name='Magma Surge',
            text='During Pokémon Checkup, put 3 more damage counters on your opponent’s Burned Pokémon.',
        ),
    ),
    attacks=(
        Attack(
            attack_id=352,
            name='Searing Flame',
            cost=(FIRE, FIRE, COLORLESS),
            damage=90,
            text='Flip a coin. If heads, your opponent’s Active Pokémon is now Burned.',
            damage_min=90,
            damage_max=90,
        ),
    ),
)
