"""Magneton (card 733). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, FIGHTING, LIGHTNING, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=733,
    name='Magneton',
    hp=90,
    energy_type=LIGHTNING,
    stage=STAGE1,
    evolves_from='Magnemite',
    weakness=FIGHTING,
    retreat_cost=2,
    attacks=(
        Attack(
            attack_id=1059,
            name='Thunder Shock',
            cost=(LIGHTNING,),
            damage=30,
            text='Flip a coin. If heads, your opponent’s Active Pokémon is now Paralyzed.',
            damage_min=30,
            damage_max=30,
        ),
    ),
)
