"""Mandibuzz ex (card 984). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, DARKNESS, FIGHTING, LIGHTNING, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=984,
    name='Mandibuzz ex',
    hp=260,
    energy_type=DARKNESS,
    stage=STAGE1,
    evolves_from='Vullaby',
    ex=True,
    weakness=LIGHTNING,
    resistance=FIGHTING,
    retreat_cost=1,
    attacks=(
        Attack(
            attack_id=1417,
            name='Bone Shot',
            cost=(COLORLESS, COLORLESS),
            damage=0,
            text='This attack does 50 damage to 1 of your opponent’s Pokémon. (Don’t apply Weakness and Resistance for Benched Pokémon.)',
        ),
        Attack(
            attack_id=1418,
            name='Vulture Claw',
            cost=(DARKNESS, COLORLESS, COLORLESS),
            damage=160,
            text='Discard a random card from your opponent’s hand.',
        ),
    ),
)
