"""Mankey (card 437). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, Clause, FIGHTING, PSYCHIC, PokemonCard)

CARD = PokemonCard(
    card_id=437,
    name='Mankey',
    hp=70,
    energy_type=FIGHTING,
    stage=BASIC,
    weakness=PSYCHIC,
    retreat_cost=1,
    tags=frozenset([]),
    default_roles=('backup_attacker',),
    attacks=(
        Attack(
            attack_id=616,
            name='Wild Kick',
            cost=(FIGHTING,),
            damage=30,
            text='Flip a coin. If tails, this attack does nothing.',
            clauses=(Clause('coin', effect='attack_fails_on_tails'),),
        ),
    ),
)
