"""Marill (card 961). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, METAL, PSYCHIC, PokemonCard)

CARD = PokemonCard(
    card_id=961,
    name='Marill',
    hp=70,
    energy_type=PSYCHIC,
    stage=BASIC,
    weakness=METAL,
    retreat_cost=1,
    tags=frozenset([]),
    attacks=(
        Attack(
            attack_id=1382,
            name='Hide',
            cost=(COLORLESS,),
            damage=0,
            text='Flip a coin. If heads, during your opponent’s next turn, prevent all damage from and effects of attacks done to this Pokémon.',
            damage_min=0,
            damage_max=0,
        ),
        Attack(
            attack_id=1383,
            name='Flop',
            cost=(PSYCHIC, COLORLESS),
            damage=20,
        ),
    ),
)
