"""Marill (card 53). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, METAL, PSYCHIC, PokemonCard)

CARD = PokemonCard(
    card_id=53,
    name='Marill',
    hp=70,
    energy_type=PSYCHIC,
    stage=BASIC,
    weakness=METAL,
    retreat_cost=2,
    attacks=(
        Attack(
            attack_id=55,
            name='Ball Roll',
            cost=(COLORLESS,),
            damage=0,
            text='Flip a coin until you get tails. This attack does 10 damage for each heads.',
            damage_min=0,
            damage_max=230,
        ),
        Attack(
            attack_id=56,
            name='Magical Shot',
            cost=(PSYCHIC, COLORLESS, COLORLESS),
            damage=40,
        ),
    ),
)
