"""Marnie's Grimmsnarl ex (card 648). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, Clause, DARKNESS, GRASS, PokemonCard, STAGE2)

CARD = PokemonCard(
    card_id=648,
    name="Marnie's Grimmsnarl ex",
    hp=320,
    energy_type=DARKNESS,
    stage=STAGE2,
    evolves_from="Marnie's Morgrem",
    ex=True,
    weakness=GRASS,
    retreat_cost=2,
    default_roles=('primary_attacker',),
    covers='full',
    abilities=(
        Ability(
            name='Punk Up',
            text='When you play this Pokémon from your hand to evolve 1 of your Pokémon during your turn, you may search your deck for up to 5 Basic {D} Energy cards and attach them to your Marnie’s Pokémon in any way you like. Then, shuffle your deck.',
            clauses=(Clause('accel', amount=5, source='deck', target='own_line', energy='basic', energy_type=DARKNESS, trigger='on_evolve'),),
        ),
    ),
    attacks=(
        Attack(
            attack_id=937,
            name='Shadow Bullet',
            cost=(DARKNESS, DARKNESS),
            damage=180,
            text='This attack also does 30 damage to 1 of your opponent’s Benched Pokémon. (Don’t apply Weakness and Resistance for Benched Pokémon.)',
            clauses=(Clause('bench_snipe', amount=30, target='opp_bench'),),
        ),
    ),
)
