"""Mega Scrafty ex (card 896). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, COLORLESS, DARKNESS, GRASS, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=896,
    name='Mega Scrafty ex',
    hp=330,
    energy_type=DARKNESS,
    stage=STAGE1,
    evolves_from='Scraggy',
    mega_ex=True,
    weakness=GRASS,
    retreat_cost=2,
    abilities=(
        Ability(
            name='Counterattacking Crest',
            text='If this Pokémon is in the Active Spot and is damaged by an attack from your opponent’s Pokémon (even if this Pokémon is Knocked Out), place 5 damage counters on the Attacking Pokémon.',
        ),
    ),
    attacks=(
        Attack(
            attack_id=1293,
            name='Outlaw Leg',
            cost=(DARKNESS, DARKNESS, COLORLESS),
            damage=160,
            text='Discard a random card from your opponent’s hand. Discard the top card of your opponent’s deck.',
        ),
    ),
)
