"""Mega Starmie ex (card 1031). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, Clause, LIGHTNING, PokemonCard, STAGE1, WATER)

CARD = PokemonCard(
    card_id=1031,
    name='Mega Starmie ex',
    hp=330,
    energy_type=WATER,
    stage=STAGE1,
    evolves_from='Staryu',
    mega_ex=True,
    weakness=LIGHTNING,
    retreat_cost=2,
    default_roles=('primary_attacker', 'sniper'),
    attacks=(
        Attack(
            attack_id=1487,
            name='Jetting Blow',
            cost=(WATER,),
            damage=120,
            text='This attack also does 50 damage to 1 of your opponent’s Benched Pokémon.\xa0(Don’t apply Weakness and Resistance for Benched Pokémon.)',
            clauses=(Clause('bench_snipe', amount=50, target='opp_bench'),),
        ),
        Attack(
            attack_id=1488,
            name='Nebula Beam',
            cost=(COLORLESS, COLORLESS, COLORLESS),
            damage=210,
            text='This attack’s damage isn’t affected by Weakness or Resistance, or by any effects on your opponent’s Active Pokémon.',
            clauses=(Clause('ignores_wr'), Clause('ignores_effects')),
        ),
    ),
)
