"""Mega Lucario ex (card 678). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, Clause, FIGHTING, PSYCHIC, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=678,
    name='Mega Lucario ex',
    hp=340,
    energy_type=FIGHTING,
    stage=STAGE1,
    evolves_from='Riolu',
    mega_ex=True,
    weakness=PSYCHIC,
    retreat_cost=2,
    tags=frozenset(['discard_energy_recur']),
    attacks=(
        Attack(
            attack_id=982,
            name='Aura Jab',
            cost=(FIGHTING,),
            damage=130,
            text='Attach up to 3 Basic {F} Energy cards from your discard pile to your Benched Pokémon in any way you like.',
            clauses=(Clause('energy_recur', amount=3, energy_type=FIGHTING, zone='discard', target='bench_only'),),
        ),
        Attack(
            attack_id=983,
            name='Mega Brave',
            cost=(FIGHTING, FIGHTING),
            damage=270,
            text='During your next turn, this Pokémon can’t use Mega Brave.',
            clauses=(Clause('same_attack_lock', duration='next_turn'),),
        ),
    ),
)
