"""Mega Gardevoir ex (card 747). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, DARKNESS, FIGHTING, PSYCHIC, PokemonCard, STAGE2)

CARD = PokemonCard(
    card_id=747,
    name='Mega Gardevoir ex',
    hp=360,
    energy_type=PSYCHIC,
    stage=STAGE2,
    evolves_from='Kirlia',
    mega_ex=True,
    weakness=DARKNESS,
    resistance=FIGHTING,
    retreat_cost=2,
    tags=frozenset([]),
    attacks=(
        Attack(
            attack_id=1078,
            name='Overflowing Wishes',
            cost=(PSYCHIC,),
            damage=0,
            text='For each of your Benched Pokémon, search your deck for a Basic {P} Energy card and attach it to that Pokémon. Then, shuffle your deck.',
        ),
        Attack(
            attack_id=1079,
            name='Mega Symphonia',
            cost=(PSYCHIC,),
            damage=0,
            text='This attack does 50 damage for each {P} Energy attached to all of your Pokémon.',
            scale_var='atk_active_energy',
            scale_per_unit=50,
        ),
    ),
)
