"""Mega Dragonite ex (card 904). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, DRAGON, LIGHTNING, PokemonCard, STAGE2, WATER)

CARD = PokemonCard(
    card_id=904,
    name='Mega Dragonite ex',
    hp=370,
    energy_type=DRAGON,
    stage=STAGE2,
    evolves_from='Dragonair',
    mega_ex=True,
    retreat_cost=2,
    abilities=(
        Ability(
            name='Sky Transport',
            text='Once during your turn, you may use this Ability. Switch your Active Pokémon with 1 of your Benched Pokémon.',
        ),
    ),
    attacks=(
        Attack(
            attack_id=1302,
            name='Ryuno Glide',
            cost=(WATER, LIGHTNING, LIGHTNING),
            damage=330,
            text='Discard 2 Energy from this Pokémon.',
        ),
    ),
)
