"""Mega Audino ex (card 1006). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, FIGHTING, PokemonCard)

CARD = PokemonCard(
    card_id=1006,
    name='Mega Audino ex',
    hp=270,
    energy_type=COLORLESS,
    stage=BASIC,
    mega_ex=True,
    weakness=FIGHTING,
    retreat_cost=1,
    attacks=(
        Attack(
            attack_id=1453,
            name='Kaleidowaltz',
            cost=(COLORLESS,),
            damage=0,
            text='Flip 3 coins. For each heads, search your deck for up to 2 Basic Energy cards and attach them to your Pokémon in any way you like. Then, shuffle your deck.',
            damage_min=0,
            damage_max=0,
        ),
        Attack(
            attack_id=1454,
            name='Ear Force',
            cost=(COLORLESS, COLORLESS, COLORLESS),
            damage=20,
            text='This attack does 80 more damage for each Energy attached to your opponent’s Active Pokémon.',
        ),
    ),
)
