"""Mega Abomasnow ex (card 723). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, Clause, METAL, PokemonCard, STAGE1, WATER)

CARD = PokemonCard(
    card_id=723,
    name='Mega Abomasnow ex',
    hp=350,
    energy_type=WATER,
    stage=STAGE1,
    evolves_from='Snover',
    mega_ex=True,
    weakness=METAL,
    retreat_cost=4,
    tags=frozenset([]),
    default_roles=('primary_attacker',),
    attacks=(
        Attack(
            attack_id=1046,
            name='Hammer-lanche',
            cost=(WATER, WATER),
            damage=0,
            text='Discard the top 6 cards of your deck, and this attack does 100 damage for each Basic {W} Energy card that you discarded in this way.',
            clauses=(Clause('mill', amount=6, target='self'), Clause('damage_boost', amount=100, per='basic_energy_discarded_this_way', energy_type=WATER)),
        ),
        Attack(
            attack_id=1047,
            name='Frost Barrier',
            cost=(WATER, WATER, WATER),
            damage=200,
            text='During your opponent’s next turn, this Pokémon takes 30 less damage from attacks (after applying Weakness and Resistance).',
            clauses=(Clause('damage_reduction', amount=30, duration='opp_next_turn', timing='after_weakness_resistance'),),
        ),
    ),
)
