"""Mega Zygarde ex (card 1056). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, FIGHTING, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=1056,
    name='Mega Zygarde ex',
    hp=310,
    energy_type=FIGHTING,
    stage=BASIC,
    mega_ex=True,
    weakness=GRASS,
    retreat_cost=2,
    tags=frozenset([]),
    attacks=(
        Attack(
            attack_id=1525,
            name='Gaia Wave',
            cost=(FIGHTING, FIGHTING, FIGHTING),
            damage=200,
            text='During your opponent’s next turn, this Pokémon takes 30 less damage from attacks (after applying Weakness and Resistance).',
        ),
        Attack(
            attack_id=1526,
            name='Nullifying Zero',
            cost=(FIGHTING, FIGHTING, FIGHTING, FIGHTING, FIGHTING),
            damage=0,
            text='For each of your opponent’s Pokémon, flip a coin. If heads, this attack does 150 damage to that Pokémon. (Don’t apply Weakness and Resistance for Benched Pokémon.)',
            damage_min=0,
            damage_max=150,
        ),
    ),
)
