"""Minccino (card 555). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, FIGHTING, PokemonCard)

CARD = PokemonCard(
    card_id=555,
    name='Minccino',
    hp=60,
    energy_type=COLORLESS,
    stage=BASIC,
    weakness=FIGHTING,
    retreat_cost=1,
    attacks=(
        Attack(
            attack_id=792,
            name='Tail Slap',
            cost=(COLORLESS,),
            damage=0,
            text='Flip 2 coins. This attack does 20 damage for each heads.',
            damage_min=0,
            damage_max=40,
        ),
    ),
)
