"""Misty's Staryu (card 360). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, LIGHTNING, PokemonCard, WATER)

CARD = PokemonCard(
    card_id=360,
    name="Misty's Staryu",
    hp=70,
    energy_type=WATER,
    stage=BASIC,
    weakness=LIGHTNING,
    retreat_cost=1,
    tags=frozenset(['paralyze']),
    attacks=(
        Attack(
            attack_id=498,
            name='Bubble Beam',
            cost=(WATER,),
            damage=20,
            text='Flip a coin. If heads, your opponent’s Active Pokémon is now Paralyzed.',
            damage_min=20,
            damage_max=20,
        ),
    ),
)
