"""Moltres (card 791). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, Clause, FIRE, PokemonCard, WATER)

CARD = PokemonCard(
    card_id=791,
    name='Moltres',
    hp=120,
    energy_type=FIRE,
    stage=BASIC,
    weakness=WATER,
    retreat_cost=1,
    tags=frozenset([]),
    default_roles=('backup_attacker',),
    attacks=(
        Attack(
            attack_id=1143,
            name='Fighting Wings',
            cost=(FIRE,),
            damage=20,
            text='If your opponent’s Active Pokémon is a Pokémon {ex}, this attack does 90 more damage.',
            clauses=(Clause('damage_boost', amount=90, condition='opp_active_ex'),),
        ),
    ),
)
