"""Morpeko (card 36). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, BASIC, FIGHTING, LIGHTNING, PokemonCard)

CARD = PokemonCard(
    card_id=36,
    name='Morpeko',
    hp=70,
    energy_type=LIGHTNING,
    stage=BASIC,
    weakness=FIGHTING,
    retreat_cost=1,
    tags=frozenset(['dig']),
    abilities=(
        Ability(
            name='Snack Seek',
            text='Once during your turn, you may look at the top card of your deck. You may discard that card.',
        ),
    ),
    attacks=(
        Attack(
            attack_id=28,
            name='Pick and Stick',
            cost=(LIGHTNING,),
            damage=0,
            text='Attach up to 2 Basic Energy cards from your discard pile to your Pokémon in any way you like.',
        ),
    ),
)
