"""Munna (card 516). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, DARKNESS, FIGHTING, PSYCHIC, PokemonCard)

CARD = PokemonCard(
    card_id=516,
    name='Munna',
    hp=70,
    energy_type=PSYCHIC,
    stage=BASIC,
    weakness=DARKNESS,
    resistance=FIGHTING,
    retreat_cost=1,
    tags=frozenset(['sleep']),
    attacks=(
        Attack(
            attack_id=733,
            name='Rest',
            cost=(COLORLESS,),
            damage=0,
            text='This Pokémon is now Asleep. Heal 30 damage from it.',
            damage_min=0,
            damage_max=0,
        ),
        Attack(
            attack_id=734,
            name='Mumble',
            cost=(PSYCHIC,),
            damage=10,
        ),
    ),
)
