"""N’s Darumaka (card 257). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, FIRE, PokemonCard, WATER)

CARD = PokemonCard(
    card_id=257,
    name='N’s Darumaka',
    hp=80,
    energy_type=FIRE,
    stage=BASIC,
    weakness=WATER,
    retreat_cost=2,
    default_roles=('backup_attacker',),
    attacks=(
        Attack(
            attack_id=353,
            name='Rolling Tackle',
            cost=(COLORLESS, COLORLESS),
            damage=20,
        ),
        Attack(
            attack_id=354,
            name='Flare',
            cost=(FIRE, FIRE, COLORLESS),
            damage=50,
        ),
    ),
)
