"""N's Zekrom (card 906). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, Clause, DRAGON, FIRE, LIGHTNING, PokemonCard)

CARD = PokemonCard(
    card_id=906,
    name="N's Zekrom",
    hp=130,
    energy_type=DRAGON,
    stage=BASIC,
    retreat_cost=2,
    tags=frozenset([]),
    default_roles=('backup_attacker',),
    attacks=(
        Attack(
            attack_id=1305,
            name='Shred',
            cost=(COLORLESS, COLORLESS, COLORLESS),
            damage=70,
            text='This attack’s damage isn’t affected by any effects on your opponent’s Active Pokémon.',
            clauses=(Clause('ignores_effects'),),
        ),
        Attack(
            attack_id=1306,
            name='Rampaging Thunder',
            cost=(FIRE, LIGHTNING, LIGHTNING, COLORLESS),
            damage=250,
            text='During your next turn, this Pokémon can’t use attacks.',
            clauses=(Clause('attack_lock', duration='next_turn'),),
        ),
    ),
)
