"""N’s Reshiram (card 303). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, Clause, DRAGON, FIRE, LIGHTNING, PokemonCard)

CARD = PokemonCard(
    card_id=303,
    name='N’s Reshiram',
    hp=130,
    energy_type=DRAGON,
    stage=BASIC,
    retreat_cost=2,
    tags=frozenset([]),
    default_roles=('backup_attacker',),
    attacks=(
        Attack(
            attack_id=420,
            name='Powerful Rage',
            cost=(FIRE, LIGHTNING),
            damage=0,
            text='This attack does 20 damage for each damage counter on this Pokémon.',
            clauses=(Clause('damage_boost', amount=20, per='damage_counter_on_self'),),
        ),
        Attack(
            attack_id=421,
            name='Virtuous Flame',
            cost=(FIRE, FIRE, LIGHTNING, COLORLESS),
            damage=170,
        ),
    ),
)
