"""N’s Darmanitan (card 258). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, Clause, FIRE, PokemonCard, STAGE1, WATER)

CARD = PokemonCard(
    card_id=258,
    name='N’s Darmanitan',
    hp=140,
    energy_type=FIRE,
    stage=STAGE1,
    evolves_from='N’s Darumaka',
    weakness=WATER,
    retreat_cost=3,
    default_roles=('backup_attacker',),
    attacks=(
        Attack(
            attack_id=355,
            name='Back Draft',
            cost=(COLORLESS, COLORLESS),
            damage=0,
            text='This attack does 30 damage for each Basic Energy card in your opponent’s discard pile.',
            clauses=(Clause('damage_boost', amount=30, per='basic_energy_in_opp_discard'),),
        ),
        Attack(
            attack_id=356,
            name='Flamebody Cannon',
            cost=(FIRE, FIRE, COLORLESS),
            damage=90,
            text='Discard all Energy from this Pokémon, and this attack also does 90 damage to 1 of your opponent’s Benched Pokémon.\xa0(Don’t apply Weakness and Resistance for Benched Pokémon.)',
            clauses=(Clause('self_discard_energy', amount='all'), Clause('bench_snipe', amount=90, target='opp_bench')),
        ),
    ),
)
