"""Numel (card 856). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, BASIC, COLORLESS, FIRE, PokemonCard, WATER)

CARD = PokemonCard(
    card_id=856,
    name='Numel',
    hp=80,
    energy_type=FIRE,
    stage=BASIC,
    weakness=WATER,
    retreat_cost=3,
    tags=frozenset(['burn']),
    abilities=(
        Ability(
            name='Incandescent Body',
            text='If this Pokémon is in the Active Spot and is damaged by an attack from your opponent’s Pokémon (even if this Pokémon is Knocked Out), the Attacking Pokémon is now Burned.',
        ),
    ),
    attacks=(
        Attack(
            attack_id=1234,
            name='Combustion',
            cost=(FIRE, COLORLESS),
            damage=20,
        ),
    ),
)
