"""Nymble (card 786). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, FIRE, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=786,
    name='Nymble',
    hp=50,
    energy_type=GRASS,
    stage=BASIC,
    weakness=FIRE,
    retreat_cost=1,
    attacks=(
        Attack(
            attack_id=1137,
            name='Flail Around',
            cost=(GRASS,),
            damage=0,
            text='Flip 3 coins. This attack does 10 damage for each heads.',
            damage_min=0,
            damage_max=30,
        ),
    ),
)
