"""Onix (card 671). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, FIGHTING, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=671,
    name='Onix',
    hp=120,
    energy_type=FIGHTING,
    stage=BASIC,
    weakness=GRASS,
    retreat_cost=4,
    attacks=(
        Attack(
            attack_id=973,
            name='Bind',
            cost=(COLORLESS, COLORLESS),
            damage=30,
            text='Flip a coin. If heads, your opponent’s Active Pokémon is now Paralyzed.',
            damage_min=30,
            damage_max=30,
        ),
        Attack(
            attack_id=974,
            name='Strength',
            cost=(COLORLESS, COLORLESS, COLORLESS, COLORLESS),
            damage=100,
        ),
    ),
)
