"""Palafin (card 51). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, LIGHTNING, PokemonCard, STAGE1, WATER)

CARD = PokemonCard(
    card_id=51,
    name='Palafin',
    hp=150,
    energy_type=WATER,
    stage=STAGE1,
    evolves_from='Finizen',
    weakness=LIGHTNING,
    retreat_cost=2,
    tags=frozenset([]),
    attacks=(
        Attack(
            attack_id=51,
            name='Vanguard Punch',
            cost=(WATER,),
            damage=130,
            text='This Pokémon also does 10 damage to itself for each damage counter on it.',
        ),
        Attack(
            attack_id=52,
            name='Double Hit',
            cost=(WATER, COLORLESS, COLORLESS),
            damage=0,
            text='Flip 2 coins. This attack does 90 damage for each heads.',
            damage_min=0,
            damage_max=180,
        ),
    ),
)
