"""Pecharunt ex (card 141). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, BASIC, Clause, DARKNESS, FIGHTING, PokemonCard)

CARD = PokemonCard(
    card_id=141,
    name='Pecharunt ex',
    hp=190,
    energy_type=DARKNESS,
    stage=BASIC,
    ex=True,
    weakness=FIGHTING,
    retreat_cost=1,
    tags=frozenset([]),
    default_roles=('backup_attacker', 'support_pokemon'),
    covers='full',
    abilities=(
        Ability(
            name='Subjugating Chains',
            text='Once during your turn, you may switch 1 of your Benched {D} Pokémon, except any Pecharunt {ex}, with your Active Pokémon. If you do, the new Active Pokémon is now Poisoned. You can’t use more than 1 Subjugating Chains Ability each turn.',
            clauses=(Clause('self_switch', target='benched', target_type=7, exclude_name='Pecharunt ex', rider='poison_new_active', allowance='card'),),
        ),
    ),
    attacks=(
        Attack(
            attack_id=184,
            name='Irritated Outburst',
            cost=(DARKNESS, DARKNESS),
            damage=0,
            text='This attack does 60 damage for each Prize card your opponent has taken.',
            clauses=(Clause('damage_boost', amount=60, per='opp_prizes_taken'),),
        ),
    ),
)
