"""Pecharunt (card 230). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, BASIC, COLORLESS, DARKNESS, FIGHTING, PokemonCard)

CARD = PokemonCard(
    card_id=230,
    name='Pecharunt',
    hp=80,
    energy_type=DARKNESS,
    stage=BASIC,
    weakness=FIGHTING,
    retreat_cost=1,
    abilities=(
        Ability(
            name='Toxic Subjugation',
            text='As long as this Pokémon is in the Active Spot, put 5 more damage counters on your opponent’s Poisoned Pokémon during Pokémon Checkup.',
        ),
    ),
    attacks=(
        Attack(
            attack_id=315,
            name='Poison Chain',
            cost=(DARKNESS, COLORLESS),
            damage=10,
            text='Your opponent’s Active Pokémon is now Poisoned. During your opponent’s next turn, that Pokémon can’t retreat.',
        ),
    ),
)
