"""Primeape (card 438). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, Clause, FIGHTING, PSYCHIC, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=438,
    name='Primeape',
    hp=110,
    energy_type=FIGHTING,
    stage=STAGE1,
    evolves_from='Mankey',
    weakness=PSYCHIC,
    retreat_cost=2,
    default_roles=('backup_attacker',),
    attacks=(
        Attack(
            attack_id=617,
            name='Drag Off',
            cost=(FIGHTING,),
            damage=0,
            text='Switch in 1 of your opponent’s Benched Pokémon to the Active Spot. This attack does 30 damage to the new Active Pokémon.',
            clauses=(Clause('gust', target='any', rider='damage_new_active', amount=30),),
        ),
    ),
)
