"""Psyduck (card 858). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, BASIC, COLORLESS, Clause, LIGHTNING, PokemonCard, WATER)

CARD = PokemonCard(
    card_id=858,
    name='Psyduck',
    hp=70,
    energy_type=WATER,
    stage=BASIC,
    weakness=LIGHTNING,
    retreat_cost=1,
    tags=frozenset([]),
    default_roles=('support_pokemon',),
    abilities=(
        Ability(
            name='Damp',
            text='Pokémon in play\xa0(both yours and your opponent’s)\xa0lose any Ability that requires the Pokémon using it to Knock Out itself.',
            clauses=(Clause('ability_suppression', applies_to='self_ko_abilities', symmetric=True),),
        ),
    ),
    attacks=(
        Attack(
            attack_id=1237,
            name='Ram',
            cost=(COLORLESS, COLORLESS),
            damage=20,
        ),
    ),
)
