"""Quaquaval (card 182). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, COLORLESS, LIGHTNING, PokemonCard, STAGE2, WATER)

CARD = PokemonCard(
    card_id=182,
    name='Quaquaval',
    hp=170,
    energy_type=WATER,
    stage=STAGE2,
    evolves_from='Quaxwell',
    weakness=LIGHTNING,
    retreat_cost=2,
    tags=frozenset(['draw']),
    abilities=(
        Ability(
            name='Up-Tempo',
            text='You must put a card from your hand on the bottom of your deck in order to use this Ability. Once during your turn, you may draw cards until you have 5 cards in your hand.',
        ),
    ),
    attacks=(
        Attack(
            attack_id=241,
            name='Hydro Splash',
            cost=(WATER, COLORLESS),
            damage=120,
        ),
    ),
)
