"""Rabsca (card 74). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, Clause, FIRE, GRASS, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=74,
    name='Rabsca',
    hp=70,
    energy_type=GRASS,
    stage=STAGE1,
    evolves_from='Rellor',
    weakness=FIRE,
    retreat_cost=1,
    tags=frozenset([]),
    default_roles=('support_pokemon',),
    covers='full',
    abilities=(
        Ability(
            name='Spherical Shield',
            text='Prevent all damage from and effects of attacks from your opponent’s Pokémon done to your Benched Pokémon.',
            clauses=(Clause('prevent_damage', applies_to='own_bench', source='opponent_attack', includes_effects=True),),
        ),
    ),
    attacks=(
        Attack(
            attack_id=88,
            name='Psychic',
            cost=(GRASS,),
            damage=10,
            text='This attack does 30 more damage for each Energy attached to your opponent’s Active Pokémon.',
            clauses=(Clause('damage_boost', amount=30, per='energy_on_opp_active'),),
        ),
    ),
)
