"""Raging Bolt (card 171). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, DRAGON, FIGHTING, LIGHTNING, PokemonCard)

CARD = PokemonCard(
    card_id=171,
    name='Raging Bolt',
    hp=130,
    energy_type=DRAGON,
    stage=BASIC,
    retreat_cost=3,
    attacks=(
        Attack(
            attack_id=226,
            name='Thunderburst Storm',
            cost=(LIGHTNING, FIGHTING),
            damage=0,
            text='This attack does 30 damage to 1 of your opponent’s Pokémon for each Energy attached to this Pokémon.\xa0(Don’t apply Weakness and Resistance for Benched Pokémon.)',
            scale_var='atk_active_energy',
            scale_per_unit=30,
        ),
        Attack(
            attack_id=227,
            name='Dragon Headbutt',
            cost=(LIGHTNING, FIGHTING, COLORLESS),
            damage=130,
        ),
    ),
)
