"""Raging Bolt ex (card 63). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, Clause, DRAGON, FIGHTING, LIGHTNING, PokemonCard)

CARD = PokemonCard(
    card_id=63,
    name='Raging Bolt ex',
    hp=240,
    energy_type=DRAGON,
    stage=BASIC,
    ex=True,
    retreat_cost=3,
    tags=frozenset([]),
    default_roles=('backup_attacker',),
    attacks=(
        Attack(
            attack_id=71,
            name='Burst Roar',
            cost=(COLORLESS,),
            damage=0,
            text='Discard your hand and draw 6 cards.',
            clauses=(Clause('draw', amount=6, cost='discard_hand'),),
        ),
        Attack(
            attack_id=72,
            name='Bellowing Thunder',
            cost=(LIGHTNING, FIGHTING),
            damage=0,
            text='You may discard any amount of Basic Energy from your Pokémon. This attack does 70 damage for each card you discarded in this way.',
            clauses=(Clause('self_discard_energy', amount='any'), Clause('damage_boost', amount=70, per='energy_discarded_this_way')),
        ),
    ),
)
