"""Rapidash (card 351). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, COLORLESS, FIRE, PokemonCard, STAGE1, WATER)

CARD = PokemonCard(
    card_id=351,
    name='Rapidash',
    hp=110,
    energy_type=FIRE,
    stage=STAGE1,
    evolves_from='Ponyta',
    weakness=WATER,
    retreat_cost=1,
    abilities=(
        Ability(
            name='Hurried Gait',
            text='Once during your turn, you may draw a card.',
        ),
    ),
    attacks=(
        Attack(
            attack_id=487,
            name='Fire Mane',
            cost=(FIRE, COLORLESS),
            damage=60,
        ),
    ),
)
