"""Relicanth (card 57). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, BASIC, COLORLESS, Clause, FIGHTING, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=57,
    name='Relicanth',
    hp=100,
    energy_type=FIGHTING,
    stage=BASIC,
    weakness=GRASS,
    retreat_cost=1,
    default_roles=('backup_attacker', 'support_pokemon'),
    covers='full',
    abilities=(
        Ability(
            name='Memory Dive',
            text='Each of your evolved Pokémon can use any attack from its previous Evolutions. (You still need the necessary Energy to use each attack.)',
            clauses=(Clause('grant_prevo_attacks', applies_to='own_evolved'),),
        ),
    ),
    attacks=(
        Attack(
            attack_id=61,
            name='Razor Fin',
            cost=(FIGHTING, COLORLESS),
            damage=30,
        ),
    ),
)
