"""Riolu (card 677). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, Clause, FIGHTING, PSYCHIC, PokemonCard)

CARD = PokemonCard(
    card_id=677,
    name='Riolu',
    hp=80,
    energy_type=FIGHTING,
    stage=BASIC,
    weakness=PSYCHIC,
    retreat_cost=2,
    default_roles=('primary_attacker',),
    attacks=(
        Attack(
            attack_id=981,
            name='Accelerating Stab',
            cost=(FIGHTING,),
            damage=30,
            text='During your next turn, this Pokémon can’t use Accelerating Stab.',
            clauses=(Clause('same_attack_lock', duration='next_turn'),),
        ),
    ),
)
