"""Riolu (card 333). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, Clause, FIGHTING, PSYCHIC, PokemonCard)

CARD = PokemonCard(
    card_id=333,
    name='Riolu',
    hp=70,
    energy_type=FIGHTING,
    stage=BASIC,
    weakness=PSYCHIC,
    retreat_cost=1,
    tags=frozenset([]),
    default_roles=('primary_attacker',),
    attacks=(
        Attack(
            attack_id=464,
            name='Quick Attack',
            cost=(FIGHTING,),
            damage=10,
            text='Flip a coin. If heads, this attack does 20 more damage.',
            clauses=(Clause('coin', effect='damage_boost', amount=20),),
        ),
    ),
)
