"""Rockruff (card 286). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, FIGHTING, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=286,
    name='Rockruff',
    hp=70,
    energy_type=FIGHTING,
    stage=BASIC,
    weakness=GRASS,
    retreat_cost=1,
    attacks=(
        Attack(
            attack_id=393,
            name='Dig It Up',
            cost=(COLORLESS,),
            damage=0,
            text='Look at the top card of your deck. You may discard that card.',
        ),
        Attack(
            attack_id=394,
            name='Stampede',
            cost=(COLORLESS, COLORLESS),
            damage=20,
        ),
    ),
)
