"""Salazzle ex (card 1026). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, FIRE, PokemonCard, STAGE1, WATER)

CARD = PokemonCard(
    card_id=1026,
    name='Salazzle ex',
    hp=260,
    energy_type=FIRE,
    stage=STAGE1,
    evolves_from='Salandit',
    ex=True,
    weakness=WATER,
    retreat_cost=1,
    attacks=(
        Attack(
            attack_id=1480,
            name='Nasty Plot',
            cost=(FIRE,),
            damage=0,
            text='Search your deck for up to 2 cards and put them into your hand. Then, shuffle your deck.',
        ),
        Attack(
            attack_id=1481,
            name='Dire Nails',
            cost=(FIRE, FIRE),
            damage=100,
            text='Your opponent’s Active Pokémon is now Burned and Poisoned. Switch this Pokémon with 1 of your Benched Pokémon.',
        ),
    ),
)
