"""Samurott (card 576). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, LIGHTNING, PokemonCard, STAGE2, WATER)

CARD = PokemonCard(
    card_id=576,
    name='Samurott',
    hp=160,
    energy_type=WATER,
    stage=STAGE2,
    evolves_from='Dewott',
    weakness=LIGHTNING,
    retreat_cost=2,
    abilities=(
        Ability(
            name='Torrential Whirlpool',
            text='Once during your turn, you may switch your Active Pokémon with 1 of your Benched Pokémon. If you do, switch out your opponent’s Active Pokémon to the Bench.\xa0(Your opponent chooses the new Active Pokémon.)',
        ),
    ),
    attacks=(
        Attack(
            attack_id=823,
            name='Energized Slash',
            cost=(WATER,),
            damage=30,
            text='This attack does 50 more damage for each Energy attached to this Pokémon.',
        ),
    ),
)
