"""Scraggy (card 895). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, DARKNESS, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=895,
    name='Scraggy',
    hp=80,
    energy_type=DARKNESS,
    stage=BASIC,
    weakness=GRASS,
    retreat_cost=2,
    tags=frozenset(['hand_disruption']),
    attacks=(
        Attack(
            attack_id=1292,
            name='Knock Off',
            cost=(DARKNESS, COLORLESS),
            damage=20,
            text='Discard a random card from your opponent’s hand.',
        ),
    ),
)
