"""Seaking (card 240). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, COLORLESS, Clause, LIGHTNING, PokemonCard, STAGE1, WATER)

CARD = PokemonCard(
    card_id=240,
    name='Seaking',
    hp=110,
    energy_type=WATER,
    stage=STAGE1,
    evolves_from='Goldeen',
    weakness=LIGHTNING,
    retreat_cost=1,
    tags=frozenset([]),
    default_roles=('backup_attacker',),
    abilities=(
        Ability(
            name='Festival Lead',
            text='If Festival Grounds is in play, this Pokémon may use an attack it has twice. If the first attack Knocks Out your opponent’s Active Pokémon, you may attack again after your opponent chooses a new Active Pokémon.',
            clauses=(Clause('attack_twice', condition='festival_grounds_in_play'),),
        ),
    ),
    attacks=(
        Attack(
            attack_id=330,
            name='Rapid Draw',
            cost=(COLORLESS,),
            damage=60,
            text='Draw 2 cards.',
            clauses=(Clause('draw', amount=2),),
        ),
    ),
)
