"""Servine (card 480). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, FIRE, GRASS, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=480,
    name='Servine',
    hp=100,
    energy_type=GRASS,
    stage=STAGE1,
    evolves_from='Snivy',
    weakness=FIRE,
    retreat_cost=1,
    tags=frozenset([]),
    attacks=(
        Attack(
            attack_id=678,
            name='Wrap',
            cost=(GRASS,),
            damage=20,
            text='コインを1回投げオモテなら、相手のバトルポケモンを【マヒ】にする。',
            damage_min=20,
            damage_max=20,
        ),
        Attack(
            attack_id=679,
            name='Vine Whip',
            cost=(GRASS, COLORLESS, COLORLESS),
            damage=60,
        ),
    ),
)
