"""Shaymin (card 343). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, BASIC, COLORLESS, Clause, FIRE, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=343,
    name='Shaymin',
    hp=80,
    energy_type=GRASS,
    stage=BASIC,
    weakness=FIRE,
    retreat_cost=1,
    tags=frozenset([]),
    default_roles=('support_pokemon',),
    covers='full',
    abilities=(
        Ability(
            name='Flower Curtain',
            text='Prevent all damage done to your Benched Pokémon that don’t have a Rule Box by attacks from your opponent’s Pokémon. (Pokémon {ex}, Pokémon {V}, etc. have Rule Boxes.)',
            clauses=(Clause('prevent_damage', applies_to='own_bench', no_rule_box=True, source='opponent_attack'),),
        ),
    ),
    attacks=(
        Attack(
            attack_id=477,
            name='Smash Kick',
            cost=(COLORLESS, COLORLESS),
            damage=30,
        ),
    ),
)
