"""Shaymin (card 1013). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, Clause, FIRE, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=1013,
    name='Shaymin',
    hp=70,
    energy_type=GRASS,
    stage=BASIC,
    weakness=FIRE,
    retreat_cost=0,
    default_roles=('support_pokemon',),
    attacks=(
        Attack(
            attack_id=1463,
            name='Send Flowers',
            cost=(GRASS,),
            damage=0,
            text='Search your deck for an Energy card and attach it to 1 of your Benched {G} Pokémon. Then, shuffle your deck.',
            clauses=(Clause('accel', amount=1, zone='deck', target='bench_only', target_type=1),),
        ),
        Attack(
            attack_id=1464,
            name='Leaf Step',
            cost=(GRASS,),
            damage=30,
        ),
    ),
)
