"""Shiftry (card 658). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, FIRE, GRASS, PokemonCard, STAGE2)

CARD = PokemonCard(
    card_id=658,
    name='Shiftry',
    hp=160,
    energy_type=GRASS,
    stage=STAGE2,
    evolves_from='Nuzleaf',
    weakness=FIRE,
    retreat_cost=2,
    attacks=(
        Attack(
            attack_id=951,
            name='Reversing Gust',
            cost=(GRASS,),
            damage=0,
            text='Flip a coin. If heads, choose 1 of your opponent’s Pokémon. Shuffle that Pokémon and all attached cards into their deck.',
            damage_min=0,
            damage_max=0,
        ),
        Attack(
            attack_id=952,
            name='Perplex',
            cost=(GRASS, COLORLESS),
            damage=100,
            text='Your opponent’s Active Pokémon is now Confused.',
        ),
    ),
)
