"""Shinx (card 1035). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, FIGHTING, LIGHTNING, PokemonCard)

CARD = PokemonCard(
    card_id=1035,
    name='Shinx',
    hp=70,
    energy_type=LIGHTNING,
    stage=BASIC,
    weakness=FIGHTING,
    retreat_cost=1,
    attacks=(
        Attack(
            attack_id=1493,
            name='Double Scratch',
            cost=(LIGHTNING,),
            damage=0,
            text='Flip 2 coins. This attack does 10 damage for each heads.',
            damage_min=0,
            damage_max=20,
        ),
    ),
)
