"""Shroodle (card 692). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, DARKNESS, FIGHTING, PokemonCard)

CARD = PokemonCard(
    card_id=692,
    name='Shroodle',
    hp=60,
    energy_type=DARKNESS,
    stage=BASIC,
    weakness=FIGHTING,
    retreat_cost=1,
    attacks=(
        Attack(
            attack_id=1002,
            name='Poison Jab',
            cost=(DARKNESS, COLORLESS),
            damage=20,
            text='Your opponent’s Active Pokémon is now Poisoned.',
        ),
    ),
)
