"""Sinistcha (card 94). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, FIRE, GRASS, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=94,
    name='Sinistcha',
    hp=70,
    energy_type=GRASS,
    stage=STAGE1,
    evolves_from='Poltchageist',
    weakness=FIRE,
    retreat_cost=1,
    attacks=(
        Attack(
            attack_id=116,
            name='Cursed Drop',
            cost=(GRASS,),
            damage=0,
            text='Put 4 damage counters on your opponent’s Pokémon in any way you like.',
        ),
        Attack(
            attack_id=117,
            name='Spill the Tea',
            cost=(GRASS,),
            damage=0,
            text='Discard up to 3 {G} Energy cards from your Pokémon. This attack does 70 damage for each card you discarded in this way.',
        ),
    ),
)
