"""Sizzlipede (card 717). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, FIRE, PokemonCard, WATER)

CARD = PokemonCard(
    card_id=717,
    name='Sizzlipede',
    hp=80,
    energy_type=FIRE,
    stage=BASIC,
    weakness=WATER,
    retreat_cost=2,
    default_roles=('backup_attacker',),
    attacks=(
        Attack(
            attack_id=1035,
            name='Ram',
            cost=(FIRE,),
            damage=10,
        ),
        Attack(
            attack_id=1036,
            name='Combustion',
            cost=(FIRE, FIRE, COLORLESS),
            damage=50,
        ),
    ),
)
