"""Skeledirge (card 203). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, COLORLESS, FIRE, PokemonCard, STAGE2, WATER)

CARD = PokemonCard(
    card_id=203,
    name='Skeledirge',
    hp=180,
    energy_type=FIRE,
    stage=STAGE2,
    evolves_from='Crocalor',
    weakness=WATER,
    retreat_cost=3,
    abilities=(
        Ability(
            name='Unaware',
            text='Prevent all effects of attacks used by your opponent’s Pokémon done to this Pokémon. (Damage is not an effect.)',
        ),
    ),
    attacks=(
        Attack(
            attack_id=274,
            name='Torcherto',
            cost=(FIRE, COLORLESS),
            damage=60,
            text='This attack does 20 more damage for each Benched Pokémon (both yours and your opponent’s).',
            scale_var='both_bench',
            scale_per_unit=20,
        ),
    ),
)
