"""Skorupi (card 1060). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, DARKNESS, FIGHTING, PokemonCard)

CARD = PokemonCard(
    card_id=1060,
    name='Skorupi',
    hp=80,
    energy_type=DARKNESS,
    stage=BASIC,
    weakness=FIGHTING,
    retreat_cost=2,
    attacks=(
        Attack(
            attack_id=1530,
            name='Poison Jab',
            cost=(DARKNESS, DARKNESS),
            damage=20,
            text='Your opponent’s Active Pokémon is now Poisoned.',
        ),
    ),
)
