"""Slowpoke (card 162). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, Clause, DARKNESS, FIGHTING, PSYCHIC, PokemonCard)

CARD = PokemonCard(
    card_id=162,
    name='Slowpoke',
    hp=80,
    energy_type=PSYCHIC,
    stage=BASIC,
    weakness=DARKNESS,
    resistance=FIGHTING,
    retreat_cost=2,
    default_roles=('primary_attacker',),
    attacks=(
        Attack(
            attack_id=211,
            name='Dangle Tail',
            cost=(COLORLESS,),
            damage=0,
            text='Put a Pokémon from your discard pile into your hand.',
            clauses=(Clause('fetch', target='pokemon', zone='discard'),),
        ),
        Attack(
            attack_id=212,
            name='Tackle',
            cost=(PSYCHIC, COLORLESS),
            damage=30,
        ),
    ),
)
