"""Slowpoke (card 327). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, LIGHTNING, PokemonCard, WATER)

CARD = PokemonCard(
    card_id=327,
    name='Slowpoke',
    hp=70,
    energy_type=WATER,
    stage=BASIC,
    weakness=LIGHTNING,
    retreat_cost=2,
    tags=frozenset([]),
    default_roles=('primary_attacker',),
    attacks=(
        Attack(
            attack_id=454,
            name='Water Gun',
            cost=(WATER,),
            damage=10,
        ),
        Attack(
            attack_id=455,
            name='Tail Whap',
            cost=(WATER, COLORLESS),
            damage=30,
        ),
    ),
)
