"""Slurpuff (card 110). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, METAL, PSYCHIC, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=110,
    name='Slurpuff',
    hp=120,
    energy_type=PSYCHIC,
    stage=STAGE1,
    evolves_from='Swirlix',
    weakness=METAL,
    retreat_cost=2,
    tags=frozenset(['confuse']),
    attacks=(
        Attack(
            attack_id=138,
            name='Slurp Slurp',
            cost=(PSYCHIC, COLORLESS),
            damage=0,
            text='Flip 2 coins. This attack does 90 damage for each heads. If both of them are tails, your opponent’s Active Pokémon is now Confused.',
            damage_min=0,
            damage_max=180,
        ),
    ),
)
