"""Snorunt (card 103). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, Clause, METAL, PokemonCard, WATER)

CARD = PokemonCard(
    card_id=103,
    name='Snorunt',
    hp=60,
    energy_type=WATER,
    stage=BASIC,
    weakness=METAL,
    retreat_cost=1,
    tags=frozenset(['hand_disruption']),
    default_roles=('backup_attacker', 'primary_attacker'),
    attacks=(
        Attack(
            attack_id=130,
            name='Astonish',
            cost=(WATER, COLORLESS),
            damage=20,
            text='Choose a random card from your opponent’s hand. Your opponent reveals that card and shuffles it into their deck.',
            clauses=(Clause('opp_hand_to_deck', amount=1, random=True),),
        ),
    ),
)
