"""Snover (card 418). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, METAL, PokemonCard, WATER)

CARD = PokemonCard(
    card_id=418,
    name='Snover',
    hp=90,
    energy_type=WATER,
    stage=BASIC,
    weakness=METAL,
    retreat_cost=3,
    tags=frozenset([]),
    default_roles=('primary_attacker',),
    attacks=(
        Attack(
            attack_id=587,
            name='Light Punch',
            cost=(COLORLESS, COLORLESS),
            damage=20,
        ),
        Attack(
            attack_id=588,
            name='Icicle',
            cost=(WATER, COLORLESS, COLORLESS),
            damage=50,
        ),
    ),
)
