"""Solrock (card 676). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, Clause, FIGHTING, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=676,
    name='Solrock',
    hp=110,
    energy_type=FIGHTING,
    stage=BASIC,
    weakness=GRASS,
    retreat_cost=1,
    default_roles=('backup_attacker',),
    covers='full',
    synergy=('Lunatone',),
    attacks=(
        Attack(
            attack_id=980,
            name='Cosmic Beam',
            cost=(FIGHTING,),
            damage=70,
            text='If you don’t have Lunatone on your Bench, this attack does nothing. This attack’s damage isn’t affected by Weakness or Resistance.',
            clauses=(Clause('requires_bench', name='Lunatone'), Clause('ignores_wr')),
        ),
    ),
)
