"""Spewpa (card 1018). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, FIRE, GRASS, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=1018,
    name='Spewpa',
    hp=80,
    energy_type=GRASS,
    stage=STAGE1,
    evolves_from='Scatterbug',
    weakness=FIRE,
    retreat_cost=3,
    tags=frozenset([]),
    attacks=(
        Attack(
            attack_id=1470,
            name='Hide',
            cost=(GRASS,),
            damage=0,
            text='Flip a coin. If heads, during your opponent’s next turn, prevent all damage from and effects of attacks done to this Pokémon.',
            damage_min=0,
            damage_max=0,
        ),
    ),
)
