"""Spoink (card 749). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, DARKNESS, FIGHTING, PSYCHIC, PokemonCard)

CARD = PokemonCard(
    card_id=749,
    name='Spoink',
    hp=70,
    energy_type=PSYCHIC,
    stage=BASIC,
    weakness=DARKNESS,
    resistance=FIGHTING,
    retreat_cost=1,
    attacks=(
        Attack(
            attack_id=1081,
            name='Triple Spin',
            cost=(PSYCHIC,),
            damage=0,
            text='Flip 3 coins. This attack does 10 damage for each heads.',
            damage_min=0,
            damage_max=30,
        ),
    ),
)
