"""Swablu (card 197). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, FIGHTING, LIGHTNING, PokemonCard)

CARD = PokemonCard(
    card_id=197,
    name='Swablu',
    hp=50,
    energy_type=COLORLESS,
    stage=BASIC,
    weakness=LIGHTNING,
    resistance=FIGHTING,
    retreat_cost=1,
    attacks=(
        Attack(
            attack_id=266,
            name='Disarming Voice',
            cost=(COLORLESS,),
            damage=10,
            text='Your opponent’s Active Pokémon is now Confused.',
        ),
    ),
)
