"""Sylveon (card 134). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, Clause, METAL, PSYCHIC, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=134,
    name='Sylveon',
    hp=120,
    energy_type=PSYCHIC,
    stage=STAGE1,
    evolves_from='Eevee',
    weakness=METAL,
    retreat_cost=1,
    default_roles=('backup_attacker',),
    attacks=(
        Attack(
            attack_id=173,
            name='Mystical Return',
            cost=(PSYCHIC,),
            damage=0,
            text='Flip a coin. If heads, choose 1 of your opponent’s Benched Pokémon. Shuffle that Pokémon and all attached cards into their deck.',
            clauses=(Clause('coin', effect='shuffle_into_deck', target='opp_bench', amount=1, rider='attached_cards_too'),),
            damage_min=0,
            damage_max=0,
        ),
        Attack(
            attack_id=174,
            name='Disarming Voice',
            cost=(PSYCHIC, COLORLESS, COLORLESS),
            damage=90,
            text='Your opponent’s Active Pokémon is now Confused.',
            clauses=(Clause('confuse', target='opp_active'),),
        ),
    ),
)
