"""Talonflame (card 1024). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, FIGHTING, FIRE, LIGHTNING, PokemonCard, STAGE2)

CARD = PokemonCard(
    card_id=1024,
    name='Talonflame',
    hp=150,
    energy_type=FIRE,
    stage=STAGE2,
    evolves_from='Fletchinder',
    weakness=LIGHTNING,
    resistance=FIGHTING,
    retreat_cost=1,
    tags=frozenset(['hand_disruption']),
    abilities=(
        Ability(
            name='Sky Hunt',
            text='Once during your turn, you may use this Ability. Flip a coin. If heads, discard a random card from your opponent’s hand.',
        ),
    ),
    attacks=(
        Attack(
            attack_id=1478,
            name='Fire Wing',
            cost=(FIRE, FIRE),
            damage=110,
        ),
    ),
)
