"""Tatsugiri (card 122). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, BASIC, DRAGON, FIRE, PokemonCard, WATER)

CARD = PokemonCard(
    card_id=122,
    name='Tatsugiri',
    hp=70,
    energy_type=DRAGON,
    stage=BASIC,
    retreat_cost=1,
    tags=frozenset(['dig']),
    abilities=(
        Ability(
            name='Attract Customers',
            text='Once during your turn, if this Pokémon is in the Active Spot, you may look at the top 6 cards of your deck, reveal a Supporter card you find there, and put it into your hand. Shuffle the other cards back into your deck.',
        ),
    ),
    attacks=(
        Attack(
            attack_id=155,
            name='Surf',
            cost=(FIRE, WATER),
            damage=50,
        ),
    ),
)
