"""Teal Mask Ogerpon (card 349). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, Clause, FIRE, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=349,
    name='Teal Mask Ogerpon',
    hp=110,
    energy_type=GRASS,
    stage=BASIC,
    weakness=FIRE,
    retreat_cost=1,
    default_roles=('support_pokemon', 'accel_source'),
    attacks=(
        Attack(
            attack_id=484,
            name='Grass Kagura',
            cost=(COLORLESS,),
            damage=0,
            text='Search your deck for a Basic {G} Energy card and attach it to 1 of your Pokémon. Then, shuffle your deck.',
            clauses=(Clause('accel', amount=1, zone='deck', energy='basic', energy_type=GRASS, target='any_pokemon'),),
        ),
        Attack(
            attack_id=485,
            name='Ogre’s Hammer',
            cost=(GRASS, GRASS, COLORLESS),
            damage=120,
            text='During your next turn, this Pokémon can’t use Ogre’s Hammer.',
            clauses=(Clause('same_attack_lock', duration='next_turn'),),
        ),
    ),
)
