"""Teal Mask Ogerpon ex (card 96). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, BASIC, Clause, FIRE, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=96,
    name='Teal Mask Ogerpon ex',
    hp=210,
    energy_type=GRASS,
    stage=BASIC,
    ex=True,
    tera=True,
    weakness=FIRE,
    retreat_cost=1,
    tags=frozenset(['draw', 'energy_accel']),
    default_roles=('primary_attacker', 'disruption_target'),
    abilities=(
        Ability(
            name='Teal Dance',
            text='Once during your turn, you may attach a Basic {G} Energy card from your hand to this Pokémon.\xa0If you attached Energy to a Pokémon in this way, draw a card.',
            clauses=(Clause('accel', amount=1, source='hand', target='self', energy='basic', energy_type=GRASS, allowance='body', rider='draw_1'),),
        ),
    ),
    attacks=(
        Attack(
            attack_id=120,
            name='Myriad Leaf Shower',
            cost=(GRASS, GRASS, GRASS),
            damage=30,
            text='This attack does 30 more damage for each Energy attached to both Active Pokémon.',
            clauses=(Clause('damage_boost', amount=30, per='energy_on_both_actives'),),
        ),
    ),
)
