"""Teal Mask Ogerpon (card 95). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, Clause, FIRE, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=95,
    name='Teal Mask Ogerpon',
    hp=110,
    energy_type=GRASS,
    stage=BASIC,
    weakness=FIRE,
    retreat_cost=1,
    default_roles=('support_pokemon', 'accel_source'),
    attacks=(
        Attack(
            attack_id=118,
            name='Mountain Stroll',
            cost=(COLORLESS,),
            damage=0,
            text='Search your deck for up to 2 Basic Energy cards, reveal them, and put them into your hand. Then, shuffle your deck.',
            clauses=(Clause('fetch', target='basic_energy', zone='deck', amount=2),),
        ),
        Attack(
            attack_id=119,
            name='Ogre Comeback',
            cost=(GRASS, COLORLESS),
            damage=20,
            text='This attack does 20 more damage for each of your opponent’s Benched Pokémon.',
            clauses=(Clause('damage_boost', amount=20, per='opp_bench'),),
        ),
    ),
)
