"""Team Rocket's Weezing (card 462). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, DARKNESS, FIGHTING, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=462,
    name="Team Rocket's Weezing",
    hp=130,
    energy_type=DARKNESS,
    stage=STAGE1,
    evolves_from="Team Rocket's Koffing",
    weakness=FIGHTING,
    retreat_cost=2,
    tags=frozenset(['team_rocket']),
    attacks=(
        Attack(
            attack_id=651,
            name='Explode Together Now',
            cost=(DARKNESS, COLORLESS),
            damage=0,
            text='This attack does 40 damage for each Pokémon in play that has “Koffing” or “Weezing” in its name\xa0(both yours and your opponent’s).',
            scale_var='both_in_play_named',
            scale_per_unit=40,
            scale_filter=('Koffing', 'Weezing'),
        ),
    ),
)
