"""Team Rocket's Honchkrow (card 891). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, DARKNESS, FIGHTING, LIGHTNING, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=891,
    name="Team Rocket's Honchkrow",
    hp=130,
    energy_type=DARKNESS,
    stage=STAGE1,
    evolves_from="Team Rocket's Murkrow",
    weakness=LIGHTNING,
    resistance=FIGHTING,
    retreat_cost=1,
    tags=frozenset(['team_rocket']),
    attacks=(
        Attack(
            attack_id=1285,
            name='Rocket Feathers',
            cost=(COLORLESS, COLORLESS),
            damage=0,
            text='You may discard any number of Supporter cards that have “Team Rocket” in their name from your hand, and this attack does 60 damage for each card you discarded in this way.',
        ),
        Attack(
            attack_id=1286,
            name='Hammer In',
            cost=(DARKNESS, COLORLESS, COLORLESS),
            damage=100,
        ),
    ),
)
