"""Team Rocket's Moltres ex (card 407). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, FIGHTING, FIRE, LIGHTNING, PokemonCard)

CARD = PokemonCard(
    card_id=407,
    name="Team Rocket's Moltres ex",
    hp=220,
    energy_type=FIRE,
    stage=BASIC,
    ex=True,
    weakness=LIGHTNING,
    resistance=FIGHTING,
    retreat_cost=2,
    attacks=(
        Attack(
            attack_id=570,
            name='Flame Screen',
            cost=(FIRE, COLORLESS, COLORLESS),
            damage=110,
            text='During your opponent’s next turn, this Pokémon takes 50 less damage from attacks (after applying Weakness and Resistance).',
        ),
        Attack(
            attack_id=571,
            name='Evil Incineration',
            cost=(FIRE, COLORLESS, COLORLESS, COLORLESS),
            damage=0,
            text='Discard a Team Rocket’s Energy from this Pokémon. If you do, discard your opponent’s Active Pokémon and all attached cards.',
        ),
    ),
)
