"""Team Rocket's Houndour (card 408). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, FIRE, PokemonCard, WATER)

CARD = PokemonCard(
    card_id=408,
    name="Team Rocket's Houndour",
    hp=70,
    energy_type=FIRE,
    stage=BASIC,
    weakness=WATER,
    retreat_cost=1,
    attacks=(
        Attack(
            attack_id=572,
            name='Steady Firebreathing',
            cost=(FIRE,),
            damage=20,
        ),
    ),
)
