"""Team Rocket's Larvitar (card 440). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, FIGHTING, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=440,
    name="Team Rocket's Larvitar",
    hp=70,
    energy_type=FIGHTING,
    stage=BASIC,
    weakness=GRASS,
    retreat_cost=1,
    tags=frozenset(['team_rocket']),
    attacks=(
        Attack(
            attack_id=619,
            name='Mountain Munch',
            cost=(COLORLESS,),
            damage=10,
            text='Discard the top card of your opponent’s deck.',
        ),
    ),
)
