"""Team Rocket's Zubat (card 456). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, DARKNESS, FIGHTING, LIGHTNING, PokemonCard)

CARD = PokemonCard(
    card_id=456,
    name="Team Rocket's Zubat",
    hp=50,
    energy_type=DARKNESS,
    stage=BASIC,
    weakness=LIGHTNING,
    resistance=FIGHTING,
    retreat_cost=1,
    tags=frozenset(['poison', 'team_rocket']),
    attacks=(
        Attack(
            attack_id=644,
            name='Poison Spray',
            cost=(DARKNESS,),
            damage=0,
            text='Your opponent’s Active Pokémon is now Poisoned.',
        ),
    ),
)
