"""Team Rocket's Sneasel (card 464). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, DARKNESS, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=464,
    name="Team Rocket's Sneasel",
    hp=80,
    energy_type=DARKNESS,
    stage=BASIC,
    weakness=GRASS,
    retreat_cost=1,
    attacks=(
        Attack(
            attack_id=654,
            name='Scratch',
            cost=(DARKNESS,),
            damage=20,
        ),
        Attack(
            attack_id=655,
            name='Strike the Sleeper',
            cost=(DARKNESS, DARKNESS),
            damage=0,
            text='This attack does 20 damage to 1 of your opponent’s Benched Pokémon for each damage counter on that Pokémon. (Don’t apply Weakness and Resistance for Benched Pokémon.)',
        ),
    ),
)
