"""Team Rocket's Porygon (card 473). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, FIGHTING, PokemonCard)

CARD = PokemonCard(
    card_id=473,
    name="Team Rocket's Porygon",
    hp=60,
    energy_type=COLORLESS,
    stage=BASIC,
    weakness=FIGHTING,
    retreat_cost=1,
    attacks=(
        Attack(
            attack_id=669,
            name='Hacking',
            cost=(COLORLESS,),
            damage=0,
            text='Discard a card from your hand. If you do, your opponent discards a card from their hand.',
        ),
    ),
)
