"""Team Rocket's Tarountula (card 400). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, FIRE, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=400,
    name="Team Rocket's Tarountula",
    hp=50,
    energy_type=GRASS,
    stage=BASIC,
    weakness=FIRE,
    retreat_cost=1,
    attacks=(
        Attack(
            attack_id=559,
            name='Take Down',
            cost=(GRASS,),
            damage=30,
            text='This Pokémon also does 10 damage to itself.',
        ),
    ),
)
