"""Team Rocket's Orbeetle (card 436). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, COLORLESS, DARKNESS, FIGHTING, PSYCHIC, PokemonCard, STAGE2)

CARD = PokemonCard(
    card_id=436,
    name="Team Rocket's Orbeetle",
    hp=130,
    energy_type=PSYCHIC,
    stage=STAGE2,
    evolves_from="Team Rocket's Dottler",
    weakness=DARKNESS,
    resistance=FIGHTING,
    retreat_cost=2,
    abilities=(
        Ability(
            name='Rocket Brain',
            text='As often as you like during your turn, you may move 1 damage counter from 1 of your Team Rocket’s Pokémon to another of your Pokémon.',
        ),
    ),
    attacks=(
        Attack(
            attack_id=615,
            name='Psychic',
            cost=(PSYCHIC, COLORLESS, COLORLESS),
            damage=40,
            text='This attack does 40 more damage for each Energy attached to your opponent’s Active Pokémon.',
        ),
    ),
)
