"""Team Rocket's Nidoqueen (card 452). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, DARKNESS, FIGHTING, PokemonCard, STAGE2)

CARD = PokemonCard(
    card_id=452,
    name="Team Rocket's Nidoqueen",
    hp=170,
    energy_type=DARKNESS,
    stage=STAGE2,
    evolves_from="Team Rocket's Nidorina",
    weakness=FIGHTING,
    retreat_cost=3,
    attacks=(
        Attack(
            attack_id=636,
            name='Love Impact',
            cost=(DARKNESS,),
            damage=60,
            text='If a Pokémon that has "Nidoking" in its name is on your Bench, this attack does 120 more damage.',
        ),
        Attack(
            attack_id=637,
            name='Mega Kick',
            cost=(DARKNESS, DARKNESS),
            damage=130,
        ),
    ),
)
