"""Team Rocket's Persian ex (card 471). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, FIGHTING, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=471,
    name="Team Rocket's Persian ex",
    hp=260,
    energy_type=COLORLESS,
    stage=STAGE1,
    evolves_from="Team Rocket's Meowth",
    ex=True,
    weakness=FIGHTING,
    retreat_cost=2,
    tags=frozenset(['confuse', 'team_rocket']),
    attacks=(
        Attack(
            attack_id=665,
            name='Haughty Order',
            cost=(COLORLESS, COLORLESS),
            damage=0,
            text='Reveal the top 10 cards of your opponent’s deck. You may choose an attack from a Pokémon you find there and use it as this attack. Shuffle the revealed cards into your opponent’s deck.',
        ),
        Attack(
            attack_id=666,
            name='Cruel Slash',
            cost=(COLORLESS, COLORLESS, COLORLESS),
            damage=140,
            text='Your opponent’s Active Pokémon is now Confused.',
        ),
    ),
)
