"""Team Rocket's Wobbuffet (card 432). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, DARKNESS, FIGHTING, PSYCHIC, PokemonCard)

CARD = PokemonCard(
    card_id=432,
    name="Team Rocket's Wobbuffet",
    hp=110,
    energy_type=PSYCHIC,
    stage=BASIC,
    weakness=DARKNESS,
    resistance=FIGHTING,
    retreat_cost=2,
    attacks=(
        Attack(
            attack_id=609,
            name='Rocket Mirror',
            cost=(PSYCHIC, COLORLESS),
            damage=0,
            text='Move all damage counters from 1 of your Benched Team Rocket’s Pokémon to your opponent’s Active Pokémon.',
        ),
        Attack(
            attack_id=610,
            name='Headbutt Bounce',
            cost=(PSYCHIC, COLORLESS, COLORLESS),
            damage=70,
        ),
    ),
)
