"""Team Rocket's Nidoking ex (card 455). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, DARKNESS, FIGHTING, PokemonCard, STAGE2)

CARD = PokemonCard(
    card_id=455,
    name="Team Rocket's Nidoking ex",
    hp=330,
    energy_type=DARKNESS,
    stage=STAGE2,
    evolves_from="Team Rocket's Nidorino",
    ex=True,
    weakness=FIGHTING,
    retreat_cost=3,
    tags=frozenset(['team_rocket']),
    attacks=(
        Attack(
            attack_id=642,
            name='Tainted Horn',
            cost=(DARKNESS, DARKNESS, COLORLESS),
            damage=100,
            text='Your opponent’s Active Pokémon is now Poisoned. During Pokémon Checkup, put 8 damage counters on that Pokémon instead of 1.',
        ),
        Attack(
            attack_id=643,
            name='Kingly Impact',
            cost=(DARKNESS, DARKNESS, DARKNESS, COLORLESS),
            damage=240,
        ),
    ),
)
