"""Team Rocket's Grimer (card 459). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, DARKNESS, FIGHTING, PokemonCard)

CARD = PokemonCard(
    card_id=459,
    name="Team Rocket's Grimer",
    hp=80,
    energy_type=DARKNESS,
    stage=BASIC,
    weakness=FIGHTING,
    retreat_cost=3,
    attacks=(
        Attack(
            attack_id=647,
            name='Corrosive Sludge',
            cost=(DARKNESS, COLORLESS),
            damage=0,
            text='At the end of your opponent’s next turn, discard the Defending Pokémon and all attached cards.',
        ),
    ),
)
