"""Team Rocket's Koffing (card 461). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, BASIC, COLORLESS, DARKNESS, FIGHTING, PokemonCard)

CARD = PokemonCard(
    card_id=461,
    name="Team Rocket's Koffing",
    hp=70,
    energy_type=DARKNESS,
    stage=BASIC,
    weakness=FIGHTING,
    retreat_cost=1,
    tags=frozenset(['team_rocket']),
    abilities=(
        Ability(
            name='Smog Signals',
            text='If this Pokémon is in the Active Spot and is damaged by an attack from your opponent’s Pokémon (even if this Pokémon is Knocked Out), search your deck for up to 2 Pokémon that have “Koffing” in their name and put them onto your Bench. Then, shuffle your deck.',
        ),
    ),
    attacks=(
        Attack(
            attack_id=650,
            name='Leaking Gas',
            cost=(DARKNESS, COLORLESS),
            damage=30,
        ),
    ),
)
