"""Team Rocket's Diglett (card 881). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, FIGHTING, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=881,
    name="Team Rocket's Diglett",
    hp=60,
    energy_type=FIGHTING,
    stage=BASIC,
    weakness=GRASS,
    retreat_cost=1,
    tags=frozenset(['team_rocket']),
    attacks=(
        Attack(
            attack_id=1271,
            name='Relentless Burrowing',
            cost=(FIGHTING,),
            damage=0,
            text='Flip a coin until you get tails. For each heads, discard the top card of your opponent’s deck.',
            damage_min=0,
            damage_max=0,
        ),
    ),
)
