"""Team Rocket's Kangaskhan ex (card 24). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, FIGHTING, PokemonCard)

CARD = PokemonCard(
    card_id=24,
    name="Team Rocket's Kangaskhan ex",
    hp=230,
    energy_type=COLORLESS,
    stage=BASIC,
    ex=True,
    weakness=FIGHTING,
    retreat_cost=2,
    attacks=(
        Attack(
            attack_id=6,
            name='Comet Punch',
            cost=(COLORLESS, COLORLESS),
            damage=0,
            text='Flip 4 coins. This attack does 30 damage for each heads.',
            damage_min=0,
            damage_max=120,
        ),
        Attack(
            attack_id=7,
            name='Wicked Impact',
            cost=(COLORLESS, COLORLESS, COLORLESS),
            damage=120,
            text='If you played a Supporter card that has “Team Rocket” in its name from your hand during this turn, this attack does 100 more damage.',
        ),
    ),
)
