"""Team Rocket's Dugtrio (card 882). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, COLORLESS, FIGHTING, GRASS, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=882,
    name="Team Rocket's Dugtrio",
    hp=100,
    energy_type=FIGHTING,
    stage=STAGE1,
    evolves_from="Team Rocket's Diglett",
    weakness=GRASS,
    retreat_cost=1,
    abilities=(
        Ability(
            name='Holes',
            text='Whenever your opponent’s Active Pokémon moves to the Bench during their turn, place 2 damage counters on that Pokémon.',
        ),
    ),
    attacks=(
        Attack(
            attack_id=1272,
            name='Mud Shot',
            cost=(FIGHTING, COLORLESS),
            damage=50,
        ),
    ),
)
