"""Team Rocket's Nidoran♂ (card 453). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, DARKNESS, FIGHTING, PokemonCard)

CARD = PokemonCard(
    card_id=453,
    name="Team Rocket's Nidoran♂",
    hp=70,
    energy_type=DARKNESS,
    stage=BASIC,
    weakness=FIGHTING,
    retreat_cost=1,
    tags=frozenset(['team_rocket']),
    attacks=(
        Attack(
            attack_id=638,
            name='Pierce',
            cost=(DARKNESS,),
            damage=10,
        ),
        Attack(
            attack_id=639,
            name='Hammer In',
            cost=(DARKNESS, COLORLESS),
            damage=30,
        ),
    ),
)
