"""Team Rocket's Flaaffy (card 427). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, FIGHTING, LIGHTNING, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=427,
    name="Team Rocket's Flaaffy",
    hp=90,
    energy_type=LIGHTNING,
    stage=STAGE1,
    evolves_from="Team Rocket's Mareep",
    weakness=FIGHTING,
    retreat_cost=2,
    tags=frozenset(['paralyze', 'team_rocket']),
    attacks=(
        Attack(
            attack_id=603,
            name='Thunder Shock',
            cost=(LIGHTNING, COLORLESS),
            damage=50,
            text='Flip a coin. If heads, your opponent’s Active Pokémon is now Paralyzed.',
            damage_min=50,
            damage_max=50,
        ),
    ),
)
