"""Team Rocket's Meowth (card 470). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, FIGHTING, PokemonCard)

CARD = PokemonCard(
    card_id=470,
    name="Team Rocket's Meowth",
    hp=70,
    energy_type=COLORLESS,
    stage=BASIC,
    weakness=FIGHTING,
    retreat_cost=1,
    tags=frozenset(['hand_disruption', 'team_rocket']),
    attacks=(
        Attack(
            attack_id=663,
            name='Paw-cket Pilfer',
            cost=(COLORLESS,),
            damage=0,
            text='Choose a random card from your opponent’s hand. Your opponent reveals that card and shuffles it into their deck.',
        ),
        Attack(
            attack_id=664,
            name='Fury Swipes',
            cost=(COLORLESS, COLORLESS),
            damage=0,
            text='Flip 3 coins. This attack does 20 damage for each heads.',
            damage_min=0,
            damage_max=60,
        ),
    ),
)
