"""Team Rocket's Spidops (card 401). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, COLORLESS, FIRE, GRASS, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=401,
    name="Team Rocket's Spidops",
    hp=130,
    energy_type=GRASS,
    stage=STAGE1,
    evolves_from="Team Rocket's Tarountula",
    weakness=FIRE,
    retreat_cost=2,
    abilities=(
        Ability(
            name='Charging Up',
            text='Once during your turn, you may attach a Basic Energy card from your discard pile to this Pokémon.',
        ),
    ),
    attacks=(
        Attack(
            attack_id=560,
            name='Rocket Rush',
            cost=(GRASS, COLORLESS),
            damage=0,
            text='This attack does 30 damage for each of your Team Rocket’s Pokémon in play.',
        ),
    ),
)
