"""Team Rocket's Nidoran♀ (card 450). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, DARKNESS, FIGHTING, PokemonCard)

CARD = PokemonCard(
    card_id=450,
    name="Team Rocket's Nidoran♀",
    hp=70,
    energy_type=DARKNESS,
    stage=BASIC,
    weakness=FIGHTING,
    retreat_cost=1,
    tags=frozenset(['team_rocket']),
    attacks=(
        Attack(
            attack_id=633,
            name='Surprise Attack',
            cost=(DARKNESS,),
            damage=30,
            text='Flip a coin. If tails, this attack does nothing.',
        ),
    ),
)
