"""Team Rocket's Raticate (card 469). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, FIGHTING, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=469,
    name="Team Rocket's Raticate",
    hp=90,
    energy_type=COLORLESS,
    stage=STAGE1,
    evolves_from="Team Rocket's Rattata",
    weakness=FIGHTING,
    retreat_cost=1,
    tags=frozenset(['team_rocket']),
    attacks=(
        Attack(
            attack_id=662,
            name='Reckless Abandon',
            cost=(COLORLESS,),
            damage=90,
            text='Flip 2 coins. If both of them are tails, this Pokémon also does 90 damage to itself.',
            damage_min=90,
            damage_max=90,
        ),
    ),
)
