"""Team Rocket's Houndoom (card 409). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, FIRE, PokemonCard, STAGE1, WATER)

CARD = PokemonCard(
    card_id=409,
    name="Team Rocket's Houndoom",
    hp=130,
    energy_type=FIRE,
    stage=STAGE1,
    evolves_from="Team Rocket's Houndour",
    weakness=WATER,
    retreat_cost=2,
    tags=frozenset(['team_rocket']),
    attacks=(
        Attack(
            attack_id=573,
            name='Cruel Coal',
            cost=(FIRE,),
            damage=0,
            text='Your opponent’s Active Pokémon is now Burned and Confused.',
        ),
        Attack(
            attack_id=574,
            name='Scorching Fire',
            cost=(FIRE, COLORLESS),
            damage=120,
            text='Discard an Energy from this Pokémon.',
        ),
    ),
)
