"""Team Rocket's Ekans (card 448). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, DARKNESS, FIGHTING, PokemonCard)

CARD = PokemonCard(
    card_id=448,
    name="Team Rocket's Ekans",
    hp=70,
    energy_type=DARKNESS,
    stage=BASIC,
    weakness=FIGHTING,
    retreat_cost=1,
    tags=frozenset(['paralyze', 'team_rocket']),
    attacks=(
        Attack(
            attack_id=630,
            name='Drag Down',
            cost=(COLORLESS,),
            damage=0,
            text='Flip a coin. If heads, your opponent’s Active Pokémon is now Paralyzed.',
            damage_min=0,
            damage_max=0,
        ),
        Attack(
            attack_id=631,
            name='Gnaw',
            cost=(DARKNESS,),
            damage=10,
        ),
    ),
)
