"""Team Rocket's Exeggcute (card 873). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, DARKNESS, FIGHTING, PSYCHIC, PokemonCard)

CARD = PokemonCard(
    card_id=873,
    name="Team Rocket's Exeggcute",
    hp=60,
    energy_type=PSYCHIC,
    stage=BASIC,
    weakness=DARKNESS,
    resistance=FIGHTING,
    retreat_cost=1,
    attacks=(
        Attack(
            attack_id=1259,
            name='Focused Wish',
            cost=(PSYCHIC,),
            damage=10,
            text='Flip a coin. If heads, this attack does 20 more damage.',
        ),
    ),
)
