"""Team Rocket's Articuno (card 414). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, BASIC, COLORLESS, Clause, FIGHTING, LIGHTNING, PokemonCard, WATER)

CARD = PokemonCard(
    card_id=414,
    name="Team Rocket's Articuno",
    hp=120,
    energy_type=WATER,
    stage=BASIC,
    weakness=LIGHTNING,
    resistance=FIGHTING,
    retreat_cost=1,
    tags=frozenset(['team_rocket']),
    default_roles=('support_pokemon',),
    abilities=(
        Ability(
            name='Repelling Veil',
            text='Prevent all effects of attacks used by your opponent’s Pokémon done to your Basic Team Rocket’s Pokémon. (Existing effects are not removed. Damage is not an effect.)',
            clauses=(Clause('prevent_effects', applies_to='own_basic', name_family="Team Rocket's", source='opponent_attack'),),
        ),
    ),
    attacks=(
        Attack(
            attack_id=583,
            name='Dark Frost',
            cost=(WATER, COLORLESS, COLORLESS),
            damage=60,
            text='If this Pokémon has any Team Rocket’s Energy attached, this attack does 60 more damage.',
            clauses=(Clause('damage_boost', amount=60, condition='team_rocket_energy_attached'),),
        ),
    ),
)
