"""Team Rocket's Ampharos (card 428). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, COLORLESS, FIGHTING, LIGHTNING, PokemonCard, STAGE2)

CARD = PokemonCard(
    card_id=428,
    name="Team Rocket's Ampharos",
    hp=140,
    energy_type=LIGHTNING,
    stage=STAGE2,
    evolves_from="Team Rocket's Flaaffy",
    weakness=FIGHTING,
    retreat_cost=2,
    tags=frozenset(['team_rocket']),
    abilities=(
        Ability(
            name='Darkest Impulse',
            text='Whenever your opponent plays a Pokémon from their hand to evolve 1 of their Pokémon, put 4 damage counters on that Pokémon. The effect of Darkest Impulse doesn’t stack.',
        ),
    ),
    attacks=(
        Attack(
            attack_id=604,
            name='Head Bolt',
            cost=(LIGHTNING, COLORLESS, COLORLESS),
            damage=140,
        ),
    ),
)
