"""Team Rocket's Blipbug (card 399). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, FIRE, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=399,
    name="Team Rocket's Blipbug",
    hp=60,
    energy_type=GRASS,
    stage=BASIC,
    weakness=FIRE,
    retreat_cost=1,
    attacks=(
        Attack(
            attack_id=558,
            name='Searching Eyes',
            cost=(COLORLESS,),
            damage=0,
            text='Look at 1 of your opponent’s face-down Prize cards.',
        ),
    ),
)
