"""Team Rocket's Arbok (card 449). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, DARKNESS, FIGHTING, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=449,
    name="Team Rocket's Arbok",
    hp=130,
    energy_type=DARKNESS,
    stage=STAGE1,
    evolves_from="Team Rocket's Ekans",
    weakness=FIGHTING,
    retreat_cost=2,
    tags=frozenset(['team_rocket']),
    abilities=(
        Ability(
            name='Potent Glare',
            text='As long as this Pokémon is in the Active Spot, your opponent can’t play any Pokémon that has an Ability from their hand, except for Team Rocket’s Pokémon.',
        ),
    ),
    attacks=(
        Attack(
            attack_id=632,
            name='Spinning Tail',
            cost=(DARKNESS, DARKNESS, DARKNESS),
            damage=0,
            text='This attack does 30 damage to each of your opponent’s Pokémon. (Don’t apply Weakness and Resistance for Benched Pokémon.)',
        ),
    ),
)
