"""Team Rocket's Muk (card 460). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, DARKNESS, FIGHTING, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=460,
    name="Team Rocket's Muk",
    hp=150,
    energy_type=DARKNESS,
    stage=STAGE1,
    evolves_from="Team Rocket's Grimer",
    weakness=FIGHTING,
    retreat_cost=4,
    attacks=(
        Attack(
            attack_id=648,
            name='Gooped Up',
            cost=(DARKNESS, COLORLESS),
            damage=40,
            text='Your opponent’s Active Pokémon is now Confused. During your opponent’s next turn, that Pokémon can’t retreat.',
        ),
        Attack(
            attack_id=649,
            name='Hazardous Venom',
            cost=(DARKNESS, DARKNESS, COLORLESS),
            damage=0,
            text='This attack does 100 damage for each Special Condition affecting your opponent’s Active Pokémon.',
        ),
    ),
)
