"""Thwackey (card 90). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, Clause, FIRE, GRASS, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=90,
    name='Thwackey',
    hp=100,
    energy_type=GRASS,
    stage=STAGE1,
    evolves_from='Grookey',
    weakness=FIRE,
    retreat_cost=2,
    tags=frozenset(['search']),
    default_roles=('backup_attacker', 'disruption_target'),
    covers='full',
    abilities=(
        Ability(
            name='Boom Boom Groove',
            text='Once during your turn, if your Active Pokémon has the Festival Lead Ability, you may search your deck for a card and put it into your hand. Then, shuffle your deck.',
            clauses=(Clause('fetch', target='any', zone='deck', condition='active_has_festival_lead', allowance='body'),),
        ),
    ),
    attacks=(
        Attack(
            attack_id=111,
            name='Beat',
            cost=(GRASS, GRASS),
            damage=50,
        ),
    ),
)
