"""Timburr (card 113). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, Clause, FIGHTING, PSYCHIC, PokemonCard)

CARD = PokemonCard(
    card_id=113,
    name='Timburr',
    hp=80,
    energy_type=FIGHTING,
    stage=BASIC,
    weakness=PSYCHIC,
    retreat_cost=2,
    tags=frozenset([]),
    default_roles=('backup_attacker',),
    attacks=(
        Attack(
            attack_id=142,
            name='Best Punch',
            cost=(FIGHTING,),
            damage=40,
            text='Flip a coin. If tails, this attack does nothing.',
            clauses=(Clause('coin', effect='attack_fails_on_tails'),),
        ),
    ),
)
