"""Togedemaru ex (card 990). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, FIRE, GRASS, METAL, PokemonCard)

CARD = PokemonCard(
    card_id=990,
    name='Togedemaru ex',
    hp=190,
    energy_type=METAL,
    stage=BASIC,
    ex=True,
    weakness=FIRE,
    resistance=GRASS,
    retreat_cost=1,
    tags=frozenset(['paralyze']),
    attacks=(
        Attack(
            attack_id=1428,
            name='Stun Needle',
            cost=(METAL,),
            damage=20,
            text='Flip a coin. If heads, your opponent’s Active Pokémon is now Paralyzed.',
            damage_min=20,
            damage_max=20,
        ),
        Attack(
            attack_id=1429,
            name='Spiky Rolling',
            cost=(METAL, COLORLESS),
            damage=80,
            text='If this Pokémon used Spiky Rolling during your last turn, this attack does 80 more damage.',
        ),
    ),
)
