"""Toxtricity (card 834). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, COLORLESS, DARKNESS, FIGHTING, PokemonCard, STAGE1)

CARD = PokemonCard(
    card_id=834,
    name='Toxtricity',
    hp=140,
    energy_type=DARKNESS,
    stage=STAGE1,
    evolves_from='Toxel',
    weakness=FIGHTING,
    retreat_cost=2,
    abilities=(
        Ability(
            name='Sinister Surge',
            text='Once during your turn, you may use this Ability. Search your deck for a Basic {D} Energy card and attach it to 1 of your Benched {D} Pokémon. Then, shuffle your deck. If you attached Energy to a Pokémon in this way, place 2 damage counters on that Pokémon.',
        ),
    ),
    attacks=(
        Attack(
            attack_id=1203,
            name='Gentle Slap',
            cost=(DARKNESS, DARKNESS, COLORLESS),
            damage=100,
        ),
    ),
)
