"""Tyrogue (card 672). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, FIGHTING, PSYCHIC, PokemonCard)

CARD = PokemonCard(
    card_id=672,
    name='Tyrogue',
    hp=30,
    energy_type=FIGHTING,
    stage=BASIC,
    weakness=PSYCHIC,
    retreat_cost=0,
    tags=frozenset([]),
    attacks=(
        Attack(
            attack_id=975,
            name='Pow-Pow Punching',
            cost=(),
            damage=10,
            text='Flip a coin until you get tails. This attack does 30 more damage for each heads.',
            damage_min=0,
            damage_max=700,
        ),
    ),
)
