"""Vanilluxe (card 582). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, METAL, PokemonCard, STAGE2, WATER)

CARD = PokemonCard(
    card_id=582,
    name='Vanilluxe',
    hp=150,
    energy_type=WATER,
    stage=STAGE2,
    evolves_from='Vanillish',
    weakness=METAL,
    retreat_cost=2,
    attacks=(
        Attack(
            attack_id=834,
            name='Ram',
            cost=(COLORLESS, COLORLESS),
            damage=60,
        ),
        Attack(
            attack_id=835,
            name='Double Freeze',
            cost=(WATER, COLORLESS, COLORLESS),
            damage=0,
            text='Flip 2 coins. This attack does 90 damage for each heads. If either of them is heads, your opponent’s Active Pokémon is now Paralyzed.',
            damage_min=0,
            damage_max=180,
        ),
    ),
)
