"""Vanillish (card 581). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, COLORLESS, METAL, PokemonCard, STAGE1, WATER)

CARD = PokemonCard(
    card_id=581,
    name='Vanillish',
    hp=90,
    energy_type=WATER,
    stage=STAGE1,
    evolves_from='Vanillite',
    weakness=METAL,
    retreat_cost=2,
    tags=frozenset(['paralyze']),
    attacks=(
        Attack(
            attack_id=832,
            name='Ram',
            cost=(COLORLESS, COLORLESS),
            damage=30,
        ),
        Attack(
            attack_id=833,
            name='Ice Beam',
            cost=(WATER, COLORLESS, COLORLESS),
            damage=50,
            text='Flip a coin. If heads, your opponent’s Active Pokémon is now Paralyzed.',
            damage_min=50,
            damage_max=50,
        ),
    ),
)
