"""Venipede (card 535). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, DARKNESS, FIGHTING, PokemonCard)

CARD = PokemonCard(
    card_id=535,
    name='Venipede',
    hp=80,
    energy_type=DARKNESS,
    stage=BASIC,
    weakness=FIGHTING,
    retreat_cost=3,
    tags=frozenset(['poison']),
    attacks=(
        Attack(
            attack_id=765,
            name='Poison Spray',
            cost=(COLORLESS,),
            damage=0,
            text='Your opponent’s Active Pokémon is now Poisoned.',
        ),
    ),
)
