"""Vileplume (card 780). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, FIRE, GRASS, PokemonCard, STAGE2)

CARD = PokemonCard(
    card_id=780,
    name='Vileplume',
    hp=150,
    energy_type=GRASS,
    stage=STAGE2,
    evolves_from='Gloom',
    weakness=FIRE,
    retreat_cost=2,
    attacks=(
        Attack(
            attack_id=1128,
            name='Pollen Bomb',
            cost=(GRASS,),
            damage=30,
            text='Your opponent’s Active Pokémon is now Asleep and Poisoned.',
        ),
        Attack(
            attack_id=1129,
            name='Lively Flower',
            cost=(GRASS,),
            damage=60,
            text='If this Pokémon was healed during this turn, this attack does 120 more damage.',
        ),
    ),
)
