"""Volbeat (card 88). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, Clause, FIRE, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=88,
    name='Volbeat',
    hp=70,
    energy_type=GRASS,
    stage=BASIC,
    weakness=FIRE,
    retreat_cost=1,
    default_roles=('support_pokemon',),
    attacks=(
        Attack(
            attack_id=107,
            name='Quick Sign',
            cost=(COLORLESS,),
            damage=0,
            text='If you go first, you can use this attack during your first turn. Search your deck for up to 2 Basic Pokémon and put them onto your Bench. Then, shuffle your deck.',
            clauses=(Clause('first_turn_attack_permission', condition='went_first'), Clause('fetch', target='basic_pokemon', zone='deck', amount=2, dest='bench')),
        ),
        Attack(
            attack_id=108,
            name='Coordinated Strike',
            cost=(COLORLESS, COLORLESS),
            damage=20,
            text='If Illumise is on your Bench, this attack does 60 more damage.',
            clauses=(Clause('damage_boost', amount=60, condition='bench_has_named', named='Illumise'),),
        ),
    ),
)
