"""Volcanion (card 1034). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, LIGHTNING, PokemonCard, WATER)

CARD = PokemonCard(
    card_id=1034,
    name='Volcanion',
    hp=130,
    energy_type=WATER,
    stage=BASIC,
    weakness=LIGHTNING,
    retreat_cost=3,
    attacks=(
        Attack(
            attack_id=1491,
            name='Strength',
            cost=(WATER, COLORLESS),
            damage=50,
        ),
        Attack(
            attack_id=1492,
            name='Powerful Steam',
            cost=(WATER, WATER, COLORLESS),
            damage=0,
            text='Flip a coin for each {W} Energy attached to this Pokémon. This attack does 90 damage for each heads.',
            damage_min=0,
            damage_max=270,
        ),
    ),
)
