"""Volcanion (card 663). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, FIRE, PokemonCard, WATER)

CARD = PokemonCard(
    card_id=663,
    name='Volcanion',
    hp=130,
    energy_type=FIRE,
    stage=BASIC,
    weakness=WATER,
    retreat_cost=2,
    attacks=(
        Attack(
            attack_id=961,
            name='Singe',
            cost=(FIRE,),
            damage=0,
            text='Your opponent’s Active Pokémon is now Burned.',
        ),
        Attack(
            attack_id=962,
            name='Backfire',
            cost=(FIRE, FIRE, COLORLESS),
            damage=130,
            text='Put 2 {R} Energy attached to this Pokémon into your hand.',
        ),
    ),
)
