"""Volcanion ex (card 259). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Ability, Attack, BASIC, COLORLESS, FIRE, PokemonCard, WATER)

CARD = PokemonCard(
    card_id=259,
    name='Volcanion ex',
    hp=220,
    energy_type=FIRE,
    stage=BASIC,
    ex=True,
    weakness=WATER,
    retreat_cost=3,
    abilities=(
        Ability(
            name='Scalding Steam',
            text='Once during your turn, if this Pokémon is in the Active Spot, you may make your opponent’s Active Pokémon Burned.',
        ),
    ),
    attacks=(
        Attack(
            attack_id=357,
            name='Scorching Cyclone',
            cost=(FIRE, FIRE, COLORLESS),
            damage=160,
            text='Move an Energy from this Pokémon to 1 of your Benched Pokémon.',
        ),
    ),
)
