"""Voltorb ex (card 951). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, FIGHTING, LIGHTNING, PokemonCard)

CARD = PokemonCard(
    card_id=951,
    name='Voltorb ex',
    hp=170,
    energy_type=LIGHTNING,
    stage=BASIC,
    ex=True,
    weakness=FIGHTING,
    retreat_cost=1,
    attacks=(
        Attack(
            attack_id=1366,
            name='Hundred-Hitting Ball',
            cost=(COLORLESS, COLORLESS, COLORLESS),
            damage=100,
            text='Flip a coin until you get tails. This attack does 100 more damage for each heads.',
            damage_min=0,
            damage_max=2400,
        ),
    ),
)
