"""Wellspring Mask Ogerpon ex (card 108). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, Clause, LIGHTNING, PokemonCard, WATER)

CARD = PokemonCard(
    card_id=108,
    name='Wellspring Mask Ogerpon ex',
    hp=210,
    energy_type=WATER,
    stage=BASIC,
    ex=True,
    tera=True,
    weakness=LIGHTNING,
    retreat_cost=1,
    tags=frozenset([]),
    default_roles=('backup_attacker',),
    attacks=(
        Attack(
            attack_id=135,
            name='Sob',
            cost=(COLORLESS,),
            damage=20,
            text='During your opponent’s next turn, the Defending Pokémon can’t retreat.',
            clauses=(Clause('retreat_lock', target='defending', duration='opp_next_turn'),),
        ),
        Attack(
            attack_id=136,
            name='Torrential Pump',
            cost=(WATER, COLORLESS, COLORLESS),
            damage=100,
            text='You may shuffle 3 Energy attached to this Pokémon into your deck. If you do, this attack also does 120 damage to 1 of your opponent’s Benched Pokémon. (Don’t apply Weakness and Resistance for Benched Pokémon.)',
            clauses=(Clause('bench_snipe', amount=120, target='opp_bench', optional=True, cost='shuffle_3_energy_into_deck'),),
        ),
    ),
)
