"""Zapdos (card 953). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, FIGHTING, LIGHTNING, PokemonCard)

CARD = PokemonCard(
    card_id=953,
    name='Zapdos',
    hp=120,
    energy_type=LIGHTNING,
    stage=BASIC,
    weakness=LIGHTNING,
    resistance=FIGHTING,
    retreat_cost=2,
    attacks=(
        Attack(
            attack_id=1369,
            name='Thunder Wave',
            cost=(LIGHTNING,),
            damage=0,
            text='Flip a coin. If heads, your opponent’s Active Pokémon is now Paralyzed.',
            damage_min=0,
            damage_max=0,
        ),
        Attack(
            attack_id=1370,
            name='Thunderbolt',
            cost=(LIGHTNING, LIGHTNING, COLORLESS),
            damage=190,
            text='Discard all Energy from this Pokémon.',
        ),
    ),
)
