"""Zorua (card 136). Generated by tools/build_pokemon_cards.py — edit there and rerun."""
from common.cards.card_facts import (Attack, BASIC, COLORLESS, DARKNESS, GRASS, PokemonCard)

CARD = PokemonCard(
    card_id=136,
    name='Zorua',
    hp=70,
    energy_type=DARKNESS,
    stage=BASIC,
    weakness=GRASS,
    retreat_cost=1,
    attacks=(
        Attack(
            attack_id=176,
            name='Stampede',
            cost=(COLORLESS,),
            damage=10,
        ),
        Attack(
            attack_id=177,
            name='Double Scratch',
            cost=(DARKNESS, COLORLESS),
            damage=0,
            text='Flip 2 coins. This attack does 20 damage for each heads.',
            damage_min=0,
            damage_max=40,
        ),
    ),
)
